### ISSUE TITLE
how to enable trace: 'retain-on-failure' feature on java

### ISSUE THREAD

**Issue by balakumaran182** [microsoft/playwright-java#1002]
how to enable trace: 'retain-on-failure' feature on java

**Comment by chaganiu** [comment]
if you're using junit 5 you can use [TestWatcher](https://junit.org/junit5/docs/5.4.0/api/org/junit/jupiter/api/extension/TestWatcher.html)

or if you're using testng use a test[TestListener](https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/ITestListener.html)

Start the trace when you create the browsercontext like you normally would but only save it if the test fails in the appropriate test failure methods.

if you're using junit 5 you can also use [junit-playwright](https://github.com/uchagani/junit-playwright) which. has a `enableTracingOnlyOnFailure()` which will handle it for you.

**Comment by yury-s** [comment]
'retain-on-failure' is a feature of playwright test runner which is only available in Node.js. Internally it runs the tests with tracing enabled but only writes the result to a file if the test fails. You can implement such logic as described in the previous comment.
