### ISSUE TITLE
Playwright Java - is there a way to use system node version ?

### ISSUE THREAD

**Issue by mEklavya** [microsoft/playwright-java#1016]
Playwright.create() is failing as it is installing the node.exe in the temp directory which the user is not allowed to run. Is there a way not to use this temp path and use system node js installed in program files

![image](https://user-images.githubusercontent.com/42370888/181646341-b7fa9419-e853-491d-9dca-d13843007868.png)

**Comment by mEklavya** [comment]
Thanks, team for the quick response.
No, it will not work. As in our organization, you can not run the .exe file until is whitelisted and digitally verified. Also, Node Js is available in Program files and the same needs to be used.

Is there any other way?

**Comment by yury-s** [comment]
We don't support running with a system node version as of today. There is a java property that is used for development purposes only, you can point that one to a preinstalled driver but you need to understand what you are doing as it has to be updated along with playwright etc. The property is [playwright.cli.dir](https://github.com/microsoft/playwright-java/blob/436fc12609176a8ae6032a9183ae54477749eb84/driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java#L96).

**Comment by yury-s** [comment]
What we can easily do is to allow providing a path to preinstalled Node.js in an environment variable or as Playwright constructor parameter. We'd still have to extract the node modules into a temp directory and run them from there. Would this approach address your issue or extracting even node js modules (all javascript, no native code as of today) to a temp directory would still be a problem?

**Comment by mEklavya** [comment]
Thanks, it will be good to have environment variables for it, if the user doesn't pass then it takes default.
Can the temp directory path be controlled using environment variables?

**Comment by yury-s** [comment]
> Can the temp directory path be controlled using environment variables?

Only with a java system property today but we can add an environment variable too. Is there a reason why the java property doesn't work for you?

**Comment by yury-s** [comment]
Now that the PR has landed you can specify custom node location with `PLAYWRIGHT_NODEJS_PATH` env variable or `playwright.nodejs.path` java system property. You can give it a try in Playwright v1.26.0-SNAPSHOT

**Comment by mEklavya** [comment]
Thank you @yury-s , will wait for updated version:)

One more query, in the current version, how can we know from where node and other dependencies are getting downloaded?

**Comment by yury-s** [comment]
The driver is extracted from [driver-bundle](https://search.maven.org/search?q=a:driver-bundle) maven package, on the first run it will download browsers from CDN.

**Comment by mEklavya** [comment]
> The driver is extracted from [driver-bundle](https://search.maven.org/search?q=a:driver-bundle) maven package, on the first run it will download browsers from CDN.

Thanks a lot, Yuri driver Bundle was clear, but what about other temp files in the Playwright-Java-xxxxxxx folder like Node.exe, playwright?cmd etc, from where it gets downloaded at the first run?

**Comment by yury-s** [comment]
Everything in the temp directory is extracted from the same module. Does it break somewhere in your environment?

**Comment by yury-s** [comment]
> Yes, we see that printdeps.exe is not signed which is getting extracted from this module, and also not able to understand its usage. Can you please help us by signing it? As it is unsigned it is not allowed to run in corporate.
> 

We can definitely sign it, it's an oversight on our end. The source code of the program is [here](https://github.com/microsoft/playwright/tree/main/browser_patches/winldd), it hasn't changed for a while and the binary we use is [here](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/bin/PrintDeps.exe). We use it to check that all browser dependency libraries are present on the host system and if they are not we will print out missing ones.

> Also how often we will be updating our node.exe and other files which are getting downloaded in temp dir? Let's say if there is a version change in the node version then we will be adapting it.

The node is baked into the driver-bundle package so it's only updated when that package is updated. If you install node separately it's up to you when to update it.

**Comment by mEklavya** [comment]
> > Yes, we see that printdeps.exe is not signed which is getting extracted from this module, and also not able to understand its usage. Can you please help us by signing it? As it is unsigned it is not allowed to run in corporate.
> 
> We can definitely sign it, it's an oversight on our end. The source code of the program is [here](https://github.com/microsoft/playwright/tree/main/browser_patches/winldd), it hasn't changed for a while and the binary we use is [here](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/bin/PrintDeps.exe). We use it to check that all browser dependency libraries are present on the host system and if they are not we will print out missing ones.
> 
Thank you, will it be also available with the next version?

**Comment by mxschmitt** [comment]
I filed an upstream feature request for it to sign the Windows binaries: https://github.com/microsoft/playwright/issues/17165

We unfortunately can't provide an eta for it, depending on the demand we'll work on it.

Since the original issue is fixed (make it possible to use a custom Node.js version) I'll close this one for now.
