### ISSUE TITLE
[Question] java -jar but timeout exception

### ISSUE THREAD

**Issue by 1355692540** [microsoft/playwright-java#1019]
it is ok when l  run code in idea.but  when l make it as a jar and run as java -jar .it seems the brower cant be instance

**Comment by yury-s** [comment]
Can you share the code please and command line that you use to launch it? You may have missed the driver package. Also running with `DEBUG=pw:browser` may give you some information on what the browser is doing during the startup.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright-java/issues/1018
