### ISSUE TITLE
[BUG] Playwright executions in jenkins throws Internal error

### ISSUE THREAD

**Issue by VigneshNates** [microsoft/playwright-java#1022]
**Playwright executions in jenkins throws Internal error:**
- Playwright Version: [1.18.0]
- Operating System: [Jenkins server in Linux]
- Node.js version: [Java 11]
- Browser: [Chromium]
- Extra: [The execution is fine in local machines. But it is failing only in jenkins execution]

**Code Snippet**

```java
page.locator(".xn-arclabel-value-text").isVisible(new Locator.IsVisibleOptions().setTimeout(60000)
```

**isVisible throws Internal error only in jenkins**

com.microsoft.playwright.PlaywrightException: Internal error
	at com.microsoft.playwright.impl.Utils.convertType(Utils.java:55)
	at com.microsoft.playwright.impl.LocatorImpl.isVisible(LocatorImpl.java:266)

**Comment by yury-s** [comment]
What is the full stack trace including the error message?

**Comment by VigneshNates** [comment]
Hi @yury-s This is the full stack trace we have 

com.microsoft.playwright.PlaywrightException: Internal error
	at com.microsoft.playwright.impl.Utils.convertType(Utils.java:55)
	at com.microsoft.playwright.impl.LocatorImpl.isEnabled(LocatorImpl.java:250)
	at com.sample.test.AbstractChartsCommon.waitForEnabledInChartContext(AbstractChartsCommon.java:194)

**Comment by yury-s** [comment]
There should be  `caused by` below that which may contain some useful information, otherwise it's hard to tell what's going on there, probably some reflection calls are not working as intended.

**Comment by VigneshNates** [comment]
@yury-s We can close this issue. Its already been discussed in https://servicenow.cloud.mattermost.com/main/pl/n9pemzggz3gum8orfz3n3mr78o






https://bytemeta.vip/repo/microsoft/playwright-java/issues/802
