### ISSUE TITLE
[Feature] add support for retries

### ISSUE THREAD

**Issue by linusnorton** [microsoft/playwright-java#1024]
The node.js version of the library has retry support. Please add it to Java:

https://playwright.dev/docs/test-retries#retries

**Comment by yury-s** [comment]
In Node.js it's a part of the Playwright Test runner rather than Playwright Library. We don't provide our own runner in other languages including java, so you have to look for generic test retry solutions depending on the test runner you are using (JUnit, TestNG etc.)

**Comment by linusnorton** [comment]
That's a shame, JUnit has no retry
