### ISSUE TITLE
[BUG] page.locator("textarea").fill(text   ); // get stuck when text length > 130000

### ISSUE THREAD

**Issue by anime777** [microsoft/playwright-java#1029]
**Context:**
- Playwright Version: 1.24.1
- Operating System: linux
- Browser:Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java

 page.locator("textarea").fill(text   ); //  Chromium UI get stuck when text length > 130000
```

**Describe the bug**

Add any other details about the problem here.
-  java code  get stuck at that line
 - Chromium UI get stuck when text length > 130000
 - it works well if text length is 1000.

**Comment by yury-s** [comment]
There is probably some event handler on the text area that chokes on the long string. Can you share your page?

It works well with a simple example:
```java
  @Test
  void shouldFillTextarea() {
    page.setContent("<textarea></textarea>");
    StringBuffer builder = new StringBuffer();
    for (int i = 0; i < 130_000; i++) {
      builder.append('a');
    }
    String value = builder.toString();
    page.fill("textarea", value);
    assertEquals(value, page.locator("textarea"). evaluate("e => e.value"));
  }
```

**Comment by anime777** [comment]
` <el-input rows="55" v-model="form.content" type="textarea"  />`
Thanks for the quick reply.
This is that page which use fornt end framework  from  https://element-plus.org/

I get around it by javascript , it not a issue for me.  
`page.evaluate("(text)=>window.enterText(text)", text);`
