### ISSUE TITLE
[Question] is there stealth plugin for java playwright?

### ISSUE THREAD

**Issue by hurek** [microsoft/playwright-java#1032]
Hello! Is there any stealth plugin for java playwright like playwright-stealth-plugin used in js version? Afaik playwright supports puppeteer plugins.

I want to make an RPA program with functionality close to the antidetect browsers. But I would not like to write functionality in js/ts.

**Comment by yury-s** [comment]
No that I know of and our main focus is web testing where this is not a problem. It may be worth asking this question on stackoverflow or elsewhere.
