### ISSUE TITLE
[Question] How to run codegen using gradle?

### ISSUE THREAD

**Issue by kishorejawalkar** [microsoft/playwright-java#1034]
I'm looking for the equivalent of below in gradle
```
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen playwright.dev"
```

**Comment by ArystanAmirov** [comment]
First of all, you need to add this to your build.gradle.kts file:

plugins {
    application
    kotlin("jvm") version "1.5.1"
}

application {
    mainClass.set("com.microsoft.playwright.CLI")
}

Don't forget to sync build.gradle.kts after adding 

Then run this in terminal:
./gradlew run --args="install"

and then run this:
./gradlew run --args="install-deps"

Finally, run this command:
./gradlew run --args="open playwright.dev" 

P.S. Don't forget to press Record button in Playwright Inspector
Good luck!

**Comment by kishorejawalkar** [comment]
> plugins {
>            application
>     kotlin("jvm") version "1.5.1"
> }

What is application in plugin block?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-java/issues/571
