### ISSUE TITLE
[Question] issue with a unicodes in Java

### ISSUE THREAD

**Issue by iDaDan** [microsoft/playwright-java#1036]
Have some troubles with unicodes, saw different cases with other programming languages here, please help with research on which part issue is 

**Context:**

- Playwright Version: 1.24.1
- Operating System: Windows 10
- Browser: Chromium
- Extra: jdk1.8.0_191

Code I use

```
page.locator("[placeholder=\"Название продукта\"]").click();
```

Logs I get:

```
авг. 21, 2022 9:29:20 PM org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFO: 0 containers and 2 tests were Method or class mismatch

Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[placeholder="РќР°Р·РІР°РЅРёРµ РїСЂРѕРґСѓРєС‚Р°"]"
============================================================
```

Is this a playwright issue, in which direction should I search?

**Comment by ArystanAmirov** [comment]
I think that "Название продукта\" should not be written using Windows-1251, I'd prefer KOI-8R or KOI-8U

**Comment by yury-s** [comment]
Something is wrong with you source code encoding, please ensure it is UTF-8. The following test passes:

```java
  @Test
  void shouldSupportCyrillic() throws InterruptedException, ExecutionException {
    page.setContent("<input placeholder=\"Название продукта\"></input>");
    page.locator("[placeholder=\"Название продукта\"]").click();
  }
```

Please share your test if it still failing.

**Comment by iDaDan** [comment]
This test shown me an error and research gave me a [decision](https://stackoverflow.com/questions/51280015/error-unmappable-character-0x98-for-encoding-windows-1251), thanks!
