### ISSUE TITLE
[Feature] add junit to playwright codegen

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright-java#1039]
similar to https://github.com/microsoft/playwright-dotnet/issues/2247

**Comment by jfgreffier** [comment]
@mxschmitt Hi, do you think that someone from the team can make a review of my PR ? 🙏

**Comment by jfgreffier** [comment]
Great idea. I'll look into it

**Comment by jfgreffier** [comment]
Now depends on https://github.com/microsoft/playwright-java/issues/1369
