### ISSUE TITLE
Please help with the gradle command to download chromium browser through CLI[Question]

### ISSUE THREAD

**Issue by shrinitg** [microsoft/playwright-java#1053]
we have this maven command to install chromium browser.
`mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps chromium"`

can someone please help me with its gradle equivalent?

**Comment by NICOGTZL** [comment]
Hello, first time you launch playwright, Gradle will download required browsers, if not. Try to change Gradle version.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-java/issues/571.
