### ISSUE TITLE
[Question] How can I get an input value?

### ISSUE THREAD

**Issue by NICOGTZL** [microsoft/playwright-java#1055]
Hello,

I've been trying this for a while but I couldn't extract the value of this.

`<input type="text" class="textCtrl" readonly="readonly" value="S3CRD" style="width: 100px; font-size: 16px;     font-weight: 600;" id="confirmationCode">`

This is the line of html code, I'd like to get this characters: S3CRD from value="S3CRD"

What I have tried:
```
if (page1.locator("xpath=/html/body/div[2]/div/div/div/div/div/div[2]/div[3]/div[3]/div[6]/div[3]/div[2]/a").isVisible()) {            
String value = page1.locator("xpath=/html/body/div[2]/div/div/div/div/div/div[2]/div[3]/div[3]/div[6]/div[3]/div[2]/a").inputValue();
}
```

I'm sure this has an easy solution, but didn't find one on the internet :(

Thanks in advance.

**Comment by yury-s** [comment]
Your selector is likely wrong, the following tests passes just fine:

```java
  @Test
  void test() {
    page.setContent("<input type=\"text\" class=\"textCtrl\" readonly=\"readonly\" value=\"S3CRD\" style=\"width: 100px; font-size: 16px; font-weight: 600;\" id=\"confirmationCode\">");
    assertEquals("S3CRD", page.locator("input").inputValue());
  }

```

The xpath selector you use looks very brittle as it depends on the order of some divs in the dom which can change over time as the web app evolves. Look at [our guide](https://playwright.dev/java/docs/debug-selectors) to see how to pick a better selector, something like `page.locator("input#confirmationCode").inputValue()` should work.
