### ISSUE TITLE
[Question] assertThat should return a boolean value instead of void

### ISSUE THREAD

**Issue by jaikishpai** [microsoft/playwright-java#1060]
I am reffering to the documentation https://playwright.dev/java/docs/test-assertions#page-assertions-to-have-url , where I am trying to assert that the page URL complies to a REGEX Pattern. However, the function returns void. Based on my understanding should it not return a boolean so that the assertion can be used to pass or fail a step?

![image](https://user-images.githubusercontent.com/35526514/189924219-40a49c09-fe65-4399-9956-178767486b94.png)

**Comment by mxschmitt** [comment]
assertThat will throw if the condition is not met, so returning a value there would be not useful. You can assume that all the code after the assertion is only reached when the condition is met.

**Comment by jaikishpai** [comment]
Thanks @mxschmitt. That helps.
