### ISSUE TITLE
[Question] Is there a way to use custom browser version in Playwright?

### ISSUE THREAD

**Issue by ErykK5** [microsoft/playwright-java#1061]
Is there a way to use custom browser version in Playwright? This code from 
 Selenium allows us to have custom version of driver and some browser configuration. Does playwright have something like that? Do you maybe have any code example?

```
System.setProperty("webdriver.chrome.driver","X://chromedriver.exe");
ChromeOptions options = new ChromeOptions();
options.addArguments("--incognito");
ChromeDriver driver = new ChromeDriver(options);
```

**Comment by yury-s** [comment]
You can specify custom path to a Chromium based browser via [`setExecutablePath`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch-option-executable-path) option. Another way to run Playwright with a preinstalled official build of Google Chrome or MS Edge is to set browser channel as described in [this guide](https://playwright.dev/java/docs/browsers#google-chrome--microsoft-edge).

**Comment by willtennien** [comment]
Can you do this with Firefox?

**Comment by yury-s** [comment]
No, stock firefox doesn't have necessary debugging protocol.
