### ISSUE TITLE
[BUG] I am trying to use AxeBuilder for accessibility testing, its giving me dependency resolution issue

### ISSUE THREAD

**Issue by pranesh517** [microsoft/playwright-java#1062]
I am trying to use AxeBuilder for accessibility testing and for that i added below gradle dependency:
implementation group: 'com.deque.html.axe-core', name: 'playwright', version: '4.4.1'

After running test with AxeResults axeResults = new AxeBuilder(page).analyze();
Getting below error:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve commons-codec:commons-codec:20041127.091804.
     Required by:
         project :
         project : > com.deque.html.axe-core:playwright:4.4.1
      > Could not resolve commons-codec:commons-codec:20041127.091804.
         > inconsistent module metadata found. Descriptor: commons-codec:commons-codec:1.3 Errors: bad version: expected='20041127.091804' found='1.3'

I am using Playwright version 1.25.0.
Below is my build.gradle:
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    // https://mvnrepository.com/artifact/com.microsoft.playwright/playwright
    implementation group: 'com.microsoft.playwright', name: 'playwright', version: '1.25.0'
    implementation group: 'com.deque.html.axe-core', name: 'playwright', version: '4.4.1'
}

test {
    useJUnitPlatform()
}

**Comment by yury-s** [comment]
Looks like a dependency issue of `com.deque.html.axe-core`, I suggest you ask this question in their repo: https://github.com/dequelabs/axe-core-maven-html

**Comment by pranesh517** [comment]
Created new issue at axe-core-maven-html:
https://github.com/dequelabs/axe-core-maven-html/issues/238

**Comment by yury-s** [comment]
Closing this issue as part of triaging since it's now tracked upstream.
