### ISSUE TITLE
[Question] Gradle task for parallel test

### ISSUE THREAD

**Issue by pranesh517** [microsoft/playwright-java#1067]
I have created Page Object Model using Gradle with capability of running tests parallel where we can specify maximum parallel tests we need to run.
In build.gradle i added

test {
useJUnitPlatform()
maxParallelForks 2
}

I have 2 test cases in src.test.java.com and once i run ./gradlew cleanTest test , both the test cases run parallely.

Repo: https://github.com/pranesh517/OrangePOMJV.git

Is this correct approach of creating framework and running tests parallel when using Gradle?

**Comment by yury-s** [comment]
From [the documentation](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks) it sounds that each  test case will run in its own process. Based on that and skimming through your code you should be fine. General rule should be to ensure that no two threads access the same playwright instance and objects created from it. See [this doc](https://playwright.dev/java/docs/multithreading). Please open a new issue with more specific questions if it's still unclear.
