### ISSUE TITLE
[Question] Is it possible to display the date and time at the time of a screenshot or video recording?

### ISSUE THREAD

**Issue by NICOGTZL** [microsoft/playwright-java#1068]
Hello,

I'm taking screenshots and recording but I need them with date and time, I'm not sure if there is any function to do this.

Thanks!

**Comment by yury-s** [comment]
There is no builtin mechanism for this, but you can add such a label into the page before taking a screenshot (see [this js example](https://github.com/microsoft/playwright/issues/15634#issuecomment-1183755954)) or use a third-party library to add it later to the image.
