### ISSUE TITLE
[Question] - Which one is recommended Playwright+Java or Playwright with typescript to suffice E2E automation requirement including CI/CD integration , parallel testing and many more

### ISSUE THREAD

**Issue by dggadhia** [microsoft/playwright-java#1083]
Need a genuine feedback to figure out which one is better to go with Playwright+Typescript or Playwright+Java

I am looking for E2E automation UI tool , started with Playwright+Java but facing issues in couple of things like paralle testing, CI/CD integration

So just wanna check is Playwright+typescript covers majority of the automation requirement.

**Comment by yury-s** [comment]
Most of the features of Playwright for Node.js are available in Playwright Java as well. One of the biggest differences is that the Java API is synchronous which makes it easier to use in many cases but may require more effort to run more stuff in parallel. Playwright for Node.js has its own test runner which is not available in other languages, it may be a decisive factor for your project. In general Playwright for Node.js is our primary port (and the most popular) hence it's the one where we put most effort into, but depending on your project requirements / experience you can pick another language port.

Feel free to open new bug / feature request If you have particular problem.
