### ISSUE TITLE
[Feature] querySelectorAll has no waitForSelector

### ISSUE THREAD

**Issue by gigitalz** [microsoft/playwright-java#1095]
It's either not needed or missing, how do I wait when using querySelectorAll?
It looks like you can wait only when selecting one element with waitForSelector.
Do I need to call twice to wait?

waitForSelector and then call querySelectorAll ?

**Comment by yury-s** [comment]
> Do I need to call twice to wait?

Yes, you can call it several times once for each selector you want to wait:

```java
page.waitForSelector("#first");
page.waitForSelector("#second");
```
or with locators:
```java
page.locator("#first").waitFor();
page.locator("#second").waitFor();
```
Does it work for you?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
