### ISSUE TITLE
[Question]viedo web page screenshot is black

### ISSUE THREAD

**Issue by sinbad01234** [microsoft/playwright-java#1099]
The following screenshot is taken through the playwright java implementation

![screenshot9-](https://user-images.githubusercontent.com/48613293/196400133-04708d60-630c-4027-9086-03ef8109fda4.jpg)

source code:
      try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch();
            Page page = browser.newPage();
            page.navigate("https://www.bilibili.com/video/BV1dv4y1g75y/?spm_id_from=333.337.search-card.all.click");
            page.waitForRequestFinished(new Runnable() {
                @Override
                public void run() {
                    try {
                        Thread.sleep(10000);
                    } catch (InterruptedException e) {
                        throw new RuntimeException(e);
                    }
                    page.screenshot(new Page.ScreenshotOptions().setPath(Paths.get("screenshot9-" + ".jpg")).setFullPage(true).setType(ScreenshotType.JPEG));
                }
            });
        }

I tried the second way, headful browser in a docker container and xvfb as a virtual display。

FROM mcr.microsoft.com/playwright/java:focal
RUN apt-get update && apt-get install -y --no-install-recommends git vim xvfb
RUN chmod a+w /ms-playwright/.links
RUN adduser pwuser
USER pwuser
RUN cd && git clone https://github.com/microsoft/playwright-java.git
WORKDIR /home/pwuser/playwright-java/examples
then in the docker edited vim src/main/java/org/example/PageScreenshot.java to add new BrowserType.LaunchOptions().setHeadless(false)

PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 xvfb-run mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot

**the screenshot result is video zone black, other zone is normal**

**Comment by yury-s** [comment]
The website doesn't serve the videos when the browser is controlled by an automation framework. You'll need to find a way to overcome that. Stealth mode is not a priority for Playwright as our main goal is web test automation, which normally means that you have access to the backend and can disable such bot detection on the server side while running the tests. Hope that helps.

**Comment by sinbad01234** [comment]
I see Thank you！
