### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by ghost** [microsoft/playwright-java#1100]
Deleted

**Comment by yury-s** [comment]
Unless there is a better selector you can use [Locator.nth](https://playwright.dev/java/docs/api/class-locator#locator-nth) as last resort here, and then call [Locator.textContent](https://playwright.dev/java/docs/api/class-locator#locator-text-content) on it. Something like:

```java
page.locator(".marketItemView--counters .counter").nth(4).locator(".label").textContent();
```
Would that work?

**Comment by NICOGTZL** [comment]
Hello,

It works half way as the information does not come in the same order all the time, I will try to get all the information out and organize it somehow. Thank you very much!

**Comment by yury-s** [comment]
> I will try to get all the information out and organize it somehow.

[Locator.allTextContents](https://playwright.dev/java/docs/api/class-locator#locator-all-text-contents) may come in handy, you can get all the values like this:

```java
page.locator(".marketItemView--counters .counter").locator(".label").allTextContents();
```

**Comment by NICOGTZL** [comment]
> This is exactly why we discourage use of `nth()`, it'd be nice if you could find a better selector.

Yes indeed, but I think the main problem is that there is no good structuring on the web. At least we have some way to scrape data in a very intuitive way, that's what I love about Playwright, even if I don't know how to do something, once I learn it I don't forget it because it's very intuitive.
