### ISSUE TITLE
[Question] [Playwright Java] How can I get the values of this?

### ISSUE THREAD

**Issue by NICOGTZL** [microsoft/playwright-java#1102]
Hello, I'm trying to get this values but I don't find any method, since with xpath it doesn't work because the page changes from one category to another. I need to get the numbers of both values. (20 & 31 in this case).

![1](https://user-images.githubusercontent.com/99368878/196488624-a7beb57f-c952-4bcc-acd8-020fbe510a65.PNG)

Thanks!

**Comment by yury-s** [comment]
Closing as duplicate of https://github.com/microsoft/playwright-java/issues/1100
