### ISSUE TITLE
[BUG] Problem selecting a div or element when there's multiple classes

### ISSUE THREAD

**Issue by calebyangsy** [microsoft/playwright-java#1104]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.27
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]

Suppose a div has something like this

&lt;div class="typea typeb"&gt; &lt;/div&gt;

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      page.querySelectorAll(".typea");
      // ...
    }
  }
}
```

**Describe the bug**

This fails to actually get the correct div although it exists.

**Comment by yury-s** [comment]
What is the page where it tries to select the element? The code doesn't navigate anywhere before querying the element.

**Comment by calebyangsy** [comment]
My apologies, I took the sample code and just used it, but it really happened in a more unusual case where I was trying to select a card using css on one page where it worked in one page and not the other.

One other thing I suspect, was that it may have had a non existent class from the css appended by my company framework

**Comment by calebyangsy** [comment]
Div sample was something like this, where I attempted to select a the .card-type class but it produced no result.

<div class="v2Index__EqxCardStyles-sc-9t3t9a-0 ckmPkr card tile cross_connect_type orders" data-automation="crossconnect_reimagined_title" data-title="crossconnect_reimagined_title"><div class="weight">26</div><div class="card-type crossconnect_reimagined_type"><div class="order-title" style="display: -webkit-box; -webkit-box-orient: vertical; overflow: hidden; -webkit-line-clamp: 2;"><div class="title-with-icon"><span>Cross Connect with Digital LOA</span></div><div class="title-icon"><i class="eqx-icon-file-pdf"></i></div></div><div data-automation="crossconnect_reimagined_title" style="display: -webkit-box; -webkit-box-orient: vertical; overflow: hidden; -webkit-line-clamp: 5; margin-top: 12px;"><span>Place an order using a digital LOA received from a Z-side provider</span></div></div></div>

**Comment by calebyangsy** [comment]
My apologies... I've determined it's due to the app calling the div faster than it loads
