### ISSUE TITLE
Playwright: Multiple Tests via xml Testsuite error to run the suite

### ISSUE THREAD

**Issue by yeassine** [microsoft/playwright-java#1107]
### Discussed in https://github.com/microsoft/playwright/discussions/18343

<div type='discussions-op-text'>

<sup>Originally posted by **yeassine** October 26, 2022</sup>
Hi,
im facing problem with xml test suite using TestNG and Playwhright, i try for example to start following test suite:
_suite name="test suite" parallel="false">
parameter name="ReportValue" value="Rep"/>
    test name="test1">
        classes>
            class name="path.test1"/>
        /classes>
    /test>
    test name="test2">
        classes>
            class name="path.test2"/>
        /classes>
    /test>
    /suite'_
i call in every test script @Aftertest annotation with teardown method:
**public static void tearDown() throws IOException {
			context.close();
			browser.close();
			playwright.close();
	}**
and in the annotation @BeforeTest i lunch the startBrowser() method with context and playwhright browser.
Problem:
the first test1 is running without problem
seconde test is opening the browser but i get the error: 
com.microsoft.playwright.PlaywrightException: Error {
  message='Target page, context or browser has been closed

please can someone help me to find out what the problem is?</div>

**Comment by mxschmitt** [comment]
Usually you keep Playwright running for your whole test execution but only re-create the context and by that the page for each test.

We don't have a dedicated section for TestNG but it should be very similar to the JUnit section: https://playwright.dev/java/docs/test-runners#junit

**Comment by yury-s** [comment]
> i call in every test script @Aftertest annotation with teardown method:
```java
public static void tearDown() throws IOException {
  context.close();
  browser.close();
  playwright.close();
}
```
Normally you don't need to close browser and playwright between the tests, closing the context should be sufficient. It might be that you close the context but don't create a new page in the next test. Can you share the entire test so with setup/teardown fixtures so that we can better help you?

**Comment by yeassine** [comment]
@yury-s  and @mxschmitt  thanks for your answer :).
the tests are like this:
public class Test1{
@BeforeTest
public static void lunchBrowser(){
lunch URL with the page and context, i call here another base class.
Baseclass.starturl(URL);
}
@Test 
public static void test1{
starting the test scripts
}
@Aftertest{
i call teardown() from the same base class
Baseclass().teardown();
}
}
test2 is also on separate class,
normally the tearDown close the browser and playwright and also the context, but in test2 i open all of them new int "lunchBrowser()" base method
Running the tests separate works without any problems, but if i will run the test suite it works on test1 but crash on the test2, 3 etc...

**Comment by yury-s** [comment]
We need too see Baseclass too, basically all the code that leads to paywright calls, otherwise we can only speculate about what's going on.

**Comment by yeassine** [comment]
here is my baseclass:
public static void initBrowser(String environmentURL) throws IOException, InterruptedException, AWTException {

			PWBaseConfigKredit.environmentUrl = environmentURL;
			playwright = Playwright.create();

		if (PWBaseConfigKredit.browserType.equalsIgnoreCase("chrome")) { 
			browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
					.setHeadless(PWBaseConfigKredit.headless)
					.setChannel("chrome"));

		} else if (PWBaseConfigKredit.browserType.equalsIgnoreCase("firefox")) {
			browser = playwright.firefox().launch(new BrowserType.LaunchOptions().setHeadless(PWBaseConfigKredit.headless));
		} else {
			browser = playwright.webkit().launch(new BrowserType.LaunchOptions().setHeadless(PWBaseConfigKredit.headless));
		}
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		int width = (int)screenSize.getWidth();
		int height = (int)screenSize.getHeight();

		context = browser.newContext(new Browser.NewContextOptions().setViewportSize(width,height));
		page = context.newPage();
		page.setDefaultTimeout(PWBaseConfigKredit.MyworkspaceDefaultTime); 

			page.navigate(PWBaseConfigKredit.url);
		
		}
		}

	public static void tearDown() throws IOException {

			PWBaseReportKredit.createReportSeperator();
			PWBaseReportKredit.softAssertion.assertAll();

			context.close();
			browser.close();
			playwright.close();

	}

**Comment by yury-s** [comment]
It's unclear from the snippet what Baseclass.starturl(URL); does and where the page, browser etc. variables are stored and when they are reset. Can you just share entire class?

**Comment by yeassine** [comment]
this is the entire class, that Baseclass.Start(URL) was only example, normally i call the initbrowser(URL); in the test1 and test2, and into PWBaseConfigKredit.url is only config class wich has different urls what i test and some configurations...

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a full repro and link it to this one.
