### ISSUE TITLE
[Question] How to fix for this problem in Maven project

### ISSUE THREAD

**Issue by pduyet** [microsoft/playwright-java#1110]
after running this command to run code gen
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen wikipedia.org"
I received this error:
[ERROR] No plugin found for prefix '.args=codegen https' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Admin\.m2\repository), central (
https://repo.maven.apache.org/maven2)] -> [Help 1]
![image](https://user-images.githubusercontent.com/39377321/199180230-01b02654-bef5-4fd7-9164-1f1912228e9c.png)
pls help me fix this!

**Comment by yury-s** [comment]
The error is clearly from a command different than `mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen wikipedia.org"` as there is no `https` in that line. Please double check the command line you use, there are likely some issues with escaping/quoting string (the command that you mentioned works fine for me locally).

**Comment by pduyet** [comment]
> The error is clearly from a command different than `mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen wikipedia.org"` as there is no `https` in that line. Please double check the command line you use, there are likely some issues with escaping/quoting string (the command that you mentioned works fine for me locally).

![image](https://user-images.githubusercontent.com/39377321/199382743-59c3f987-d636-4eea-907a-aa6c3110dcfc.png)
I add https to this link. but this issue still exists. (Window 10)

**Comment by pduyet** [comment]
> The error is clearly from a command different than `mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen wikipedia.org"` as there is no `https` in that line. Please double check the command line you use, there are likely some issues with escaping/quoting string (the command that you mentioned works fine for me locally).

my fault. just works correctly when running the command line in explorer. not work in terminal in IntelliJ. thank you

**Comment by bilalmohsin200** [comment]
I have tried running **mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen wikipedia.org"**

![image](https://github.com/user-attachments/assets/7d2a10ce-1364-4d5a-b283-b5b2ac27f10e)
