### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by cyrly97** [microsoft/playwright-java#1114]
![image](https://user-images.githubusercontent.com/43930599/200112577-85cf675b-db3b-4106-957e-6295326b87ca.png)

![image](https://user-images.githubusercontent.com/43930599/200112561-0f57e555-a35e-4a91-a283-1a188c906f33.png)

I user env in Idea
![image](https://user-images.githubusercontent.com/43930599/200112671-dc6e01ac-2e08-4896-b083-b70bdd39ad1d.png)
![image](https://user-images.githubusercontent.com/43930599/200112728-605bdf2c-d86b-4291-aad9-603a76224a30.png)

So how to solve this problem?

platform:windows
version: 1.22.0

**Comment by yury-s** [comment]
Try updating to the latest playwright version and run it with `pw:install` environment variable to get more logs, it may give you an idea what breaks. Most likely temp directory where the driver is extracted is not working as intended or some antivirus software blocks access to it.

**Comment by cyrly97** [comment]
> Try updating to the latest playwright version and run it with `pw:install` environment variable to get more logs, it may give you an idea what breaks. Most likely temp directory where the driver is extracted is not working as intended or some antivirus software blocks access to it.

![image](https://user-images.githubusercontent.com/43930599/201291725-7857bd93-e16a-40cb-8e5c-54de675bf1e5.png)
It looks like the system problem,because I use Windows 7.

**Comment by yury-s** [comment]
> It looks like the system problem,because I use Windows 7.

Note that Playwright doesn't officially support Windows 7.
