### ISSUE TITLE
[Question] How to get response body of redirects?

### ISSUE THREAD

**Issue by DSimsek000** [microsoft/playwright-java#1128]
Hi all,

I noticed that accessing the body of a response is not possible if the client has been redirected, for example by an appropriate status code or by meta refresh. My current code looks like this:

```java
final BrowserContext cxt = browser.newContext();
final Page page = cxt.newPage();
page.onResponse(response -> {
    response.body(); // throws error
});
```

It gives me the exception: `Response body is unavailable for redirect response`. 

Is there a way to get the response body regardless?

**Comment by yury-s** [comment]
Currently you cannot, also redirect's body is usually empty. What's your use case?

**Comment by DSimsek000** [comment]
Often redirect responses contain data that can be used for evaluation, e.g. to identify web servers or detect EAR flaws. Thats what I am looking for. Is there a workaround?

**Comment by yury-s** [comment]
You can use APIRequestContext to send an API request with [`setMaxRedirects(0)`](https://playwright.dev/java/docs/api/class-apirequestcontext#api-request-context-get) and get the original response, would that work?

**Comment by DSimsek000** [comment]
I had a look at this class, but afaik the browser itself is not used for this, but only an http request is sent. I had hoped that this was somehow possible within the browser context.
