### ISSUE TITLE
[Question] disabled Chrome is being controlled by automated test software

### ISSUE THREAD

**Issue by cosoc** [microsoft/playwright-java#1129]
![image](https://user-images.githubusercontent.com/19447682/202375999-4b1848c7-efdd-414a-a24d-4af10a7b275b.png)

how to ban this message

![image](https://user-images.githubusercontent.com/19447682/202375344-49b9012c-2b19-4e83-8195-05c090e06ef3.png)

but have

![image](https://user-images.githubusercontent.com/19447682/202375473-e28c9e3d-56c7-4abf-9509-c5b6abd71faf.png)

**Comment by yury-s** [comment]
What does it say when launched in English locale? Also can you share the code that launches the browser and produces the error?

**Comment by cosoc** [comment]
> 在英语语言环境中启动时会说什么？您还可以共享启动浏览器并产生错误的代码吗？

will prompt three messages

1. You are using an unsupported command flag: --no-sandbox. Stability and performance will suffer.
2. The Google API key is missing. Therefore, some functions of Chromium cannot be used
3. Chromium is not your default browser, set default browser.


```java
  public void openAWindow( ) {
      
        Playwright.CreateOptions createOptions = new Playwright.CreateOptions();

        Map<String, String> map = new HashMap<>();
        createOptions.setEnv(map);
        map.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "1");
        Playwright playwright = Playwright.create(createOptions);


        BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions();
        launchOptions.setHeadless(false);


        Path userDataDir =  Paths.get("/tmp" , "browser","chromium");
        File dataDir = new File(String.valueOf(userDataDir));
        if(!dataDir.exists()) {
            dataDir.mkdirs();
        }

        BrowserType.LaunchPersistentContextOptions pcOptions = new  BrowserType.LaunchPersistentContextOptions();
        pcOptions.setHeadless(false);
      
        //   Do not show  [Chrome is being controlled by automated test software]
        pcOptions.setIgnoreDefaultArgs(Arrays.asList(
                 "--enable-automation"
        ));
        BrowserType chromium = playwright.chromium();
        BrowserContext context = chromium.launchPersistentContext(userDataDir, pcOptions);
        

    }
```

There is no error message in the code

**Comment by yury-s** [comment]
All messages look appropriate, this are the message Chrome will show if you use those flags. Is there a reason you set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD and what browser do you download instead?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
