### ISSUE TITLE
[Bug] Chaining Locator.getByRole() returns null

### ISSUE THREAD

**Issue by zhahaoyu** [microsoft/playwright-java#1130]
If I use `page.getByRole()` then chaining the element with another `getByRole()`, it returns null.

It appears that in the implementation, it is returning `null` regardless - https://github.com/microsoft/playwright-java/blob/main/playwright/src/main/java/com/microsoft/playwright/impl/LocatorImpl.java#L248

**Comment by yury-s** [comment]
Thanks for your report! The fix has been published in v1.28.1, please update Playwright to that version.
