### ISSUE TITLE
[Feature] Network Request Interception: keep a request in-flight/pending

### ISSUE THREAD

**Issue by Fabian-K** [microsoft/playwright-java#1136]
Hi all,

when intercepting network requests with https://playwright.dev/java/docs/network#handle-requests is there any way to keep a request in-flight/pending to test the “loading” state in the app?

Thanks, Fabian

**Comment by Fabian-K** [comment]
Awesome, thanks a lot for your support!

**Comment by yury-s** [comment]
The fix will be published in 1.29, if you want to see it earlier you can install 1.29.0-SNAPSHOT.
