### ISSUE TITLE
Wrong version in the getting started guide

### ISSUE THREAD

**Issue by mattiaskagstrom** [microsoft/playwright-java#1147]
The "Getting started" guide is referencing a version that hasn't been released:
https://playwright.dev/java/docs/intro

<dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
      <version>1.29.0</version>
    </dependency>
  </dependencies>

Latest version on https://repo.maven.apache.org/maven2/com/microsoft/playwright/playwright/
is version 1.28.1

**Comment by yury-s** [comment]
The docs have been updated but the Java port (as well as .Net and Python) has not been published yet. Stay tuned.

**Comment by yury-s** [comment]
1.29.0 is now available.
