### ISSUE TITLE
[Question] I'm using Java.  How can I set by default for all my tests creating a screenshot if a test fails.  

### ISSUE THREAD

**Issue by mjim79** [microsoft/playwright-java#1155]

**Comment by yury-s** [comment]
This functionality is apart of Playwright Test runner which is only available in Node.js version of Playwright. In Java you'll have to write this logic manually depending on the testing framework you use. E.g. in JUnit you could implement such logic in @AfterEach test fixture by calling [page.screenshot](https://playwright.dev/java/docs/api/class-page#page-screenshot) in case of test failures. There is no ready solution for that.

**Comment by mjim79** [comment]
Thank you Yury!  Is there any documentation regarding the available and not available features for java?

**Comment by yury-s** [comment]
There is  no feature sheet or something like that, we have [this page](https://playwright.dev/java/docs/languages) but it's quite basic. The biggest difference is that Playwright Test runner is only available in Node.js, other than that all core features (those that allow to test web APIs and are available in all browsers, unlike e.g. extensions) are available in all language ports.
