### ISSUE TITLE
[BUG] Code Compilation Errors in Java Documentation 

### ISSUE THREAD

**Issue by emecas** [microsoft/playwright-java#1158]
This is my first time experimenting with the project and I'm finding difficulties about the current documentation for specific topics.

In addition to syntax/code problems reported here, also with aspects about Maven or basic Java prerequisites, as minimum versions required to use the framework, even incomplete code or descriptions. 

I could help to improve those things, please let me know if this is the right way to report issues and/or if there is place to suggest PRs about improving documentation and provided examples.

**Context:**
page : https://playwright.dev/java/docs/writing-tests

**Code Snippet**

```java
package org.example;

import java.util.regex.Pattern;
import com.microsoft.playwright.*;

import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;

public class App {
    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch();
            Page page = browser.newPage();
            page.navigate("http://playwright.dev");

            // Expect a title "to contain" a substring.
            assertThat(page).hasTitle(Pattern.compile("Playwright"));

            // create a locator
            Locator getStarted = page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Get Started"))

            // Expect an attribute "to be strictly equal" to the value.
            assertThat(getStarted).hasAttribute("href", "/docs/intro");

            // Click the get started link.
            getStarted.click();

            // Expects the URL to contain intro.
            assertThat(page).hasURL(Pattern.compile(".*intro"));
        }
    }
}
```

**Describe the bug**

The previous code has compilation errors

 it's missing an import:
```java
import com.microsoft.playwright.options.AriaRole;
```
and a semicolon at the end of the line creating a locator:

```java
 Locator getStarted = page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Get Started"));
```

**Comment by yury-s** [comment]
Looks like that part of the docs was not fully updated during our recent rewrite of the intro. The sources of the docs live under https://github.com/microsoft/playwright/tree/main/docs/src and this particular file is [here](https://github.com/microsoft/playwright/blob/main/docs/src/writing-tests-java.md). We accept patches, if you want to fix it yourself, just upload a PR to https://github.com/microsoft/playwright After that the docs are rolled periodically to https://github.com/microsoft/playwright.dev and published to playwright.dev
