### ISSUE TITLE
[BUG] Playwright 1.29.0 is not yet available on Maven Central

### ISSUE THREAD

**Issue by emecas** [microsoft/playwright-java#1159]
**Context:**

Playwright 1.29.0 is not yet available on Maven Central, latest version available right now is 1.28.1 released Nov 29, 2022

That cause compilation issues while following  the _**Getting Started, Installation, Usage**_ section [here](https://playwright.dev/java/docs/intro#usage).  The page is referencing the 1.29.0 version in the `pom.xml`

A temporal solution is using 1.28.1

https://mvnrepository.com/artifact/com.microsoft.playwright/playwright

![image](https://user-images.githubusercontent.com/849502/210838355-e9e80a9c-b944-401c-90c8-e990ddd3d2c5.png)
 
**Code Snippet**

```xml
    <dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
      <version>1.29.0</version>
    </dependency>
```

**Describe the bug**

`Missing artifact com.microsoft.playwright:playwright:jar:1.29Java(0)`

**Comment by yury-s** [comment]
1.29.0 is now available.
