### ISSUE TITLE
[Feature] Add taking screenshots-on-failure config property

### ISSUE THREAD

**Issue by darkallure** [microsoft/playwright-java#1169]
Node.js has screenshots-on-failure property in config that you can use to take screenshot upon failure. This is especially useful when you run headless or in container

**Comment by yury-s** [comment]
This is a part of the Playwright Test runner which is only available in Node.js version. In java we recommend using existing testing frameworks with their runners (JUnit, TestNG etc.). I'm closing this issue as there are no plans to bring that support into java but if we decide to port test runner functionality to java it is definitely at the top of the feature list.
