### ISSUE TITLE
[BUG] Version 1.30 is not available on mvn repo, even though the Getting Start Guide indicates to use it.

### ISSUE THREAD

**Issue by erikpragt-connectid** [microsoft/playwright-java#1192]
The installation guide here: https://playwright.dev/java/docs/intro is mentioning to use version 1.30, but it's not available on Maven Repo yet, causing some confusion, which is especially confusing a Getting Started Guide.

I saw there have been similar issues in the past, like https://github.com/microsoft/playwright-java/issues/1159, but maybe it would be better to avoid confusion and only publish the documentation when the release is done?

<img width="717" alt="image" src="https://user-images.githubusercontent.com/119275045/215413915-29f1b1ef-f9dd-48b7-9baf-69ac36d73096.png">

<img width="718" alt="image" src="https://user-images.githubusercontent.com/119275045/215413986-ced6c4e2-99eb-4481-867c-d4d5af3e4f77.png">

**Comment by erikpragt-connectid** [comment]
Thanks for sharing that information, I was unaware of this. I know the statistics on OSS Sonatype are usually 3 weeks behind, but I didn't know publishing is affected now too. Thanks again, I'll close this issue.

**Comment by jasonparallel** [comment]
@yury-s any updates you know of?  The ticket and https://status.maven.org/ seem to point to issues having been resolved.

**Comment by yury-s** [comment]
Should be available now.
