### ISSUE TITLE
[Feature] Apple Silicon support in node executable

### ISSUE THREAD

**Issue by rkennedy-mode** [microsoft/playwright-java#1198]
Attempting to run Playwright (1.29.0) using Java (Azul 17.0.2) on macOS (Monterey 12.5.1) fails with the following error:

```
/var/folders/_0/vt4nh35x6fl9ztp69p2ss5rm0000gq/T/playwright-java-4698062101453362777/playwright.sh: line 6: /private/var/folders/_0/vt4nh35x6fl9ztp69p2ss5rm0000gq/T/playwright-java-4698062101453362777/node: Bad CPU type in executable
```

Unpacking the driver-bundle JAR and examining the bundled version of `node` reveals:

```
➜  file driver/mac/node 
driver/mac/node: Mach-O 64-bit executable x86_64
```

This results in the program failing to execute because it can't install browsers:

```
Exception in thread "main" java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
	at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
	at com.microsoft.playwright.Playwright.create(Playwright.java:110)
	at com.microsoft.playwright.Playwright.create(Playwright.java:114)
	at Scratch.main(scratch_1.java:5)
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: 126
	at com.microsoft.playwright.impl.driver.jar.DriverJar.installBrowsers(DriverJar.java:100)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:69)
	at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)
	... 6 more
```

Can we add proper Apple Silicon support (i.e. without needing to install Rosetta)?

**Comment by yury-s** [comment]
We had [a PR](https://github.com/microsoft/playwright-java/pull/914) doing this, but decided not to land it as it would bloat the driver-bundle package even further while x64 node already worked well under Rosetta. Can you elaborate on the use case when it's not acceptable? Is it Azul specific?

**Comment by rkennedy-mode** [comment]
Ah, yes…I see [a former colleague of mine in that thread](https://github.com/microsoft/playwright-java/pull/914#issuecomment-1212691653) several months back.

The reason is I'm unwilling to install Rosetta. Once installed, Rosetta can not easily be uninstalled. Additionally, having Rosetta installed suppresses notifications if you're about to run an amd64 binary, denying the opportunity to ask, "was there an aarch64 version I could have downloaded, instead?"

Apple doesn't sell Intel laptops anymore aside from the old Mac Pro. If the project is opposed to adding another binary format, one potential solution is to drop the amd64 binary and only package the aarch64 binary.

Alternatively, have playwright.[sh|cmd] install an appropriate node version for the processor architecture.

In the meantime, it looks like maybe I can install my own node executable and have playwright.sh reference it via the `PLAYWRIGHT_NODEJS_PATH` environment variable. I'll give that a shot.

**Comment by rkennedy-mode** [comment]
Unfortunately it looks like com.microsoft.playwright.CLI does not pass environment variables down to the `playwright.sh` process. So setting `PLAYWRIGHT_NODEJS_PATH` doesn't seem to do what you'd hope:

```
➜  playwright-easy-install PLAYWRIGHT_NODEJS_PATH=$(basename $(nvm which default)) && ./mvnw exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps chromium"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< mode:cappie-playwright >-----------------------
[INFO] Building cappie-playwright 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:3.1.0:java (default-cli) @ cappie-playwright ---
/var/folders/_0/vt4nh35x6fl9ztp69p2ss5rm0000gq/T/playwright-java-17354919005993866201/playwright.sh: line 6: /private/var/folders/_0/vt4nh35x6fl9ztp69p2ss5rm0000gq/T/playwright-java-17354919005993866201/node: Bad CPU type in executable
```

It passes a `Collections.emptyMap()` as the environment variables when creating an instance of the Driver class: https://github.com/microsoft/playwright-java/blob/e81b874bbb382894deb6d729057cd7340100e743/playwright/src/main/java/com/microsoft/playwright/CLI.java#L32
