### ISSUE TITLE
[BUG]  Wrong error message when assert checkbox is unchecked

### ISSUE THREAD

**Issue by mgesreha** [microsoft/playwright-java#1209]
**Context:**
- Playwright Version: [1.30.0]
- Operating System: [Windows]
- Browser: [Chromium]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
locator.stream().forEach(locator -> assertThat(locator).isChecked(new LocatorAssertions.IsCheckedOptions().setChecked(false)));
```

**Resulted Error**
`
org.opentest4j.AssertionFailedError: Locator expected to be checked
Call log:
Locator.expect with timeout 5000ms
waiting for locator("[id*=]").first()
  locator resolved to <input checked type="checkbox" id="ClinicalKPIId.PainMe…/>
  unexpected value "checked"
`

**Describe the bug**

I was trying to assert the checkbox is unchecked, and it was checked, the validation works fine, but the main error message was inconsistent, first is say **Locator expected to be checked** and then says **unexpected value "checked"**

**Comment by mxschmitt** [comment]
What you can do as a workaround is: `assertThat(locator).not().isChecked()` which should generate a good error message.
