### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mgesreha** [microsoft/playwright-java#1216]
**Context:**
- Playwright Version: [1.30.0]
- Operating System: [Linux]
- Browser: [Chromium]

**Code Snippet**

```Docker
docker pull mcr.microsoft.com/playwright/java:v1.31.0-focal
Error response from daemon: manifest for mcr.microsoft.com/playwright/java:v1.31.0-focal not found: manifest unknown: manifest tagged by "v1.31.0-focal" is not found
```

**Describe the bug**

When I pull Docker image using the tag and command that is mentioned in PW JAva documentation, I receive an error "manifest tagged by "v1.31.0-focal" is not found"

**Comment by yury-s** [comment]
1.31.0 for java is not published yet.

**Comment by yury-s** [comment]
1.31 including [1.31.0](https://github.com/microsoft/playwright-java/actions/runs/4298279364) docker image have been published.
