### ISSUE TITLE
[Question] How to block certain redirects using routes?

### ISSUE THREAD

**Issue by ryankennedy** [microsoft/playwright-java#1217]
The documentation for [Route.fetch()](https://playwright.dev/java/docs/api/class-route#route-fetch) indicates that we can (as of 1.31, which doesn't seem to have been released anywhere) limit redirects via setMaxRedirects. The documentation for setMaxRedirects, however, indicates that an error will be thrown if the number is exceeded.

There doesn't appear to be any way to be able to step in during each redirection to indicate to Playwright if the redirect is safe/okay to follow. If, for example, I want to prevent the browser from requesting http://sensitive-host.com/secret there's no way to do so safely via the routes functionality because the page could make an explicit request to http://safe-looking-host.com/, which redirects to http://sensitive-host.com/secret. In that example, my route intercept will only see the initial request to http://safe-looking-host.com/, which isn't going to provide sufficient detail for me to know if I should deny the outbound request.

Is there some other way to intercept outbound calls, including redirects, in order to sandbox the browser/page from requesting something that I don't want it to access?

Relatedly, what happened to 1.31? The docs indicate that setMaxRedirects functionality is only available in 1.31+ but the most recent version on [the repo releases ](https://github.com/microsoft/playwright-java/releases) and also [Maven Central](https://central.sonatype.com/artifact/com.microsoft.playwright/playwright/1.30.0/versions) is 1.30.

**Comment by yury-s** [comment]
> Relatedly, what happened to 1.31? 

It has just been release. We usually release language ports with some delay compared to node.js version but the docs are published all at once which may create some confusion.

> Is there some other way to intercept outbound calls, including redirects, in order to sandbox the browser/page from requesting something that I don't want it to access?

As the documentation suggests you can pass 0 to not follow redirects. You'll have to handle each fetch response manually and decide wether you want to send request to the redirected location. Will this work for you?

**Comment by ryankennedy** [comment]
The docs mention “an error will be thrown if the number is exceeded.” So if I set maxRedirects to zero, then send a request using fetch() and the response is a redirect, will that throw or will I be able to inspect the response to examine the redirect and decide if I want to follow it?

It’s unclear what this will look like in practice.

**Comment by yury-s** [comment]
The doc says "Pass 0 to not follow redirects.", so as long as you pass 0 you will get the response  without following any redirects and no errors will be thrown. We can probably improve the wording in the docs.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
