### ISSUE TITLE
[BUG] Playwright package is not available in Maven repository

### ISSUE THREAD

**Issue by apetrovskiy** [microsoft/playwright-java#1222]
The problem is that Playwright JVM package is regularly late to be represented in Maven repository. Whereas docker image is available with 1.31, and (for example) dotnet package is already available
![image](https://user-images.githubusercontent.com/2947151/222115924-26dd3e39-b2fc-4daf-b567-68f3385aff9b.png)
the JVM package is missing and we're getting error like this:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/2947151/222116105-80f9c3cb-52d8-43c6-a184-33108e094f15.png">

### System info
- Playwright Version: docker image 1.31, Maven repository (thus, our gradle) 1.30
- Operating System: any
- Browser: Chrome
- Other info:

### Source code
The mostly related source code is content of build.gradle.kts:
![image](https://user-images.githubusercontent.com/2947151/222116424-9c799ed4-828a-4106-857d-b2ef513a1d2d.png)
![image](https://user-images.githubusercontent.com/2947151/222116546-5b3442d4-07e9-42d2-973b-74b011f00169.png)
we cannot write down 1.31 or 1.31.1 unless nothing is published in Maven repository (or do you use another repository for the first binaries?)

Please fix the missing packages not an ad-hoc, but on regular basis. Thanks in advance

### Use case
Recently, we minimized the time required for downloading browsers by switching our CI/CD to use Playwright docker image.
Earlier it was:
- compilation, code style check, pmd, etc
- downloading of browsers (a time-consuming stage)
- running tests & reporting

Now we are creating a docker image based on yours (soon I'll be taking out browsers only and use a more slim image) and our tests works the following way:
- pulling image with the latest 'develop' (or a specific branch) compiled binaries and with browsers
- run tests over the image pulled
Here is the problem: gradle contains, let's say, version 1.30 and the latest image was built with browsers 1.31
we cannot get package 1.31, so the only option is to hard code the docker image used to 1.30

**Comment by yury-s** [comment]
Docker image for 1.31.0 was published after 1.31.0 packages became available in Maven. I believe what causes confusion is that we publish language ports with some delay after corresponding minor release for Node.js (sometimes after publishing first patch release for the node version). Closing this report as both maven packages for 1.31.0 and docker image are available. Please file a new issue if the problem repeats in the future releases, we'll reconsider the process.

**Comment by yury-s** [comment]
Note also that since docs, docker image and maven packages are published on 3 different pipelines there is inhererently some delay between the 3:
- docs are published for all ports at the same time when next minor release for Node.js is published
- maven packages are published next with some delay as I described above (sometimes it can be a few weeks after Node.js release but more often it is within a week)
- docker image for java is published after the previous step successfully finished and the maven packages are already available.
You can probably wait for the docker image to be available before updating you CI, this way you can be sure that all parts are in place. Hope this helps.

**Comment by apetrovskiy** [comment]
I noticed that the same was when 1.30 was released, and 1.29 too. I can't say about previous ones as at that time we didn't use Playwright docker and updated package versions in gradle manually

**Comment by apetrovskiy** [comment]
"You can probably wait for the docker image to be available before updating you CI, this way you can be sure that all parts are in place."
I used the latest image,l i.e. FROM mcr.microsoft.com/playwright/java to get browsers from.
Manual check in two places: Dockerfile and build.gradle.kts is not what I would like and unfortunately these two files are different to updated from one place.
Okay, I'll inverstigate into how it's possible to check automatically both hub.docker and mavenCentral for both new versions, and how to write down this new version automatically into both Dockerfile and the build.gradle file, via a combination of env. variables and the .env file, probably...

**Comment by yury-s** [comment]
With 1.30 the problem was exacerbated by a maven central outage, see [this thread](https://github.com/microsoft/playwright-java/issues/1192#issuecomment-1408988878).

**Comment by apetrovskiy** [comment]
thank you very much, now the package is available
