### ISSUE TITLE
[Feature] Expose runUntil functionality in Page/Frame objects

### ISSUE THREAD

**Issue by rkennedy-mode** [microsoft/playwright-java#1228]
There's currently no way to drive the [ChannelOwner.runUntil](https://github.com/microsoft/playwright-java/blob/f8fc1068bcf3121e95472fa8aca9e232c34bb3b3/playwright/src/main/java/com/microsoft/playwright/impl/ChannelOwner.java#L105-L115) loop as a Playwright user. The method is package protected and so is the ChannelOwner class.

Playwright users can drive that event loop so long as they do so via one of Playwright's internal conditions, such as waiting for a [console message](https://playwright.dev/java/docs/api/class-page#page-wait-for-console-message) or [page request](https://playwright.dev/java/docs/api/class-page#page-wait-for-request).

There is no way, however, for Playwright users to drive that loop when an external condition is needed (e.g. drive the Playwright event loop while I wait for some CompletableFuture object to finish).

I would like to expose such functionality by adding a method to the Page/Frame (and whatever other objects make sense) along the lines of:

```java
/**
 * Yields execution to the Playwright event loop until the given {@link Supplier} returns true.
 *
 * @param condition The condition to check when determining if the method should continue yielding time to Playwright.
 */
void yieldUntil(Supplier<Boolean> condition) {
    while (!condition.get()) {
        connection.processOneMessage();
    }
}
```

I could take this on myself and submit it as a PR. But I first wanted to know if this was something the project maintainers would consider allowing.

**Comment by rkennedy-mode** [comment]
Draft PR to illustrate what I have in mind: microsoft/playwright-java#1229

**Comment by yury-s** [comment]
You can achieve the same today with code like this:

```java
    while (!condition.get()) {
        page.waitForTimeout(100);
    }
```
but we can probably wrap it into something like `waitUntil(callback)`, let me discuss this with the team in the meeting tomorrow.

**Comment by rkennedy-mode** [comment]
Page.waitForTimeout() executes a full round trip into the browser, which I would like to avoid.

Also, there are [strong caveats in the docs](https://playwright.dev/java/docs/api/class-page#page-wait-for-timeout) against using it for anything other than debugging.
