### ISSUE TITLE
[Feature] Possibility to improve the Locator options API?

### ISSUE THREAD

**Issue by jhyot** [microsoft/playwright-java#1231]
The current recommended Locator API basically always needs some options to select some locator. Example from the manual:
```java
page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Sign in"))
    .click();
```

In the older, not recommended anymore, API, often the desired selector could be passed directly as the first parameter, and the options parameter was used for more special options, e.g. the above line could be written like this:
```java
page.click("button >> text=Sign in");
```
or:
```java
page.locator("button >> text=Sign in").click();
```

The idea of the newer API is good. But compare the readability of the old and new API. The API that was chosen to set any options is very verbose and the selectors more difficult to read as a result. Especially since now a part of the selector is in the options, the level of abstraction varies widely in one line of code: mixing `new Page.GetByRoleOptions()` technical object creation with text to be found on the website.

Further, for setting the individual options, the JavaBean format was chosen (`setXyz()`), although clearly the options objects don't need to be used in any context that expects the bean format. They are actually fluent builders. JavaBean is very old, and newer code in the Java community is distancing itself more and more from that format (see e.g. Java17 Records don't use it).

Most new APIs that use the builder / fluent format opt for the setter methods to just have the same name as the properties, i.e. here just `name(String)`.

In summary, the Playwright Options API has the following deficiencies:
* Inserting technical concerns (i.e. explicit object creation) in the middle of a selector (in the example between `AriaRole.BUTTON` and the selector text)
* The options class is even an inner class, which looks even uglier
* JavaBeans format instead of more modern Builder/Fluent setter format

Obviously, we are here limited somewhat by the Java language, but a better API would be for me something like that:
```java
import static com.microsoft.playwright.Page.getByRoleOptions;

page.getByRole(AriaRole.BUTTON, getByRoleOptions().name("Sign in"))
    .click();
```

with the implementation of getByRoleOptions being just something like:
```java
public static Page.GetByRoleOptions getByRoleOptions() {
    return new Page.GetByRoleOptions();
}
```

Potentially even better, but trickier, would be to have a static factory method maybe with the most commonly used option, so that the method call reads nicely:
```java
import static com.microsoft.playwright.Page.withName;
// or: import static com.microsoft.playwright.Page.GetByRoleOptions.withName;

page.getByRole(AriaRole.BUTTON, withName("Sign in").disabled(false))  // <-- illustrating setting more options
    .click();

// implementation:
public static Page.GetByRoleOptions withName(String name) {
    return new Page.GetByRoleOptions().name(name);
}
```

----

I understand that making such a change is quite difficult for API stability/compatibility reasons, but biting the bullet now for a far better Java Playwright experience indefinitely in the future could be a tradeoff worth making?

**Comment by yury-s** [comment]
> They are actually fluent builders. JavaBean is very old, and newer code in the Java community is distancing itself more and more from that format (see e.g. Java17 Records don't use it).

Unfortunately we are bound to Java 8 which is still widely used, this limits the new language features that we can employ. Re changing the existing API - that ship has sailed, we cannot change the API because of the backwards compatibility that you mentioned. The options syntax is more concise in TypeScript/JavaScript and even .NET, so hopefully java will come up with a more lightweight syntax in the future. I believe people had more readable code by using Playwright Java in Kotlin, this could be another option.

I'm going to close this request as we are not planning to change the options structure for the reasons above.
