### ISSUE TITLE
[Question] Font not loading when enabling basic auth

### ISSUE THREAD

**Issue by cavemansspa** [microsoft/playwright-java#1233]
i am using playwright's pdf feature to print a page that's using fomantic-ui css. the page prints fine with the fomantic css imported font when there's no authorization. however, setting:

` BrowserContext browserContext = browser.newContext(
                    new Browser.NewContextOptions().setExtraHTTPHeaders([
                                    Authorization: 'Basic xxxxxx'
                            ])
            )
`

and running the page results renders fine except that the fomantic css font is not being used. i tried some other solutions (e.g. #3322) from other posted issues, but unable to resolve.

any insight into what would cause the issue?

**Comment by yury-s** [comment]
It's hard to tell what's going on without seeing the code. We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.

You can also ask questions on [discord](https://aka.ms/playwright/discord).

**Comment by Maadtin** [comment]
> UPDATE: for others that may come across this issue.
> 
> by logging network requests, i was able to isolate this to a CORS error on the google fonts request. setting the basic auth headers is resulting in a CORS error, whereas no auth headers loads the font files without issue.
> 
> i have worked around based on: [17631](https://github.com/microsoft/playwright/issues/17631)

But what if u neeed the basic auth headers? I'm having problems with webkit aswell.

**Comment by cavemansspa** [comment]
> But what if u neeed the basic auth headers? I'm having problems with webkit aswell.

you can set basic auth headers @Maadtin. snippets below are how i worked around the problem (i'm using playwright-java).

```
            Browser browser = playwright.chromium().launch(
                    new BrowserType.LaunchOptions()
                            .setArgs(['--disable-web-security'])
            );
```

```
            BrowserContext browserContext = browser.newContext(
                    new Browser.NewContextOptions()
                            .setExtraHTTPHeaders([
                                    Authorization: 'Basic xxxxxx'
                            ])
                            .setBypassCSP(true)
            )
```
