### ISSUE TITLE
[Question] getting chrome-error://chromewebdata/ for page.url()

### ISSUE THREAD

**Issue by xJayVex** [microsoft/playwright-java#1234]
### System info
- Playwright Version: [v1.31.0]
- Operating System: [ Windows 10]
- Browser: [Chromium]

### Code snippet
`
Request request = page.waitForRequest(redirectUri + "*",
                () -> {
                    page.click(LOGIN_BUTTON);
                    page.waitForLoadState(LoadState.NETWORKIDLE);
                });
System.out.println(page.url());`

**Expected**

Hi all,
After login I am redirected to another url which contains a fragment (hash) called 'access_token' 
(e.g. https://test.com/callback#access_token=lkjunyciOi45671NiIsInR5cCI6IkpXVCIsImtpZCI6Ij)
But if I request page.url() I get chrome-error://chromewebdata/.
Is there any way how to get whole url with # fragmet?  

**Actual**
chrome-error://chromewebdata/

**Comment by yury-s** [comment]
> Is there any way how to get whole url with # fragmet?

The URL fragment identifier is not sent to the server by the web browser. If the server redirect response contains it, you can get it by inspecting 'location' header:

```java
    Response resp = page.navigate("http://example.com");
    String location = resp.request().redirectedFrom().response().headerValue("location");
```

> But if I request page.url() I get chrome-error://chromewebdata/.

This means that the network request failed and Chromium ended up on an error page, page.navigate will throw in that case. You can [fulfill](https://playwright.dev/java/docs/api/class-route#route-fulfill) failing response with mock data and then traverse redirect chain as described above.

**Comment by xJayVex** [comment]
Hi Yury,

thank you for your response that helped me to solve my problem.
I used little bit different solution but it works well.

Here is my solution:
page.navigate(url);
page.fill(USERNAME_INPUT, username);
page.fill(PASSWORD_INPUT, password);
Response response = page.waitForResponse("**/*", () -> {
            page.click(LOGIN_BUTTON);
            page.waitForLoadState(LoadState.NETWORKIDLE);
        });
String location = response.request().redirectedTo().response().headerValue("location");

Thank you again and have a nice day.
