### ISSUE TITLE
[Feature] Add image on GitHub Codespace

### ISSUE THREAD

**Issue by MathieuSoysal** [microsoft/playwright-java#1258]
## Introduction

Currently, we need to add this line in the `devcontainer.json` file: 
```bash 
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps"
```
To use *playwright-java* inside your project.

But this is so slow.
## Solution

I wanted to know if is possible to ass the *Playwrgiht-cli* to the GitHub Codespace additional features.
![image](https://user-images.githubusercontent.com/43273304/228881303-5f47f0a5-5721-4462-9dda-2a804610ca45.png)

**Comment by yury-s** [comment]
What it is the action required on Playwright end?  It sounds like a feature request for GitHub Codespace that should be filed in their repository.

**Comment by yury-s** [comment]
We publish [docker images](url) for each release of playwright java, they contain all browser dependencies and the browser binaries themselves. You can [specify](https://code.visualstudio.com/docs/devcontainers/create-dev-container#_create-a-devcontainerjson-file) corresponding image in .devcontainer/devcontainer.json. Will this work for you?

**Comment by mxschmitt** [comment]
Looks out of scope for the Playwright project. Closing it for now since it can be easily done manually or use the official Docker image what we use when working on Codespaces.
