### ISSUE TITLE
[BUG] Unable to open Firefox with setIsMobile(true)

### ISSUE THREAD

**Issue by Mosorathia** [microsoft/playwright-java#1278]
### System info
- Playwright Version: [v1.33]
- Operating System: [Windows.]
- Browser: [Firefox]
- Other info:

### Source code
```
browserType = playwright.firefox();
                browser = browserType.launch(new BrowserType.LaunchOptions().setHeadless(false));
                browserContext = browser.newContext(new Browser.NewContextOptions().setViewportSize(360, 640).setUserAgent(userAgentVal).setIsMobile(true).setHasTouch(true));
- [ ] I provided exact source code that allows reproducing the issue locally.


```

**Expected**

I should be able to open browser in mobile view with given browserContext

**Actual**

It gives an error "The batch file cannot be found" and ends. Works fine for chromium but gives error for firefox when setIsMobile(true)

**Comment by yury-s** [comment]
As the exception's message says Playwright does not support mobile emulation in Firefox:

```
 message='options.isMobile is not supported in Firefox
```
