### ISSUE TITLE
com.microsoft.playwright.PlaywrightException: Error {  message='Browser closed.

### ISSUE THREAD

**Issue by saikiran7702** [microsoft/playwright-java#1281]
The scenario I tried to run works totally fine when I run on local but when I run on pipeline it throws an error, browser closes off with no error.

**SYSTEM INFO :**

Playwright Version: [v1.27.1]
Operating System: [macOS 16.0 ]
Browser: [Chromium]
Java 11
Gradle 

**SOURCE CODE:**

```java
public Page createPlaywrightPageInstance(String browserTypeAsString) {
        BrowserType browserType = null;
        switch (browserTypeAsString) {
            case "Firefox":
                browserType = Playwright.create().firefox();
                break;
            case "Chromium":
                Map<String,String> env = new HashMap<>();
                env.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD","1");
                browserType = Playwright.create(new Playwright.CreateOptions().setEnv(env)).chromium();
                break;
            case "Webkit":
                browserType = Playwright.create().webkit();
                break;  

        }
        if (browserType == null) {
            throw new IllegalArgumentException("Could not launch a browser for type " + browserTypeAsString);
        }
        browser = browserType.launch(new BrowserType.LaunchOptions().setHeadless(false).setExecutablePath(Path.of("browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium"))
                .setProxy(new Proxy("ps01usproxy.es.eoryup.com:8080:8080")
                ));
        page = browser.newPage();
        return page;
```

**ERROR:**

```
com.microsoft.playwright.PlaywrightException: Error {
      message='Browser closed.
    ==================== Browser output: ====================
    <launching> browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --proxy-server=http://ps01usproxy.es.eoryup.com:8080 --proxy-bypass-list=<-loopback> --user-data-dir=/tmp/playwright_chromiumdev_profile-CVCpFZ --remote-debugging-pipe --no-startup-window
    <launched> pid=209
    [pid=209][err] browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium: 1: browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium: Syntax error: "(" unexpected
    [pid=209] <process did exit: exitCode=2, signal=null>
    [pid=209] starting temporary directories cleanup
    =========================== logs ===========================
    <launching> browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --proxy-server=http://ps01usproxy.es.eoryup.com:8080 --proxy-bypass-list=<-loopback> --user-data-dir=/tmp/playwright_chromiumdev_profile-CVCpFZ --remote-debugging-pipe --no-startup-window
    <launched> pid=209
    [pid=209][err] browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium: 1: browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium: Syntax error: "(" unexpected
    [pid=209] <process did exit: exitCode=2, signal=null>
    [pid=209] starting temporary directories cleanup
    ============================================================
      name='Error
      stack='Error: Browser closed.
```

**Comment by yury-s** [comment]
This error has to do with your setup and the browser configuration:

```
[pid=209][err] browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium: 1: browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium: Syntax error: "(" unexpected
```

 Please attach a self-contained example which we can run locally so that we could act on this report.

**Comment by saikiran7702** [comment]
I have placed chromium browser in browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium path and I have set up executable path as below 

 browser = browserType.launch(new BrowserType.LaunchOptions().setHeadless(false).setExecutablePath(Path.of("browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium"))
                .setProxy(new Proxy("ps01usproxy.es.eoryup.com:8080")
                ));

I ran this locally it "PASSED" but wasn’t bale to run on build pipeline.


Can you please elaborate on setup and the browser configuration ?

**Comment by yury-s** [comment]
> Can you please elaborate on setup and the browser configuration ?

Playwright downloads browsers automatically if you don't set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD. Try running without that flag and without custom setExecutablePath, if the problem goes away then it has something to do with how you install `browsers/chrome-mac/Chromium.app/Contents/MacOS/Chromium` on CI. Btw, if you want to test with a vendor build of the browser you can try setting a [channel](https://playwright.dev/java/docs/browsers#google-chrome--microsoft-edge) instead. What is the reason you use custom executable path?

Also you code seems to set executable path to Chromium for all 3 browsers, I don't think this will work for Firefox or WebKit. 

As  I mentioned above it's hard to tell what's going on without a repro.

**Comment by saikiran7702** [comment]
If i don’t  set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD it downloads automatically which gives an error because of firewall issues as it is running inside my. Company’s network. when I run on docker in build pipeline I wouldn’t know if there is a vendor version on the VM that is getting created in side the docker. I don’t  want to run my script against different browsers currently I only want chromium to get succeeded. 

as this is my company’s repo I cannot share the code here. 

As I have mentioned before this only happens on build pipeline and runs perfectly good on local machine.

**Comment by yury-s** [comment]
> when I run on docker in build pipeline I wouldn’t know if there is a vendor version browser present on the VM that is getting created in the docker.

You can preinstall it into that docker image with e.g. `npx playwright install chrome` and then use `setChannel("chrome")`. But it looks like you don't even need a vendor build and using just Chromium in which case our [docker image](https://playwright.dev/java/docs/docker) should already have the browser installed. Can you use that image in your pipeline? 


> As this is my company’s repo I cannot share the code here.
>
> As I have mentioned before this only happens on build pipeline and runs perfectly good on local machine.

Unfortunately we can't help much in that case as the issue has to do with how you run the build pipeline and how the browser gets copied there.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
