### ISSUE TITLE
[Feature] Update java version to java8 within Docker image

### ISSUE THREAD

**Issue by dragonsappire** [microsoft/playwright-java#1284]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Most of us do not use java7 instead of java8, I hope we can upgrade java version to java8.

**Comment by yury-s** [comment]
> Most of us do not use java7 instead of java8, I hope we can upgrade java version to java8.

Our 1.33 docker image goes with Java 17. Did you mean downgrading that to Java 8 instead?

Can you be more specific on what version of docker image you are using and what is not working with currently installed JDK version?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
