### ISSUE TITLE
[Question] Where are sources for docs ?

### ISSUE THREAD

**Issue by paulwwisl** [microsoft/playwright-java#1309]
Where are sources for docs https://playwright.dev/java/docs/docker ?

For example 
https://playwright.dev/java/docs/docker#image-tags
> See [all available image tags](https://mcr.microsoft.com/en-us/product/playwright/java/about).

Should point to https://mcr.microsoft.com/en-us/product/playwright/java/tags
not https://mcr.microsoft.com/en-us/product/playwright/java/about

**Comment by yury-s** [comment]
> Where are sources for docs https://playwright.dev/java/docs/docker ?

https://github.com/microsoft/playwright/blob/main/docs/src/docker.md

In general, sources for playwright.dev are in the main repo: https://github.com/microsoft/playwright/tree/main/docs/src
