### ISSUE TITLE
[Feature] Dockerfile in /examples

### ISSUE THREAD

**Issue by paulwwisl** [microsoft/playwright-java#1310]
I was preparing case example for #1308 to reproduce problem within docker,  
and then I noticed that /examples folder has several good enough example to be tried out.
Just adding `Dockerfile` with image `mcr.microsoft.com/playwright/java:latest` or other specific version

I might find time to do the PR,
but I would not definitely start if you don't like the idea.

So do you think that this project should have an (working) example of [playwright-java](https://github.com/microsoft/playwright-java) usage with `mcr.microsoft.com/playwright/java` docker image?

**Comment by yury-s** [comment]
Not sure what you want to see in the examples. There is already a page [about docker](https://playwright.dev/java/docs/docker#end-to-end-tests) images and how to pull them. It should be good enough to start for people familiar with docker, if one needs to learn more about docker in general they should look at the docker guides. Do you suggest we build another image with the examples baked into it or something else?

**Comment by paulwwisl** [comment]
I have read through https://playwright.dev/java/docs/docker it is too short

Definitely there is no need to 
> build another image with the examples baked into it

But users should be given a hint how to build/run playwright-java scripts with docker

I created https://github.com/paulwwisl/playwright-java-example-in-docker

for this issue check https://github.com/paulwwisl/playwright-java-example-in-docker/blob/main/Dockerfile

**Comment by yury-s** [comment]
The repo that you linked demonstrates basic Docker usage example, we expect people to use Docker guides to learn how to use it. It's up to the clients to decide whether they want to build their own image or just mount a directory with the project files into the container. We'd rather keep the docs concise and focused on playwright specifics.

**Comment by yury-s** [comment]
Closing per the comment above.
