### ISSUE TITLE
[BUG] new WaitForRequestOptions().setTimeout(0) does NOT work

### ISSUE THREAD

**Issue by darkallure** [microsoft/playwright-java#1312]
### System info
- Playwright Version: [v1.35]
- Operating System: [All]
- Browser: [All]
- Other info:

### Source code

Request request = page.waitForRequest(request -> "https://example.com".equals(request.url()) && "GET".equals(request.method()), new WaitForRequestOptions(**).setTimeout(0**),() -> {
  page.getByText("trigger Incorrect request").click();
});

**Steps**
- [Run the test]

**Expected**

The test fails immediately due to 0 timeout (according to the docs it disables timeout)

**Actual**

The test waits indefinitely for the request to be triggered

**Comment by yury-s** [comment]
I cannot reproduce this with the following project: https://github.com/yury-s/bug-java-1312

Please provide a full self-contained repro that we could run locally.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.
