### ISSUE TITLE
[Question]How to set the same key in formData

### ISSUE THREAD

**Issue by zengchao304** [microsoft/playwright-java#1318]
### System info
- Playwright Version: [v1.30]
- Operating System: [Windows.]
- Browser: [ Chromium]
- Other info:

### Source code

```java
import com.microsoft.playwright.*;

        private final String ID_CARD_KEY = "lycxQO.gg_sfzhm";
        private final String CERT_NO_KEY = "lycxQO.cy_zshm";
        private final String VERIFY_CODE_KEY = "yanzhm";
        private final String SCORE_KEY = "lycxQO.applScope";
        private final String CERT_TYPE_KEY = "lycxQO.zslxarr";

        RequestOptions requestOptions = buildCommonRequestOptions();

        FormData formData = FormData.create().set(ID_CARD_KEY, idCard).set(CERT_NO_KEY, StringUtil.EMPTY)
                .set(VERIFY_CODE_KEY, getVerifyCode(apiRequestContext)).set(SCORE_KEY, SCORE_VALUE)
                .set(CERT_TYPE_KEY, CERT_TYPE_VALUE_H)
                .set(CERT_TYPE_KEY, CERT_TYPE_VALUE_S)
                .set(CERT_TYPE_KEY, CERT_TYPE_VALUE_J)
                .set(CERT_TYPE_KEY, CERT_TYPE_VALUE_Y)
                .set(CERT_TYPE_KEY, CERT_TYPE_VALUE_T)
                .set(CERT_TYPE_KEY, CERT_TYPE_VALUE_N)
                .set(CERT_TYPE_KEY, CERT_TYPE_VALUE_X)
                .set(CERT_TYPE_KEY, CERT_TYPE_VALUE_Q);

        requestOptions.setMethod(HttpMethod.POST.name()).setHeader(HttpHeaders.REFERER,
                seamanBrowserConfig.getRequestUrl()).setForm(customerFormData);

        APIResponse apiResponse = apiRequestContext.post(seamanBrowserConfig.getRequestUrl(), requestOptions);
```

**Steps**

How can I set multiple identical "lycxQO. zslxarr" strings in FormData?
Just like I saw in the network tab of Chrome devtool that its request parameter formData looks like this
![image](https://github.com/microsoft/playwright-java/assets/40383836/8539c2a5-599c-4760-a617-2b88d8dfe4de)
How to construct the same parameters in formData？

**Expected**

construct the same parameters in formData

**Actual**

![image](https://github.com/microsoft/playwright-java/assets/40383836/014c45f1-40f8-4ccd-a46b-5932f6d3f79f)
Due to the fact that the fields in the FormDataImpl class are LinkedHashMap, there can only be one key for 'lycxQO. zslxarr'. Can we consider using IdentityHashMap to allow for the same key?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/26520.
