### ISSUE TITLE
[BUG]formData[0].value: expected string, got object

### ISSUE THREAD

**Issue by zengchao304** [microsoft/playwright-java#1319]
### System info
- Playwright Version: [v1.30]
- Operating System: [Windows]
- Browser: [Chromium]
- Other info:

### Source code
I want to construct a formData request parameter as shown in the following pics：

![image](https://github.com/microsoft/playwright/assets/40383836/7a8a7520-66d6-4e63-889d-43459b3f6f3b)

![image](https://github.com/microsoft/playwright/assets/40383836/2e0192b3-fc69-4964-ae17-ed3f506b3e61)

![image](https://github.com/microsoft/playwright/assets/40383836/228d395b-a934-42ce-8d0a-1e289a287541)

**Expected**

I want to construct a formData request parameter with value as an array type.

**Actual**

But! Error reported, as shown in the image above.
How can I construct a formData request parameter with an array type value?

**Comment by yury-s** [comment]
You have to manually serialize JsonArray to string first:

```java
    JsonArray value = new JsonArray();
    value.add("foo");
    value.add("bar");
    context.request().post(url, RequestOptions.create().setForm(
      FormData.create()
        .set("arrayField", value.toString())));

```
