### ISSUE TITLE
[BUG] File explorer stays open after uploading an image

### ISSUE THREAD

**Issue by NICOGTZL** [microsoft/playwright-java#1323]
### System info
- Playwright Version: [v1.32.0]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info: Apparently when playwright loads a file the file explorer stays open, causing an error in other functions as it appears that when the file explorer opens, other locators cannot be found or filled.

### Source code
![Capture](https://github.com/microsoft/playwright-java/assets/99368878/1f00f9fe-d66a-4f18-ba80-55f8f8e72836)

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```
    public static void main(String[] args) throws Exception {
        Playwright playwright = Playwright.create();
        Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
        BrowserContext browserContext = browser.newContext());
        Page page = browserContext.newPage();
        
        // Cannot publish the website I am working in, sorry.
        page.navigate("x.com");
        page.waitForLoadState(LoadState.NETWORKIDLE);

        uploadPhotos(page, "C:/Users/xUser/Pictures/panel.png");

    }

// I have tried:

    private static void uploadPhotos(Page page, String photoPath) {
        try {
            page.setInputFiles("input[type='file']", Paths.get(photoPath));

            page.waitForLoadState(LoadState.NETWORKIDLE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
// And:
    private static void uploadPhotos(Page page, String photoPath) {
        try {
            FileChooser fileChooser = page.waitForFileChooser(() -> {
                page.getByText("UPLOAD IMAGE").click();
            });
            fileChooser.setFiles(Paths.get(photoPath));
            
            page.waitForLoadState(LoadState.NETWORKIDLE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

**Steps**
- Copy the method

**Expected**

The file explorer should be closed right after the file is uploaded.

**Actual**

The file explorer keeps opened after the file is uploaded.

**Comment by yury-s** [comment]
`page.setInputFiles` does not open file chooser at all. Your code/page is probably triggering it somewhere else. Please share full self-contained example including the page where the code is failing, you can reduce it to a minimal page which would not expose any proprietary details. We cannot help you without a repro, sorry.

**Comment by mxschmitt** [comment]
Closing since we don't have a repro. Please re-file with a repro, thanks!

**Comment by rubini881213** [comment]
The below code also always opened the file explorer window & After uploading images to layer 1, it is opening file explorer 5 times. It is uploaded the images only in layer 1. It is not uploaded images for other layers since file explorer is opened always. How to handle this to upload images for other layers also (layer 2, layer 3,layer 4 & layer 5) ? 
async addImages() {
const dm=5;
        for(let i=1; i<=dm; i++){
        await this.page.getByPlaceholder('Enter new layer').click();
        await this.page.getByPlaceholder('Enter new layer').fill(`layer ${i}`);
        await this.page.getByText('Add').nth(0).click();
        await this.page.waitForLoadState("domcontentloaded");
        await this.page.getByRole('button', { name: `layer ${i}` }).click();
        await this.page.waitForLoadState("domcontentloaded");
        await this.page.locator('div').filter({ hasText: /^Upload Image$/ }).nth(1).click();
        await this.page.setInputFiles("input[type='file'][accept='image/png,.png']", [
          'uploads/Rose.png',
          'uploads/image.png'
        ]);
        await this.page.waitForLoadState("domcontentloaded");
        }
        }
