### ISSUE TITLE
[Feature] Support Debian 12

### ISSUE THREAD

**Issue by lin-mt** [microsoft/playwright-java#1334]
At [playwright](https://github.com/microsoft/playwright), it seems that 1.37 is planned to support Debian 12, which version of playwright-java is planned to support it, is it also 1.37.0?

https://github.com/microsoft/playwright/pull/24090
https://github.com/microsoft/playwright/issues/24028
https://github.com/microsoft/playwright/issues/23532

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/23532

Yes, 1.37

**Comment by lin-mt** [comment]
> Folding into [microsoft/playwright#23532](https://github.com/microsoft/playwright/issues/23532)
> 
> Yes, 1.37

Is there a plan for when version 1.37 will be released?
