### ISSUE TITLE
[BUG] page.offResponse doesn't work

### ISSUE THREAD

**Issue by chenxing890** [microsoft/playwright-java#1338]
**Steps**
`
 Playwright playwright = Playwright.create();
        BrowserType.LaunchOptions options = new BrowserType.LaunchOptions().setHeadless(false);
        Browser browser = playwright.chromium().launch(options);

        BrowserContext browserContext = browser.newContext();

        Page page = browserContext.newPage();

        page.onResponse(response -> {
            System.out.println("onResponse :" + response.url());
        });

        page.navigate("https://www.google.com");
        page.waitForLoadState(LoadState.NETWORKIDLE);

        page.offResponse(r -> {
            System.out.println("remove onResponse");
        });

        page.navigate("https://www.facebook.com/");

        page.waitForLoadState(LoadState.NETWORKIDLE);
`

**Expected**

Do not output Facebook's response

**Actual**

Output Facebook's response。

[Describe actual behavior]

```[tasklist]
### Tasks
```

**Comment by yury-s** [comment]
There are two different instances of the handler in your code snippet, you add one and remove the other (which has not been added so it's a no-op). You should make sure that the same handler instance is removed as was added, which can be achieved by storing it in a variable:

```java
    Consumer<Response> responseConsumer = response -> {
        System.out.println("onResponse :" + response.url());
    });
    page.onResponse(responseConsumer);

    page.navigate("https://www.google.com");
    page.waitForLoadState(LoadState.NETWORKIDLE);

    page.offResponse(responseConsumer);
```
