### ISSUE TITLE
[Feature]Support screenshots of specific scenarios

### ISSUE THREAD

**Issue by v-chenyiqiang** [microsoft/playwright-java#1347]
I have a scene where the page consists of three areas: top title bar, left menu bar, and right content bar. Among them, only the right content bar supports scrolling. 
When I try to use Page. ScreenshotOptions(). setFullPage (true), it can only capture the size of the visible area, without the effect of scrolling long images. Then I couldn't achieve it by switching to element level screenshots.
 Before reading the explanation from the boss and others, the principle of this screenshot is to change the window size and start calculating from (0,0), so theoretically, I can only use setViewportSize.Is it possible to support this scenario in the future？
Looking forward to the boss's answer, thank you

**Comment by yury-s** [comment]
Unfortunately, it is not currently possible today to take screenshot of the full element if it doesn't fit into viewport, see https://github.com/microsoft/playwright/issues/23845.
