### ISSUE TITLE
[QUESTION] How can I disable onDialog listener?

### ISSUE THREAD

**Issue by LichieLich** [microsoft/playwright-java#1352]
Hi!

I use `onDialog` method to handle browser dialog boxes. But if there is no one, listener remains in page instance. So if I have this situation:
```
page.onDialog(dialog -> dialog.dismiss());
page.getByRole(AriaRole.BUTTON).click(); // but this click doesn't create browser dialog for some reasons

// I need to disable onDialog here

page.onDialog(dialog -> dialog.accept());
page.getByRole(AriaRole.BUTTON).click(); // This one creates dialog box
```

The dialog from second button click will be handled with first `onDialog` and the second one will be failed with exception: 

> "Cannot accept dialog which is already handled!"

How can I disable `onDialog` before next `onDialog`? This happens even with `onceDialog` because first button click doesn't create browser dialog. `offDialog` doesn't help with this.

**Comment by yury-s** [comment]
> offDialog doesn't help with this.

It should. You didn't provide source code of the actual test, so it's hard to tell what exactly is wrong, but this code works (prints "Dialog" exactly once):

```java
    Consumer<Dialog> handler = dialog -> {
      System.out.println("Dialog");
      dialog.dismiss();
    };
    page.onDialog(handler);
    page.evaluate("alert(1)");
    page.offDialog(handler);
    page.evaluate("alert(1)");
```

Feel free to create a new issue with full self-contained repro if it still doesn't work for you.

**Comment by LichieLich** [comment]
Thanks a lot, I just did it in a wrong way. Your solution works.
