### ISSUE TITLE
[BUG] Failed to decompress 'deflate' encoding: Error: incorrect header check

### ISSUE THREAD

**Issue by sanfeng790** [microsoft/playwright-java#1354]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```
 RequestOptions requestOptions = buildCommonRequestOptions()
                .setHeader(HttpHeaders.CONTENT_TYPE, APPLICATION_JSON_UTF8_VALUE)
                //.setHeader(HttpHeaders.ACCEPT_ENCODING, "*")
                .setHeader(HttpHeaders.REFERER, irseBrowserConfig.getReferer())
                .setData(JacksonConverter.write(parameDO));

        APIResponse apiResponse = apiRequestContext.post(irseBrowserConfig.getDetailUrl(), requestOptions);
```
**Steps**
- [Run the test]
- [...]

**Expected**
[Describe expected behavior]

Actual
Failed to decompress 'deflate' encoding: Error: incorrect header check
[Describe actual behavior]

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a self-contained repro and link it to this one.
