### ISSUE TITLE
[BUG] Paywright with java throws error when running with Newcontextoptions.setRecordVideoDir from linux machine pointing to selenium grid

### ISSUE THREAD

**Issue by akashbondar** [microsoft/playwright-java#1355]
### System info
- Playwright Version: [v1.34]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

I have added additional env variable: playWrightCreateOptions.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD","1");

`BrowserContext browserContext = getBrowser().newContext(new NewContextOptions()
                        .setRecordVideoDir(Paths.get(videoRecordingPath)));` -->This works perfectly fine from  local MAC also when pointing to selenium grid from local mac it works fine. 

But when I am running same code with Linux machine pointing to selenium grid it throws the error (Detsiled error pasted at the end).

Please note when I am removing newcontext options then it is workiing from linux machine as well.

So the only problem is with adding **NewContextOptions** and then executing the code from linux machine

Error is thrown before starting any test. It justs connects with selenium grid and then before launching the browser below error is thrown

**Complete Error:**

```
tmp/playwright-java-9059110801962375538/package/lib/server/chromium/crPage.js:377
      this._firstNonInitialNavigationCommittedReject(new Error('Page closed'));
                                                     ^

Error: Page closed
    at CRSession.<anonymous> (/tmp/playwright-java-9059110801962375538/package/lib/server/chromium/crPage.js:377:54)
    at Object.onceWrapper (node:events:627:28)
    at CRSession.emit (node:events:525:35)
    at /tmp/playwright-java-9059110801962375538/package/lib/server/chromium/crConnection.js:211:39
```

Node.js v18.16.0

**Comment by yury-s** [comment]
> Playwright installation is required for NewContextOptions() .setRecordVideoDir. For normal context creation playwright installation is not needed on the machine from which we are triggering the code.

Can you elaborate on what you mean by 'Playwright installation is required'? You do need playwright modules to be present on the machine that connects to a remote browser. I assume it's already there as otherwise you wouldn't be able to create playwright instance and connect to a browser. Depending on how you connect to the remote machine you may need to have playwright on the remote server, but if you use [connectOverCDP](https://playwright.dev/java/docs/api/class-browsertype#browser-type-connect-over-cdp) then you just need to launch Chromium on the remote machine. Can you share the code and full logs?

**Comment by akashbondar** [comment]
We are exporting a jar file on linux machine(where playwright is not insatalled) which contains playwright dependency (1.37) and then we are running this using mvn test command pointing to remote selenium grid env  with option - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD","1". Now when I run this without adding the code: NewContextOptions() .setRecordVideoDir it works fine . And when this code for video is added , playwright fails to launch the browser with the error: tmp/playwright-java-9059110801962375538/package/lib/server/chromium/crPage.js:377
      this._firstNonInitialNavigationCommittedReject(new Error('Page closed'));.
   So I installed playwright in linux machine and ran the code for video and it worked. 
   I am not sure but from above steps it seems in playwright java module is missing some library/functionality required for video recording

**Comment by yury-s** [comment]
I cannot reproduce it with the following steps:

1. Launch docker with the following command: `docker run -p 9222:9222 -it --rm --ipc=host mcr.microsoft.com/playwright/java:v1.37.0-jammy /bin/bash`
2. Launch chrome inside docker: `/ms-playwright/chromium-1076/chrome-linux/chrome --no-sandbox --headless --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0`
3. Run the following test with the websocket address printed in the previous step passed as a parameter to `connectOverCDP` using `mvn compile exec:java -Dexec.mainClass=org.example.PrintTitle`:

```java
package org.example;

import com.microsoft.playwright.*;

import java.nio.file.Paths;

public class PrintTitle {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().connectOverCDP("ws://127.0.0.1:9222/devtools/browser/6afd0842-5aa7-4ff8-9923-6d6cb759d776");
      BrowserContext context = browser.newContext(new Browser.NewContextOptions().setRecordVideoDir(Paths.get("/tmp/videos")));
      Page page = context.newPage();
      page.navigate("http://playwright.dev");
      context.close();
    }
  }
}
```

Everything works fine, video is recorded.

**Comment by yury-s** [comment]
Please provide a minimal self-contained project that we could run locally to reproduce the problem.

**Comment by mxschmitt** [comment]
Closing for now since its stale and we need a reproduction in order to triage this further. Please re-file for further questions/bug reports since we don't monitor closed issues, thanks!
