### ISSUE TITLE
[Bug/Feature] Video Recordings and Screenshots should capture the URL bar as well if possible

### ISSUE THREAD

**Issue by pabitra-qa** [microsoft/playwright-java#1359]
As, we are using Playwright for our UI tests, it's really important to have a trace of the environment or URL we are using. Hence Video Recordings and Screenshots should capture the URL bar as well if possible.

**Comment by yury-s** [comment]
Playwright only captures web content of the page and the browser window is not a part of it. You can capture the URL of the page via [Page.url()](https://playwright.dev/java/docs/api/class-page#page-url). Also if you need it to be on the picture you can add a DOM element with the label positioned on top of the page's content before taking a screenshot. Closing this request as it's out of scope of the project.
