### ISSUE TITLE
[Feature]Timeout error in playwright Java

### ISSUE THREAD

**Issue by siva90144** [microsoft/playwright-java#1363]
When executing the automation script, it waits for the element and its failing for 30 seconds. Is there a way to set this to 1 min?
For my Application, it is 1 min.
FYI... I am using playwright java with cucumber
`com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("#somethingToDo")
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("#somethingToDo")
============================================================
    at ProgressController.run (/private/var/folders/tz/rq17vzrs1lvcpy9cwv1rbcd80000gr/T/playwright-java-16364056006871193493/package/lib/server/progress.js:88:26)
    at Frame.click (/private/var/folders/tz/rq17vzrs1lvcpy9cwv1rbcd80000gr/T/playwright-java-16364056006871193493/package/lib/server/frames.js:1003:23)
    at FrameDispatcher.click (/private/var/folders/tz/rq17vzrs1lvcpy9cwv1rbcd80000gr/T/playwright-java-16364056006871193493/package/lib/server/dispatchers/frameDispatcher.js:151:30)
    at DispatcherConnection.dispatch (/private/var/folders/tz/rq17vzrs1lvcpy9cwv1rbcd80000gr/T/playwright-java-16364056006871193493/package/lib/server/dispatchers/dispatcher.js:312:46)
}`

**Comment by NikkTod** [comment]
if you want to wait for an element for 60 seconds do this:

`page.locator("......").waitFor(new Locator.WaitForOptions().setState(WaitForSelectorState.ATTACHED).setTimeout(60000));`

You can also use assert:

`assertThat(page.locator(".....")).isVisible(new LocatorAssertions.IsVisibleOptions().setTimeout(60000));`

**Comment by siva90144** [comment]
Thanks @NikkTod. it worked :)

**Comment by goshcc** [comment]
My program executes the following code, continuously taking screenshots for over three or four hours. However, suddenly subsequent requests fail to load; it freezes at the `screenshot` function and only recovers after restarting the Java process. I've checked the Chrome process and thread pool queue, and they appear fine. It seems like some kind of exception is preventing the screenshot resources from being retrieved.
 
my code like:try (Playwright playwright = createPlaywright()) {
            Browser browser = getBrower(playwright);

            try (BrowserContext context = getBrowserContext(browser)) {
                Page page = context.newPage();
                page.setDefaultTimeout(PAGE_TIMEOUT_MS);
                page.addInitScript(STEALTH_SCRIPT);
                page.navigate(url, new Page.NavigateOptions()
                        .setWaitUntil(WaitUntilState.DOMCONTENTLOADED)
                        .setTimeout(5000));
                page.waitForTimeout(waitingTime);
                beforeScreenshot(url, page);
                page.screenshot(new Page.ScreenshotOptions()
                        .setPath(tempFile)
                        .setFullPage(true)
                        .setTimeout(10000));

my log is:
com.microsoft.playwright.TimeoutError: Error { message='Timeout ms exceeded. name='TimeoutError stack='TimeoutError: Timeout 25000ms exceeded. at ProgressController.run (/tmp/playwright-java-3241808961379444685/package/lib/server/progress.js:86:28) at PageDispatcher._runCommand (/tmp/playwright-java-3241808961379444685/package/lib/server/dispatchers/dispatcher.js:91:31) at DispatcherConnection.dispatch (/tmp/playwright-java-3241808961379444685/package/lib/server/dispatchers/dispatcher.js:325:39) } Call log: - - taking page screenshot - - waiting for fonts to load... - - fonts loaded at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:52)
