### ISSUE TITLE
[BUG] Failed to read message from driver, pipe closed.

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright-java#1364]
### System info
- Playwright Version: [v1.32]
- Operating System: [Windows 10]
- Browser: [playwright version browsers, chromium v1055]
- Other info:
java 11
surefire version 2.22.2
cucumber 7.11.1
junit 4.13.2
org.testng 7.7.0

**Steps**

**All is working fine on 1.31.0**

Problem starts from 1.32.0 and onwards

Because of organization policies we are not allowed to download any external jars/software hence I added PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

When starting the tests with `mvn test` the initializing of playwright is failing, see below screenshow.

![image](https://github.com/microsoft/playwright-java/assets/94455079/e9974de0-4539-48d9-b2ec-06d0014c9439)

**Comment by yury-s** [comment]
Did you pre-install browsers? In this mode you are supposed to download and install them yourself, see [this page](https://playwright.dev/java/docs/browsers#managing-browser-binaries).

**Comment by NikkTod** [comment]
@yury-s, on the machine I have chrome (114.0.5735.134) and edge already installed. With playwright version 1.30 and 1.31 all is working fine browser is started, but from 1.32 playwright initialization is failing.

**Comment by NikkTod** [comment]
Found the problem, I had "" for the env variable PLAYWRIGHT_NODEJS_PATH due to a previous bug, so it seems that this was fixed in 1.32 and I had to remove the "".
