### ISSUE TITLE
[BUG] IOException: Stream closed on 1.31 and onwards within TeamCity

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright-java#1367]
### System info
- Playwright Version: [v1.31]
- Operating System: [Linux amd 64]
- Browser: [Chrome]
- Other info: TeamCity

Tests are running fine with 1.30.0

The issue starting to appear in 1.31.0.   

When running the tests with the following env variable set DEBUG=pw:browser,pw:install, pw:channel,pw:protocol

I get the following error (sorry that it is a screenshot, I am not able to copy content out of the machine)

![image](https://github.com/microsoft/playwright-java/assets/94455079/5a02dfe7-7d07-4097-95eb-eb5b803610c8)
![image](https://github.com/microsoft/playwright-java/assets/94455079/eb091f4c-46b6-4e87-a191-99a35d717c75)
![image](https://github.com/microsoft/playwright-java/assets/94455079/ea14cd08-a661-40d3-b742-437beb2d288f)
![image](https://github.com/microsoft/playwright-java/assets/94455079/097e4b93-6d3e-47b8-9ad5-ad61f6636bc6)
![image](https://github.com/microsoft/playwright-java/assets/94455079/1345fa3e-2539-4345-84e7-a7efcc540112)

**Comment by yury-s** [comment]
Sounds like a problem with running the driver from `tmp` directory. Can you share a repro?

**Comment by NikkTod** [comment]
Hey @yury-s I am attaching a screenshot of the env variables that I have added 

![image](https://github.com/microsoft/playwright-java/assets/94455079/fe78b542-12f2-4a2f-94ac-45e64d02e681)

Interesting it what has changed in the code in 1.31, which could cause that issue.

**Comment by yury-s** [comment]
> Interesting is what has changed in the code in 1.31, which could cause that issue.

We bumped Node.js version in the driver from 16 to 18 which may have something to do  with the error.

**Comment by yury-s** [comment]
The driver used by playwright-java has Node.js 18 bundled and it might be failing for the same reason. You can set a breakpoint at line https://github.com/microsoft/playwright-java/blob/86f929aaf0c58eb4c6a27f4cdcb5adb6180bb6cc/driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java#L68 and the try to launch node from the  temp directory to see if it throws or works just fine. 

You can also try running by instructing Playwright to use preinstalled node via `PLAYWRIGHT_NODEJS_PATH` environment variable. Can you try this and see if the problem persists?

**Comment by NikkTod** [comment]
@yury-s, I was trying with PLAYWRIGHT_NODEJS_PATH within TeamCity, but still the same error appeared. 

Locally I am using also PLAYWRIGHT_NODEJS_PATH pointing to 16.14.0 and all is working fine. 

What I see from the debug logs is that driver is initialized and then we have this Stream Closed.

![image](https://github.com/microsoft/playwright-java/assets/94455079/84b54e1e-7703-487a-ab4c-17d87796871d)

Very difficult to build you a repro :(

**Comment by yury-s** [comment]
It's hard to tell what's failing without a repro. Maybe you can reproduce it in a docker container?

> and the try to launch node from the temp directory to see if it throws or works just fine.

Did you try this? If you run `/tmp/playwright-java-5068179633187653821/playwright.sh` it should print playwright help if everything works fine.

**Comment by NikkTod** [comment]
I played around also with the playwright.driver.tmpdir in order to set different directory, but still the same problem. 

Actually setting up PLAYWRIGHT_NODEJS_PATH broke also the 1.30 version with the same error.

So it seems it is something connected to the node js version and the only thing I can do is find another TeamCity agent.

Thanks for the help Yury, I will close the ticket.
