### ISSUE TITLE
Is there a way to set chrome driver version in Playwright with Java? Due to some security issue, our Jenkins servers are not allowed to use internet for downloading chromedriver

### ISSUE THREAD

**Issue by gaurav05153** [microsoft/playwright-java#1372]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      // ...
    }
  }
}
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

To be clear about my question, I am not looking for setting the chrome binary version as I tried to set up chrome binary version installed at my system with setExecutablePath method and it was working.

Apart from chrome binary, I want to set the path of chromedriver version too as I am not allowed to download it on run time while running my test scripts on Jenkins. I can only download it manually and keep it somewhere in my system.

**Comment by yury-s** [comment]
Playwright does not use chromedriver. Everything except browser binaries is packaged as Maven modules and should not require any extra downloads. Can you explain what is not working in your case?

**Comment by gaurav05153** [comment]
After manually downdoading and adding the chrome binary, I can see that browser is getting opened and my application is also launched.

After that, I have a method which adds userid and password to login page and gets into application. This is working perfectly on my local 
but on Jenkins, playwright is not able to do any action. Not even enter username and password there, waiting for some time and gives Playwrightexception( message='Execution context was destrooyed, most likely because of navigation.

I can also see that below is appearing in log
Driverexception( message='Execution context was destrooyed, most likely because of navigation.

Note I am passing -Dplaywright.driver.tmpdir=./target/ with mvn test. I can see that it adds a folder with name playwright-java and adds node.exe on my local and test cases are running. I am assuming, on Jenkins playwright is trying to do the same but not able to do the same.

**Comment by gaurav05153** [comment]
Thanks for your response Yury. I thougt to get rid of chrome version issues, let's use the docker container where chrome will be already there. I tried with both the containers mcr.microsoft.com/playwright/java:v1.36.0-jammy and mcr.microsoft.com/playwright/java:v1.37.0-jammy.

But test cases are not getting executed. it is looking for the chrome and giving below error:
Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome

Even after using container, test cases are not getting executed.

**Comment by yury-s** [comment]
> But test cases are not getting executed. it is looking for the chrome and giving below error:
> Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome

Playwright images only contain open-source browser builds (i.e. chromium not google chrome). See [this page](https://playwright.dev/java/docs/browsers#google-chrome--microsoft-edge) for more details. Looks like you set browser channel to "chrome", in which case you need to install it yourself, e.g.

```bash
mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install msedge"
```

**Comment by mxschmitt** [comment]
Also to note is that `install msedge` or `install chrome` will also always install the latest version. There is no way of installing a specific Microsoft Edge or Google Chrome version except channels which are 1 or 2 releases in the future. They don't allow it and want to make sure you are using the latest version, like users do.

Closing as per above.
