### ISSUE TITLE
centos7:failed to create driver

### ISSUE THREAD

**Issue by Cesslia** [microsoft/playwright-java#1379]
We need to deploy our program on the Centos7, but after running it, an error was reported indicating failed to create driver, but i found several playwright programs in /tmp.
![image](https://github.com/microsoft/playwright-java/assets/49901423/515c2a84-6b0c-48bf-a217-8476124b133d)
and this is what in the playwright folder
![image](https://github.com/microsoft/playwright-java/assets/49901423/4441a6c8-2a76-44a6-a629-b54d6903c28c)
Where should I check the logs of playwright ？

**Comment by yury-s** [comment]
Centos is [not officially supported](https://playwright.dev/java/docs/intro#system-requirements), see this [feature request](https://github.com/microsoft/playwright/issues/9199). You can try enabling logs with `DEBUG=pw:install`
