### ISSUE TITLE
[BUG] java.lang.OutOfMemoryError: Required array size too large when uploading large files

### ISSUE THREAD

**Issue by railwayursin** [microsoft/playwright-java#1381]
### System info
- Playwright Version: [v1.37]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

We use `page.setInputFiles(String selector, Path[] files)` to trigger file uploads in our tests. When using large or many files (in one case  2 files, 7GB in total) a `java.lang.OutOfMemoryError` will be thrown.

```java
java.lang.OutOfMemoryError: Required array size too large
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3294)
	at com.microsoft.playwright.impl.Utils.toFilePayload(Utils.java:239)
	at com.microsoft.playwright.impl.Utils.toFilePayloads(Utils.java:231)
	at com.microsoft.playwright.impl.FrameImpl.setInputFilesImpl(FrameImpl.java:773)
	at com.microsoft.playwright.impl.PageImpl.lambda$setInputFiles$74(PageImpl.java:1171)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.PageImpl.setInputFiles(PageImpl.java:1170)
	at com.microsoft.playwright.Page.setInputFiles(Page.java:6779)
...
```

The `hasLargeFile()` check in `FrameImpl.setInputFilesImpl(String selector, Path[] files, SetInputFilesOptions options)` returns `false` for the 7GB files, but should be `true`.

When debugging the method `Utils.hasLargeFile(Path[] files)`, the calculated `totalSize` of the files overflows to `-1204753599` making the method return false. Playwright will then try to load the files into memory, causing the `java.lang.OutOfMemoryError`.

```java
  static boolean hasLargeFile(Path[] files) {
    int totalSize = 0;
    for (Path file: files) {
      try {
        totalSize += Files.size(file);
      } catch (IOException e) {
        throw new PlaywrightException("Cannot get file size.", e);
      }
    }
    return totalSize > maxUplodBufferSize;
               ^ -1204753599, in my case, it should be 7385180993
  }
```

As a fix, I would suggest to replace the type for `totalSize` with long or something else more suitable.

Many thanks - U

**Comment by yury-s** [comment]
@railwayursin would you like to send a pull request with a fix?

**Comment by railwayursin** [comment]
@yury-s, could you please estimate how long it would take until a pull request would be merged and used in a release?

**Comment by yury-s** [comment]
We are going to release java port this week, probably today, so it can make it into this release. If not next release is going to be in about a month from now.

**Comment by railwayursin** [comment]
@yury-s,  When the fix makes it into the next or the one after next is perfect. I prepared a fix. But I am not allowed to push the branch to the repository.

```bash
19:20:12.176: [playwright-java] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/fix-setfiles-oom:refs/heads/fix-setfiles-oom --set-upstream
remote: Permission to microsoft/playwright-java.git denied to railwayursin.
fatal: unable to access 'https://github.com/microsoft/playwright-java/': The requested URL returned error: 403
```

**Comment by yury-s** [comment]
You need to fork the repo, push a fix a branch in the fork and then create a PR from it which we will merge.
