### ISSUE TITLE
[BUG] playwright url navigation issue

### ISSUE THREAD

**Issue by siva90144** [microsoft/playwright-java#1382]
I am using page.navigate("url") to launch the application.

When I try to run locally it will take SSO authentication(When i connected to VPN). when i try to run in Jenkins it will ask authentication.

I have coded as below and url will redirect to multiple times with random ID's. After first redirect, its trying to find the elements. 

```java
page.navigate("url");

 page.waitForLoadState(LoadState.DOMCONTENTLOADED);
 page.waitForLoadState(LoadState.NETWORKIDLE);
 if (!page.isVisible(profile)) {
                if(page.isVisible(userName,new Page.IsVisibleOptions().setTimeout(5000))) {
                    page.fill(userName, Util.getProperty("userName"));
                    page.fill(password, Util.getProperty("password"));
                    page.click(login_btn);
                }
   }
 page.click(profile);
```

But the problem is before loading the url, its going to find the elements and script is failing . 
here I want to wait before visible method to come into picture. Also I don't want to use hard wait like thread.Sleep()
how can I resolve the issue?

**Comment by yury-s** [comment]
`isVisible` does not wait for the element to become visible and its timeout parameter is ignored as mentioned in the documentation. You can try [`assertThat(locator).isVisible()`](https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-be-visible) which will auto-wait for the element to become visible. Will that work?
