### ISSUE TITLE
[BUG] playwright url navigation issue1 

### ISSUE THREAD

**Issue by siva90144** [microsoft/playwright-java#1395]
I am using page.navigate("url") to launch the application.

When I try to run locally it will take SSO authentication(When i connected to VPN). when i try to run in Jenkins it will ask authentication.

I have coded as below and url will redirect to multiple times with random ID's. After first redirect, its trying to find the elements.

```java
page.navigate("url");

 page.waitForLoadState(LoadState.DOMCONTENTLOADED);
 page.waitForLoadState(LoadState.NETWORKIDLE);
 if (!page.isVisible(profile)) {
                if(page.isVisible(userName,new Page.IsVisibleOptions().setTimeout(5000))) {
                    page.fill(userName, Util.getProperty("userName"));
                    page.fill(password, Util.getProperty("password"));
                    page.click(login_btn);
                }
   }
 page.click(profile);
```

But the problem is before loading the url, its going to find the elements and script is failing .
here I want to wait before visible method to come into picture. Also I don't want to use hard wait like thread.Sleep()
how can I resolve the issue?

as you suggested, I tried as below.

here is the error log for
assertThat(page.locator(userNameOrProfile)).isVisible();

But I kept max wait time as setDefaultTimeout(60000);
Its not waiting till that time and script is failing with below error.

org.opentest4j.AssertionFailedError: Locator expected to be visible
Call log:
```
Locator.expect with timeout 5000ms
waiting for locator("text=User or input#accountName")
at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:68)
at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:50)
at com.microsoft.playwright.impl.LocatorAssertionsImpl.expectTrue(LocatorAssertionsImpl.java:352)
at com.microsoft.playwright.impl.LocatorAssertionsImpl.isVisible(LocatorAssertionsImpl.java:347)
at com.microsoft.playwright.assertions.LocatorAssertions.isVisible(LocatorAssertions.java:672)
```

**Comment by yury-s** [comment]
> But I kept max wait time as setDefaultTimeout(60000);
> Its not waiting till that time and script is failing with below error.

To change assertions timeout you need to call [`setDefaultAssertionTimeout()`](https://playwright.dev/java/docs/api/class-playwrightassertions#playwright-assertions-set-default-assertion-timeout) or just pass `timeout` option to [`isVisible`](https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-be-visible).

**Comment by siva90144** [comment]
@yury-s i couldn't get the public url to share it and i can't share my application url here. But I am clearly seeing the issue with isVisible method.

below pseudo code is working with while condition.
`while (!elementVisible && timer < timeoutSec) {
            try {
                Thread.sleep(1000);
                elementVisible = page.isVisible(locator);
                timer++;

            }`

**Comment by yury-s** [comment]
`assertThat(page.locator("foo")).isVisible(new LocatorAssertions.IsVisibleOptions().setTimeout(60_000));` should also work. Unfortunately we cannot help without a repro, feel free to file a new bug if the problem persists and you can share more details.
