### ISSUE TITLE
Failed to install browsers - Jenkins | PW-Java | Linux

### ISSUE THREAD

**Issue by GirishbKulkarni** [microsoft/playwright-java#1396]
we are observing below issue when executing on a jenkins machine (Linux)

java.lang.RuntimeException: Failed to create driver
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: 1

**Comment by yury-s** [comment]
Can you run with `DEBUG=pw:install` and see if the logs give you any hints? It might be that the CI machine doesn't have access to the CDN.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
