### ISSUE TITLE
[Feature] how to print/log request curl in playwright api automation

### ISSUE THREAD

**Issue by siva90144** [microsoft/playwright-java#1399]
I would like to save the request and responses in a file. Also want to log request curl(along with headers) in console log. 

Can you please provide an example for logging the request curl in console?

**Comment by yury-s** [comment]
See [our docs](https://playwright.dev/java/docs/api/class-page#page-event-request).

```java
page.onRequest(request -> {
  System.out.println(request.url());
});
```
