### ISSUE TITLE
[BUG] Getting 400 bad request for x-www-form-urlencoded Data in HTTP Requests

### ISSUE THREAD

**Issue by siva90144** [microsoft/playwright-java#1400]
As mentioned in document, sending the data in form. But its throwing as 400 bad request.

Note: Authentication is working fine

Here is the sample code.

```java
 Map<String, String> headers = new HashMap<>();
        headers.put("content-type", "application/x-www-form-urlencoded");

        APIResponse apiResponse=Playwright.create().request().newContext(new APIRequest.NewContextOptions().
                setHttpCredentials("username","password").setExtraHTTPHeaders(headers)).post("https://example.com/signup", RequestOptions.create().setForm(
                FormData.create()
                        .set("grant_type", "client_credentials")));`
```

in postman its working fine and here is the example curl

```sh
curl --location 'https://example.com/signup' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic grggfhnghHJGFknkjsdgndfkhfghjtyy5456gdfbndfgrgNKKkmgjkdngdhd==' \
--header 'Cookie: XSRF-TOKEN=565677-f58f-49er-a282-56756kMNK77' \
--data-urlencode 'grant_type=client_credentials'
```

**Comment by yury-s** [comment]
You can [record a trace](https://playwright.dev/java/docs/trace-viewer-intro#recording-a-trace) and inspect what request was sent. Alternatively you can enable console logging with `DEBUG=pw:api`. Compare those headers to what comes from postman to see why your server may not like the request. You can also log the request on the server and see what's missing. I don't see `cookie` header set when you construct the request in APIRequestContext.

**Comment by siva90144** [comment]
@yury-s for API automation, i am not using browerContext or page(which is not required for me). Also as per document how can I  use below code to log/print the request in console?

```
page.onRequestFailed(request -> {
  System.out.println(request.url() + " " + request.failure());
});
```

**Comment by yury-s** [comment]
The logging I mentioned works for API automation as well. There are no listeners similar to page.onRequestFailed etc as you usually have full control over the construction of such requests and when they are sent, so you can add your own logging around the call sites if aforementioned mechanisms are not sufficient:

```java
    APIRequestContext request = playwright.request().newContext();
    String url = "https://playwright.dev";
    APIResponse response = request.get(url);
    System.out.println(url + " => " + response.status());
```

**Comment by siva90144** [comment]
@yury-s Thanks for info. if you implement this feature, its really helpful . Also many people are also facing same issue and they don't have answers. see the [StackOverflow](https://stackoverflow.com/questions/76882812/how-to-extract-the-exact-request-with-payload-and-url-in-playwright-java)

In Restassured framework its pretty straight forward and easy  to log/print the request in console along with the headers.

**Comment by yury-s** [comment]
Closing this request for now as we have this information exposed in the [Trace Viewer](https://playwright.dev/java/docs/trace-viewer-intro). We may improve the docs to make it more obvious but there is no immediate work planned on adding listeners for the API requests.
