### ISSUE TITLE
[Feature] Documentation: Artifact repository format?

### ISSUE THREAD

**Issue by jfrantzius** [microsoft/playwright-java#1413]
Hi,
https://playwright.dev/java/docs/browsers#download-from-artifact-repository explains how to use a custom artifact repository for downloading browser binaries. Unfortunately, it doesn't specify what repository format is required here. Is this e.g. NPM?

It would be great if the documentation could be more specific here!

**Comment by yury-s** [comment]
Judging by the question you may no need this feature and you may be better off using [a proxy](https://playwright.dev/java/docs/browsers#install-behind-a-firewall-or-a-proxy). Can you describe what you are trying to achieve?

**Comment by jfrantzius** [comment]
Hi,
thanks for asking, this is for making Playwright work in an air-gapped CI environment, where everything required needs to be provisioned in advance using Artifactory

**Comment by yury-s** [comment]
Well, for that you can specify [PLAYWRIGHT_BROWSERS_PATH](https://playwright.dev/java/docs/browsers#managing-browser-binaries). You can download browsers there first and then have the folder available on the bots.
