### ISSUE TITLE
[Feature] Add grouping steps in TraceViewer

### ISSUE THREAD

**Issue by EldoradoEU** [microsoft/playwright-java#1416]
Hi,

Is it possible to implement something similar to test.step() in Java? I'm searching something to group actions in TraceViewer.
Maybe something similar to "Step" in Allure reports.

**Comment by yury-s** [comment]
`test.step()` is a part of Playwright test runner in Node.js. We don't provide our test runner in Java, so this is out of scope for us for now. Closing for now, but we may reconsider this if we decide to build a test runner for playwright java.
