### ISSUE TITLE
[Feature]Does the Playwright-java support running on CentOs7?

### ISSUE THREAD

**Issue by sunxlChinaSD** [microsoft/playwright-java#1421]
I tried running playwright-java on CentOs7, executing the command: mvn compile exec: java - D exec. mainClass=" org. example. App ", but ran an error:  java. lang. RuntimeException: Failed to create driver
                                        Caused by: java. lang. RuntimeException: Failed to install browsers, exit code: 1
The operating environment was installed with reference to the official website information:
mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"

How can I install playwrigt Java on CentOs7 so that the code can run correctly？

**Comment by yury-s** [comment]
Not, it is not supported. You can upvote upstream issue: https://github.com/microsoft/playwright/issues/9199
