### ISSUE TITLE
[Feature] add manage frontend and backend fake camera

### ISSUE THREAD

**Issue by Benjamiche** [microsoft/playwright-java#1430]
I need to automate the using of frontend camera on mobile device, in fact our product force the using frontend camera if the device is a mobile and force the backend camera if the user use a pad or PC.

If I'm using a PC, theses options work :
- "--use-fake-ui-for-media-stream"
- "--use-fake-device-for-media-stream"

else If i'm using a emulted mobile device, even with this option, the frontend camera doesn't work :
- "--use-file-for-fake-video-capture=src/test/resources/videos/fake-camera-1-1.y4m"

I don't find any answers to solve my problem, I test with a preload.js file with page.addInitScript() but without success.
ChatGPT tell me what it's not possible today in 1.40 Playwright version.

Can you confirm it ? And if it's confirmed, could you add this feature to the next roadmap please ?

Thank you.

**Comment by yury-s** [comment]
> else If i'm using a emulted mobile device, even with this option, the frontend camera doesn't work :

You may search crbug.com for bugs related to this behavior (Playwright doesn't modify the option, you can try launching the browser directly without Playwright with the flag and check).

Folding this request into https://github.com/microsoft/playwright/issues/2973, please upvote that issue instead.
