### ISSUE TITLE
[Feature] Introduce common interface for locating elements API

### ISSUE THREAD

**Issue by valfirst** [microsoft/playwright-java#1431]
`com.microsoft.playwright.Page` and `com.microsoft.playwright.Locator` provides very similar (maybe even equal) API to search for elements, but they do not have common interface and they do not reuse the same `*Options` classes. This fact makes impossible to rely on polymorphism principle (for example, when there is a need to operate at Page or at some limited page area, there is no way to introduce an abstraction layer)

**Comment by yury-s** [comment]
You can achieve that on the client side by wrapping Page/Locator in a class that will hide the differences and expose a common interface.

Closing this request as we are not planning to introduce such interface at the moment.

**Comment by valfirst** [comment]
@yury-s would you mind explaining the reasons behind this decision?
