### ISSUE TITLE
Catching custom JavaScript events

### ISSUE THREAD

**Issue by dimitrifankhauserebp** [microsoft/playwright-java#1433]
Hello everyone
I am using playwright 1.22.0 and I would like to take a screenshot whenever a custom JavaScript event is fired. I also tried other approaches i.E. creating a div with a specific id whenever my condition is fullfilled and then Locator.waitfor() but that didn't work either (timeout exception). Any help is appreciated

**Comment by dimitrifankhauserebp** [comment]
Here is the TypeScript Code that I would like to catch:

```
TypeScript: 

 if (condition) {
      // 
      this.dispatchCustomEvent('chartLoaded', 'chart-section');
    }


 public dispatchCustomEvent(eventType: string, section: string): void {
    const event = new CustomEvent(eventType, {
      detail: {
        section
      }
    });
    document.dispatchEvent(event);
  }

```

**Comment by yury-s** [comment]
You can use [`page.exposeBinding`](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-expose-binding) that would trigger a callback in your java code whenever the event is fired in the page.

**Comment by dimitrifankhauserebp** [comment]
Thanks a lot. Could you make an example for this particular case? I have trouble understanding the examples given in the doc/using it for this case. In my Java code I have a function that takes a Page as a parameter and I'm trying to wait for this event to be fired before I continue

**Comment by yury-s** [comment]
Here you go:

```java
    page.exposeBinding("myCallback", (BindingCallback.Source source, Object... args) -> {
        System.out.println("called");
        return null;
    });
    page.evaluate("document.addEventListener('chartLoaded', () => { myCallback(); })");
    page.evaluate(" " +
      "    const event = new CustomEvent('chartLoaded', {\n" +
      "      detail: {\n" +
      "      }\n" +
      "    });\n" +
      "    document.dispatchEvent(event);\n" +
      "  ");

```

**Comment by dimitrifankhauserebp** [comment]
Thank you very much, that helped
