### ISSUE TITLE
[BUG] BrowserType.name() returns the wrong name when channel is used

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright-java#1435]
### System info
- Playwright Version: [v1.XX] 1.40
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.] mac
- Browser: [All, Chromium, Firefox, WebKit] all
- Other info:

### Source code

```java
Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setChannel("chrome"));
assertEquals(browser.browserType().name(), "chrome")

//org.opentest4j.AssertionFailedError: 
//Expected :chrome
//Actual   :chromium
```

- [x] I provided exact source code that allows reproducing the issue locally.

**Expected**

Expect BrowserType.name() to return the channel that was used.

**Actual**

returns the BrowserType that was used to launch ("chromium")

**Comment by mxschmitt** [comment]
This is expected as per [here](https://playwright.dev/java/docs/api/class-browsertype). The underlying BrowserType did not change. You can manually store the settings you pass a your launch options to get the channel later on in your execution.
