### ISSUE TITLE
[BUG] Proxy Pac file does not work for downloading Playwright Browsers

### ISSUE THREAD

**Issue by herdoepfel** [microsoft/playwright-java#1437]
### System info
- Playwright Version: [v1.40.0]
- Operating System: Debian GNU/Linux 11 (bullseye)
- Browser: All
- Other info:

### Source code

No source code needed. It's basically before the browser are started, when the browser download is done by Playwright. 

**Link to the GitHub repository with the repro**
not available. 

**Steps**
Set HTTPS_PROXY=https://my-pac-file.com. 

**Expected**
Browsers get successfully downloaded by using the proxy. 

**Actual**
There is a socket connect error logged by Playwright: 

Downloading Chromium 120.0.6099.28 (playwright build v1091) from https://playwright.azureedge.net/builds/chromium/1091/chromium-linux.zip
Error [ERR_SOCKET_CLOSED]: Socket is closed
    at new NodeError (node:internal/errors:406:5)
    at Socket._writeGeneric (node:net:942:8)
    at Socket._write (node:net:964:8)
    at doWrite (node:internal/streams/writable:465:12)
    at clearBuffer (node:internal/streams/writable:625:7)
    at Writable.uncork (node:internal/streams/writable:407:7)
    at ClientRequest._flushOutput (node:_http_outgoing:1151:10)
    at ClientRequest._flush (node:_http_outgoing:1120:22)
    at onSocketNT (node:_http_client:898:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_SOCKET_CLOSED'
}

**Comment by yury-s** [comment]
Looks like https://my-pac-file.com/ is not a proxy or is not accessible from your network. Did you try other proxies?

**Comment by herdoepfel** [comment]
It's reachable, I can use curl to download it and it works. 
It's not a proxy URL. It's an download URL for a proxy pac file: https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file
Is this something that is even supported by Playwright browser download? If yes, maybe I need to do it differently than using the HTTPS_PROXY environment variable?

**Comment by yury-s** [comment]
No, pac files are not supported for downloads, only proxy address will work. Closing as there are no plans to support it.
