### ISSUE TITLE
[BUG] Intermittent Assertion Error during Condition Waiting Java.lang.AssertionError in WaitableRace.java:40

### ISSUE THREAD

**Issue by abhi19yadav** [microsoft/playwright-java#1438]
I am encountering an intermittent assertion error during regression testing using version 1.40.0. The issue occurs randomly at different points during execution. Below is the relevant code snippet responsible for waiting for a condition in my tests:

```java        
 @AfterStep("@ui_test")
    public void takeScreenshot(Scenario scenario) {
        String pageTitle = "Page title is not available";
        try {
            page.waitForLoadState(LoadState.LOAD);
            pageTitle = page.title();
            page.waitForCondition(() -> !page.getByText("Loading...").isVisible());
            byte[] screenshot = page.screenshot(new Page.ScreenshotOptions().setFullPage(true));
            scenario.attach(screenshot, "image/png", page.title());
        } catch (Exception e) {
            logger.warn("Failed to capture a screenshot of the page '{}' due to the following error: {}", pageTitle,
                    e.getMessage());
        }
    }
```

**Error Details:**

```          
at com.microsoft.playwright.impl.WaitableRace.get(WaitableRace.java:40)
WaitableRace.java:40
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:120)
ChannelOwner.java:120
	at com.microsoft.playwright.impl.PageImpl.waitForCondition(PageImpl.java:1458)
PageImpl.java:1458
	at com.microsoft.playwright.Page.waitForCondition(Page.java:7861)
```

**Additional Information:**

1. The error seems to be related to waiting for a condition using the page.waitForCondition method.
2. The issue is encountered sporadically during regression testing.
3. The tests are written using Cucumber alongside Playwright for Java.

**Comment by yury-s** [comment]
The element with text "Loading..." apparently doesn't go away and the test times out waiting for the condition. This is working as intended. You can use [`LocatorAssertions.isVisible()`](https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-be-visible) that will auto-wait for the condition. Try recording [traces](https://playwright.dev/java/docs/trace-viewer-intro)  and see what's going on. If you think this is a playwright bug, please open a new issue with a repro that we could run locally.
