### ISSUE TITLE
[BUG] Cannot run tests on amazon linux 2

### ISSUE THREAD

**Issue by vasyafomiuk** [microsoft/playwright-java#1441]
tmp/playwright-java-8963853327691113698/node: /1ib64/libm.so.6: version 'GLIBC_2.27' not found (required by /tmp/playwright-java-8963853327691113698/node) 14:14:04 / tmp/playwright-java-
8963853327691113698/node: /lib64/libc.so.6: version GLIBC_2.28' not found (required by /tmp/playwright-java-8963853327691113698/node)

### System info
- Playwright Version: [v1.39.0]
- Operating System: Amazon Linux 2
- Browser: All
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      // ...
    }
  }
}
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by vasyafomiuk** [comment]
Can someone explain how Playwright on Java is using NodeJS?

**Comment by yury-s** [comment]
Playwright [officially supports](https://playwright.dev/java/docs/intro#system-requirements) only Debian and Ubuntu linux distributions. With that said, we are an open source and you may figure out the dependencies for your environment. 

Related issue: https://github.com/microsoft/playwright/issues/11640

> Can someone explain how Playwright on Java is using NodeJS?

Playwright Java shares most of the logic with Playwright for Node.js and its "server" part is a node program bundled into the the java version. So we have to be able to run node in order for Playwright Java to work. You can look at [`driver-bundle` ](https://github.com/microsoft/playwright-java/tree/main/driver-bundle) to learn more.

**Comment by vasyafomiuk** [comment]
thank you Yury. what's the minimum required NodeJS version? We are using 16 and it doesn't seem to be working. 

> Playwright [officially supports](https://playwright.dev/java/docs/intro#system-requirements) only Debian and Ubuntu linux distributions. With that said, we are an open source and you may figure out the dependencies for your environment, but this is out of scope for us currently.
> 
> Related issue: [microsoft/playwright#11640](https://github.com/microsoft/playwright/issues/11640)
> 
> > Can someone explain how Playwright on Java is using NodeJS?
> 
> Playwright Java shares most of the logic with Playwright for Node.js and its "server" part is a node program bundled into the the java version. So we have to be able to run node in order for Playwright Java to work. You can look at [`driver-bundle` ](https://github.com/microsoft/playwright-java/tree/main/driver-bundle) to learn more.

**Comment by yury-s** [comment]
Node 16 has been [end-of-lifed](https://nodejs.org/en/about/previous-releases), our minimal requirement is Node 18 at the moment.

**Comment by jpabeem** [comment]
A workaround (albeit unofficial) would be to use `mise-en-place` (https://mise.jdx.dev/) to install `Node` with the `asdf-nodejs` plugin which patches the `GLIBC` issue.

1. Install `mise` (see https://mise.jdx.dev)
2. Install `asdf-nodejs` (`mise plugins install node https://github.com/asdf-vm/asdf-nodejs`)
3. Install `node` via `mise` (e.g., `mise use -g node@20`)
4. Verify `node` was installed successfully using `node -v && which node`
   * The path to `node` should look something like `~/.local/share/mise/installs/node/20/bin/node`


Now, in your `Java` project we have to override the `node` path which `Playwright` uses under the hood using `PLAYWRIGHT_NODEJS_PATH`. The output of `which node` would suffice here.

Note: `Playwright` doesn't seem officially supported on this platform so use at your own risk. Getting a bunch of warnings (which seem to be harmless, at least for now) such as:

```
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
```
