### ISSUE TITLE
[BUG] Number of GitHub stars misleading too high

### ISSUE THREAD

**Issue by RobertRad** [microsoft/playwright-java#1442]
The number of GitHub stars displayed on https://playwright.dev/java/ is misleading.
The text tells **57k+**, but that's only true for the `playwright` repo, not the `playwright-java` repo.
When clicking on the link, you land at the playwright-java repository, which has currently **905** stars.

**Comment by RobertRad** [comment]
I figured out, this belongs into the repository containing the website.
So an issue is created there:
https://github.com/microsoft/playwright.dev/issues/1239

Feel free to close this one.

**Comment by yury-s** [comment]
The number is for Playwright for Node.js, we should either update the counter when switching language or at least make the link point to https://github.com/microsoft/playwright instead. Folding into https://github.com/microsoft/playwright.dev/issues/1239
