### ISSUE TITLE
[Feature] Allow listening for beforeunload

### ISSUE THREAD

**Issue by cbottomline** [microsoft/playwright-java#1444]
We're looking to do accessibility testing and we wanted to make use of our existing automation tests to do this without adding additional code to each test for accessibility checks.

we've tried hooking into onLoad but that isn't reliable.  we were hoping to maybe use the beforeunload to hook into when a user navigates away from the page, and before that happens, we could run the accessibility check.  we're not sure if this makes sense but was wondering if there was a way for us to hook into this event (maybe through evaluate)?

**Comment by yury-s** [comment]
You can add beforeunload listener using e.g. eval:

```java
    page.evaluate("window.addEventListener('beforeunload', event => {\n" +
      "  // Chromium & WebKit way.\n" +
      "  event.returnValue = 'Leave?';\n" +
      "  // Firefox way.\n" +
      "  event.preventDefault();\n" +
      "});\n");
```

Note that you need to call `Page.close()` with `setRunBeforeUnload(true)` option to ensure that `beforeunload` handlers are executed.

But probably a better approach would be to perform the check in `afterEach()` method right before the page is closed.
