### ISSUE TITLE
[Feature] Android and Electron automation for Java

### ISSUE THREAD

**Issue by dtomantest** [microsoft/playwright-java#1445]
Hi Playwright team,

I have checked the docs for the Node.js version of Playwright and I have seen that it supports Android and Electron application testing, though it's still in an experimental phase. I am also aware of the simulation feature of Playwright, but after reading [this ](https://developer.chrome.com/docs/devtools/device-mode/#limitations) I have some concerns if this really gives me enough confidence.

So I came to the conclusion that some sort of emulation/real-device testing should support the simulated testing and was wondering if the Java language port will support it in the near future?

The company I work at would like to have a single authentication module instead of native ones and utilize WebViews during login flows (same as Microsoft and Google have for example) and I am looking for a test automation tool to support it.

Thank you for your time.

**Comment by yury-s** [comment]
> So I came to the conclusion that some sort of emulation/real-device testing should support the simulated testing and was wondering if the Java language port will support it in the near future?

If you are asking about testing on real devices, it is tracked in https://github.com/microsoft/playwright/issues/1122

Support for Electron in Java is tracked by https://github.com/microsoft/playwright-java/issues/830. We are not planning to port Android/Electron APIs from Node.js to java at the moment, our focus is on testing standard web features, available across all browsers.

**Comment by dtomantest** [comment]
Hi,

thanks for the response. 

Regarding your question, I was just curious if Playwright is planning to support not just cross-browser testing for Java, but electron and mobile as well. We have native apps currently, but login flows will be replaced with a single web based solution which will be loaded into webviews in our apps. That's why it would be helpful for me to have a single framework that is able to test all this together.

This maybe is not Playwrights territory, but I have been searching for differences between UI testing in actual Chrome browser using device toolbar and in Android Webview. If I am correct both use chromium engine under the hood, but still not sure about the confidence it can give me about the latter while executing test against the former. If you have experience with this your answer would be much appreciated.

Thank you.

**Comment by yury-s** [comment]
In Node.js we have [AndroidWebView](https://playwright.dev/docs/api/class-androidwebview) class for that, we are not planning to port it to java as of today. You may still get some luck if you find a way to connect to the web view via [connectOverCDP](https://playwright.dev/java/docs/api/class-browsertype#browser-type-connect-over-cdp). Closing this issue as there are no plans to port android support to java.
