### ISSUE TITLE
[Feature] support docker with pure java remote api (without requiring local node for "bounce")

### ISSUE THREAD

**Issue by k1w1m8** [microsoft/playwright-java#1446]
Per https://github.com/microsoft/playwright/issues/26482 we can use playwright-java with driver/node and browser(s) inside a docker container, even for unsupported OS. I have provided a sample test case there which demonstrates this.

However, there is a major practical drawback for the PW java API that the host needs to have an additional driver/node available purely to do the "bounce" to the docker driver/node, either installed automagically via PW or by hand for unsupported O/S. 

For the use case of API client and server Docker, this additional host driver node seems clunky, heavyweight and is using only a tiny fraction of the available host driver/node capability.

Would it possible to extend the existing Java API to provide a "pure java" way to connect to remote driver/node, without requiring a host driver/node connection first? 

For this use case, it would have many benefits:

* works on any any OS 
* doesn't require internet access to download host node (in case of unsupported OS at least)
* consume fewer host resources.
* quicker PW start time
* etc

Not sure about other API languages such as Python etc, but possibly they could also benefit from such a change.

Selenium already provides a pure java API to connect to Docker server, RemoteWebDriver.

**Comment by yury-s** [comment]
We've considered this idea in the past but decided not to do that as it would increase the maintenance burden. Currently the logic of connecting to the remote playwright is implemented in the driver which is shared by all implementations. The benefit of porting that to each language is basically saving on some resources which is not a problem at this point.

There are two related requests: https://github.com/microsoft/playwright-java/issues/467 and https://github.com/microsoft/playwright-java/issues/1196.

I'm closing this issue as we are not planning to do the proposed change.

**Comment by k1w1m8** [comment]
OK.

We will use Selenium instead of Playwright to avoid this limitation.
