### ISSUE TITLE
[BUG] Failed to create driver when using in sbt plugin

### ISSUE THREAD

**Issue by gmkumar2005** [microsoft/playwright-java#1447]
### System info
- Playwright Version: [1.40.0]
- Operating System: [macOS] (Not tested on other os. It is fair to assume this issue exists on all OS)
- Browser: [All]
- Other info:

**Expected**
The playwright drivers should be loaded and open the browser when running in an sbt plugin. 

I am using playwright in an sbt plugin. It fails to load the driver with following error 
`Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because the return value of "java.lang.ClassLoader.getResource(String)" is null`

**Actual**

I am using playwright in an sbt plugin. It fails to load the driver with following error 
`Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because the return value of "java.lang.ClassLoader.getResource(String)" is null`

The root cause seems to be due to the way class loader is used in the `DriverJar.Java`
The function `getDriverResourceURI()` is using a classloader from current Thread 
`ClassLoader classloader = Thread.currentThread().getContextClassLoader(); `

sbt is not able to provide all the libraries inthis class loader. It works with `DriverJar.class.getClassLoader() `

**Can this function `getDriverResourceURI()` be updated to use the class loader as in DriverJar.class.getClassLoader()**

https://github.com/microsoft/playwright-java/blob/e889b20fda31695d0815cdc1eb3cde7efd54db73/driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java#L117

**Comment by yury-s** [comment]
Sounds like a problem with sbt as it works in regular environment. Providing more context on how you use Playwright and how this can be reproduced, ideally with a minimal repro that we could run locally, would help us better understand what's going on. I don't know what sbt is, but it sounds like some environment that would be out of scope for the project. With that said, if you have an idea for the fix we accept contributions.

**Comment by gmkumar2005** [comment]
I fixed this issue by writing a custom DriverJar. I changed the classLoading logic to `DriverJar.class.getClassLoader() ` .
To make it work system property is setup as below.

`System.setProperty("playwright.driver.impl", "jsenv.DriverJar")`

**Comment by gmkumar2005** [comment]
Issue is fixed please see previous comment
