### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dishask99** [microsoft/playwright-java#1455]
Playwright.create() taking  more than 2 seconds 

Code -
<img width="765" alt="image" src="https://github.com/microsoft/playwright/assets/40157092/dbdd6a0e-dfe4-4ddd-8e57-8f4a7156284c">

Log - 
<img width="1253" alt="image" src="https://github.com/microsoft/playwright/assets/40157092/5b8938fa-25d8-4a63-b2dc-56e65abf51be">

**Comment by yury-s** [comment]
First time Playwright runs, it downloads browser binaries which may take significant time depending on your connection speed. On subsequent runs it will reuse cached browsers. Another thing that is happening in create is extraction of playwright driver into a temp dir.

**Comment by dishask99** [comment]
I am downloading the binaries pre-hand using the mvn command.
I am creating a multihread application and in each thread I am using playwright.create() function... so that one thread won't be dependent on the other for the playwright resource.
