### ISSUE TITLE
[BUG] all timeouts should be in long/int  not double type

### ISSUE THREAD

**Issue by turnitin-rshanker** [microsoft/playwright-java#1457]
currently all timeout is set in double

it should be either in int/long definitely not double

**Comment by yury-s** [comment]
Does it cause you any issues in a real world scenario?

**Comment by turnitin-rshanker** [comment]
by default, no one passes in  double for timeouts

**Comment by yury-s** [comment]
This is a strong statement, I'm not sure what it is based upon. In any case, you can pass an int or long value, the will be converted to double automatically.
