### ISSUE TITLE
How to connect to device cloud devices using playwright with java?

### ISSUE THREAD

**Issue by Akhourisharma** [microsoft/playwright-java#1458]
1.currently my framework is having playwright with java(cucumber +maven)

Requirement - I need to run my tests in device cloud.So how can i connect to device cloud using playwright?

**Comment by yury-s** [comment]
You can use [`connect`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-connect) or [`connectOverCDP`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-connect-over-cdp) depending on what protocol the cloud exposes.
