### ISSUE TITLE
[Query] Using playwright with completable futures

### ISSUE THREAD

**Issue by dishask99** [microsoft/playwright-java#1459]
Hi Team, we are using playwright to capture screenshot in our application, we have created a completable future for it... so that whenever a rest api call will reach server the playwright execution can happen in a separate thread.
We are trying to optimise the below things - 

- We are creating Playwright in every API call
- Launching a new browser and context in every API call

Like below - 

```java
        Playwright.CreateOptions createOptions = new Playwright.CreateOptions();
        createOptions.setEnv(new HashMap<>(Map.of("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "true")));
        try (Playwright playwright = Playwright.create(createOptions)) {
            Browser browser = playwright.webkit().launch();
            BrowserContext context = browser.newContext();
            Page page = context.newPage();
            page.setDefaultTimeout(RESOURCE_TIMEOUT_MSEC);
            try {
                page.navigate(screenCapture.getTargetUrl());
                page.evaluate("() => { document.documentElement.style.backgroundColor = 'white'; }");
                int fullPageHeight = (int) page.evaluate("() => document.documentElement.scrollHeight");
                page.setViewportSize(screenCapture.getWindowWidth(), fullPageHeight);
                captureFullPageScreenShot(screenCapture, page);
                captureModulesScreenShot(screenCaptureList, page);
            } catch (Exception exception) {
                throw new ScreenCaptureException(exception);
            } finally {
                browser.close();
            }
        }
```
Can I create my playwright once and use it again and again... what will be the impact if large number of requests are coming, my threads will be waiting for the resource to get free?

**Comment by dishask99** [comment]
Hi Team, can someone please help us with this?

**Comment by yury-s** [comment]
You don't need to create Playwright instance on every request. In fact, we recommend reusing playwright and browser as much as possible. Playwright uses BrowserContext for [test isolation](https://playwright.dev/java/docs/writing-tests#test-isolation), so you can keep your browsers open and create a new page in a new context when sending a request, this will guarantee that it starts with a fresh state and would be most efficient if you need the isolation. Just beware of [thread-safety](https://playwright.dev/java/docs/multithreading) issues.

Closing this report as this is neither a bug nor feature request for Playwright.
