### ISSUE TITLE
[Feature]This version of C:\Users\Group\AppData\Local\Temp\playwright-java-3452437643505612743\node.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

### ISSUE THREAD

**Issue by VirtualSyneGit** [microsoft/playwright-java#1465]
This version of C:\Users\Group\AppData\Local\Temp\playwright-java-3452437643505612743\node.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

```[tasklist]
### Tasks
```

**Comment by VirtualSyneGit** [comment]
why do i get this

**Comment by VirtualSyneGit** [comment]
i am having 
![image](https://github.com/microsoft/playwright-java/assets/157975797/c1fae956-8976-4edd-9591-3219c3f4c784)

**Comment by yury-s** [comment]
Playwright [requires](https://playwright.dev/java/docs/intro#system-requirements) Windows 10+ (Node.js can't run on Windows 7 in your case).
