### ISSUE TITLE
[BUG] Playwright is changing the terminal mode and hiding the error stream

### ISSUE THREAD

**Issue by gmkumar2005** [microsoft/playwright-java#1466]
### System info
- Playwright Version: [v1.XX]
- Operating System: [ macOS ]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

**Steps**
Run test cases in scala. 
**Expected**
I am running test cases in scala. The test case run as expected. However playwright is changing the behavior of the terminal.  The up arrow start showing ^[OA^. Additionally all the error details disappear. Apparently playwright is not allowing standard error stream to work.  

Playwright should not consume the data from error streams. Terminal behavior should not be changed.
Below is the output with out playwright. It displays error details and line numbers. 
```
==> X basic.BasicSuite.renders empty elements 0.02s munit.FailException: <<masked path>>/BasicSuite.scala:51 querySelector returned null check if the query is correct
50:          val actual = dom.document.querySelector("#app > td")
51:          assert(actual != null, "querySelector returned null check if the query is correct")
52:          assertEquals(actual.outerHTML, expectedEl.outerHTML)
```

**Actual**

Below is the output with playwright it does not show the additional error message
```
basic.BasicSuite:
==> X basic.BasicSuite.renders empty elements 0.01s munit.FailException:
```

**Comment by yury-s** [comment]
Playwright itself doesn't print any special symbols to the terminal, so it's likely something coming out of the user code. Can you provide a repro that we could run locally to reproduce the problem?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
