### ISSUE TITLE
[BUG] I upload mp4 file in the browser, and then createObjectURL to create a link how to play not out, is not support h264 decoding?

### ISSUE THREAD

**Issue by YYYQG** [microsoft/playwright-java#1467]
![image](https://github.com/microsoft/playwright-java/assets/34999895/456903e0-ac13-40b2-a815-a1f2c740026c)

I upload mp4 file in the browser, and then createObjectURL to create a link how to play not out, is not support h264 decoding?

**Comment by yury-s** [comment]
H.264 is not free, so it is only available if browser vendor included it or if it is available in the OS media stack. 

Related bugs: https://github.com/microsoft/playwright/issues/13659, https://github.com/microsoft/playwright/issues/13819

**Comment by YYYQG** [comment]
thanks
