### ISSUE TITLE
[Bug]: The batch file cannot be found error in Java

### ISSUE THREAD

**Issue by pete89-p** [microsoft/playwright-java#1499]
### Version

1.41.2

### Steps to reproduce

clone repo: https://github.com/pete89-p/playwright_sample
mvn clean test -Pchromium

### Expected behavior

The tests run in multithread 4 at a time of 8.
To disable comment-out properties in src/test/resources/junit-platform.properties.
There should be no errors produced

### Actual behavior

Running the test with or without a multithread setting produces a `The batch file cannot be found.` error. Moreover, a lot of temp folders are visible in AppData.
![image](https://github.com/microsoft/playwright-java/assets/62641395/8d3b2fd9-d82b-4708-83e9-09690aeed0cb)
an 

### Environment

Windows 11
Java 21
maven 3.8.4

**Comment by yury-s** [comment]
Can you run the test with DEBUG=pw:install env variable and see if playwright.cmd at the path it prints out does exist and can be executed?

**Comment by yury-s** [comment]
Yeah, the output looks normal except for the tests runs go before driver extraction which maybe just how your runner mixes output from different processes. The error is likely about `C:\Users\piotr\AppData\Local\Temp\playwright-java-11460941810274873103\playwright.cmd` missing, can you check if it's actually there while the test is running?

**Comment by yury-s** [comment]
Can you also try to reduce the tests to the minimal scenario where it fails? Sounds like multithreading is irrelevant but it hinders understanding what's going on.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by yury-s** [comment]
The problem is likely caused by the thread that called playwright.create to finish while the rest of the program is still running. This could lead to deletion of the temp directory with the driver.
