### ISSUE TITLE
[Bug]: chrome set LaunchPersistentContextOptions return's browser is null 

### ISSUE THREAD

**Issue by Apyz** [microsoft/playwright-java#1507]
### Version

1.41.1

### Steps to reproduce

I do not understand why there is an error in the execution of this code, and the browser obtained by this code is null. It works if I use launch, but I need to set up the persistence context. This is distressing.

```java
Playwright playwright = Playwright.create();
        int port = 9001;
        BrowserType chromium = playwright.chromium();
        BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions().setHeadless(false).setArgs(Arrays.asList("--remote-debugging-port=%d".formatted(port)));
        BrowserType.LaunchPersistentContextOptions launchPersistentContextOptions = new BrowserType.LaunchPersistentContextOptions()
                .setHeadless(false).setAcceptDownloads(true).setBypassCSP(true).setSlowMo(1000).setChannel("chrome")
                .setArgs(Arrays
                        .asList("--remote-debugging-port=%d".formatted(port)));
        Browser browser = chromium.
                launchPersistentContext(
                        Path.of("d:\\chromium_data%d".formatted(port)),
                        launchPersistentContextOptions).browser();
        Page page = browser.newPage();
        page.navigate("https://www.google.com");
        System.out.println(page.title());
```

### Expected behavior

I want the browser not to be null and to return an instance of the browser as normal, as the api sets it to do.

### Actual behavior

I don't understand why this error occurs, it seems to me that this is a normal demand.

### Environment

Operating System: [windows 10] - CPU: [i7-8850H] - Browser: [ Chromium] - Java Version: [31] - Maven Version: [3.9.6]

**Comment by yury-s** [comment]
This is by design, as the [API documentation](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-browser) reads "If it was launched as a persistent context null gets returned."

**Comment by yury-s** [comment]
You can launch browser with [`launch`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch) method if you need a `Browser` instance.
