### ISSUE TITLE
[Feature]: Add @Inherited to @UsePlaywright

### ISSUE THREAD

**Issue by otbe** [microsoft/playwright-java#1514]
### 🚀 Feature Request

Hi there,

Im playing around with the new Junit integration and while it works as expected we cannot use it right now within our tests.
We use some abstract super classes and also `@Nested` classes to group scenarios. `@UsePlaywright` currently is not `@Inherited` and therefore during extension disovery it fails at this place `com.microsoft.playwright.junit.impl.ExtensionUtils#hasUsePlaywrightAnnotation` 

### Motivation

```
@UsePlaywright
public class TestExample {
  @Nested
  class Scenario {  
    @Test
    void shouldCheckTheBox(Page page) {
      page.setContent("<input id='checkbox' type='checkbox'></input>");
      page.locator("input").check();
      assertEquals(true, page.evaluate("window['checkbox'].checked"));
    }
  }
}
```

**Comment by uchagani** [comment]
Thanks, @yury-s i can work on this. It's a bit more involved than just adding `@inherited`. Should have a fix soon.

**Comment by otbe** [comment]
True I was more thinking about the abstract super class case. :)
Therefore we would need @Inherited I assume based on `org.junit.platform.commons.util.AnnotationUtils#findAnnotation(java.lang.reflect.AnnotatedElement, java.lang.Class<A>, boolean, java.util.Set<java.lang.annotation.Annotation>)`

**Comment by uchagani** [comment]
@otbe can your provide an example of what you need working? The example you gave above is working without @Inherited after the pull request is merged in.

**Comment by otbe** [comment]
For example:

```
@UsePlaywright
public abstract class AbstractBrowserTest {
  // .. some shared test code
}

public class TestFixturesWithNestedClass extends AbstractBrowserTest {

  @Test
  void worksWithOuterClass(Page page) {
    assertNotNull(page);
  }

  @Nested
  class NestedClass {
    @Test
    void worksWithNestedClasses(Page page) {
      assertNotNull(page);
    }

    @Nested
    class DeeplyNestedClass {
      @Test
      void worksWithDeeplyNestedClass(Page page) {
        assertNotNull(page);
      }
    }
  }
}
```

In our case `AbstractBrowserTest` has `@SpringBootTest`, junits `@Tag` and some shared test code like login(), goToPage(...). I think `@Inherited` is needed so that `AnnotationUtils` goes up the tree to our super class.

**Comment by uchagani** [comment]
Ah ok I understand your use case now.  #1515 now also adds `@Inherited` to the fixture annotation.
