### ISSUE TITLE
[Feature]: Can I use proxy to connectOverCDP?

### ISSUE THREAD

**Issue by LaiZhou** [microsoft/playwright-java#1520]
### 🚀 Feature Request

I want to connect remote chrome browsers ,  which may be started on AWS or GCP. but in my country,the network can't be reached .  I want to have a ConnectOverCDPOptions , like 'proxy' to set a http proxy to connect them. 

### Example
`
overCDPOptions.setProxy("127.0.0.1:8000");
`

### Motivation

I want to connect remote chrome browsers ,  which may be started on AWS. but in my country,the network can't be reached .  I want to have a ConnectOverCDPOptions , like 'proxy' to set a http proxy to connect them.

**Comment by yury-s** [comment]
There is no built in proxy support for `connectOverCDP`. The easiest you can do probably is to bring up local server that would forward the requests via proxy to AWS.

Closing this issue as we are not planning to implement this.
