### ISSUE TITLE
[Bug]: Run a playwright on an ARM-based machine  Execution IO error 

### ISSUE THREAD

**Issue by wm475390847** [microsoft/playwright-java#1523]
### Version

java-1.20.0

### Steps to reproduce

It can run normally on X86 machines, but an error was reported on arm machines, and it is not possible to confirm whether it is due to the architecture！

code：
![image](https://github.com/microsoft/playwright-java/assets/68719907/f0de1891-2dbd-44d8-adef-4e72eccfa30d)

Run error：
![image](https://github.com/microsoft/playwright-java/assets/68719907/3e8581d7-c11d-435a-a3ab-198ea0ffae54)

Browser files in pod：
![image](https://github.com/microsoft/playwright-java/assets/68719907/277cf8fa-bd7d-4566-8373-c056f3240898)

### Expected behavior

X86 run  result:
![image](https://github.com/microsoft/playwright-java/assets/68719907/70fefce6-7193-479f-8288-8a5a23fc0e79)

### Actual behavior

IOExecption：Stream closed

### Environment

操作系统：linux
架构：arm64
java：jdk1.8
maven：3.6.3
浏览器：chrome

**Comment by yury-s** [comment]
> ### Version
> java-1.20.0

Try running with latest Playwright (1.42 at the moment) and see if the problem persists. I believe we added support for arm after 1.20.

**Comment by wm475390847** [comment]
ok, I'll try.

**Comment by mxschmitt** [comment]
Closing as per above. Linux-arm64 support was added in [v1.22.0](https://github.com/microsoft/playwright-java/releases/tag/v1.22.0). We strongly recommend using the latest Playwright version.
