### ISSUE TITLE
[Feature]: Make all playwright fixture's getOrCreateX methods public

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright-java#1524]
### 🚀 Feature Request

I would like all of the `getOrCreateX` methods in various playwright-java fixtures to be made public.  Currently they are all package-private.

### Example

Test Class:

```java
//Registers the NavigateExtension and auto-navigates to the given URL before each test
@Navigate("https://playwright.dev")
public class MyTestClass {

  void myTest(Page page) {
    // at this point the page has already navigated to https://playwright.dev
    // and I can start my test right away because the navigation is handled by the NavigateExtension
  }
}
```

Navigate Extension:

```java
public class NavigateExtension implements BeforeEachCallback {

  public void beforeEach(ExtensionContext extensionContext) {
    // Can't call this yet because it is package-private
    var page = PageExtension.getOrCreatePage(extensionContext);
    page.navigate(someUrlFromCustomAnnotation);
  }

}
```

### Motivation

The main reason for this is to allow people to create their own extensions on top of what playwright-java provides.

**Comment by yury-s** [comment]
> The main reason for this is to allow people to create their own extensions on top of what playwright-java provides.

I'd wait for such clients to come first, they might need a different shape of the API, e.g. I can imagine someone wanting more than one context per test to be managed automatically.

**Comment by uchagani** [comment]
I was in the process of updating my test framework with the new fixtures and that's when i came across this issue.  Right now, as a workaround, i am using reflection to call those methods.  The navigate extension was just one of various extensions we have so I think there is a real need for it.

Another thing that I just came across is the inability to save trace files based on test status.  I'll create a new issue for that.

**Comment by yury-s** [comment]
We can certainly make them public if you need it. These classes live in an `impl` package, so I'd just add a note that the implementation details can change in the future. WDYT?

**Comment by uchagani** [comment]
That sounds great. Thanks! I can do it this evening unless you're able to get to it sooner.
