### ISSUE TITLE
[Bug]: playwright cpu usage too high

### ISSUE THREAD

**Issue by zscorpio** [microsoft/playwright-java#1528]
### Version

1.40.0

### Steps to reproduce

Playwright.create();
Create four Playwright and page to visit website.

### Expected behavior

CPU less than 50%

### Actual behavior

CPU reached 99%

### Environment

Centos with 4C8G. Chome
playwright cpu usage high...is there anyway to solve?

**Comment by yury-s** [comment]
We can't take any action based on the provided information. If you think this is a bug in playwright, please open a new issue and provide a reproduction.
