### ISSUE TITLE
How to get chrom extension background page

### ISSUE THREAD

**Issue by hzk007** [microsoft/playwright-java#1530]
### Please do not submit this issue.

- [X] I understand

**Comment by hzk007** [comment]
Hi, as the doc shown. https://playwright.dev/java/docs/api/class-page 

Page provides methods to interact with a single tab in a [Browser](https://playwright.dev/java/docs/api/class-browser), or an [extension background page](https://developer.chrome.com/extensions/background_pages) in Chromium. One [Browser](https://playwright.dev/java/docs/api/class-browser) instance might have multiple [Page](https://playwright.dev/java/docs/api/class-page) instances.

But how can I switch to background_pages?
For now ,I have already loaded  extension and this extension already display in the page,  but I don't known how to switch to the extension.

**Comment by hzk007** [comment]
from the https://playwright.dev/docs/chrome-extensions, I have use the same launchPersistentContext to launch the chromium with java version, but lack of browserContext.backgroundPages()

**Comment by yury-s** [comment]
Looks like the method is not exposed in Java API, we can fix that.

**Comment by hzk007** [comment]
> Looks like the method is not exposed in Java API, we can fix that.

thanks

**Comment by hzk007** [comment]
Hi, [yury-s](https://github.com/yury-s) How can I use the latest code for our project? could you give me some suggestion?

**Comment by yury-s** [comment]
This will be published in the next release. Before that you can build the project from source.

**Comment by sushantmishra** [comment]
@yury-s Do we have a timeline for the next release , I mean by when we can expect this change to be available for use ?

**Comment by yury-s** [comment]
It didn't make it to 1.43, so the earliest release it will be available in is 1.44. We are going to push 1.43 in the next few days, so 1.44 will be in about a month.

**Comment by hzk007** [comment]
> It didn't make it to 1.43, so the earliest release it will be available in is 1.44. We are going to push 1.43 in the next few days, so 1.44 will be in about a month.

Hi,[yury-s](https://github.com/yury-s), how can I package this from source code?  I wan to publish to our nexus with the latest code? But mvn install failed and seems need some configuration for package...

**Comment by hzk007** [comment]
Hi, [yury-s](https://github.com/yury-s),we need this function for our automation project. could you give some instruction how to build the snapshot version?

**Comment by yury-s** [comment]
Take a look at our yaml file: https://github.com/microsoft/playwright-java/blob/2829a37d58e7c1ce3bd30e3a41334874f58a4830/.github/workflows/test.yml#L21-L32

**Comment by hzk007** [comment]
Hi, [yury-s](https://github.com/yury-s) seems have some error with the latest code. the  plugin have been loaded, but with this code 
    context.onBackgroundPage(page1 -> backgroundPages.add(page1));
    context.waitForCondition(() -> !backgroundPages.isEmpty(),
      new BrowserContext.WaitForConditionOptions().setTimeout(20_000));
    Page backgroundPage = backgroundPages.get(0);

it can not get the plugin page until 20000ms...
<img width="1727" alt="image" src="https://github.com/microsoft/playwright-java/assets/41773976/f2cb98d6-4dd9-4504-9bac-6a3a38aee779">

<img width="1640" alt="image" src="https://github.com/microsoft/playwright-java/assets/41773976/dcee1c31-d8fb-4899-9e80-93d9145f6cea">

**Comment by Mani-151** [comment]
Hi @yury-s , We have built the snapshot version and used it it our project. However, we have noticed that browser is getting launched although we have passed  "mvn test -Dheadless=true" command.
Did you have similar observation?
