### ISSUE TITLE
[Feature]: Allow user to pass in wsEndpoint and ConnectOptions to fixtures

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright-java#1537]
### 🚀 Feature Request

I would like to be able to specify a `wsEndpoint` and `ConnectOptions` in the `OptionsFactory` and use the `connect` method to get a `Browser`.  Similar to https://playwright.dev/docs/api/class-testoptions#test-options-connect-options

### Example

options can be defined like this:

```java
class PlaywrightOptions implements OptionsFactory {
    @Override
    public Options getOptions() {
      return new Options()
        .setWsEndpoint("ws://localhost:5678")
        .setConnectOptions(new BrowserType.ConnectOptions().setTimeout(10000));
    }
}
```

The `BrowserExtension` could check to see if the `wsEndpoint` field is not null and if so, use the connect method to create a `Browser` object instead of the `launch` method.

### Motivation

The fixtures need to be able to use this option in order to run against cloud services like BrowserStack or Saucelabs.

**Comment by uchagani** [comment]
@yury-s I think this is more important than tracing since there is no workaround for this currently.  If you're okay with it, I can work on this right away.

**Comment by yury-s** [comment]
We wanted to change the shape of that API in Node.js version, so I'd hold off for now and do it inline with upstream later.

**Comment by yury-s** [comment]
Basically something along these lines: https://github.com/microsoft/playwright/pull/29484 where launch would be able to connect to a remote browser.

**Comment by uchagani** [comment]
Are there plans to implement this soon? I'm afraid without this feature, fixtures will be unusable for those that develop locally but run tests in the cloud.

**Comment by yury-s** [comment]
After talking to the team about the `remote` option inside launch, it seems that it is not pressing at this point and will likely slip to future releases, in which case I agree that it's ok for you to proceed with connect options.
