### ISSUE TITLE
[Bug]: Drag and drop in a canvas is not working in playwright

### ISSUE THREAD

**Issue by Nagarajan1990** [microsoft/playwright-java#1546]
### Version

1.42.0

### Steps to reproduce

Below manual mouse operations are performed
1. Drag an element from side pane
2. Perform mouse down to simulate left click operation
3. Hover on the destination (inside canvas area)
4. Drop the element inside canvas by performing mouse up operation

### Expected behavior

Element to be dragged and dropped inside canvas

### Actual behavior

Could not see any action in the UI
I understand the mouse movements and other actions will be simulated inside the browser but this making the debugging also difficult

### Additional context

Locator source = page.locator("xpath");
source.hover();
page.mouse().down();
//destination
page.locator("#canvas area").hover(new Locator.HoverOptions().setPosition(x,y));
page.mouse().up();

### Environment

-Windows 10
-Chrome v 123.0.6312.106

**Comment by yury-s** [comment]
> Element to be dragged and dropped inside canvas

Can you share complete reproduction so that we could try it locally?

**Comment by Nagarajan1990** [comment]
Please find the attached screenshot for exact action that we are trying to perform in UI. Kindly let me know if you need any further details.

**Comment by Nagarajan1990** [comment]
Hello,
Please find the attached image for the detailed steps.![Bug1546_Reproduciblesteps.png](https://github.com/microsoft/playwright-java/assets/166710267/7bf25950-0ad5-47c9-b035-4129f50d3c16)

Kindly let me know if you need any further details.

**Comment by mxschmitt** [comment]
Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
