### ISSUE TITLE
[Feature]: ApiRequestContext: Add support for SSL Context

### ISSUE THREAD

**Issue by emeraldjava** [microsoft/playwright-java#1549]
### 🚀 Feature Request

Allow the playwright api request make secure https requests. In our case that endpoint has https enabled and we need to provide the keystore/truststore credentials with the http request.

### Example

In the config/setup of the playwright tests, the developer would provide paths the keystore/truststore. In the test code - the developer would config/inject the SSL Context details to the Transport interface implementation. The underlying calls would exchange the ssl details.

### Motivation

Allows playwright api to be used to call https secured endpoints.

**Comment by yury-s** [comment]
Related https://github.com/microsoft/playwright/issues/1799

**Comment by jasonparallel** [comment]
You can manage the connection yourself in Java

`
page.route("**/*", route -> {
  FulfillOptions responseData = customJavaRequest(route.request());
  route.fulfill(responseData);
}
`

**Comment by mxschmitt** [comment]
@emeraldjava is this about TLS client certificates? Playwright supports [them now](https://playwright.dev/java/docs/release-notes#tls-client-certificates) (as files and as a direct content).

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if it doesn't work for you.
