### ISSUE TITLE
[Feature]: Ubuntu 24.04

### ISSUE THREAD

**Issue by aghasemi** [microsoft/playwright-java#1558]
### 🚀 Feature Request

Hi,

May I ask please, whether we know an approximate date for the release that will support Ubunutu 24.04, the new LTS?

Currently it seems some dependencies are missing(?) and need to get updated.

### Motivation

I believe Playwright consistently supports the two latest LTS Ubuntu releases. Hence it is about time to think about supporting Ubuntu 24.04, I guess :)

**Comment by yury-s** [comment]
Previously we waited until first patch release is out, so it's likely a few months from now.
