### ISSUE TITLE
[Bug]: Incognito mode in chromium with version 1.43

### ISSUE THREAD

**Issue by joseRodenasMinderest** [microsoft/playwright-java#1577]
### Version

1.43.0

### Steps to reproduce

Open a new context like always, it opens a non incognito browser.

https://playwright.dev/java/docs/api/class-browsercontext

`// Create a new incognito browser context
BrowserContext context = browser.newContext();
// Create a new page inside context.
Page page = context.newPage();
page.navigate("https://example.com");
// Dispose context once it is no longer needed.
context.close();`

### Expected behavior

The browser opens in incognito mode

### Actual behavior

The browser opens in non incognito mode

### Additional context

Just check that in 1.42.0 version works like always

### Environment

Operating System: Ubuntu 22.04
Browser: Chromium
Java: OpenJdk 11

**Comment by mxschmitt** [comment]
Due to a Chromium change, it does not look like Incognito anymore but it is actually an incognito tab - do you experience issues with your page behaving different?

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if you still experience issues.
