### ISSUE TITLE
How to speed up headless Chromium loading speed?

### ISSUE THREAD

**Issue by yidasanqian** [microsoft/playwright-java#1593]
### Please do not submit this issue.

- [X] I understand

**Comment by yidasanqian** [comment]
I checked the contents of trace.zip, and in reality, the main content loaded in about 3 seconds, but the total duration was around 23 seconds. Why did it take so long? Is there any way to speed up the loading time?

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
