### ISSUE TITLE
[Feature] how to get request curl format with APIRequestContext

### ISSUE THREAD

**Issue by Hansanto** [microsoft/playwright-java#1614]
### 🚀 Feature Request

Like #1399, I would like to know how to obtain all information about a request sent from [request object](https://playwright.dev/docs/api/class-apirequestcontext).

In this context, I'm interacting only with API and not Website, so I don't use the [page object](https://playwright.dev/docs/api/class-page)

### Motivation

Get the possibility to log requests & responses easily for API calls

**Comment by mxschmitt** [comment]
Looks similar to https://github.com/microsoft/playwright/issues/30082 - since Trace Viewer is the UI we recommend for debugging, thats probably a good place to add it.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/30082
