### ISSUE TITLE
Find Xpath or Path or JsPath of an element from the locator in Playwright Java

### ISSUE THREAD

**Issue by ThatYodaCoder** [microsoft/playwright-java#1619]
IS there anyway to find the xpath/path/jspath of an element from the locator in playwright java apis?

**Comment by mxschmitt** [comment]
There is no such way as of today. We recommend using a Locator to perform actions from it. For what do you need the xpath for? Maybe we have a method for it already / or we make a feature request out of it. Thanks!

**Comment by yury-s** [comment]
Closing per the comment above. Also it doesn't seem to be a testing scenario. We recommend using [codegen](https://playwright.dev/java/docs/codegen-intro#running-codegen) to pick selector of an element.
