### ISSUE TITLE
I am facing the issue of the 'self sign certificate in certification chain', while using the mail sender tool (nodemailer) in my express framework, please help me out

### ISSUE THREAD

**Issue by Abdul8081** [microsoft/playwright-java#1622]
### Please do not submit this issue.

- [X] I understand
```[tasklist]
### Tasks
```

**Comment by Abdul8081** [comment]
Error: self-signed certificate in certificate chain at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34) at TLSSocket.emit (node:events:518:28) at TLSSocket._finishInit (node:_tls_wrap:1085:8) at ssl.onhandshakedone (node:_tls_wrap:871:12) { code: 'ESOCKET', command: 'CONN' }

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
