### ISSUE TITLE
[Bug]: Cannot run program "/tmp/playwright-java-9325996558200189516/node": error=2, No such file or directory

### ISSUE THREAD

**Issue by anobilisgorse** [microsoft/playwright-java#1630]
## Version

1.45.0

### Context
This is how we use Playwright in our application:
```java
try (Playwright playwright = Playwright.create();
    Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(true));
    Page page = browser.newContext().newPage()) {
   // do something with page
} catch (Exception e) {
   // throw e
}
```

However the JAR of our application became too large for our CI/CD pipeline due to Playwright - we noticed this is due to the drivers which includes for all supported OS, thus we did a Gradle workaround to only include the drivers we need [(we used this as reference)](https://github.com/microsoft/playwright-java/issues/1196#issuecomment-1869043692).
- In our `build.gradle`, we repackaged `driver-bundle.jar` via Gradle's `distribution` plugin  
- From 163 MB, we were able to size down the `driver-bundle.jar` to 63 MB by only retaining the Linux drivers.

## Expected behavior

When our application is run locally like via IDE, we are able to use Playwright without any issues.

## Actual behavior

However if we run our app in Docker and invoked the API that uses Playwright, we encountered this error:
![image](https://github.com/user-attachments/assets/e855c4a4-3d01-4080-8beb-57054eb5875d)

We then applied permissions to the `/tmp/` folder via the Dockerfile 
```bash
RUN chmod g+s /tmp/
RUN chown -R 1000:1000 /tmp/
```
but still we receive the same error. That's when we noticed that the `playwright-java-***` folder below is actually only created during the first instance `Playwright.create()` is invoked, as it only initializes the driver by then.
![image](https://github.com/user-attachments/assets/a271a11d-6bec-4ba5-99e6-fcf748590bdb)

We tried manually invoking the said `node` program inside the Docker instance and we received the same error as the logs.

What is the problem here? Is it because of our container using Alpine?

## Environment

- Operating System: [Alpine Linux via Docker]
- Browser: [Chromium]
- Java Version: [17]
- Gradle Version: [8.1.1]

**Comment by yury-s** [comment]
> What is the problem here?

Hard to tell, you run some custom packages. The standard package seems to run [fine in docker](https://github.com/microsoft/playwright-java/actions/workflows/test_docker.yml). If you want to skip the driver extraction step, you can pass 'playwright.cli.dir' [property](https://github.com/microsoft/playwright-java/blob/main/driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java#L110C51-L112) pointing to already installed driver's location which is probably your best bet. There is an open request for splitting the driver which is tracked in https://github.com/microsoft/playwright-java/issues/1196, you can upvote that issue.

> Is it because of our container using Alpine?

Alpine is not supported officially: https://playwright.dev/java/docs/intro#system-requirements
