### ISSUE TITLE
How to set download path of browser (like how we set in selenium) while launching the Browser?

### ISSUE THREAD

**Issue by imran0692** [microsoft/playwright-java#1636]
### Please do not submit this issue.

- [X] I understand

**Comment by imran0692** [comment]
I am trying to set the download path as part of LaunchOptions using below method,

setDownloadsPath(Paths.get(WebFunctions.createFolderForTC(this.getClass().getSimpleName()+"/"))));

**Comment by mxschmitt** [comment]
https://playwright.dev/java/docs/browsers#managing-browser-binaries

**Comment by imran0692** [comment]
Hi [mxschmitt] - Thanks for the reply, in the above mentioned link it states about where to download the drivers to launch the browser but my query is how to set the download path while launching browser which can be default path where files get saved when they are downloaded.

I need to set the download path in the browser as shown below in the image,
<img width="595" alt="image" src="https://github.com/user-attachments/assets/ac964195-25f9-46aa-b7d4-f30f48d597e6">

Please provide the code snippet in java

**Comment by mxschmitt** [comment]
We don't support that afaik but we support programmatic downloads: https://playwright.dev/java/docs/downloads

**Comment by imran0692** [comment]
Then what is the use of **setDownloadsPath** method in LaunchOptions.

What does the  **.setDownloadsPath(Paths.get("path/to/downloads"))** method do in the below code snippet

BrowserType.LaunchOptions options = new BrowserType.LaunchOptions()
                **.setDownloadsPath(Paths.get("path/to/downloads"))**
                .setHeadless(false);
