### ISSUE TITLE
I need the documentation where all the CreateOption arguments which we can use to set the browserBheaviour?

### ISSUE THREAD

**Issue by imran0692** [microsoft/playwright-java#1637]
### Please do not submit this issue.

- [X] I understand

**Comment by imran0692** [comment]
Please find snippet of code in which there is argument used, I want to get all the list of arguments which can use like this.

Map<String, String> env=new HashMap<String, String>();
env.put("PLAYWRIGHT_BROWSERS_PATH", WebFunctions.createFolderForTC(this.getClass().getSimpleName()+"/"));

CreateOptions cr=new CreateOptions();
cr.setEnv(env);
playwright=  Playwright.create(cr);

Question : I need argument which I can add it in the **env** Hashmap like **PLAYWRIGHT_BROWSERS_PATH**

**Comment by mxschmitt** [comment]
There is no such list, we recommend the documentation to see all the supported environment variables: https://playwright.dev/java/docs/browsers

If you have concrete requests, feel free to file a new issue.
