### ISSUE TITLE
[BUG] Can't work with some selectors

### ISSUE THREAD

**Issue by VladToporkov** [microsoft/playwright-java#164]
undefined:1
{"id":5,"guid":"Frame@3f7bb17e06603ea8d8186b3190c0e61c","method":"click","params":{"selector":"xpath \u003d //*[text()\u003d\u002709B8\u0027]"}}
                                                                                                                                  ^

SyntaxError: Unexpected token  in JSON at position 130
    at JSON.parse (<anonymous>)
    at Transport.onmessage (/snapshot/playwright-cli/lib/driver.js:48:75)
    at Immediate.<anonymous> (/snapshot/playwright-cli/node_modules/playwright/lib/protocol/transport.js:70:26)
    at processImmediate (internal/timers.js:456:21)

testCode
@Test
    public void test () throws Exception {
        Playwright playwright = Playwright.create();
        List<BrowserType> browserTypes = Arrays.asList(
                playwright.chromium(),
                playwright.webkit()
        );
        for (BrowserType browserType : browserTypes) {
            BrowserType.LaunchOptions options = new BrowserType.LaunchOptions();
            options.headless = false;
            Browser browser = browserType.launch(options);
            BrowserContext context = browser.newContext(
                    new Browser.NewContextOptions().withViewport(800, 600));
            Page page = context.newPage();
            page.navigate("http://ya.ru");
            page.click("xpath = //*[text()='Найти']");
            page.screenshot(new Page.ScreenshotOptions().withPath(Paths.get("screenshot-" + browserType.name() + ".png")));
            browser.close();
        }
        playwright.close();
    }

**Comment by yury-s** [comment]
Should be fixed in 0.171.0
