### ISSUE TITLE
[Docs]: 1.46 version not available in maven even though docs already states that it is released

### ISSUE THREAD

**Issue by MantasGurskis** [microsoft/playwright-java#1645]
### Page(s)

https://playwright.dev/java/docs/release-notes

### Description

1.46 version not available in maven even though docs already states that it is released

**Comment by yury-s** [comment]
It's not released yet. The documentation is rolled out for all languages at once when Playwright for Node.js is released, but the other language ports are published a few days later. You can watch corresponding GitHub Releases updates.
