### ISSUE TITLE
[Bug]: Trace Viewer Snapshots shows incomplete image

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright-java#1651]
### Version

1.45.1

### Steps to reproduce

The snapshot screenshots show the image as if the page has not fully rendered and/or some CSS is missing.  However, if you hover over the timeline, the correctly rendered image is shown

I don't have steps to reproduce but can provide a trace privately.  

### Expected behavior

I expect the screenshots in the snapshot to show the images properly

### Actual behavior

Trace sent via email

### Additional context

I can provide a trace privately that will show this behavior.  

### Environment

- OS: Mac
- Browser: Chromium
- Java: 17

**Comment by yury-s** [comment]
Do you mean that the styling of "Sign-in" box is off in the snapshot?

You can send the trace to the email in my profile.

**Comment by uchagani** [comment]
this is odd...i just viewed it on a different computer and the trace looks fine.  may be my machine.  I need to do some more investigation and if i can't figure it out i'll send the trace.  thank you.

**Comment by uchagani** [comment]
ok it looks like on chrome, the styling is off.  when viewed on Firefox, it looks fine.  sending trace.
