### ISSUE TITLE
[Bug]: Few buttons are not working on Playwright Browser Mobile View for "https://www.redbus.in"

### ISSUE THREAD

**Issue by Krishna-D-Hegde** [microsoft/playwright-java#1674]
### Version

1.47.0

### Steps to reproduce

1. Launch any Playwright Browser in mobile view for "https://www.redbus.in". Code used for the same:

Playwright playwright = Playwright.create();
		Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
        BrowserContext context = browser.newContext(
        new Browser.NewContextOptions()
        		.setViewportSize(414, 896) 
                .setDeviceScaleFactor(3)   
        		.setUserAgent("Mozilla/5.0 (iPhone14,6; U; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/19E241 Safari/602.1") 
                .setHasTouch(true)         
                .setIsMobile(true) 
        		);       
        Page page = context.newPage();
        page.navigate("https://www.redbus.in");

2. In the opened browser select any city as Source and Destination. This can be done manually as well in the opened browser
Example: Source - Bangalore; Destination - Hyderabad

3. Click any of the below highlighted buttons. None works

![image](https://github.com/user-attachments/assets/a718c7c4-c91d-41f7-b90b-47371a3170c9)

Note: The same works when we manually open the browser in mobile view. Also works fine with Selenium Java.

### Expected behavior

Clicks should work for the mentioned buttons

### Actual behavior

Clicks don't work

### Environment

Windows

**Comment by mxschmitt** [comment]
This one is similar to https://github.com/microsoft/playwright/issues/32301#issuecomment-2338580225. The buttons only attach `touchstart`/`touchend` listeners when they detect that its a mobile device. Playwright on the other hand does not dispatch these events, we only dispatch pointer events and click events. touchstart/touchend are deprecated as per https://github.com/microsoft/playwright/issues/32301#issuecomment-2338580225.

**Comment by yury-s** [comment]
Folding this request into https://github.com/microsoft/playwright/issues/2903, please upvote that one instead.
