### ISSUE TITLE
[Bug]: The Paypal window is not available in headless mode

### ISSUE THREAD

**Issue by pawel747** [microsoft/playwright-java#1675]
### Version

1.45.0

### Steps to reproduce

1. In the e-commerce store, I choose the Pay pal payment method.
2. An additional window pops up.
3. I want to fill out the form fields in the additional Pay pal window

`public Page switchToPayPalWindowAndPlaceOrder(String payPalEmail, String payPalPassword){
    Page popup = page.waitForPopup(() -> {
        page.waitForTimeout(5000);
        getPlaceOrderButton().click();
        page.waitForTimeout(5000);
        getPlaceOrderButton().click();
    });
    popup.getByPlaceholder("Email o numero di cellulare").fill(payPalEmail);
    popup.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Avanti")).click();
    popup.getByPlaceholder("Password").fill(payPalPassword);
    popup.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Accedi")).click();
    popup.getByTestId("submit-button-initial").click();
    return popup;
}`

### Expected behavior

It is possible to fill out the form fields in an additional Pay pal window

### Actual behavior

It is possible to fill out the form fields in an additional Pay pal window only in browser mode. I would like to fill in the fields in headless mode as well.

### Environment

Mac OS Sonoma 14.5 (23F79)
CPU - Apple M1
Chromium
Oracle OpenJDK 21.0.1
Maven 3.9.2

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Comment by pawel747** [comment]
Please provide additional information, what specific data you need to reproduce the problem.
