### ISSUE TITLE
[Bug]: Compilation issue while running my project on the latest version of playwright docker image

### ISSUE THREAD

**Issue by fabytta** [microsoft/playwright-java#1676]
### Version

1.47.0

### Steps to reproduce

we have a maven framework with java 11
we added the playwright library version 1.47.0, created our tests and everythong was going good localy
Now, while running tests on the latest version of playwright docker image available in dockerhub i get compilation issues : 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project test-starter-kit-ui: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x224d537d) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x224d537d -> [Help 1]`

How can I have a docker image which is java  11 compatible 

### Expected behavior

I expect to be able to pull playwright docker images according to java version I'm using 

### Actual behavior

Only latest version of playwright docker image is availabe 

### Environment

docker image used : mcr.microsoft.com/playwright/java
java version : 11 
playwright library version 1.47.0

**Comment by yury-s** [comment]
> I expect to be able to pull playwright docker images according to java version I'm using

Our docker image comes with ['openjdk-21-jdk'](https://github.com/microsoft/playwright-java/blob/db52fa94e75b0e2883d9b1590d2731550928f8fa/utils/docker/Dockerfile.noble#L10C48-L10C62) preinstalled. If you want to use different jdk version, you can install it manually. You can also pass target source version if you want.

Closing this report as it is not a Playwright bug. If you believe this is a Playwright problem, feel free to open another issue and attach a full reproduction example that we could run locally.

**Comment by fabytta** [comment]
well maybe, it's  a good idea that you mention these details in the documentation
