### ISSUE TITLE
how to set Chrome to full screen display？ using setArgs (List. of ("-- start maxized") does not work

### ISSUE THREAD

**Issue by yangwutong** [microsoft/playwright-java#1689]
### Please do not submit this issue.

- [x] I understand

**Comment by yangwutong** [comment]
>  Playwright playwright = Playwright.create();
>  Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
>                     .setHeadless(isHeadless)
>                     .setArgs(List.of("--start-maximized"))
>                     .setSlowMo(100));

this is my code, but setting is not work

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
