### ISSUE TITLE
[One Driver Download]

### ISSUE THREAD

**Issue by scrushy** [microsoft/playwright-java#1704]
### Please do not submit this issue.

- [x] I understand

**Comment by scrushy** [comment]
Currently, Playwright downloads all supported browser drivers (Chromium, Firefox, and WebKit) by default, even if only one browser is needed. This behavior can be inconvenient, especially in scenarios where storage or bandwidth is limited, or when only one specific browser (e.g., Chromium) is required for testing.

**Comment by mxschmitt** [comment]
You can skip browser downloads as per [here](https://playwright.dev/java/docs/browsers#skip-browser-downloads) and install them as a [separate step](https://playwright.dev/java/docs/browsers#install-browsers). Would that work for you?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
