### ISSUE TITLE
[ISSUE]How to download a browser that supports "all-codecs" and adapt it to the current version

### ISSUE THREAD

**Issue by xiaoqinqq** [microsoft/playwright-java#1707]
The default downloaded browsers do not have "all-codecs"？

- [ ] I understand

**Comment by mxschmitt** [comment]
You can leverage Google Chrome or Microsoft Edge for that. Only these browsers contain the codecs: https://playwright.dev/docs/browsers#media-codecs

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
