### ISSUE TITLE
[Regression]: NS_ERROR_NET_INTERRUPT errors with version 1.45.0 (no errors with 1.44.0)

### ISSUE THREAD

**Issue by BoD** [microsoft/playwright-java#1711]
### Last Good Version

1.44.0

### First Bad Version

1.45.0

### Steps to reproduce

1. `git clone https://github.com/BoD/repro-playwright-network-interrupt.git`
2. `./gradlew run`

## With 1.44.0

The page that appears has a blue panel on the left and should look like this:

![Image](https://github.com/user-attachments/assets/ea174065-ca3d-4178-9d6a-b4864d909e3f)

Also if you edit the url to remove everything except the domain name, and go to it, you should see this:

![Image](https://github.com/user-attachments/assets/b2c3e2b3-3af2-4a34-bd79-00cc83073211)

If you show the network calls while doing this, they all work normally:

![Image](https://github.com/user-attachments/assets/790baae9-213a-44c4-ba5b-78e8b17123d8)

## With 1.45.0

The page that appears doesn't have the blue left panel, and looks like this:

![Image](https://github.com/user-attachments/assets/772ebf18-8b3f-4537-a654-be407b4433c8)

If you edit the url to remove everything except the domain name and go to it the page doesn't load and show a network error instead:

![Image](https://github.com/user-attachments/assets/d4394f80-1d53-49ca-a552-cac853b72d43)

If you show the network calls while doing this, we can see a a `NS_ERROR_NET_INTERRUPT` error on the first request and no further requests:

![Image](https://github.com/user-attachments/assets/4129bf47-f2a4-4929-9330-641a7436f6f0)

### Additional context

- This also doesn't work with the latest Playwright version
- I'm noticing v1.44.0 is using Firefox 125.0.1, whereas v1.45.0 is using Firefox 127.0
- Trying to load these pages with the latest version of a "regular Firefox" (not within Playwright) works - you can try yourself to go to `https://suiviconso.edf.fr/comprendre` with Firefox, you should land on the page that looks like the first screenshot (blue left panel). 

### Environment

- System: ARM Mac
- OS: MacOS Sonoma 14.7.1

**Comment by yury-s** [comment]
Looks like the web site serves different content to the browser controlled by automation. Do you have an example with the page whose source you control which exposes this behavior?

**Comment by BoD** [comment]
Thanks for having a look. 

> Do you have an example with the page whose source you control which exposes this behavior?

I don't. I'm only using Playwright to scrape that website. 

Are you saying this site is detecting the presence of Playwright, but only with recent versions? Is Playwright setting a special User-Agent maybe? And if yes can I override it?

**Comment by yury-s** [comment]
> Are you saying this site is detecting the presence of Playwright, but only with recent versions?

Yes, that was my hunch.

> Is Playwright setting a special User-Agent maybe? And if yes can I override it?

You can override user-agent in the context options: https://playwright.dev/java/docs/emulation#user-agent

> I don't. I'm only using Playwright to scrape that website.

Playwright's primary focus is on testing scenarios, where you have some control over the web app under test. Given that this is a third-party app that exposes the issue and it's unclear if it's an intended behavior, we can't help with it. If you manage to narrow the problem down to a simple repro, feel free to open another request.

**Comment by BoD** [comment]
Actually, it looks like the site in question is broken with Firefox 127, independently of Playwright (no idea why).

I does work with the latest Firefox 134 though, so I'll just wait until Playwright uses a more recent version of Firefox before upgrading.
