### ISSUE TITLE
[Regression]: Screenshot not considering complete content when scrollable

### ISSUE THREAD

**Issue by awenirbanL** [microsoft/playwright-java#1712]
### Last Good Version

1.17.2

### First Bad Version

1.18.0

### Steps to reproduce

Hi,
It looks like I have stumbled upon a regression regarding ElementHandle.screenshot() for pages with scroll. Using 1.17.2, when a screenshot is invoked on an ElementHandle that does not fit the viewport, it expands the window to fit the element and then screenshots, resulting in the entire element being captured. However, starting from 1.18.0, it does not expand and captures only what is present in the viewport of the opened window. I have tried both with headful and headless using chromium and can replicate the issue.
I cannot provide the actual code but here's a snippet of the implementation in kotlin:
```kotlin
playwright.chromium().launch(
                BrowserType.LaunchOptions().apply {
                    setHeadless(false)
                    setArgs(listOf("--disable-crash-reporter", "--no-crashpad"))
                }
            ).use { browser ->
                val context = browser.newContext(Browser.NewContextOptions().setJavaScriptEnabled(true))
                val page = context.newPage()
                page.setDefaultTimeout(clientTimeout.toDouble())
                logger.debug("Navigating to URL: $clientUrl")
                page.navigate(clientUrl)
                
                val myElem = page.waitForSelector(
                    "#my-elem",
                    Page.WaitForSelectorOptions()
                        .setState(WaitForSelectorState.VISIBLE)
                        .setTimeout(clientTimeout.toDouble())
                )
               
                if (myElem != null && myElem.isVisible && myElem.isEnabled) {
                    val screenshot = myElem.screenshot(
                        ElementHandle.ScreenshotOptions()
                            .setType(ScreenshotType.PNG)
                        //.setAnimations(ScreenshotAnimations.DISABLED) //This was not available in 1.17.*
                    )
..... remaining code
``` 
```
implementation("com.microsoft.playwright:playwright:1.17.2")
``` 

### Expected behavior

I expect to see the entire content of myElem when the content is large enough to require both vertical and horizontal scrolling.

### Actual behavior

I see only the currently scrolled content.

### Additional context

I checked the Javadoc differences between the versions 1.17.2 and 1.48.0 where I first noticed the discrepancy:

v1.17.1 

```
public abstract byte[] screenshot(     ElementHandle. ScreenshotOptions options )
 
Returns the buffer with the captured screenshot.
This method waits for the actionability   checks, then scrolls element into view before taking a screenshot. If the element is detached from DOM, the method throws an error

```
v1.48.0

```
public abstract byte[] screenshot(     ElementHandle. ScreenshotOptions options )
 
This method captures a screenshot of the page, clipped to the size and position of this particular element. If the element is covered by other elements, it will not be actually visible on the screenshot. If the element is a scrollable container, only the currently scrolled content will be visible on the screenshot.
This method waits for the actionability   checks, then scrolls element into view before taking a screenshot. If the element is detached from DOM, the method throws an error.
Returns the buffer with the captured screenshot
```
Trying to figure where it first crept in, I reached v1.18.0, although the documentation did not reflect a change.

I observed the difference in the chromium versions they download and think it could be because of that as well.
v1.17.2 uses chromium v939194
v1.18.0 uses chromium v956323

### Environment

- OS: MacOS
- CPU: arm64
- Java: 20
- Browser: Chromium

**Comment by yury-s** [comment]
The behavior you describe is consistent with what our [documentation](https://playwright.dev/java/docs/api/class-elementhandle#element-handle-screenshot) says: "If the element is covered by other elements, it will not be actually visible on the screenshot. If the element is a scrollable container, only the currently scrolled content will be visible on the screenshot."

> Using 1.17.2

I recommend trying with the latest Playwright (1.49 as of today).

> I observed the difference in the chromium versions they download and think it could be because of that as well.

Each minor version of Playwright comes with the new version of the browsers (new major version for chromium).

> I cannot provide the actual code but here's a snippet of the implementation in kotlin:

Unfortunately, we can't take any action on this without a repro. Feel free to file another issue if you can provide a reproduction demonstrating that this is a bug in Playwright.

**Comment by awenirbanL** [comment]
Hi @yury-s , thanks for your prompt response. Do you have a test for the scenario where the ElementHandle.screenshot() is used, the width and height of the element is greater than the viewport, resulting in the need to scroll and still the .screenshot() captures the entire content? If there exists such a test, then you can easily repro this by changing the versions between 1.17.* and anything later, to see the difference in behaviour.
I will try to come up with a working example of this test that can be shared with you.
There's [this](https://github.com/microsoft/playwright/issues/12962#issuecomment-2092355051) bug link that speaks about the same issue.
