### ISSUE TITLE
Using page.route can degrade performance.

### ISSUE THREAD

**Issue by bookzhan** [microsoft/playwright-java#1713]
When I use page.route, the page loads much slower, about twice as slow as not using page.route. What could be the reason for this, and is there a solution?

**Comment by Drew-Ackerman** [comment]
To help debug what you are seeing, it would be helpful if you provided an example project that reproduces what you are seeing.

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
