### ISSUE TITLE
[Bug]: BrowserContext.onClose is not called with browser window is closed

### ISSUE THREAD

**Issue by davidnewcomb** [microsoft/playwright-java#1719]
### Version

1.49.0

### Steps to reproduce

```
git clone git@github.com:davidnewcomb/playright-bug-onclose.git
cd playright-bug-onclose
mvn clean install
```

I have modified the repo to only show this issue and moved registering event handlers to directly after the object is instantiated.

### Expected behavior

When I shutdown the browser with control+q or click the [X] window button then the event handler given to `BrowserContext.onClose` should be called.

According to your documentation at on [BrowserContext.close() Event](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-event-close) it says you *do* detect that the browser has disappeared and you *do* call the event handler registered with `BrowserClose.onClose(handler)` but you don't as my program demonstrates.

### Actual behavior

Playwright does not notice the browser is gone.

### Additional context

This is related to #1714 but I've moved the problem to the BrowserContext level because it occurs there too.

How can I call anything if Playwright never tells me the browser has disappeared. Do I have to get the browser PID myself and have a thread which constantly checks if the PID is active and then calls `BrowserContext.close()`? That feels like a Playwrite job ;)

According to your documentation at on [BrowserContext.close() Event](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-event-close) it says you *do* detect that the browser has disappeared and you *do* call the event handler registered with `BrowserClose.onClose(handler)` but you don't as my program demonstrates.

I can't even use `Browser.isConnected()` or `Page.isClosed()` in order to detect that the browser is not connected to anything, they don't notice either.

### Environment

-Operating System: MacOS Sequioa 15.2
-CPU: intel core i9
-Browser: Nightly
-Java version: Java version: 22.0.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/22.0.1/libexec/openjdk.jdk/Contents/Home
-Java compiled for v 1.8 and 21
-Tested on Nightly/firefox and Chromium
-Maven: 3.9.8
-Running in: Spring Tool Suite 4 - Version: 4.26.0.RELEASE

**Comment by Drew-Ackerman** [comment]
I ran a test using Playwright's Junit fixture to see if I could recreate what you were seeing.

```java
@UsePlaywright(PlaywrightOptions.class) // Setting headless to false
public class Test {
	@Test
	void onClose(Page page, BrowserContext context) throws InterruptedException {
		context.onClose(onClose -> {
			System.out.println("AHHH");
		});
		page.navigate("https://playwright.dev/");
		page.waitForTimeout(5000);
		assertThat(page).hasTitle(Pattern.compile("Playwright"));
	}
``` 
I did see `AHHH` printed to my console when the test closed successfully and when I closed the browser manually. 
I see you did not use Fixtures in demonstrating your test, I can try to recreate that later.

**Comment by yury-s** [comment]
`BrowserContext` is not expected to be closed when you close last window. E.g. you can have a scenario where you create and close pages (leaving 0 pages in the context):

```java
		for (int i = 0; i < 3; i++) {
			Page page = browserContext.newPage();
			page.close();
		}
```

This is working as intended. When the browser process exits, you'll receive [`onDisconnected`](https://playwright.dev/java/docs/api/class-browser#browser-event-disconnected) event. Also note, that Thread.sleep will not dispatch any events, see https://playwright.dev/java/docs/multithreading#synchronous-api-and-event-dispatching.

**Comment by davidnewcomb** [comment]
@Drew-Ackerman I'm not using fixtures I'm running it in a real program.

@yury-s in real life there are no `Thread.sleeps()` in my program I just wait in real life. I updated my program to use `waitForTimeout`

I think I have worked out what the problem is. Playwrite does not detect that the browser is gone and then call the event handlers. It waits until there is some interaction with the page which then fails and that failure triggers sending the event messages.

If you set up a browser and leave it waiting for a human to come along and tell it what to do (via my program). However if someone else has closed the window then Playwright does not notice. When the next person comes along they will find out it's broken when they try and use it. Basically the event is reactionary and not proactive, so you don't see the problem until you try to use it.

I guess I need something to keep poking the page so it can notice that the browser is gone and trigger the onClose callbacks. Does Playwrite have any heartbeat facilities?

Now when I create the Page with `BrowserContext.newPage` then I give the Page instance to another `Thread`  and that sits in a 60 second waitForTimeout. While it is in there if anyone closes the page then I get notified straight away. I hear what you said about the non-thread safe nature of Playwrite and am prepared to deal with that when the time comes but at the moment this seems to be working.

I still think that it's something that should be done on your side though. Or at least have a configuration option to switch on heartbeats in order to get a pro-active onClose.

**Comment by yury-s** [comment]
> It waits until there is some interaction with the page which then fails and that failure triggers sending the event messages.

This is the downside of the synchronous API and you have to make a playwright API call in order to pump events from the browser, see the link I sent above: https://playwright.dev/java/docs/multithreading#synchronous-api-and-event-dispatching

`page.waitForTimeout` is one way to make sure the events are dispatched while you are waiting. You can also use `waitForCondition()` to accomplish that in your program :
```java
        log("Close window, you have " + 100 + " seconds to comply! Connected=" + browser.isConnected());
        browserContext.waitForCondition(() -> !browser.isConnected(), new BrowserContext.WaitForConditionOptions().setTimeout(100_000));
```
This code will dispatch browser events, including disconnect, properly. Note that Chromium headed won't exit on `Cmd+q` when controlled by Playwright over pipe (but you can still `kill -9` browser process), webkit and firefox exit just fine. Hope this helps.
