### ISSUE TITLE
Error doesn't shows when playwright can't find selector

### ISSUE THREAD

**Issue by VladToporkov** [microsoft/playwright-java#173]
Expected result: User see exception If he try to find elementHandle which doesn't exist when timeout is done. 

@Test
    public void test () throws Exception {
        Playwright playwright = Playwright.create();
        List<BrowserType> browserTypes = Arrays.asList(
                playwright.chromium(),
                playwright.webkit()
        );
        for (BrowserType browserType : browserTypes) {
            BrowserType.LaunchOptions options = new BrowserType.LaunchOptions();
            options.headless = false;
            Browser browser = browserType.launch(options);
            BrowserContext context = browser.newContext(
                    new Browser.NewContextOptions().withViewport(800, 600));
            Page page = context.newPage();
            page.navigate("http://ya.ru");
            page.waitForSelector("\"text = ура123123123\"", new Page.WaitForSelectorOptions()
                    .withState(Page.WaitForSelectorOptions.State.ATTACHED));
            page.screenshot(new Page.ScreenshotOptions().withPath(Paths.get("screenshot-" + browserType.name() + ".png")));
            browser.close();
        }
        playwright.close();
    }

**Comment by yury-s** [comment]
`waitForSelector()` returns an object and doesn't wait for the selector, you should call `get()` on the object to wait for the event to happen:

```java
    Deferred<ElementHandle> event = page.waitForSelector("text = ура123123123", new Page.WaitForSelectorOptions()
      .withState(Page.WaitForSelectorOptions.State.ATTACHED));
    event.get();
```

This is the trickiest part in the API as it is very easy to forget to call `.get()` (made this mistake many times myself), we need to fix this somehow. Having an annotation on `waitForSelector` that the method's result must be used would be very helpful but unfortunately there is no such annotation in standard java and all existing solutions would be IDE/vendor specific and would bring in extra dependencies for each of them.
