### ISSUE TITLE
BrowserType.LaunchOption set option 'withEnv' type mismatch

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#175]
When use BrowserType.LaunchOptions to set environment, the function definition syntax of 'withEnv' has parameter as string, but when compile it's fail on type check asking parameter as an Array of string

playWright = Playwright.create();
BrowserType browserType = playWright.chromium();
BrowserType.LaunchOptions options = new BrowserType.LaunchOptions();
options.withEnv("DEBUG=pw:protocol");

parameter define as string
![image](https://user-images.githubusercontent.com/6579909/103175656-93816a80-4839-11eb-982c-ebafdefeb904.png)

compilation error: expect an array
![image](https://user-images.githubusercontent.com/6579909/103175666-aac05800-4839-11eb-903f-7f2e5874429a.png)

**Comment by yury-s** [comment]
Thanks for the report, there is indeed a bug in the generated API, it has to be a map of strings.

Looking at your code snippet it seems that what you need is actually to change environment of playwright driver process not the browser. For that it should be enough to set `DEBUG=pw:protocol` for the java process. E.g.
```bash
DEBUG=pw:protocol mvn test
```
Will dump protocol for the test to stderr.
