### ISSUE TITLE
[Bug] Improve ignoreDefaultArgs option

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-java#178]
I came here while reviewing this property in the .NET version. I think we can make some improvements.
` public Boolean ignoreDefaultArgs;` could be an object.
We could have `withIgnoreDefaultArgs` with overloads.

```java
public LaunchOptions withIgnoreDefaultArgs(List<String> ignoreDefaultArgs) {
    this.ignoreDefaultArgs = ignoreDefaultArgs;
    return this;
}
public LaunchOptions withIgnoreDefaultArgs(Boolean ignoreDefaultArgs) {
    this.ignoreDefaultArgs = ignoreDefaultArgs;
    return this;
}
```

I also found that this option is a string in `LaunchPersistentContextOptions` is that ok?

**Comment by yury-s** [comment]
Sounds like a bug to me.
