### ISSUE TITLE
Dockerfile is outdated

### ISSUE THREAD

**Issue by mboitet** [microsoft/playwright-java#190]
Hello,

Dockerfile.focal looks to be outdated and references script that is no more existing :
./scripts/download_driver.sh
As a consequence the image can't be build .

Regards.
Michael

**Comment by codeboyzhou** [comment]
@mboitet Hi, thanks for your feedback, there is indeed a minor issue.
Now the script file should be `./scripts/download_driver_for_all_platforms.sh`, I have try to fix it.
Or you can also correct it temporarily in your local `Dockerfile.focal` file before the code is merged into branch `master`.
