### ISSUE TITLE
Failed to process descriptor 

### ISSUE THREAD

**Issue by skanga** [microsoft/playwright-java#207]
Fabulous project. Thanks for creating it!

My playwright java program works just fine but I always get the following warning:
Failed to process descriptor at C:\Users\SKANGA\AppData\Local\Temp\playwright-java-6634219733458767107

What does this mean and how do I prevent it?
Thanks

**Comment by yury-s** [comment]
This is printed out by playwright-cli when it's installing browsers, it's purely information message and you should ignore it as it is a part of normal workflow which didn't exist in typescript. I'll update playwright-cli to suppress it.

**Comment by mxschmitt** [comment]
I think it was already fixed here: https://github.com/microsoft/playwright/pull/4786

**Comment by yury-s** [comment]
Yeah, I just realized it was fixed there and should work now in 0.180.0-SNAPSHOT

**Comment by skanga** [comment]
It does NOT happen only first time. Seems to happen every time. Which release has your fix?
