### ISSUE TITLE
[Question] does playright-java support recording and generating code like playright-python?

### ISSUE THREAD

**Issue by ivanli1990** [microsoft/playwright-java#209]
Playwright-python can record user interactions in a browser and generate code，so does playwright-java support this feature？

**Comment by yury-s** [comment]
Not yet but stay tuned we'll add it once the java API is more stable (we're going to change the way waitForEvent() is handled).

**Comment by ivanli1990** [comment]
> Not yet but stay tuned we'll add it once the java API is more stable (we're going to change the way waitForEvent() is handled).

By the way, what are the correct steps to start playwright-java usage?

In the readme just say that user need to add maven dependency, I did it but got an error as below in idea:
```
Exception in thread "main" java.lang.RuntimeException: Failed to find playwright-cli
```
And then, I installed drivers successful by executing `download_driver_for_all_platforms.sh` , but got an error as below when executed `install_local_driver.sh`:
```
Downloading driver for macOS
Downloading driver for mac to /Users/ivanli/Documents/mt/fromGit/qa/waimai/ui/play-ui-java/src/main/resources/driver/mac
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   215  100   215    0     0     84      0  0:00:02  0:00:02 --:--:--    84
Archive:  playwright-cli-1.8.0-next-1610046700000-mac.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of playwright-cli-1.8.0-next-1610046700000-mac.zip or
        playwright-cli-1.8.0-next-1610046700000-mac.zip.zip, and cannot find playwright-cli-1.8.0-next-1610046700000-mac.zip.ZIP, period.
```
So, what are the correct steps to start playwright-java usage? I am a bit confused now how to get started.
And, I also want to know what is the difference between driver and playwright-cli.

**Comment by ivanli1990** [comment]
> > Not yet but stay tuned we'll add it once the java API is more stable (we're going to change the way waitForEvent() is handled).
> 
> By the way, what are the correct steps to start playwright-java usage?
> 
> In the readme just say that user need to add maven dependency, I did it but got an error as below in idea:
> 
> ```
> Exception in thread "main" java.lang.RuntimeException: Failed to find playwright-cli
> ```
> 
> And then, I installed drivers successful by executing `download_driver_for_all_platforms.sh` , but got an error as below when executed `install_local_driver.sh`:
> 
> ```
> Downloading driver for macOS
> Downloading driver for mac to /Users/ivanli/Documents/mt/fromGit/qa/waimai/ui/play-ui-java/src/main/resources/driver/mac
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   215  100   215    0     0     84      0  0:00:02  0:00:02 --:--:--    84
> Archive:  playwright-cli-1.8.0-next-1610046700000-mac.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of playwright-cli-1.8.0-next-1610046700000-mac.zip or
>         playwright-cli-1.8.0-next-1610046700000-mac.zip.zip, and cannot find playwright-cli-1.8.0-next-1610046700000-mac.zip.ZIP, period.
> ```
> 
> So, what are the correct steps to start playwright-java usage? I am a bit confused now how to get started.
> And, I also want to know what is the difference between driver and playwright-cli.

Update, it works now after I execute `download_driver_for_all_platforms.sh`, but playwright starts very slowly, it takes about 40s from startup to running, and some error is printed as below:
```
(node:91725) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at /snapshot/playwright-cli/node_modules/proper-lockfile/lib/lockfile.js:68:47
    at callback (/snapshot/playwright-cli/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:168:5)
(node:91725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:91725) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
How to fix this error? and does the slow startup time related to this error?

**Comment by yury-s** [comment]
> So, what are the correct steps to start playwright-java usage? I am a bit confused now how to get started.

Did you follow the steps from [this page](https://github.com/microsoft/playwright-java#usage)? Look at [the example project](https://github.com/microsoft/playwright-java/tree/master/examples) you need something like that.


> And, I also want to know what is the difference between driver and playwright-cli.

These are roughly two names for the same thing .


> Update, it works now after I execute `download_driver_for_all_platforms.sh`, but playwright starts very slowly, it takes about 40s from startup to running, and some error is printed as below:

You should not need to use `download_driver_for_all_platforms.sh` at all unless you are developing playwright. If you set up your Maven project correctly it will download the driver automatically.


> How to fix this error? and does the slow startup time related to this error?

You are running two playright-cli at the same time and they are competing for a lockfile. First time you launch playwright it will download browser binaries for you platform which may take some time. Next run should be faster as the binaries will be picked up from cache.

**Comment by ivanli1990** [comment]
@yury-s hi, thx reply

> You are running two playright-cli at the same time and they are competing for a lockfile. First time you launch playwright it will download browser binaries for you platform which may take some time. Next run should be faster as the binaries will be picked up from cache.

I still don't quite understand why I am running two playright-cli at the same time. I just ran [the example project](https://github.com/microsoft/playwright-java/tree/master/examples)  once in IDEA or terminal(as shown in the example readme), then error happened:
```
(node:91725) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
```

**Comment by ivanli1990** [comment]
@yury-s Hi, thx reply. I found browsers were installed in driver-bundle-x.jar by executing `playwright-cli install`, then I have 2 questions:
1. Can I just install a single specific browser not all browsers? e.g., just chromium
2. Every time running will execute playwright-cli to install the browser, and if remote browser version updated, the next running will down and install again the latest browser but not using the older in local cache? If so it, how to avoid? I only want the browser to be installed once whether the version is updated or not.

**Comment by yury-s** [comment]
> 1. Can I just install a single specific browser not all browsers? e.g., just chromium.
No, there is no such option at the moment.

> 2. Every time running will execute playwright-cli to install the browser, and if remote browser version updated, the next running will down and install again the latest browser but not using the older in local cache? If so it, how to avoid? I only want the browser to be installed once whether the version is updated or not.

Each version of playwright-java comes with a fixed version of playwright-cli which in turn comes with a fixed version of the browsers. So it will be downloaded only once.

Closing this issue as it strayed too far from the original topic. Feel free to file a separate feature request for java codegen but in any case it's already on our roadmap.
