### ISSUE TITLE
[test] Test failed: com.microsoft.playwright.TestBrowserContextProxy.shouldExcludePatterns

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#210]
Test failed on windows: Chromium/Webkit/Firefox

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.microsoft.playwright.TestBrowserContextProxy
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/C:/Users/ephun/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar) to field java.io.DataInputStream.bytearr
[ERROR] WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.94 s <<< FAILURE! - in com.microsoft.playwright.TestBrowserContextProxy
[ERROR] com.microsoft.playwright.TestBrowserContextProxy.shouldExcludePatterns  Time elapsed: 0.409 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: did not throw
        at com.microsoft.playwright.TestBrowserContextProxy.shouldExcludePatterns(TestBrowserContextProxy.java:180)

**Comment by mxschmitt** [comment]
Closing since it seems stale and passing on the CI.
