### ISSUE TITLE
[Question] does playwright object design to be thread safety?

### ISSUE THREAD

**Issue by Farley-Chen** [microsoft/playwright-java#212]
I found that when doing operation with the same playwright object under multi-thread may throw `PlaywrightException: Object doesn't exist: BrowserContext@3453a9326319bd981cb8ebe57b0c34d2` or `PlaywrightException: Cannot find command to respond`,

`PlaywrightException: Object doesn't exist`'s cause seems like that every component create by the same playwright object should register to the same connection object by `Connection.registerObject() `

and connection use a `HashMap` to do so, but `HashMap` is not thread safety

when `HashMap` expand its size under multi-thread, some data will lose

and `PlaywrightException: Cannot find command to respond` seems to be caused by the same reason, that `Connection.internalSendMessage()` put the message in the `callbacks` attribute which is a `HashMap`

test code like this:
```java
 public static void main(String[] args) throws Exception {
        var playwright = Playwright.create();
        var browser = playwright.firefox().launch(new BrowserType.LaunchOptions().withHeadless(true));
        for (int i = 0; i < 100; i++) {
            new Thread(() -> {
                // create the component, seems it will be registered in the connection object
                var context = browser.newContext();
                System.out.println("create ok");
                // use the component, it will get from the connection object but not found
                context.cookies("http://www.bing.com");
            }).start();
        }
        Thread.sleep(30000);
        playwright.close();
    }
```
(I'm not a native English speaker, and I'm a beginner of coding so if there something wrong, please tell me, Thanks!)

**Comment by yury-s** [comment]
No, Playwright is not thread safe, i.e. all its methods as well as methods on all objects created by it (such as BrowserContext, Browser, Page etc.) are expected to be called from the same thread where `Playwright` object was created  or proper synchronization should be implemented to ensure only one thread calls playwright methods at any given time. Having said that it's okay to create new playwright instance on a new thread. I'll update README.md to reflect this.
