### ISSUE TITLE
[Question] - Is there a way to define where the browsers should be installed?

### ISSUE THREAD

**Issue by LawrenceZ** [microsoft/playwright-java#213]
Similar to what it does in nodejs - https://playwright.dev/docs/installation?_highlight=home#managing-browser-binaries, by passing **PLAYWRIGHT_BROWSERS_PATH**, to allow user to change the default path e.g. for mac - **~/Library/Caches/ms-playwright to $HOME/pw-browsers**

**Comment by kblok** [comment]
@LawrenceZ you can use the same environment variables :)

**Comment by LawrenceZ** [comment]
@kblok, I’m not so sure I can set (or how to set) with java binding. I see launch options has withEnv() but there’s a bug with that method as of now to try it out, and also not sure if that’s where you can pass that env variable. Any idea? Thanks!

**Comment by LawrenceZ** [comment]
worked when setting it as environment variable
