### ISSUE TITLE
[Feature] Page.addInitScript not support inject file with path or javascript contents

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#230]
In playwright nodejs it support path and content, but not in playwright-java
example support inject with file path:
await page.addInitScript({ path: path.join(__dirname, 'assets/injectedfile.js') });

example: support inject with js content:
await page.addInitScript({ content: 'window["injected"] = 123' });

**Comment by yury-s** [comment]
Should be fixed now.
