### ISSUE TITLE
Playwright.close() should not throw Exception

### ISSUE THREAD

**Issue by jnizet** [microsoft/playwright-java#239]
Exception is not specific enough.

The method actually throws IOException and InterruptedException.

But IOException is caught and rethrown as PlaywrightException by `Playwright.create()`, so it would be logical to be consistent and to do the same thing in `close()`.

Regarding the InterruptedException, it's only thrown if the wait for the end of the driver process is being interrupted. But since the method ignores such failures anyway after a timeout, it would also seem logical to catch the InterruptedException, set back the interrupt status of the thread, and ignore the exception:

    boolean didClose = false;
    try {
      didClose = driverProcess.waitFor(30, TimeUnit.SECONDS);
    } catch (InterruptedException e) {
      // reset the interrupted status of the thread so that callers higher on the stack know the thread has been interrupted
      Thread.currentThread().interrupt();
    }
    if (!didClose) {
      System.err.println("WARNING: Timed out/Interrupted while waiting for driver process to exit");
    }

**Comment by yury-s** [comment]
Agreed, let's remove Exception from the signature and either swallow (when appropriate) or wrap all exceptions into PlaywrightException.
