### ISSUE TITLE
[Question] Is it any plans for async interfaces?

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [microsoft/playwright-java#242]
Currently when video record is enabled closing context taking additional 15-20 second, so im curious will async operation be available in neares future or maybe there is a way to dissmiss video recording (like when test passed there is no need of video)

**Comment by yury-s** [comment]
There are no plans to add async API in java (lack of async/awai makes it really cumbersome to write async code like we do in typescript). That said context closure taking that long is not acceptable, do you have an example where it happens? Which browsers experience this problem?

There is a similar upstream bug report so I'd like to collect more information about the scenarios, we'd much rather make the recording always faster without extra params but if that fails being able to dismiss video on context closure is also an option.

**Comment by yury-s** [comment]
Closing this issue as there are no plans to add async APIs at the moment and the video problem is tracked upstream (https://github.com/microsoft/playwright/issues/5051) and will be addressed there.
