### ISSUE TITLE
[BUG] Can't seem to get viewport = null and lauch args --start-maximized to work

### ISSUE THREAD

**Issue by haukia875** [microsoft/playwright-java#258]
Based on the docs and node.js version viewport null should maximize viewport and launch args "--start-maximized" to launch browser (chromium in my case) maximized.

Did I miss something?

Test code below:
```
package org.example;

import com.microsoft.playwright.*;

import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;


public class PageScreenshot {

  public static void main(String[] args) throws Exception {
    try (Playwright playwright = Playwright.create()) {
          
      BrowserType browserType = playwright.chromium();
     
      Browser.NewContextOptions options = new Browser.NewContextOptions();
      options.viewport = null;

      BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions().withArgs(Arrays.asList(new String[]{"--start-maximized"}));
      launchOptions.withHeadless(false);

      try (Browser browser = browserType.launch(launchOptions);
            BrowserContext context = browser.newContext(options);
            Page page = context.newPage()) {
        page.navigate("http://whatsmyuseragent.org/");
        page.screenshot(new Page.ScreenshotOptions().withPath(Paths.get("screenshot-" + browserType.name() + ".png")));
    
        System.out.print("Press enter to quit . . . ");
        System.in.read();
      }
    }
  }
}
```

This works as intented on node.js version
```
const { chromium } = require('playwright');

async function test() {
    const browser = await chromium.launch({
        args: ['--start-maximized'],
        headless : false, slowMo : 50});
    const context = await browser.newContext({viewport : null});
    const loginPage = await context.newPage();
    await loginPage.goto('http://todomvc.com'); 
}

test();
```

Also the "mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot" in readme to run example did not work. 
Fixed that with:

```
<plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.0.0</version>
            <configuration>
                <mainClass>org.example.PageScreenshot</mainClass>
            </configuration>
        </plugin>
```
Then  mvn compile exec:java to execute

**Comment by yury-s** [comment]
> Based on the docs and node.js version viewport null should maximize viewport and launch args "--start-maximized" to launch browser (chromium in my case) maximized.
> 
> Did I miss something?

No, you are absolutely right. Just need to implement this part. Will have a look into this next week.

> Also the "mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot" in readme to run example did not work.
> Fixed that with:

Hm, this is weird. What Maven version do you use? I didn't see such problem with `3.6.3`. We can add that plugin to the example's pom.xml if necessary but I'd like to keep it lean and mean so that there are fewer distractions for people less familiar with Maven configs.
