### ISSUE TITLE
[Question] Downloads temp file

### ISSUE THREAD

**Issue by MacoGaminG** [microsoft/playwright-java#269]
Hi, I'm making a program that will be able to bypass captchas. The problem is, I have to download the audio as a temporary file and then delete it.

I don't know how to do with playwright-java to download a file and put it in app directory with relative path.

(The audio is a web link like this: http://www.evidenceaudio.com/wp-content/uploads/2014/10/lyricslap.mp3)

Thanks.

**Comment by yury-s** [comment]
You could create a page with a download link and then use playwright to click on it, something like this:

```java
    Download download = page.waitForDownload(() -> page.click("a"));
    System.out.println(download.path());
```
