### ISSUE TITLE
[BUG] TestWaitForFunction is failing

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#300]
[ERROR]   TestWaitForFunction.shouldAvoidSideEffectsAfterTimeout:82 did not throw
[ERROR]   TestWaitForFunction.shouldFailWithPredicateThrowingOnFirstCall:106 did not throw
[ERROR]   TestWaitForFunction.shouldFailWithPredicateThrowingSometimes:121 did not throw
[ERROR]   TestWaitForFunction.shouldFailWithReferenceErrorOnWrongPage:131 did not throw
[ERROR]   TestWaitForFunction.shouldNotBeCalledAfterFinishingSuccessfully:260 expected: <[waitForFunction1, waitForFunction2, waitForFunction3]> but was: <[]>
[ERROR]   TestWaitForFunction.shouldNotBeCalledAfterFinishingUnsuccessfully:277 did not throw
[ERROR]   TestWaitForFunction.shouldWorkWithMultilineBody:228 expected: <true> but was: <null>
[ERROR] Errors:
[ERROR]   TestWaitForFunction.shouldPollOnInterval:68 NullPointer

**Comment by yury-s** [comment]
Which platform/browser is it?

**Comment by ephung01** [comment]
Windows Platform (chrome, webkit, and firefox)

**Comment by ephung01** [comment]
nevermind:  I did a force download and it fix the issue >> $ ./scripts/download_driver_for_all_platforms.sh -f

**Comment by yury-s** [comment]
Perhaps we should do force download by default, people who run the script usually understand what they are doing.
