### ISSUE TITLE
请问playwright-java是否支持centos6？

### ISSUE THREAD

**Issue by zdx0122** [microsoft/playwright-java#305]
求救，playwright-java是否支持centos6，安装依赖包崩溃中。。。
利用Jenkins在centos6.9上跑playwright-java，提示缺少包
`  Missing libraries are:
      libatk-bridge-2.0.so.0
      libxkbcommon.so.0
      libgbm.so.1
      libgtk-3.so.0
      libgdk-3.so.0
      libatspi.so.0
      libxshmfence.so.1`
![image](https://user-images.githubusercontent.com/16571331/108941073-67466680-768f-11eb-8dd0-78d66afde4e8.png)

**Comment by yury-s** [comment]
CentOS is not officially supported, we create binaries run tests on ubuntu 18.04 and 20.04 which are the two linux distros that we officially supported. With that said you can try to install missing dependencies and see if it fixes the problem but the chances are slim, most likely it'd require a dedicated build.

**Comment by arkasandr** [comment]
@zdx0122  I had the same problem with trying to start my app in Docker on Linux Alpine on my server. These dependencies were missing. But my problem was in uncorrect Dockerfile. 
`FROM mcr.microsoft.com/playwright as backend
ENV TZ=Europe/Moscow
ENV LANG=en_US.UTF-8
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-11-jdk maven
USER root
RUN mkdir /vpk
COPY / .
RUN mvn install
#ENTRYPOINT exec java -cp target/vpkPaper-1.0.jar
ENTRYPOINT exec java -cp target/vpkPaper-1.0.jar
`
may be it hepls you

**Comment by wasd345** [comment]
请问python版本的是否支持centos?

**Comment by zdx0122** [comment]
> 请问python版本的是否支持centos?

@wasd345 作者回复说不支持centos，但是我在centos7上面是可以安装成功的，已经运行了很长时间

**Comment by sunxlChinaSD** [comment]
@zdx0122 求救，在Jenkins centos7上执行playwright-java文件，一直报错“An exception occured while executing the Java class. null: InvocationTargetException: Failed to create driver: Failed to install browsers”，这个问题有遇到过吗，在centos7除了下面两个命令安装之外，还有其他环境需要安装吗
官网给的安装操作如下：
“mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
“mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"


但是我执行这两个命令后，再执行“mvn compile exec:java -D exec.mainClass="org.example.App"，就会报错“ Failed to create driver: Failed to install browsers”

**Comment by zdx0122** [comment]
> @zdx0122 求救，在Jenkins centos7上执行playwright-java文件，一直报错“An exception occured while executing the Java class. null: InvocationTargetException: Failed to create driver: Failed to install browsers”，这个问题有遇到过吗，在centos7除了下面两个命令安装之外，还有其他环境需要安装吗 官网给的安装操作如下： “mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install" “mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"
> 
> 但是我执行这两个命令后，再执行“mvn compile exec:java -D exec.mainClass="org.example.App"，就会报错“ Failed to create driver: Failed to install browsers”

看上去是安装浏览器失败，可能是网络原因，下载浏览器失败或者浏览器对应的依赖包没有安装导致的

**Comment by NineSu** [comment]
> > 请问python版本的是否支持centos?
> 
> @wasd345 作者回复说不支持centos，但是我在centos7上面是可以安装成功的，已经运行了很长时间

您好，请问一下您在centOS7上安装的playwright是哪个版本的

**Comment by NineSu** [comment]
你在CentOS7上装的哪个版本的playwright鸭
