### ISSUE TITLE
Playwright and Browser not implementing AutoCloseable

### ISSUE THREAD

**Issue by youp0214** [microsoft/playwright-java#313]
I get an error on
`` (Playwright playwright = Playwright.create())``
I checked the ``Playwright`` interface code in the libraries of my project and found out that it doesn't implement ``AutoCloseable`` (same thing for ``Browser`` interface) but the code here on github has them both implementing ``AutoCloseable``
here is my code snippet :

     try (Playwright playwright = Playwright.create()) {
            BrowserType firefox = playwright.firefox()
            Browser browser = firefox.launch();
            Page page = browser.newPage();
            page.navigate("https://example.com");
           browser.close();}

**Comment by yury-s** [comment]
This is not in 0.180* revisions, only available in tip-of-tree now. We'll release a new version with all api updates in a few days.
