### ISSUE TITLE
[Question] Can Playwright Inspector generate json, csv, xls?

### ISSUE THREAD

**Issue by cyrly97** [microsoft/playwright-java#336]
In my case, I use Playwright to build my web app, so I hope that it can import. Are there any plans to do this in the future version?thanks!

**Comment by yury-s** [comment]
Could you explain what kind of content you want to see in the generated csv/json/xls files? (I assume you are referring to codegen feature of the inspector which currently records user actions in the form of a playwright script).

**Comment by cyrly97** [comment]
> Could you explain what kind of content you want to see in the generated csv/json/xls files? (I assume you are referring to codegen feature of the inspector which currently records user actions in the form of a playwright script).

such as page operation, element selectors and input

**Comment by yury-s** [comment]
Inspector codegen produces playwright java code snippets (see [documentation](https://playwright.dev/java/docs/cli?_highlight=codegen#usage)) with selectors and actions. This is the only format used to record them and there are no plans to add other at the moment.
