### ISSUE TITLE
[Question] Is HAR recording possible

### ISSUE THREAD

**Issue by bgmf** [microsoft/playwright-java#337]
Sorry if this is a silly question, but I just learned of this library and was wondering, whether or not Playwright-Java can do HAR capturing.

A quick search seemed to indicate that on node.js this seems possible... Am I correct?

Thanks in advance!

**Comment by yury-s** [comment]
Yes, it is possible same way as in node.js version, you need specify output path via [`setRecordHarPath`](https://playwright.dev/java/docs/api/class-browser?_highlight=setrecordharpath#browsernewpageoptions) when creating context, e.g.:

```java
Path harFile = Paths.get("test.har");
BrowserContext context = browser.newContext(new Browser.NewContextOptions().setRecordHarPath(harFile));
Page page = context.newPage();
```

In general playwright java supports all features that its javascript counterpart except for some edge-case browser specific stuff (like CDP session etc).

**Comment by bgmf** [comment]
@yury-s thank you for your answer! Have a nice day!
