### ISSUE TITLE
[Question] target release date

### ISSUE THREAD

**Issue by materia2021** [microsoft/playwright-java#343]
Not an issue but just a question.

Do you have a target release date for version 1? 
I want to use this for my next project. I'm more comfortable with java than JS/TS.

**Comment by yury-s** [comment]
So far we haven't seen any serious problems with the alpha version so I if nothing unexpected popups in the next week or we should be ready to remove alpha flag. Meanwhile we are approaching Playwright 1.10 release date so we'll likely wait for that and push 1.10 as first stable Java release. So it should be in the next few weeks if nothing breaks badly.
