### ISSUE TITLE
[Question] Disabled cache resources?

### ISSUE THREAD

**Issue by drrodio** [microsoft/playwright-java#344]
Hi there, 

We are facing a weird behaviour with Playwright Java. We are testing load speed of different websites and we have seen that chromium is not caching resources. With the same chromium version and config in nodejs we see memory and disk cache sources for resources like js, images, ... in network tab (javascript console), but it doesn't happen when we execute in Java

We are a bit lost because it seems all ok, could you please guide us?

Thanks a lot

**Comment by drrodio** [comment]
With Webkit and Firefox is caching properly ... any ideas?

**Comment by drrodio** [comment]
Hey!

We have found that the problem appears when using a proxy with credentials to make a request.

We cannot understand why the cache is disabled when credentials are set. This is an snippet of crNetworkManager.js

`async _updateProtocolRequestInterception() {
        const enabled = this._userRequestInterceptionEnabled || !!this._credentials;
        if (enabled === this._protocolRequestInterceptionEnabled)
            return;
        this._protocolRequestInterceptionEnabled = enabled;
        if (enabled) {
            await Promise.all([
                this._client.send('Network.setCacheDisabled', { cacheDisabled: true }),
                this._client.send('Fetch.enable', {
                    handleAuthRequests: true,
                    patterns: [{ urlPattern: '*' }],
                }),
            ]);
        }
        else {
            await Promise.all([
                this._client.send('Network.setCacheDisabled', { cacheDisabled: false }),
                this._client.send('Fetch.disable')
            ]);
        }
    }
`

**Comment by yury-s** [comment]
This is a known limitation of Plywright, emulating http credentials requires network interception in Chromium which in turns requires disabling cache . In general perf testing with Playwright may give skewed numbers and is not recommended.

**Comment by drrodio** [comment]
Thanks for the info
