### ISSUE TITLE
[Question]: How do i switch to new tab or window in playwright-java?

### ISSUE THREAD

**Issue by chetanSrajiv** [microsoft/playwright-java#345]
How can we Switch to a new window that has opened while running test and how can i get back to the parent window in playwright-java

**Comment by yury-s** [comment]
You can wait for child windows created by the page using [`page.waitForPopup`](https://playwright.dev/java/docs/api/class-page/#pagewaitforpopupoptions-callback) and [`context.waitForPage`](https://playwright.dev/java/docs/api/class-browsercontext?_highlight=context.wait#browsercontextwaitforpageoptions-callback), e.g.:

```java
Page popup = page.waitForPopup(() -> {
  page.click('a');
});
System.out.println(popup.evaluate("location.href"));
```

See documentation [here](https://playwright.dev/java/docs/multi-pages#handling-popups). Note that modal dialogs created via `alert(), prompt(), confirm()` are handled using [`page.onDialog`](https://playwright.dev/java/docs/dialogs).

**Comment by suneel944** [comment]
this.page.context().pages().get(index_you_want_to_switch)
this.page.bringToFront()

then you can easily perform your task with ease

**Comment by LucasParsly** [comment]
String newUrl = page.context().pages().get(1).url();
page.navigate(newUrl);
