### ISSUE TITLE
[Question] The ElementHandle for a disabled link does not return true when I call isDisabled()

### ISSUE THREAD

**Issue by skanga** [microsoft/playwright-java#354]
Consider the following link
`<a href="http://blahblah.com" disabled class="mylink">text here</a>`

Then in my Java code:
```
ElementHandle nextLink = page.querySelector("a:has-text(\"text here\")");
if (nextLink.isDisabled()) doSomething();    // This returns FALSE - it should return TRUE

if (nextLink.toString().contains(" disabled")) doSomething();    // This is my workaround

```

NB: Edited formatting for clarity

**Comment by yury-s** [comment]
What is the actual selector that you pass to `page.querySelector`?

It may be that the element that resolve to the selector changes after you got the handle, [`Page.isDisabled(selector)`](https://playwright.dev/java/docs/api/class-page?_highlight=page.isdi#pageisdisabledselector-options) may come in handy in some of such scenarios.

**Comment by skanga** [comment]
Thanks @yury-s - I've edited my question to make it more clear.

1. The actual selector is as shown in the Java code.
2. I do NOT think the element changes because then the "workaround" would also break. But that works.

**Comment by yury-s** [comment]
Thanks for correcting the example. The problem is `disabled` attribute doesn't affect behavior of `<a/>` tag and `isDisabled` will always return false for them. This behavior is described in [out documentation](https://playwright.dev/java/docs/actionability#enabled), there are some more details [here](https://www.w3schools.com/tags/att_disabled.asp). If you merely need to check if the element has `disabled` attribute you can always use [`getAttribute("disabled")`](https://playwright.dev/java/docs/api/class-elementhandle?_highlight=getat#elementhandlegetattributename). Something like this:

```java
package org.example;

import com.microsoft.playwright.*;

public class Example {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create();
         Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
           .setHeadless(false));
         BrowserContext context = browser.newContext()) {
      Page page = context.newPage();
      {
        page.setContent("<a href=\"http://blahblah.com\" disabled class=\"mylink\">text here</a>");
        ElementHandle nextLink = page.querySelector("a:has-text(\"text here\")");
        System.out.println("isDisabled() = " + nextLink.isDisabled());
        System.out.println("getAttribute = " + (nextLink.getAttribute("disabled") != null));
      }
      {
        page.setContent("<button disabled>text here</button>");
        ElementHandle nextLink = page.querySelector("button:has-text(\"text here\")");
        System.out.println("isDisabled() = " + nextLink.isDisabled());
        System.out.println("getAttribute = " + (nextLink.getAttribute("disabled") != null));
      }
    }
  }
}
```

**Comment by skanga** [comment]
Thanks @yury-s 
You are a rockstar. Such a great example - I now understand it.

 I would say that the API design is very counter-intuitive! Deciding that calling isDisabled() should return false on `<a href="" disabled></a>` is weird but that's what it is, so OK.

BTW - when I ran your example it printed this error. Any reason why?

```
isDisabled() = false
getAttribute = true
isDisabled() = true
getAttribute = true
[Error: EPERM: operation not permitted, unlink 'C:\Users\SKANGA\AppData\Local\Temp\playwright_chromiumdev_profile-JcckV1\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\SKANGA\\AppData\\Local\\Temp\\playwright_chromiumdev_profile-JcckV1\\CrashpadMetrics-active.pma'
}

```
