### ISSUE TITLE
[Question] page.waitForEvent supported?

### ISSUE THREAD

**Issue by chaganiu** [microsoft/playwright-java#363]
I don't see a `waitForEvent` in the java version of playwright.  Is it supported?  

https://playwright.dev/docs/api/class-page#pagewaitforeventevent-optionsorpredicate

**Comment by yury-s** [comment]
There is no generic waitForEvent in Java version, instead there are methods with typed callbacks for the corresponding events such as [Page.waitForPopup](https://playwright.dev/java/docs/api/class-page?_highlight=waitfor#pagewaitforpopupoptions-callback), [Page.waitForWebSocket](https://playwright.dev/java/docs/api/class-page?_highlight=page.waitforwe#pagewaitforwebsocketoptions-callback) etc. See also [this page](https://playwright.dev/java/docs/events).

**Comment by chaganiu** [comment]
@yury-s does this mean i can't listen for generic javascript events?  for example, if i wanted to listen for event from Ag-Grid?

**Comment by yury-s** [comment]
`waitForEvent` in typescript doesn't allow that either, it's only for the events defined in Playwright. If you need your code on the Playwright side to be triggered when there is something happening inside the page you can use [`Page.exposeBinding()`](https://playwright.dev/java/docs/api/class-page?_highlight=exposebind#pageexposebindingname-callback-options) and hook it up to certain events in the web page. Can you say a bit more on what you are trying to achieve?

**Comment by chaganiu** [comment]
our ui uses Ag-Grid to display data.  When the user uses the filter functionality of the grid it takes a couple seconds for the grid to update.  Ag-Grid emits events (https://www.ag-grid.com/javascript-grid/grid-events/) when things happen in the grid and i wanted to listen for the `filterChanged` or `modelUpdated` event so my UI tests will know when the grid has finished filtering.

**Comment by yury-s** [comment]
[`Page.waitForFunction`](https://playwright.dev/java/docs/api/class-page?_highlight=waitforfun#pagewaitforfunctionexpression-arg-options) is likely what you need. You can do something like this:

```java
// Get a handle to a promise in the page that resolves when the event is fired
JSHandle promise = page.evaluateHandle("() => {" +
  "  const p = new Promise(r => {\n" +
  "    const listener = e => {\n" +
  "      document.removeEventListener('my-event', listener);\n" +
  "      r('done');\n" +
  "    };\n" +
  "    document.addEventListener('my-event', listener);\n" +
  "  });" +
  "  return { p };" +
  "}");
// Do something that eventually triggers the event
page.evaluate("setTimeout(() => document.dispatchEvent(new Event('my-event')), 1000)");
// Wait for the promise to get fulfilled
JSHandle result = page.waitForFunction("arg => arg.p", promise);
System.out.println(result.jsonValue());
```

**Comment by chaganiu** [comment]
I'll try that thank you!
