### ISSUE TITLE
[Question] How to Start Recording in Browser Full Screen Mode?

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#383]
`mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen --target=java"` 
The resolution of the browser started in this way is not adaptive.
`mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="open --viewport-size=1920,1040 about:blank"`
The resolution of the browser started in this way is large enough, but the page does not adapt to the length. As a result, some content may not be visible.
Therefore, it is difficult to simulate operations in a real environment during recording.

**Comment by yury-s** [comment]
Are you trying to emulate fixed layout? There is --device flag for that, which will set other options too, but it will flip [`isMobile`]() option to true. There is no separate flag in cli to enable mobile emulation right now, the only way to do it is to pass --device flag:

```sh
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="open --device='Pixel 2' about:blank"
```

Does that solve your problem? We can probably add command line flag for that but device emulation involves more stuff like custom user agent, dpr etc, so it may be easier to just use --device param.

**Comment by LongLiveY96** [comment]
> Are you trying to emulate fixed layout? There is --device flag for that, which will set other options too, but it will flip [`isMobile`](https://playwright.dev/java/docs/api/class-browser?_highlight=newcon#browsernewcontextoptions) context option to true. There is no separate flag in cli to enable mobile emulation right now, the only way to do it is to pass --device flag:
> 
> ```shell
> mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="open --device='Pixel 2' about:blank"
> ```
> 
> Does that solve your problem? We can probably add command line flag for that but device emulation involves more stuff like custom user agent, dpr etc, so it may be easier to just use --device param.

I mean, is there any way to make the browser open from the command line consistent with everyday use, at least adaptive to the screen resolution? Not in mobile mode.

**Comment by yury-s** [comment]
`--viewport-size` does that, you can pass whatever resolution you like. If you are asking about opening it in the full screen mode from command line there is no such option (only manually expanding browser window to full screen after you started). If the browser window took full screen it would obscure inspector window.

**Comment by yury-s** [comment]
Closing per response above, feel free to reopen.
