### ISSUE TITLE
[Feature] connectOverCDP Support

### ISSUE THREAD

**Issue by regbo** [microsoft/playwright-java#385]
Are there plans to add "connectOverCDP" support to the playwright-java? This feature would finally allow me to do away with selenium webdriver in my use case.

**Comment by yury-s** [comment]
Can you say a bit more about what you are trying to achieve and your limitations? Do you need to connect to an already running browser launched by web driver?

`connectOverCDP` is Chromium-specific and we've been trying to stay away of browser-specific APIs in the Java library. There is already [`browserType.connect()`](https://playwright.dev/java/docs/api/class-browsertype#browsertypeconnectwsendpoint-options) which works for all browsers and enables java clients to connect to the browsers launched remotely. This requires the browser to be launched by playwright though.

**Comment by regbo** [comment]
> Can you say a bit more about what you are trying to achieve and your limitations? Do you need to connect to an already running browser launched by web driver?

Sure. We have a selenium grid setup in place, that proxies CDP to each node. The infrastructure in place allows us to scale up and done the number of nodes depending on the work load. Unfortunately, we can't currently switch everything over to playwright, as some legacy code requires webdriver.

It would be great to be able to use both, and with node this is currently possible by first creating a session with webdriver, and then connecting to the developer tools. We've tested this with Nodejs (using connectOverCDP) and it works just fine. Ideally we'd like to have the same in place with Java.

Totally understand if this isn't a high priority. Happy to help in any way I can.

**Comment by yury-s** [comment]
Thanks for your detailed reply, this is very helpful for prioritizing the feature! It looks like we may want to get it to java for the transition scenarios like yours. How does it work with WebKit and Firefox or you run the tests only in Chromium?

**Comment by regbo** [comment]
We have only tested this for chromium (Chrome), as we don't use Firefox/Webkit for much. I believe connectOverCDP is limited to Chromium anyway, so this probably does have a limited audience.

**Comment by yury-s** [comment]
Yes, it's chrome-specific which is why I asked. But as long as you don't care much about testing in other browsers it solves the problem.

**Comment by regbo** [comment]
That was fast! I saw that the microsoft/playwright api was updated to include java. Is the implementation automatically generated or must that be done manually? I am happy to test as soon as test environments can be built.

**Comment by yury-s** [comment]
I'm working on the implementation and porting some tests, stay tuned.

**Comment by yury-s** [comment]
I landed the change and now republishing new 1.11.0-SNAPSHOT. You can give it a try if you like. Just in case you'd need to add the following lines to pom.xml to let Maven now where to download the snapshots:

```xml
  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
    </repository>
  </repositories>
```

**Comment by regbo** [comment]
Awesome! Testing now

**Comment by regbo** [comment]
Happy to report his works perfectly. We are running a pool of browserless.io images, and this works perfectly over their standard puppeteer endpoint. Fantastic work and thanks again.

**Comment by yury-s** [comment]
Awesome, thanks for confirming!

**Comment by dgozman** [comment]
@regbo We are experimenting with automatically connecting to Selenium Grid Hub for **Chrome** browser. This requires Selenium Grid nodes to be directly accessible from the machine that runs Playwright - is that the case for you?

If you are willing to give it a try, below are instructions for using the recent build.

1. Add the following to your `pom.xml`:
```xml
  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
    </repository>
  </repositories>
```

2. Change Playwright dependency to use a recent snapshot:
```xml
    <dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
      <version>1.16.0-SNAPSHOT</version>
    </dependency>
```

3. Run with `SELENIUM_REMOTE_URL` pointing to your hub. This will make all `playwright.chromium().launch()` calls use the grid instead of launching locally.
```bash
SELENIUM_REMOTE_URL=http://internal.grid:4444/wd/hub PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 mvn test
```

Let us know if you encounter any issues, and especially if it works for you 😄
