### ISSUE TITLE
[Question] Running Playwright without downloading browsers

### ISSUE THREAD

**Issue by chuanhhoang** [microsoft/playwright-java#388]
I already have my custom Chromium browser that I built. Is there anyway that I can run Playwright without checking/download existing browsers first? (I just want to use Chromium but Playwright download all the available browsers first)

**Comment by yury-s** [comment]
Using [`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1`](https://playwright.dev/java/docs/installation#skip-browser-downloads) and providing custom `executablePath` in [browserType.launch()](https://playwright.dev/java/docs/api/class-browsertype?_highlight=launch#browsertypelaunchoptions) should do the trick.

**Comment by regbo** [comment]
Is there a way to do this when using connect()? If so, is there a way to set it at runtime? In our use case connect()/launch() is decided at runtime, and so setting a variable would be difficult.

**Comment by yury-s** [comment]
> Is there a way to do this when using connect()?

Yes, it should work for `BrowserType.connect()` as well as for `launch()`. Note that there is no `launchServer()` API in java and you'll need to launch it separately (e.g. using nodejs), if you want that process to skip download phase pass the same variable to it.

> If so, is there a way to set it at runtime? In our use case connect()/launch() is decided at runtime, and so setting a variable would be difficult.

The environment variable should be set for the current process before `Playwright.create()` is called. `System.getenv()` returns read-only copy of the map so I don't think there is an easy way to set the env for the current process in runtime. We could add such flag as an option to `Playwright.create()`  but perhaps the code that starts the playwright client can decide on that? Can you share more details about how you decide whether to use `connect()` or `launch()`?
