### ISSUE TITLE
[Question] Spring boot app fails to initialize driver

### ISSUE THREAD

**Issue by iamquirarte** [microsoft/playwright-java#389]
Hi,

I have a spring boot app using playwright 1.10, in the testing env (win) all goes flawless, however when I dockerize and deploy in prod env (linux) the app I get the following error

SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Failed to create driver] with root cause

java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.microsoft.playwright.impl.DriverJar.installBrowsers(DriverJar.java:45)
	at com.microsoft.playwright.impl.DriverJar.<init>(DriverJar.java:33)

And this is if I manually pass the cli directory with a property:
VERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.microsoft.playwright.PlaywrightException: Failed to launch driver] with root cause

java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:37)
	at com.microsoft.playwright.Playwright.create(Playwright.java:76)

When I see the files created by PW I can see the driver is unpacked ok
ls -l playwright-java-14910156150549741988/
total 47860
-rwxr--r-- 1 root root    81255 Apr  7 21:58 LICENSE
-rwxr--r-- 1 root root 48914680 Apr  7 21:58 node
drwxr-xr-x 6 root root     4096 Apr  7 21:58 package
-rwxr--r-- 1 root root      116 Apr  7 21:58 playwright.sh

But somehow the app fails to read the driver with above error (hence unable to run/install the browsers)

Any help? Thanks.

**Comment by yury-s** [comment]
Can you check what is the value of `System.getenv("HOME")` inside docker? This issue sounds similar to #346

> And this is if I manually pass the cli directory with a property:

Could you share more details about which directory you pass "manually" and how you do this? Also it'd be helpful if you told us how you launch inside docker, are you launching single jar or you the app with `mvn` ?

**Comment by iamquirarte** [comment]
> Can you check what is the value of `System.getenv("HOME")` inside docker? This issue sounds similar to #346

Thanks for the reply.

In my case, I'm passing PLAYWRIGHT_BROWSERS_PATH=/tmp/somelocation which I know it exist as it mapped to a volume in the host machine. The HOME variable maps to /root and the directory exists.

So from the code (following the stacktrace)

`
    Path driver = driverTempDir.resolve(cliFileName);

    if (!Files.exists(driver)) {
      throw new RuntimeException("Failed to find " + cliFileName + " at " + driver);
    }
    ProcessBuilder pb = new ProcessBuilder(driver.toString(), "install");
    pb.redirectError(ProcessBuilder.Redirect.INHERIT);
    pb.redirectOutput(ProcessBuilder.Redirect.INHERIT);
    Process p = pb.start();`

The app is able to resolve and validate the driver, but the execution fails with "java.io.IOException: error=2, No such file or directory"... which looks weird to me.

> Could you share more details about which directory you pass "manually" and how you do this? Also it'd be helpful if you told us how you launch inside docker, are you launching single jar or you the app with mvn ?

This I did in order to try to debug, looking at the stacktrace and the impl, I manually set the "playwright.cli.dir" system property (used in PlaywrightImpl.java) to point to the unpacked driver from the first execution (from my previous post), because this is being done OK by the app, the problem comes when it tries to execute playwright.sh (it fails to find it), but as you can see Im getting a similar error.

And yes, my app is a single jar dockerized with a dockerfile and launching the jar, nothing special.

**Comment by yury-s** [comment]
> Just as suggestion, please fix the java documentation for docker, https://playwright.dev/java/docs/docker#image-tags, it is poiting to python images.
> 

This is already fixed for @next version: https://playwright.dev/java/docs/next/docker We just didn't update the docs for 1.10.

Closing the bug since the problem has been resolved.
