### ISSUE TITLE
Default Chrome arguments breaking sites

### ISSUE THREAD

**Issue by chuanhhoang** [microsoft/playwright-java#390]
I noticed that when running Chrome, it has the following argument:
--disable-component-extensions-with-background-pages

This breaks some sites, especially Google sites. For example when I try to login to Google Accounts, I face with this error
**browser or app may not be secure**

**Comment by yury-s** [comment]
Evading bot detection on web sites like Google ones is not a priority for Playwright. With that said you can always disable some of the arguments that we pass to the browser using [`setIgnoreDefaultArgs`](https://playwright.dev/java/docs/api/class-browsertype?_highlight=ignoredef#browsertypelaunchoptions):

```java
Browser browser = browserType.launch(new BrowserType.LaunchOptions().setIgnoreDefaultArgs(
    Arrays.asList("--disable-component-extensions-with-background-pages")));
```
