### ISSUE TITLE
[question] we are planning to implement playwright with Java, one feature we want to check on whether playwright supports Browserstack for CBT

### ISSUE THREAD

**Issue by kaneganti** [microsoft/playwright-java#393]

**Comment by yury-s** [comment]
Playwright does support various client-server modes (see [`connect`](https://playwright.dev/java/docs/next/api/class-browsertype#browsertypeconnectwsendpoint-options) and [`connectOverCDP`](https://playwright.dev/java/docs/next/api/class-browsertype#browsertypeconnectovercdpendpointurl-options)) and can itself run in the cloud. For Firefox and WebKit it requires custom builds which are bundled with Playwright. You'd better ask Browserstack if and how they support such browsers. If some particular missing features prevent you from running in the cloud we can consider adding them to Playwright.

Please reopen if you need more information.
