### ISSUE TITLE
[Question]How to make web pages in browser default to specified language in English system？

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#394]
I tried to use setLocale("zh-CN") and it did't work.

**Comment by yury-s** [comment]
Can you share your code and tell us what exactly doesn't work?

I tried the following and works fine:

```java
BrowserContext context = browser.newContext(new Browser.NewContextOptions().setLocale("zh-CN"));
Page page = context.newPage();
```

**Comment by LongLiveY96** [comment]
> Can you share your code and tell us what exactly doesn't work?
> 
> I tried the following and works fine:
> 
> ```java
> BrowserContext context = browser.newContext(new Browser.NewContextOptions().setLocale("zh-CN"));
> Page page = context.newPage();
> ```

I tested it on linux today and found it worked.😅
