### ISSUE TITLE
 BrowserType.connect websocket endpoint not working

### ISSUE THREAD

**Issue by Zanis7** [microsoft/playwright-java#396]
Connecting to existing chrome not working. BrowserType.launch() works fine

Sample code to reproduce the issue:
```java
package com.test;

import com.microsoft.playwright.*;

public class GoogleSearch {
	public static void main(String[] args) {
		try (Playwright playwright = Playwright.create()) {
			BrowserType browserType = playwright.chromium();
			Browser browser = browserType
					.connect("ws://127.0.0.1:9002/devtools/browser/1109fd4e-b326-4b8d-bed6-61a76d7bd11c");
			Page page = browser.newPage();
			page.navigate("http://google.com");
			System.out.println(page.title());
		}
	}
}

```
getting the following exception
```
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Playwright connection closed
	at com.microsoft.playwright.impl.WebSocketTransport.checkIfClosed(WebSocketTransport.java:116)
	at com.microsoft.playwright.impl.WebSocketTransport.poll(WebSocketTransport.java:84)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:183)
	at com.microsoft.playwright.impl.Connection.waitForObjectWithKnownName(Connection.java:162)
	at com.microsoft.playwright.impl.BrowserTypeImpl.connectImpl(BrowserTypeImpl.java:66)
	at com.microsoft.playwright.impl.BrowserTypeImpl.lambda$connect$1(BrowserTypeImpl.java:55)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.BrowserTypeImpl.connect(BrowserTypeImpl.java:55)
	at com.microsoft.playwright.BrowserType.connect(BrowserType.java:559)
	at com.test.GoogleSearch.main(GoogleSearch.java:9)
```

Also  "Playwright.create()" always take time

**Comment by Zanis7** [comment]
Found the reason for connection issue. It is because I used the chrome devtools websocket endpoint instead of playwright websocket server endpoint . In node js, there is an api to start the server and get the websocket endpoint , is there any available in java.

From the docs
```node
const { chromium } = require('playwright');  // Or 'webkit' or 'firefox'.

(async () => {
  const browserServer = await chromium.launchServer();
  const wsEndpoint = browserServer.wsEndpoint();
  // Use web socket endpoint later to establish a connection.
  const browser = await chromium.connect({ wsEndpoint });
  // Close browser instance.
  await browserServer.close();
})();
```

My use case is to run chrome in container and connect using websocket endpoint

**Comment by yury-s** [comment]
There's `connectOverCDP` if you need to connect to chromium browser via devtools websocket (the api is only available in 1.11.0-SNAPSHOT at the moment).

As for `connect` you need to start the server separately, you can use `npx playwright run-server webkit` to start the server from command line. There's no `launchServer` api in java.

**Comment by hlr1983** [comment]
> There's `connectOverCDP` if you need to connect to chromium browser via devtools websocket (the api is only available in 1.11.0-SNAPSHOT at the moment).
> 
> As for `connect` you need to start the server separately, you can use `npx playwright run-server webkit` to start the server from command line. There's no `launchServer` api in java.

Is there a plan for a `launchServer` api in java or a 'BrowserServer' class in java?

Thanks.

**Comment by yury-s** [comment]
No, we were not planning to add `launchServer` and `BrowserServer` to java. We assume that is should be sufficient to have it in node.js and allow to launch it from command line with `npx playwright run-server chromium` (not released yet). There is also an alternative approach to remote connection that we are considering: https://github.com/microsoft/playwright/issues/4687

**Comment by manishmnit01** [comment]
@hlr1983 I have the same requirement where I need to create a browser instance in the container and connect using web socket endpoint from the client side. How did you achieve this without having the launch server API in the playwright java library?
