### ISSUE TITLE
[Feature] - allow configuration of WebSocketTransport

### ISSUE THREAD

**Issue by regbo** [microsoft/playwright-java#398]
The WebSocketTransport class is currently protected, and creates a new org.java_websocket.client.WebSocketClient when constructed.

It would be great to have the ability to pass in a configuration consumer that allows for WebSocketTransport /WebSocketClient configuration. Here are a few use cases:

- Adding authorization headers
- Modifying the user agent for routing (ex 'playwright' user agent routed to separate endpoint vs 'selenium' user agent)
- Expanding the size of the WebSocketTransport incoming queue (currently capped at 1k, which is easy to fill if you are stepping through the debugger. We currently use reflection to make it unbounded)

Perhaps a Consumer<WebSocketTransport> options could be added to ConnectOptions? (assuming WebSocketTransport  is made public)

**Comment by regbo** [comment]
Another use case:
Adding a proxy between the client and the playwright server

**Comment by yury-s** [comment]
> * Adding authorization headers
> * Modifying the user agent for routing (ex 'playwright' user agent routed to separate endpoint vs 'selenium' user agent)

Providing a way to pass extra headers should be relatively easy. I'm not sure about the user agent, can you elaborate more on that? who routes it based on the user agent rather than a header?

> * Expanding the size of the WebSocketTransport incoming queue (currently capped at 1k, which is easy to fill if you are stepping through the debugger. We currently use reflection to make it unbounded)
> 

We can lift this constraint, I've added it just to be extra cautious but there is no particular reason it cannot be bigger/unlimited.

**Comment by yury-s** [comment]
@regbo, will #406 solve the queue capacity issue for you?

**Comment by regbo** [comment]
> @regbo, will #406 solve the queue capacity issue for you?

Definitely. This is what we did with reflection. This probably is an edge case, but the capacity was only an issue if we were slowly debugging (and hacking together some things) while a lot of messages were coming from the server.

**Comment by regbo** [comment]
> > * Adding authorization headers
> > * Modifying the user agent for routing (ex 'playwright' user agent routed to separate endpoint vs 'selenium' user agent)
> 
> Providing a way to pass extra headers should be relatively easy. I'm not sure about the user agent, can you elaborate more on that? who routes it based on the user agent rather than a header?

The main use case for our purposes is routing webdriver/puppeteer/playwright requests intelligently over the same endpoint. We use caddy to manage SSL/auth in front of a browser, and we currently re-route webdriver requests based on a selenium user agent, and use Authorization headers to verify JWTs.

If it were up to me, I'd make the following classes public:

- com.microsoft.playwright.impl.WebSocketTransport
- com.microsoft.playwright.impl.WebSocketTransport$ClientConnection

That way, the "addHeader" method could be used to modify requests.

I would also add another method in BrowserType to accept the WebSocketTransport as an argument:

 @Override
  public Browser connect(WebSocketTransport webSocketTransport) 

This would allow for deep customization, but I also understand that this would further deviate from the NodeJS implementation. A "deep customization" we currently use via reflection hacks is an idle timeout that is canceled every time a message is sent to or from a websocket server. This forces any stuck code to be killed if a browser isn't closed properly.

Again, these are all just ideas from our experiences, and I understand if you consider them to be edge cases.

**Comment by yury-s** [comment]
The issue has been closed as we now support extra headers in connect and connectOverCDP and the socket incoming queue is now boundless. One remaining thing is idle detector that one could use to detect silence in the protocol. We've discussed this in a team meeting and decided to collect more feedback before adding anything in that area - the reason is oftentimes your test runner will anyway have a timeout per test and will interrupt hanging tests, so there doesn't seem to be much benefit in listening just for a timeout at the protocol level. With that said feel free to file a separate feature request (this one is quite loaded already) for such functionality and we can prioritize it higher if there is enough interest.

**Comment by regbo** [comment]
This is TT

> The issue has been closed as we now support extra headers in connect and connectOverCDP and the socket incoming queue is now boundless. One remaining thing is idle detector that one could use to detect silence in the protocol. We've discussed this in a team meeting and decided to collect more feedback before adding anything in that area - the reason is oftentimes your test runner will anyway have a timeout per test and will interrupt hanging tests, so there doesn't seem to be much benefit in listening just for a timeout at the protocol level. With that said feel free to file a separate feature request (this one is quite loaded already) for such functionality and we can prioritize it higher if there is enough interest.

Thank you for the feedback, and changes, very helpful. I will check it out soon.
