### ISSUE TITLE
Chromium extension can't establish connection with receiver with Playwright-Java

### ISSUE THREAD

**Issue by dakLSS** [microsoft/playwright-java#402]
We have an extension that adds a listener to establish a channel with a cloud service, which works fine when side-loading the extension, or using Playwright-Javascript.  With the Java implementation, the extension logs the following to the console:

`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

I believe it's occurring when the extension make this call (or something similar):

`.extension.onRequest.addListener((e, t, n) => {
                    t.id === chrome.runtime.id && "?" === e.locked && n({state: this.locked, message: this.lastMessage})
                })`

The call to .launchPersistentContext is nearly identical to the one that works in Playwright-Javascript:

```javascript
       Path userDataDir = Paths.get("/tmp/chrome-user" + Integer.toString(instanceCount));
        String extensionPath =
                "./src/test/java/classroom/resources/extensions/crx-" + ClassroomPlaywright.env.getString("customerID");
        List<String> chromeArgs = new ArrayList<>();
        chromeArgs.add("--disable-background-timer-throttling");
        chromeArgs.add("--disable-backgrounding-occluded-windows");
        chromeArgs.add("--disable-renderer-backgrounding");
        chromeArgs.add("--no-sandbox");
        chromeArgs.add("--disable-setuid-sandbox");
        chromeArgs.add("--disable-dev-shm-usage");
        chromeArgs.add("--disable-extensions-except=" + extensionPath);
        chromeArgs.add("--load-extension=" + extensionPath);
        BrowserType.LaunchPersistentContextOptions options = new BrowserType.LaunchPersistentContextOptions();
        options.channel = BrowserChannel.CHROME;
        options.setHeadless(false);
        options.setDevtools(false);
        options.args = chromeArgs;

        studentContext = student.chromium().launchPersistentContext(userDataDir, options);
        studentPage = studentContext.pages().get(0);
```
I also tried `options.setIgnoreAllDefaultArgs` and switched off all but the 2 needed for loading the extension, but the error still occurred.

I may be able to provide the extension source, if it will help to debug

**Comment by yury-s** [comment]
My hunch is that since you are passing `channel` option the problem might be caused by different Chrome versions started by java and js playwrights. Can you check Chrome versions there? The launcher code is implemented on the playwright server side which is the same in node js and java which is why I suspect difference in browser versions (or maybe playwright version is different). If you could share the extension and the test code so that I could reproduce it locally that'd be super helpful (you can do it privately if you don't feel like sharing the code publicly).

**Comment by dakLSS** [comment]
It's actually the same with native chromium.  I only added the channel option to see if it would be better.

I will see if I can provide the extension code, privately or otherwise.
Thanks very much!

**Comment by dakLSS** [comment]
I'm unable to provide the extension, sadly.  Would be the easiest way to debug it quickly.  Maybe I can throw together a generic extension that can reproduce the problem.

I really want to use the Java implementation because we have a mandate to use Java in our automation team.  Currently using Selenium, and Playwright is so superior it's ridiculous.

I'll see what I can do about a mocked up extension.  Please let me know if you have any ideas about debugging it in the meantime.

**Comment by yury-s** [comment]
Try running both java and nodejs versions with `DEBUG=pw:browser` environment variable and see what are the actual command line options passed to chrome in each case. If it's the same binary, launched with the same arguments the behavior should not differ.

**Comment by dakLSS** [comment]
That was a great suggestion.  I thought for sure it would reveal it, but alas, the options are exactly the same in both cases:

```
Java - DEBUG=pw:browser

pw:browser <launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
--disable-background-networking 
--enable-features=NetworkService,NetworkServiceInProcess 
--disable-background-timer-throttling 
--disable-backgrounding-occluded-windows 
--disable-breakpad 
--disable-client-side-phishing-detection 
--disable-component-extensions-with-background-pages 
--disable-default-apps 
--disable-dev-shm-usage 
--disable-extensions 
--disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading 
--disable-hang-monitor 
--disable-ipc-flooding-protection 
--disable-popup-blocking 
--disable-prompt-on-repost 
--disable-renderer-backgrounding 
--disable-sync 
--force-color-profile=srgb 
--metrics-recording-only 
--no-first-run 
--enable-automation 
--password-store=basic 
--use-mock-keychain 
--user-data-dir=/tmp/chrome-user1 
--remote-debugging-pipe 
--no-sandbox 
--disable-background-timer-throttling 
--disable-backgrounding-occluded-windows 
--disable-renderer-backgrounding 
--no-sandbox 
--disable-setuid-sandbox 
--disable-dev-shm-usage 
--disable-extensions-except=./src/test/java/classroom/resources/extensions/crx-99-9999-F000 
--load-extension=./src/test/java/classroom/resources/extensions/crx-99-9999-F000 about:blank
```
```
node.js DEBUG=pw:browser

  pw:browser <launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
--disable-background-networking 
--enable-features=NetworkService,NetworkServiceInProcess 
--disable-background-timer-throttling 
--disable-backgrounding-occluded-windows 
--disable-breakpad 
--disable-client-side-phishing-detection 
--disable-component-extensions-with-background-pages 
--disable-default-apps 
--disable-dev-shm-usage 
--disable-extensions 
--disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading 
--disable-hang-monitor 
--disable-ipc-flooding-protection 
--disable-popup-blocking 
--disable-prompt-on-repost 
--disable-renderer-backgrounding 
--disable-sync 
--force-color-profile=srgb 
--metrics-recording-only 
--no-first-run 
--enable-automation 
--password-store=basic 
--use-mock-keychain 
--user-data-dir=/tmp/chrome-user1 
--remote-debugging-pipe 
--no-sandbox 
--disable-background-timer-throttling 
--disable-backgrounding-occluded-windows 
--disable-renderer-backgrounding 
--no-sandbox 
--disable-setuid-sandbox 
--disable-dev-shm-usage 
--disable-extensions-except=/Users/darin/Code/Javascript/Automation.Playwright-Classroom/resources/agents/classroom/dest 
--load-extension=/Users/darin/Code/Javascript/Automation.Playwright-Classroom/resources/agents/classroom/dest about:blank +23s
```

**Comment by dakLSS** [comment]
I particularly thought `--disable-background-networking` might be the culprit, but then I found it in the node.js run, where the extension is fine.

**Comment by dakLSS** [comment]
Even though the node.js version also had `--disable-background-networking`, I still tried in the Java version:
```
List<String> disableArgs = new ArrayList<>();
        disableArgs.add("--disable-background-networking");
```
```
options.setIgnoreDefaultArgs(disableArgs);
```

But it still didn't work

**Comment by yury-s** [comment]
Another observation: you launch both chromes with the same profile directory (`--user-data-dir=/tmp/chrome-user1`) but load extensions from different paths, I wonder if it has anything to do with the issue. Can you try and use different user data dirs for the two browsers?

**Comment by yury-s** [comment]
I'd also try using same path to the extension just to make sure that the code is the same (it probably is but I can't tell it looking at ./src/test/java/classroom/resources/extensions/crx-99-9999-F000  and /Users/darin/Code/Javascript/Automation.Playwright-Classroom/resources/agents/classroom/dest)

**Comment by yury-s** [comment]
> I particularly thought `--disable-background-networking` might be the culprit, but then I found it in the node.js run, where the extension is fine.

The error occurs in Chrome and and it should make no difference whether you launch it from java or javascript (all parameters should be the same), so I don't think it caused by a missing command line flag.

**Comment by dakLSS** [comment]
Yes!!!! That was a very good observation, indeed!  I can't believe I did that.  The bug was all mine.  The /dest directory has the extension with the user email poked into the index.js for the extension.

Thank you Yury!!!  You may happily close this one out

**Comment by herrouhajar** [comment]
@yury-s please im facing the same issue when i try to run e2e tests for playwright and docker-compose : 
---------------------------------------------------------------------------------------
   **browserType.launch: Failed to launch: Error: spawn /home/node/.cache/ms-playwright/chromium-920619/chrome-linux/chrome ENOENT
=========================== logs ===========================
<launching> /home/node/.cache/ms-playwright/chromium-920619/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-backg
round-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disab
le-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter --a
llow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --for
ce-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/tmp/playwright_chromi
umdev_profile-FNPmeB --remote-debugging-pipe --no-sandbox --no-startup-window
[pid=N/A] starting temporary directories cleanup
[pid=N/A] finished temporary directories cleanup**
============================================================
Any idea please how to fix this???
