### ISSUE TITLE
[Question] proxy error 

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#407]
<img width="1304" alt="截屏2021-04-21 上午9 57 32" src="https://user-images.githubusercontent.com/1261933/115487073-7f4ef680-a28a-11eb-874e-707c7c97c5c0.png">
 os:mac 
chromium  
version:1.11.0

**Comment by yury-s** [comment]
Could you tell us what you're trying to achieve and what is not working?

**Comment by xiaowenhuman** [comment]
I listen on a port locally and forward it to the remote  proxy server.
Why do I do that? Because you can't change the agent once the context is started.

**Comment by xiaowenhuman** [comment]
<img width="1093" alt="截屏2021-04-22 下午12 09 09" src="https://user-images.githubusercontent.com/1261933/115654355-99103c80-a363-11eb-8175-130b13319ddd.png">

I often run into this problem when working with proxies.

**Comment by xiaowenhuman** [comment]
https://github.com/microsoft/playwright-java/issues/407#issue-863384779

When I cancel the ssl  parameter, the code runs.

**Comment by yury-s** [comment]
> I listen on a port locally and forward it to the remote � proxy server.
> Why do I do that? Because you can't change the agent once the context is started.

Why  do you need to change user gent after the context is created? If you need to try different user agents you can merely create new contexts, does it not work for your use case?


> When I cancel the ssl parameter, the code runs.

Which ssl parameter? Can you share your code snippet, otherwise it's hard to guess what you are talking about?
