### ISSUE TITLE
[Question] How to wait for multiple responses ?

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright-java#413]
In js I can do this

```

    async waitForFindingUpload(findingName) {
        return await this.page.waitForResponse(async (response) => {
            const body = await response.text();
            return body.includes(findingName)
        });
    }
        const responses = await Promise.all([
            this.waitForFindingUpload("Name of Finding 1"),
            this.waitForFindingUpload("Name of Finding 2"),
            this.#uploadFile()
        ])
```

How to do the same in java ? Your API suggests this waiting mechanism:
```
        Response res = page.waitForResponse(response -> {
            return response.url().equals("https://url_/gateway/graphql") &&
                    response.request().postData().contains("sidebar");
        }, () -> {
            page.click("//button[@type='submit']");
        });
```
this way I can wait only for 1 response

I tried just several waiting in a row after click on a button:
```
page.click("//button[@type='submit']");
page.waitForResponse()
page.waitForResponse()
page.waitForResponse()
page.waitForResponse()
page.waitForResponse()
```
 and not all of them are resolved. For example after page loaded there are 5 graphql responses, 3-4 consequent waits are resolved I guess based on timings.

**Comment by yury-s** [comment]
You can have nested `waitForResponse` calls:

```java
    Response response2 = page.waitForResponse(response -> {
      return response.url().contains("first.png");
    }, () -> {
      Response response1 = page.waitForResponse(response -> {
          return response.url().contains("second.html");
        },
        ()-> {
          page.click("//button[@type='submit']");
        });
    });
```

Or alternatively you can always use [`page.onResponse()`](https://playwright.dev/java/docs/api/class-page?_highlight=onrespon#pageonresponsehandler) that will be called for all responses.

Hope it answers your question.

**Comment by yury-s** [comment]
Nested `waitForResponse` look a bit awkward but we anticipated that to be a rather rare use case to justify a better dedicated API. If it becomes a problem we can always add a convenience API that would enable waiting for multiple responses with a single call.

**Comment by Kremliovskyi** [comment]
Well I will just leave it here - You can pass an array of aliases that will be waited on before resolving. https://docs.cypress.io/api/commands/wait#Aliases
Also it is possible with js version of playwright. This issue is just a limitation of java API.

**Comment by yury-s** [comment]
> Well I will just leave it here - You can pass an array of aliases that will be waited on before resolving. https://docs.cypress.io/api/commands/wait#Aliases

There are many ways to achieve this (and I'd rather have `waitForResponses` returning list of response than introduce a new concept of aliases to the API) but all of them would complicate current API for what is deemed to be an edge case at the moment. All scenarios are already possible with current API and it's merely a question of ergonomics.

> Also it is possible with js version of playwright. This issue is just a limitation of java API.

JavaScript API is asynchronous which makes it easier to compose multiple calls with `Promise.all` but it comes with a price that it's easier to write code that doesn't work as expected. Is there anything you could not achieve in java with the solutions I described above?

**Comment by Kremliovskyi** [comment]
@yury-s If we resolve this https://github.com/microsoft/playwright-java/issues/412 then I would be able to verify your suggestion.

**Comment by chaganiu** [comment]
@yury-s how could I do this in a loop?  Say I have a list of endpoints that I want to wait for and verify their response codes and all of them are triggered after a click event on a button.  I'm having a hard time figuring out how to set that up.

**Comment by yury-s** [comment]
You can do this recursively via waitForResponse, like this: 

```java
  void checkAllResponses(List<String> urls, Runnable code) {
    if (urls.isEmpty()) {
      code.run();
    }
    String url = urls.remove(urls.size() - 1);
    Response response = page.waitForResponse(url, () -> checkAllResponses(urls, code));
    assertTrue(response.ok(), url);
  }
```
or the same without recursion: 

```java
    List<String> urls = ...
    page.onResponse(r -> {
      if (!urls.remove(r.url())) {
        return;
      }
      assertTrue(r.ok(), r.url());
    });
    while (!urls.isEmpty()) {
      page.waitForTimeout(100);
    }
```

**Comment by chaganiu** [comment]
thanks for this @yury-s .  I had to make a small change to the if statement because it was throwing an index out of bounds exception.  For anyone else reading this here is how I modified it:

```java
    void checkAllResponses(List<String> urls, Runnable code, Page page) {
        if (urls.isEmpty()) {
            code.run();
        } else {
            String url = urls.remove(urls.size() - 1);
            Response response = page.waitForResponse(url, () -> checkAllResponses(urls, code, page));
            assertTrue(response.ok(), url);
        }
    }
```

**Comment by canbax** [comment]
maybe I'm wrong but if 2 requests are parallel then we cannot estimate which one will respond faster. So let's say response1, takes longer than response2. In that case, will the below code will work? 

@yury-s codes
```
Response response2 = page.waitForResponse(response -> {
      return response.url().contains("first.png");
    }, () -> {
      Response response1 = page.waitForResponse(response -> {
          return response.url().contains("second.html");
        },
        ()-> {
          page.click("//button[@type='submit']");
        });
});
```
