### ISSUE TITLE
[Question] Can't run in Docker container

### ISSUE THREAD

**Issue by cyrly97** [microsoft/playwright-java#420]
![image](https://user-images.githubusercontent.com/43930599/116675045-fb0e1900-a9d7-11eb-833e-2f08986994be.png)
what's problem? Thanks

**Comment by yury-s** [comment]
Looks like the node is not there for some reason. Both playwright.sh and node are extracted at the same time to that folder, so it might be that node was deleted? We'd need more information: which Docker image is that, what playwright version and also how do you run playwright (mvn, single jar etc).

**Comment by cyrly97** [comment]
By using offical base image,I solve it. Thanks! @yury-s
