### ISSUE TITLE
Feature Request : Self Healing Mechanism

### ISSUE THREAD

**Issue by bhargavkumar-65** [microsoft/playwright-java#424]
Hi Playwright Java Team,
https://github.com/healenium/healenium-web  is a Project which heals NoElementFound Exception of Selenium Webdriver by simply adding try/catch method when the exception occur. 
It is a 3 step process

> Simply create a delegate to Webdriver 

> Run it's backend service 

> continue with selenium tests.

Requesting for same kind of features for Playwright.

**Comment by yury-s** [comment]
Note that Playwright already auto-waits until the selector is resolved and element is actionable (see [this doc](https://playwright.dev/java/docs/next/actionability)) so if e.g. `click()` fails there is normally no much point in retrying it, as it's a genuine error (which maybe a race condition in the page that you can address by adding extra conditions like `waitForRequest` etc). Considering this what kind of added value do you expect from a tool like healenium in case of Playwright?

**Comment by bhargavkumar-65** [comment]
Let's say my application in very early development stage. With attributes of a web element like below
name: ABC, class name: def.

If developer updates the attribute name value to xyz tomorrow, my automation script fails as I am not aware of Dom changes.

This Is where healenium comes in rescue. When we run with healenium it will store the other attributes of that element in its backend postgres instance and try to perform the failed Webdriver action with other attributes from it's database.

**Comment by yury-s** [comment]
Ok, this sounds like full-fledged auto-healing service. I agree that it'd be useful, on the other hand it could be implemented using Playwright API today and there could be competing approaches to that problem so this belongs to one level above Playwright library not to its basic functionality. Closing this request as we don't have immediate plans to work on that right now (if we decide to implement something in that realm it will likely be a part of upstream Playwright project or perhaps a new separate one).

**Comment by bhargavkumar-65** [comment]
@yury-s,  sure, Thank you.
