### ISSUE TITLE
[Question] FullPageScreenshot is not capturing the full page

### ISSUE THREAD

**Issue by senthilkumar10** [microsoft/playwright-java#436]
Hi - I have the following script to capture the full page screenshot 

```java
@Test
    public void googleTest(){
       Playwright playwright = Playwright.create();
        BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions();
        launchOptions.setHeadless(false)
                .setChannel(BrowserChannel.CHROME);
        Browser browser = playwright.chromium().launch(launchOptions);
        BrowserContext browserContext = browser.newContext();
        Page page = browserContext.newPage();
        page.navigate("https://google.com");
        page.click("text=I agree");
        System.out.println(page.title());
        page.screenshot(new Page.ScreenshotOptions()
                .setPath(Paths.get("colosseum-pixel2.png"))
                .setFullPage(true)
        );

    }
```

The script runs fine and it takes the screenshot at the end. But the screenshot is not full page. Please refer attached the screenshot. 

![Screenshot-Taken-By-Playwright](https://user-images.githubusercontent.com/34428474/117535827-7b8fd380-afef-11eb-81a0-145d1230dd80.png)

I am running this script using Playwright 1.10.0
OS - Ubuntu 20.04.2

**Comment by senthilkumar10** [comment]
I believe you're asking me to change launchOptions.setHeadless(true)?

I did that and it is taking the full page screenshot in headless mode as expected. Please refer attached the screenshot.

Looks like the problem occurring only when it is launchOptions.setHeadless(false)

![playwright-screenshot](https://user-images.githubusercontent.com/34428474/117877542-9aff5880-b29c-11eb-9d60-ff6fa6b30d9f.png)

**Comment by yury-s** [comment]
> I believe you're asking me to change launchOptions.setHeadless(true)?
> 

Yes, thank you!

> I did that and it is taking the full page screenshot in headless mode as expected. Please refer attached the screenshot.

Yes, I see. Does the problem reproduce if you drop `BrowserChannel.CHROME` option and use bundled version of Chromium? (it looks like a regression on Chrome side but I don't have the most recent stable version to test it locally yet)

**Comment by reggiepierce** [comment]
I can confirm that this is happening. It looks like the viewport gets squashed right before the screenshot is rendered

**Comment by yury-s** [comment]
It seems to be a timing issues,  basically not all tiles of the page image are rasterized by the time the snapshot is taken. @senthilkumar10 @reggiepierce To validate that, could you insert timeout before the screenshot to give the browser time to render:

```java
...
        page.click("text=I agree");
        System.out.println(page.title());
        page.waitForTimeout(1000);
        page.screenshot(new Page.ScreenshotOptions()
...
```

You can also open DevTools on the page and in the Console drawer > Rendering tab (you may have to click &#x22EE; menu to open it) enable `Layer borders` option:
![layer-borders-option](https://user-images.githubusercontent.com/9798949/118020037-865ba880-b30e-11eb-8fe2-b583b720b848.png)

It will draw the tiles grid, our hypothesis is that some of the tiles are not rendered yet when the screenshot is taken, on my machine it looks like this:
![tiles](https://user-images.githubusercontent.com/9798949/118020264-be62eb80-b30e-11eb-9d9a-181597e7bac7.png)

**Comment by senthilkumar10** [comment]
I have added the page wait from 1000 and increased up till 5000 but still the screenshots is not full page.

**Comment by yury-s** [comment]
Hmm, thanks for trying that's weird :thinking: Can you also try with this argument:

```java
...
    launchOptions.setHeadless(false)
      .setArgs(Collections.singletonList("--use-gl=swiftshader"))
      .setChannel(BrowserChannel.CHROME);
...
```
It will force Chrome to use software sharer implementation (which is what is used in headless I believe).

**Comment by yury-s** [comment]
@senthilkumar10 does it work if you just remove `.setFullPage(true)` ?

**Comment by senthilkumar10** [comment]
I ran the following tests

Test 1 :-

'''
  launchOptions.setHeadless(false)
      .setArgs(Collections.singletonList("--use-gl=swiftshader"))
      .setChannel(BrowserChannel.CHROME);
'''

 removed '.setFullPage(true)

Result - Screenshot is not FullPage

Test 2:-

'''
  launchOptions.setHeadless(false)
      .setArgs(Collections.singletonList("--use-gl=swiftshader"))
      .setChannel(BrowserChannel.CHROME);
'''

 with '.setFullPage(true)

Result - Screenshot is not FullPage

Test 3:-

'''
  launchOptions.setHeadless(true)
      .setArgs(Collections.singletonList("--use-gl=swiftshader"))
      .setChannel(BrowserChannel.CHROME);
'''

with '.setFullPage(true)

Result - Screenshot is FullPage

Test 4:-

'''
  launchOptions.setHeadless(true)
      .setArgs(Collections.singletonList("--use-gl=swiftshader"))
      .setChannel(BrowserChannel.CHROME);
'''

removed '.setFullPage(true)

Result - Screenshot is FullPage

**Comment by yury-s** [comment]
So in **headful** mode passing "--use-gl=swiftshader" solves the problem and you get entire page captured regardless of `setFullPage` value, correct?

**Comment by senthilkumar10** [comment]
Sorry for the confusion. In headful mode (launchOptions.setHeadless(false)) passing "--use-gl=swiftshader" also doesn't solves the problem regardless of '''setFullPage''' value

**Comment by regbo** [comment]
Below is a simple test (using 1.11.0) that illustrates the issue.

Here's the images outputted: https://imgur.com/a/O3C0Dw7


```java
package test;

import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.BrowserType.LaunchOptions;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;

public class ScreenshotTest {

	public static void main(String[] args) {
		try (Playwright playwright = Playwright.create()) {
			List<BrowserType> browserTypes = Arrays.asList(playwright.chromium(), playwright.firefox());
			for (BrowserType browserType : browserTypes) {
				for (var headless : List.of(false, true)) {
					for (var swiftshader : List.of(false, true)) {
						var launchOptions = new LaunchOptions().setHeadless(headless);
						if (swiftshader)
							launchOptions.setArgs(List.of("--use-gl=swiftshader"));
						try (Browser browser = browserType.launch(launchOptions)) {
							BrowserContext context = browser.newContext();
							Page page = context.newPage();
							page.navigate(
									"https://stackoverflow.com/questions/33770549/viewport-vs-window-vs-document");
							var path = Paths.get(String.format("temp/screenshot-%s-%s-%s-%s.png", browserType.name(),
									headless ? "headless" : "headfull", swiftshader ? "swiftshader" : "defaultshader",
									UUID.randomUUID().toString()));
							page.screenshot(new Page.ScreenshotOptions().setFullPage(true).setPath(path));
							System.out.println(path.toFile().getAbsolutePath());
						}
					}
				}
			}
		}
	}
}

```

**Comment by regbo** [comment]
I think this may be an underlying driver problem:

https://github.com/microsoft/playwright/issues/6691

**Comment by yury-s** [comment]
This is a driver or more precisely Chromium problem. Unfortunately we haven't been able to reproduce it locally so far which makes it hard to debug. It may be specific to some graphics cards, what does `sudo lshw -C display` print for you?

**Comment by senthilkumar10** [comment]
I get the below output

*-display                 
       description: VGA compatible controller
       product: UHD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:134 memory:b0000000-b0ffffff memory:a0000000-afffffff ioport:4000(size=64) memory:c0000-dffff

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible if you still face issues with Playwright for Java.
