### ISSUE TITLE
[BUG] Remote browser close not sending close event

### ISSUE THREAD

**Issue by yashLadha** [microsoft/playwright-java#450]
In the case of remote browser-connection client binding is not sending a close message (`close`) to the server and directly closing the transport (WebSocket). While in javascript client binding it sends `close` message in a remote session if one does `browser.close`.

**Comment by yury-s** [comment]
Does it cause any problems? 

> In the case of remote browser-connection client binding is not sending a close message (`close`) to the server and directly closing the transport (WebSocket). While in javascript client binding it sends `close` message in a remote session if one does `browser.close`.

In case of remote connection javascript client also [terminates connection](https://github.com/microsoft/playwright/blob/57f3a53a7e99d160a00bb1da7dec131af8873d5a/src/client/browser.ts#L102) without sending  close.

**Comment by yury-s** [comment]
Closing per last comment, feel free to reopen if some functionality is broken.
