### ISSUE TITLE
Host system is missing dependencies! in rhel 7.5

### ISSUE THREAD

**Issue by Vijay757943** [microsoft/playwright-java#462]
I am using Playwright version **0.172.3** which was working fine but, suddenly it is not working in the below machine .
Distributor ID: RedHatEnterpriseServer
Description: Red Hat Enterprise Linux Server release 7.5 
Release: 7.5

**Error**:
 Error: Host system is missing dependencies!

Missing libraries are:
libatk-bridge-2.0.so.0
libxkbcommon.so.0
libgtk-3.so.0
libgdk-3.so.0
libatspi.so.0

**Note :** this is still working fine in windows. 

I am not sure if I need to install above dependencies manually or if I upgrade latest playwright will it work ?

Kindly share your thought.

**Comment by yury-s** [comment]
We only officially support Ubuntu LTS, if you want to run on other distributions you'll need to install missing dependencies yourself.

**Comment by Vijay757943** [comment]
Hi @yury-s . Thank you for the response.

I am absolutely fine with installing the missing dependencies myself, But need a confirmation that if I install these it will work in RHEL 7.5 right ?

**Comment by yury-s** [comment]
It may work, people managed to run Playwright on various linux distros but  like I said we don't test on RHEL and cannot guarantee that it will work after adding those libs.
