### ISSUE TITLE
[Question]How do I maximize the launch of Firefox?

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#464]
I found that when I ran the script, the Firefox browser started was not automatically maximized, causing some  selectors to be invisible. I wanted to ask if Firefox had a startup args similar to chrome's "--start-maximized".

**Comment by yury-s** [comment]
There is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=873618) in Firefox bug tracker which is still open, so they don't seem to have such flag. 

There is an open [feature request](https://github.com/microsoft/playwright/issues/1086) about such API in Playwright, please thumb up if you need it.
