### ISSUE TITLE
[Bug] On printing with playwright, images not visible. 

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#469]
I tried to print a pdf from html using playwright.
On printing with playwright -> images are not visible in the generated pdf.

But the same html if printed through google chrome directly, images are visible in the generated pdf.

Is this a bug in playwright? 

Sharing the files for reference.
[outputPrintFromChrome.pdf](https://github.com/microsoft/playwright-java/files/6598139/outputPrintFromChrome.pdf)
[outputPrintFromPlaywright.pdf](https://github.com/microsoft/playwright-java/files/6598141/outputPrintFromPlaywright.pdf)

[inputhtml.zip](https://github.com/microsoft/playwright-java/files/6598136/inputhtml.zip)

**Comment by abhinav-kipper** [comment]
printBackground option was set to true.

**Comment by yury-s** [comment]
Can you also share the code snippet?

**Comment by abhinav-kipper** [comment]
This is the major code snippet.
```
BrowserContext context = getBrowserContext(); 
Page page = context.newPage();

Page.NavigateOptions navigateOptions = new Page.NavigateOptions(); 
navigateOptions.setWaitUntil(WaitUntilState.NETWORKIDLE); 
page.navigate("file://pathto/index.html", navigateOptions);

Page.PdfOptions pagePdfOptions = getPagePdfOptions();
page.pdf(pagePdfOptions);

private Page.PdfOptions getPagePdfOptions() { 
    Page.PdfOptions pagePdfOptions = new Page.PdfOptions(); 
    pagePdfOptions.displayHeaderFooter = true;
   pagePdfOptions.printBackground = true; 
   pagePdfOptions.landscape = false;
   pagePdfOptions.path = Paths.get("outputFilePath);    
   return pagePdfOptions;


```

**Comment by yury-s** [comment]
I can reproduce it locally, the images are partially visible in my case as if they were not completely loaded. But if I take a screenshot they are all good. Looks like a bug in Chromium.

[output.pdf](https://github.com/microsoft/playwright-java/files/6600467/output.pdf)

![screenshot](https://user-images.githubusercontent.com/9798949/120845444-b2d99d80-c525-11eb-8276-749d617f5113.png)

**Comment by yury-s** [comment]
What is your platform?

**Comment by abhinav-kipper** [comment]
I ran it on windows machine.

**Comment by yury-s** [comment]
I see, I reproduced it on Linux. I wonder if it has something to do with #436

**Comment by yury-s** [comment]
I managed to get full pictures with the combination of emulated media, updated viewport and custom pdf dimensions (kudos to @aslushnikov):

```java
    page.navigate("file://pathto/index.html", navigateOptions);
    page.emulateMedia(new Page.EmulateMediaOptions().setMedia(Media.SCREEN));
    page.setViewportSize(1024, 768);
    page.pdf(new Page.PdfOptions()
      .setPath(path)
      .setPrintBackground(true)
      .setWidth("1024px").setHeight("768px"));
```

You can try that as a workaround for now.

**Comment by abhinav-kipper** [comment]
Thanks @yury-s but this workaround does not seem to work for me i.e. still images are visible for me

**Comment by banchl** [comment]
Hello, I tried the following code. It seems to work for me. I don’t know if it can help you. 
[outputFilePath.pdf](https://github.com/microsoft/playwright-java/files/6801335/outputFilePath.pdf)

```
      try (Playwright playwright = Playwright.create()) {
          BrowserType browserType = playwright.chromium();
          try (Browser browser = browserType.launch()) {
              BrowserContext context = browser.newContext(new Browser.NewContextOptions().setDeviceScaleFactor(2));
              Page page = context.newPage();
              page.navigate("file://D:/inputhtml/index.html", new Page.NavigateOptions().setWaitUntil(WaitUntilState.NETWORKIDLE));
              Page.PdfOptions pagePdfOptions = getPagePdfOptions();
              page.pdf(pagePdfOptions);
          }
      }
```

**Comment by mitchchristow** [comment]
I would like to reopen this bug. I am also not able to get images printed when performing a print to pdf command. Here is the routine that I implemented. 

`
from playwright.async_api import async_playwright
import asyncio
import re

targeturl = '' #add the web site that you want to print


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(
            viewport={"width": 2550, "height": 3300},
            device_scale_factor=1,
        )
        page = await context.browser.new_page()
        await page.goto(targeturl)
        title = await page.title()
        saveTitle = re.match("^[^|]*", title).group(0)
        pdfPath = "./" + saveTitle + ".pdf"
        await page.emulate_media(media="screen")
        await page.wait_for_load_state("networkidle")
        await page.pdf(path=pdfPath, format="Letter", landscape=False, print_background=True)
        await browser.close()

asyncio.run(main())
`

**Comment by akmalmzamri** [comment]
I wrote my web page in Next.js and was using the `Image` component from `next/image` to load the images. Since they are lazily loaded by default, the images were not visible in the PDF print. 

This can be solved by adding `priority` to the `<Image>` component or get Playwright to scroll to the bottom of the page ([example](https://github.com/microsoft/playwright/issues/4302#issuecomment-1882853669))
