### ISSUE TITLE
[BUG]Alert dialog not automatically dismissed

### ISSUE THREAD

**Issue by qwpnqjucz** [microsoft/playwright-java#470]
I'm trying to mock out print functionality in my site to verify some behavior that happens after print.  I thought about doing this:

`page.evaluate("window.print = function() { alert('Print was triggered'); };");`

and while the above works the alert dialog is not automatically dismissed.

**Comment by yury-s** [comment]
Which version of Playwright are you using (note that the dialog are auto dismissed starting v1.9.0-alpha-0)? Can you share code snippet where the dialog is not dismissed? The following worked with no issues:

```java
    page.evaluate("window.print = function() { alert('Print was triggered'); };");
    page.evaluate("print()");
    System.out.println("done");
```

**Comment by qwpnqjucz** [comment]
i'm using 1.11.1.  I will retry this this week and report back.  Perhaps it's something i'm doing wrong.

**Comment by yury-s** [comment]
Closing for now. Please reopen if you have a repro.
