### ISSUE TITLE
[Question] IsVisible Timeout not adhered

### ISSUE THREAD

**Issue by munichbughunter** [microsoft/playwright-java#478]
I Open my page with an ad authentication and Made my login playwright is redirected back to the application. 

I wanna then verify if the login was successful. 
For that I use: 
page.waitForSelector("my selector").isVisible(); 
But that fails. 

When i put a thread.sleep(5000) before it is working. 
Seems that the timeout for wait for selector or isVisible Not working.

**Comment by yury-s** [comment]
Could you share sample page and exact code snippet that fails to wait for visibility? `page.waitForSelector("my selector")` wait by default for the element to be [visible](https://playwright.dev/java/docs/api/class-page/#page-wait-for-selector) The fact that `thread.sleep(500)` means that elements visibility state likely changes a few times before it gets stable, i.e. waitForSelector returns when the element is visible but when isVisible() is called the element is already hidden again.

**Comment by munichbughunter** [comment]
The snippet is the following: 

page.waitForSelector("btn_New_Product").IsVisible(); 

That gives me every time false back. 

Ok is it possible to wait for a stable visible State? 

For the page direct I have to communicate with our devs.

**Comment by yury-s** [comment]
> Ok is it possible to wait for a stable visible State?

This would be page-specific so there is no generic way, `page.waitForSelector` will return immediately once all the conditions are met but there is no guarantee that the state won't change right after. The easiest way would likely be to check some condition in the page that would tell you if it's still updating. Just curious, is it a React page?

**Comment by munichbughunter** [comment]
It is a react page. 
What is with the load State? 
waitForLoadState(LoadState.DOMCONTENTLOADED) or waitForLoadState(LoadState.NETWORKIDLE)

PS: I wanna say that I love playwright and the idea. I find it better than cypress and really love that. Thank you.

**Comment by yury-s** [comment]
> It is a react page.

Yeah, most likely there is race with [reconciliation](https://reactjs.org/docs/reconciliation.html)/[hydration](https://reactjs.org/docs/react-dom.html#hydrate) in React and adding thread.sleep(5000) just ensures that the DOM tree is fully updated by React. There is no generic way to detect it in Playwright at the moment.

> What is with the load State?
> waitForLoadState(LoadState.DOMCONTENTLOADED) or waitForLoadState(LoadState.NETWORKIDLE)
> 

See [this page](https://playwright.dev/java/docs/next/navigations#navigation-lifecycle) for a brief overview of the navigation lifecycle, I doubt it will help you in this case since you already wait for the selected element to become visible.

> PS: I wanna say that I love playwright and the idea. I find it better than cypress and really love that. Thank you.

:heart:

**Comment by munichbughunter** [comment]
Ok, I found a "solution / workaround":

Response response = page.waitForResponse("MyAppURL", () -> {});
page.waitForSelector("#btn_New_Product").isVisible()

**Comment by yury-s** [comment]
Closing this issue for now as you have a solution. Please reopen if you need further help. In the future we may provide something generic for React problems like this one.
