### ISSUE TITLE
[Question] Is there mechanism to set Minimum, None and Default margin while printing?

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#481]
Hi, 
In chrome print preview we have Minimum, None and Default  and custom margin types that user can set.
But in playwright only custom margin setting (margin top , margin bottom , margin left , margin right) is available.

Is there a way I can set Minimum, None and Default  margin types instead of custom?

I think, correct if am wrong, for None (All 0 dimensions) and Default (0.4inch I guess) can be used? But what about Minimum margin setting? How can I replicate that using custom margin option?

**Comment by yury-s** [comment]
There is no way to set minimum margins. Also by default if you don't specify anything it will [default to 0](https://playwright.dev/java/docs/api/class-page/#page-pdf).

> How can I replicate that using custom margin option?

You need to compute the margin yourself based on the page you are going to print and your criteria.
