### ISSUE TITLE
[Question] CDPSession to talk to raw Chrome Devtools Protocol

### ISSUE THREAD

**Issue by kumar-muthu** [microsoft/playwright-java#497]
Is there a java equivalent of CDPSession to talk to the raw Chrome Devtools Protocol?

Nodejs Equivalent => https://playwright.dev/docs/api/class-cdpsession/

**Comment by yury-s** [comment]
No, CDPSession is not exposed in the java API. Now that we have connectOverCDP there should be much less demand for this. Can you tell us more about your use case and where Playwright API is lacking to that you have to turn to raw CDP?

**Comment by kumar-muthu** [comment]
I have the following use cases to use CDP,
1. Use [CSS.getPlatformFontsForNode](https://chromedevtools.github.io/devtools-protocol/tot/CSS/#method-getPlatformFontsForNode) to see if network font or system font is being used for a element
2. Use [Network.setRequestInterception](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setRequestInterception) to modify network responses

Is it doable via `connectOverCDP` ?

**Comment by yury-s** [comment]
Thanks for sharing the details!

> Is it doable via `connectOverCDP` ?

These are not currently possible but we can add an API for those that would work across all browsers.

> 1. Use [CSS.getPlatformFontsForNode](https://chromedevtools.github.io/devtools-protocol/tot/CSS/#method-getPlatformFontsForNode) to see if network font or system font is being used for a element

Can you file a feature request for this in https://github.com/microsoft/playwright repo?

> 2. Use [Network.setRequestInterception](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setRequestInterception) to modify network responses
> 

This is being tracked in https://github.com/microsoft/playwright/issues/1774 and we are working on this (there is an [open PR](https://github.com/microsoft/playwright/pull/7122) adding initial support upstream), so hopefully it will make it to the next release.

**Comment by kumar-muthu** [comment]
Thanks. I'll raise a feature request.
