### ISSUE TITLE
[Question] Playwright java installation without using maven

### ISSUE THREAD

**Issue by tushitaaggarwal** [microsoft/playwright-java#500]
Hi, 

I want to install playwright on server machine by adding it in chef's recipe in deploys's cookbook. Is there any command for installing playwright-java using terminal or without using maven which can be executed on the server to download ms-playwright jar and its dependencies jar files.

**Comment by yury-s** [comment]
This is a question to chef.io and how they support Maven packages. You can find all Playwright jar files in [Maven Central](https://search.maven.org/search?q=com.microsoft.playwright), they can be downloaded by any https client not necessarily Maven (e.g. this [playwright.jar ](https://search.maven.org/remotecontent?filepath=com/microsoft/playwright/playwright/1.12.1/playwright-1.12.1.jar) file). How to make it work efficiently with Chef recipes is outside of this Project.
