### ISSUE TITLE
[Question] Is it possible to use playwright for java in AWS Lambda?

### ISSUE THREAD

**Issue by munichbughunter** [microsoft/playwright-java#501]
I build my container image based on this: mcr.microsoft.com/playwright/java:focal
Also installed gradle and make some copy operations to get my classes on the right place. 

sam build and sam local invoke are running. 

When I trigger my Lambda Function after the deployment the chrome browser is not working. 

I get the following message: 'Protocol error (Page.enable): Browser closed.

So is it possible to use playwright for java in combination with AWS Lambda?

**Comment by munichbughunter** [comment]
Found the solution.

**Comment by munichbughunter** [comment]
@tomconnors, I wrote a blog post about. You can find it there: 
https://medium.com/tech-p7s1/scaling-out-end-to-end-tests-with-7facette-playwright-to-infinity-742da7533c05

and here i the repository: 
https://github.com/munichbughunter/aws-lambda-sevenfacette-playwright

**Comment by tomconnors** [comment]
@munichbughunter Thanks!
