### ISSUE TITLE
[Documentation] Unclear how to configure playwright-java - e.g. screenshots on test failure

### ISSUE THREAD

**Issue by cameronhsemsci** [microsoft/playwright-java#503]
Hi,
I'm using playwright with java/maven/junit and trying to get it to take a screenshot on test failure.  

I initially tried to implement this using junit, but this was not as straightforward as I hoped.  I eventually found [this](https://playwright.dev/java/docs/test-configuration/) page which looks like a good solution, however much of the information on that page appears to be related to the node version of playwright.  After reading through it I am still unsure how to do the configuration.  

My questions:
- What format should the configuration file be? Is it the same for all playwright versions/languages?
- Where does playwright look for the configuration file by default?
- Is it possible to set the configuration at run time? The [local configuration](https://playwright.dev/java/docs/test-configuration/#local-configuration) section suggests that it is, but I can't find any methods in the java api for it.

My suggestions for improvements to the documentation:
- Answers to the questions above
- The [configuration page](https://playwright.dev/java/docs/test-configuration/) was difficult for me to find, so I suggest that it could be linked somewhere in the introduction section of the docs (Perhaps the [Getting Started](https://playwright.dev/java/docs/intro) page, or just as a separate "configuration" page somewhere in the sidebar). 
- Link to the [configuration page](https://playwright.dev/java/docs/test-configuration/) from the [screenshot](https://playwright.dev/java/docs/screenshots/) section of the docs. (The "automatic screenshots on test failure" feature is not mentioned on this page at all.) 
- Provide an example configuration file
- Maybe an example project that shows how to configure playwright with these options
- Update the sections in this page that refer to npx to their java equivalent

**Comment by mxschmitt** [comment]
Where did you find [this](https://playwright.dev/java/docs/test-configuration/) page - was it linked somewhere? Since this is unfortunately Node.js specific.

For Java we currently recommend JUnit, see [here](https://playwright.dev/java/docs/test-runners).

To get your screenshot-on-failure behaviour, it seems you can use a TestWatcher, see [here](https://junit.org/junit4/javadoc/4.12/org/junit/rules/TestWatcher.html) or [here](http://www.thinkcode.se/blog/2012/07/08/performing-an-action-when-a-test-fails). But both needs adjustments to work with Playwright. Talking about Playwright, we recommend to use the Tracing feature instead of taking screenshots to debug failing tests, for that see the guide [here](https://playwright.dev/java/docs/next/trace-viewer). A trace is basically a zip file, which you can then upload as an artifact on your Continuous integration provider and then download if the test is failing. This allows you to see screenshots before and after an action, more verbose logs, the DOM tree and network requests. (more is following).

**Comment by cameronhsemsci** [comment]
Hi, Thanks for your time!
I don't remember how I found it, I think it came up in my internet searches, but I might have got to the node version of the page through my searching, and then switched it to java in the top bar.  The difficulty of finding it makes sense now - it isn't linked anywhere because it isn't an intended feature!

Thanks for the tips, we have now implemented this using JUnit (JUnit5).  The complication with implementing this in JUnit is to do with the order of things.  
- The `@AfterEach` annotation gets run before the test watcher
- Taking a screenshot requires the page/context, which is closed in the `@AfterEach` function (copied from [here](https://playwright.dev/java/docs/test-runners/))
- `@AfterEach` does not know if the test failed, only the test watcher knows that  

We could think of a few solutions
1. Close the context in the test watcher instead of the `@AfterEach` (the blog post you linked did it this way)
2. Save a screenshot for every test
3. Save a screenshot to memory for every test, and only save it to file if the test fails

I like 3 best, so went with that one. I have added an example of my implementation below for reference.   

Your tracing feature looks great, I think the screenshot has a lot of utility because it can be viewed directly in the browser from a link in our CI. But the trace will be a big help for more difficult debugging.  

I tried to implement tracing alongside the screenshots, but as far as I can tell its not possible to save it to memory? Seems like I can't get a byte array like I can with the screenshot? The only option is to save it [directly to file](https://playwright.dev/java/docs/next/api/class-tracing#tracing-stop)? I may end up needing to use a different solution for the trace. 
```java
   byte[] screenshot;

   @AfterEach
   public void closeContext() {
      screenshot = page.screenshot();
      context.close();
   }

   public void onFailedTest(String filePath, String testName) {
      try (FileOutputStream stream = new FileOutputStream(filePath + new SimpleDateFormat("yyyy-MM-dd_HH:mm:ss").format(new Timestamp(System.currentTimeMillis())) + "_" + testName + ".png")) {
         stream.write(screenshot);
      } catch (IOException e) {
         e.printStackTrace();
      }
   }

```
```java
import com.semsci.sensuris.PlaywrightTestBase;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.TestWatcher;

public class FailedTestHandler implements TestWatcher {

   @Override
   public void testFailed(ExtensionContext context, Throwable cause) {
      if (context.getRequiredTestInstance() instanceof PlaywrightTestBase) {
         ((PlaywrightTestBase) context.getRequiredTestInstance()).onFailedTest("target/surefire-reports/", context.getRequiredTestMethod().getName());
      }
   }
}

```

**Comment by mxschmitt** [comment]
cool, awesome to hear! Yeah a screenshot is super simple for basic debugging and a trace better for more detailed investigations when a test is failing.

Yes a trace can only saved into a file for now - if you need it as a byte array, I would recommend to open an [upstream feature request](https://github.com/microsoft/playwright/issues/new/choose) for it with providing more details about your use-case there.

**Comment by mxschmitt** [comment]
Closing since it seems solved.
