### ISSUE TITLE
[Feature] Add BrowserContext.backgroundPages()

### ISSUE THREAD

**Issue by limshuang** [microsoft/playwright-java#504]

**Comment by mxschmitt** [comment]
Its currently not yet implemented, I marked it as collecting-feedback so we can add it once more people are interested in.

**Comment by 15jszlszbysj** [comment]
We need this method, too! Ծ‸Ծ

**Comment by mxschmitt** [comment]
Looks like this has been implemented by https://github.com/microsoft/playwright-java/pull/1532
