### ISSUE TITLE
[QUESTION] Possibility to wait for a specific Websocket?

### ISSUE THREAD

**Issue by gitvitox** [microsoft/playwright-java#505]
I was playing around with websockets:

```java
    public void getWebsocket() {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch();
            Page page = browser.newPage();
            page.navigate("http://wormax.io");

            page.waitForWebSocket(() -> { // I only want Websocket x
                page.onWebSocket(webSocket -> {
                    System.out.println("WebSocket opened: " + webSocket.url());
                });
            });
        }
    }
```

## Problem
Multiple websockets will appear after calling the website

## Question
Is it somehow possible, to wait for an specific Websocket, based on the URL for example? 
Thanks in advane!

**Comment by mxschmitt** [comment]
WebSockets are unfortunately not yet implemented in Java. I marked it as collecting-feedback so it can gets considered once more people are interested in. (JavaScript and Python have it already)

**Comment by gitvitox** [comment]
> WebSockets are unfortunately not yet implemented in Java. I marked it as collecting-feedback so it can gets considered once more people are interested in. (JavaScript and Python have it already)

Huh? I am already using WebSockets, as shown in my example.

**Comment by mxschmitt** [comment]
You are absolutely right! My bad. Does [this](https://playwright.dev/java/docs/next/api/class-page#page-event-web-socket) work for you?

**Comment by gitvitox** [comment]
Hm not really. I can't get good with the docs.

I just need a function which lets the browser wait until a specific WebSocket appears. I think `waitForWebSocket`. I think I miss some arguments or something.

**Comment by mxschmitt** [comment]
It accepts a callback, here is an example implementation. Inside this callback, you can call/click the action which creates the websocket. also page.navigate should be possible in there.

https://github.com/microsoft/playwright-java/blob/1958a2fa64adecdc6be9a0605571b9dfc332085b/playwright/src/test/java/com/microsoft/playwright/TestWebSocket.java#L164-L190

**Comment by gitvitox** [comment]
Thanks, that fixed my problem!
