### ISSUE TITLE
[QUESTION] Blocking resources

### ISSUE THREAD

**Issue by gitvitox** [microsoft/playwright-java#506]
Hey again!

Im trying to block some resources like images on an website.

I tried this:

```
                        context.onRequest(request -> {
                            if (request.resourceType().equals("image")) {
                                request.failure();
                            }
                        });
```

**Comment by yury-s** [comment]
You need to use [`page.route()`](https://playwright.dev/java/docs/api/class-page#page-route) and [`fulfill`](https://playwright.dev/java/docs/api/class-route#route-fulfill) the request with an error response (such as 404), something like this:

```java
page.route("**/*", route -> {
  if (route.request().resourceType().equals("image")) {
    route.fulfill(new Route.FulfillOptions()
      .setStatus(404);
  } else {
    route.resume();
  }
});
```
