### ISSUE TITLE
[Question] Want to execute playwrite-java with chrome on jenkins/docker

### ISSUE THREAD

**Issue by royanindya-code** [microsoft/playwright-java#507]
Hi Team,

This is not an issue. I am planning to use playwright on jenkins/ docker. I know playwright have in-build chromium installed. I am looking for an information if there is any way to use chrome instead of chromium on jenkins pipeline. Please note that I don't have chrome installed on jenkins. So, I am looking for a way around if I could use chrome image using docker or if playwright has any in-build solution for this.

Any help or documentation will be highly appreciated !!!!

Thanks!!!

**Comment by yury-s** [comment]
To run Playwright with official build of Chrome or Edge you just need to specify corresponding [`channel`](https://playwright.dev/java/docs/browsers#google-chrome--microsoft-edge) value. Note that the browsers have to be installed manually.  Playwright command line interface provides a convenient way to install corresponding browsers with required dependencies, e.g. for Chrome stable just run this command:

```sh
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install chrome"
```

**Comment by royanindya-code** [comment]
Hi,

Thanks for your input. However after using the above mentioned command I am getting this below mentioned exception - 

+ sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
Reading package lists...
Building dependency tree...
Reading state information...
E: Release 'google-chrome-stable_current_amd64.deb' for 'account-plugin-aim' was not found
E: Release 'google-chrome-stable_current_amd64.deb' for 'empathy' was not found
E: Release 'google-chrome-stable_current_amd64.deb' for 'telepathy-haze' was not found
E: Release 'google-chrome-stable_current_amd64.deb' for 'mcp-account-manager-uoa' was not found

There are lot more logs on "not found" errors. I am not capturing all of those and due to these I am not able to install chrome on Jenkins. Could you please help ?

**Comment by royanindya-code** [comment]
One more thing, is there any way to use docker containers ? something like, selenium-hub ??

**Comment by yury-s** [comment]
You may need to run `sudo apt-get update` to refresh apt package registry. Which Linux distribution are you using?

**Comment by yury-s** [comment]
> One more thing, is there any way to use docker containers ? something like, selenium-hub ??

Yes, see https://playwright.dev/java/docs/docker

**Comment by royanindya-code** [comment]
Yeah I have seen this, but Im looking for some to create a selenium-hub type connection in docker containers and then use on our playwright scripts by passing the url in connectOverCDP method. 

Sample snippet - 

.connectOverCDP("ws://127.0.0.1:3000/?--window-size=1920,1080&headless=false", new BrowserType.ConnectOverCDPOptions().setSlowMo(10.0).setTimeout(120000.0D))

I have tried connecting in browerless-chrome. Looking similar type of solution here. Do you have something like this ?

**Comment by yury-s** [comment]
For that you can launch browser in the docker in [server mode](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server) (this is method is only available in javascript version not in java) and then you can connect to it via [`browserType.connect`](https://playwright.dev/java/docs/api/class-browsertype/#browser-type-connect).

If you are ok to use just Chromium browsers, you can also use `connectOverCDP` launching the browser similar to [this test](https://github.com/microsoft/playwright-java/blob/5a0dd8595ccf3716a9708736e5f7d76827b863ba/playwright/src/test/java/com/microsoft/playwright/TestChromium.java#L58-L67).

**Comment by royanindya-code** [comment]
So in java, we can launch chromium browser using docker and then we can connect using connectOverCDP. Is it ? If it's then I am ok to use chromium browser for now. But , do you have any documentation for the same ? I did not find any so checking with you if you have any.

**Comment by royanindya-code** [comment]
Hi @yury-s ,

Thanks for sharing all the options with me. I have tried couple of options and here are my findings - 

1. I am not able to install the chromium/chrome using command line cli because I don't have the admin access in the Jenkins nodes. Moreover, we are using nodes without GUI.
2. I have also explored the option of running playwright in docker hub. I have found this process little complex , since we have to install git, maven , browser everything inside docker. Also , I have to figure out a way to pass username and password to clone our project in docker. Since, we are using private repository with ssh key enabled.

Till now, we are using selenium and configuring selenium hub and node using docker is very easy compare to this. Are you going to provide anything like this in future ? I have already done with my analysis of using Playwright in our current project and looks very promising to me. Only if I able to overcome this hurdle I will be good to use playwright in our project. So checking with you if you have any plan in future for this.

Thanks,
Anindya

**Comment by yury-s** [comment]
> 1. I am not able to install the chromium/chrome using command line cli because I don't have the admin access in the Jenkins nodes. Moreover, we are using nodes without GUI.

Installing official builds currently requires root privileges. You can probably work around this by copying the files manually but it's probably easier to just install the browser using the official way. Note that for playwright CLI you don't need GUI.

> 2. I have also explored the option of running playwright in docker hub. I have found this process little complex , since we have to install git, maven , browser everything inside docker. Also , I have to figure out a way to pass username and password to clone our project in docker. Since, we are using private repository with ssh key enabled.

Well you can build an image based on one of the playwright images to include all dependencies. You can pass the credentials as `docker run` arguments or as environment variables when running the image.

> Till now, we are using selenium and configuring selenium hub and node using docker is very easy compare to this. Are you going to provide anything like this in future ?

Yes, the library has all the capabilities for launching in client/server mode and building something like selenium grid on top of that. There is not out of the box solution at the moment but we'll likely add one in the future. Some people have been running playwright with the browsers running in selenium nodes, so you can explore that too, if you have browser with exposed CDP port playwright will be able to connect to it with `connectOverCDP`
