### ISSUE TITLE
[Question]: Why can't I get the name information for the frame obtained after using page.frames(), which causes page.frame("name") to fail to find the frame using name? 

### ISSUE THREAD

**Issue by 15jszlszbysj** [microsoft/playwright-java#512]
### Playwright version

1.12

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Java 8, PW 1.12

### What happened? / Describe the bug

**if I click an element and the page generates an iframe, the url and name of the iframe cannot be obtained using page.frames()**
![image](https://user-images.githubusercontent.com/46314526/124882403-eadf6f00-e002-11eb-89ea-83185686d2fc.png)
![image](https://user-images.githubusercontent.com/46314526/124882443-f6329a80-e002-11eb-9bd6-37ca405a9846.png)

### Code snippet to reproduce your bug

```shell
page.frames();
page.frame("name");
```

### Relevant log output

```shell
Not a runtime exception
```

**Comment by yury-s** [comment]
Can you share an repro page and the code snippet that doesn't work?

Note that `page.frame("foo");` will return null if there is no frame with `name='foo'`. Also is the problem that `page.frame("decorateDetailEditor")` returns null or that there is a frame with empty name in the list? If it's the latter you probably have such iframe elsewhere in the DOM tree.

**Comment by yury-s** [comment]
Closing as there was no response.
