### ISSUE TITLE
[Question]: Can playwright prevent buttons/links (like '_blank') from opening a new window. Keep the current page jump.

### ISSUE THREAD

**Issue by limshuang** [microsoft/playwright-java#513]
### Your question

Can playwright prevent buttons/links (like '_blank') from opening a new window.Keep the current page jump.

**Comment by yury-s** [comment]
There is no special API for this but you can probably edit the links using playwright (see e.g. [Page.evalOnSelector](https://playwright.dev/java/docs/api/class-page#page-eval-on-selector)) to change `target=_blank` to whatever you want before clicking the link.
