### ISSUE TITLE
[Question]: What  is the meaning of hermetic install mentioned in documentation? and how can we use it?

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#518]
### Your question

<img width="993" alt="Screenshot 2021-07-15 at 4 55 45 PM" src="https://user-images.githubusercontent.com/22498015/125780537-bc88aba8-56cd-46ea-9eba-7b3aca86ce2b.png">

I want to manually add browsers to be used by playwright, how can I achieve it with hermetic install

**Comment by abhinav-kipper** [comment]
Q2 - I also tried putting browser to particular/ manual location . It seems I have to create and keep them in a particular directory structure i.e. MyGivenPath/chromium-888113/chrome-mac/Chromium . Is this path fixed and static as playwright looks at this path only?

**Comment by yury-s** [comment]
> I want to manually add browsers to be used by playwright, how can I achieve it with hermetic install

Hermetic install only makes sense for nodejs, I'm removing mentions of it from the java guides.

> Q2 - I also tried putting browser to particular/ manual location . It seems I have to create and keep them in a particular directory structure i.e. MyGivenPath/chromium-888113/chrome-mac/Chromium . Is this path fixed and static as playwright looks at this path only?

You can change the cache location by setting `PLAYWRIGHT_BROWSERS_PATH=<your dir>` as described in [this doc](https://playwright.dev/java/docs/installation/#managing-browser-binaries), Playwright will create required structure underneath and download browsers there if necessary.
