### ISSUE TITLE
[Question]: How can I intercept the outgoing HTTP request as in NodeJS? 

### ISSUE THREAD

**Issue by manuman94** [microsoft/playwright-java#524]
### Your question

Hi! 

I have a NodeJS Playwright project that intercepts the outgoing HTTP request in order to authenticate via PFX certificate.

Example of how I'm doing that:
```js
context.route('**/*', (route, req) => {
    const options = {
      uri: req.url(),
      method: req.method(),
      headers: req.headers(),
      body: req.postDataBuffer(),
      timeout: 10000,
      followRedirect: false,
      agentOptions: { // <-------- This is the important part, add the PFX to the request options
        ca: config_general.ca,
        pfx: cert,
        passphrase: 'cert_pass',
      },
    };
    let firstTry = true;
    const handler = function handler(err, resp, data) {
      if (err) {
        /* Strange random connection error on first request, do one re-try */
        if (firstTry) {
          firstTry = false;
          return request(options, handler);
        }
        console.error(`Unable to call ${options.uri}`, err.code, err);
        return route.abort();
      } else {
        return route.fulfill({
          status: resp.statusCode,
          headers: resp.headers,
          body: data,
        });
      }
    };
    return request(options, handler);
});
```  
This is because Playwright for NodeJS provides the "req" object, instance of the NPM request library.

In the Java version, I can intercept the network request but the only methods I found are to change status, body, headers but not the agentOptions (such as the PFX option). That's what I can do with the route object:
https://www.javadoc.io/doc/com.microsoft.playwright/playwright/latest/com/microsoft/playwright/Route.FulfillOptions.html

Can I do this with Playwright Java version?

Thanks in advance.

**Comment by yury-s** [comment]
In node.js you get intercepted [request](https://playwright.dev/docs/api/class-request) and then construct another request object (perhaps from [request](https://www.npmjs.com/package/request) library or from built-in [https](https://nodejs.org/api/https.html#https_https_get_options_callback) module). The former is part of Playwright and available in Java version as well via [`route.request()`](https://playwright.dev/java/docs/api/class-route#route-request) but the latter is node.js-specific and needs to be replaced with something that Java provides. You can try sending intercepted request using [HttpClient](https://openjdk.java.net/groups/net/httpclient/intro.html) or some other http client library.
