### ISSUE TITLE
[Question]: When use "page.evaluate()", when receiving JS objects ,the return value is null 

### ISSUE THREAD

**Issue by 15jszlszbysj** [microsoft/playwright-java#525]
### Your question

When we first embed a JS function in the page, and then call the function through the page method to get the return value, we find that the return value received by the Java method is always null. We tested the existence of the return value on the browser console.

Object response = page.evaluate("(url) => {return httpRequestGet(url);}", url);

![image](https://user-images.githubusercontent.com/46314526/126807971-db685006-2d27-4be1-a019-e9d3c4eaa668.png)

this is console.log print this object
![image](https://user-images.githubusercontent.com/46314526/126808052-2a3e4367-5a17-47d4-8e72-77d5f483f309.png)

**Comment by yury-s** [comment]
The response is an empty object on your screenshot (not null). This result is specific to your `httpRequestGet` function and it's hard to tell what it is supposed to do and what is not not working without seeing the code. Please reopen the issue with the code snippet (java and the js function that you inject into the page) if it's still not working.
