### ISSUE TITLE
[Question]: Is there a way to use expect snapshot in a Java project?

### ISSUE THREAD

**Issue by fgmaltez** [microsoft/playwright-java#527]
### Your question

Currently I have a test project in Java language where I am using Playwright, and I needed to take a screenshot during a run of a test and compare it with a screenshot I already have stored.

From what I can read in Playwright's documentation it is fairly easy to compare screenshots if I was using Jest, it would be something like this:
expect(value).toMatchSnapshot(snapshotName)

However, in Java this doesn't seem to be available. Can you confirm that I am not able to use this in a Java project or is there a dependency/class/etc. I can use in order to achieve this? (if relevant my project is a Maven project).

Thank you.

**Comment by yury-s** [comment]
`toMatchSnapshot` is a part of Playwright Test (not Playwright library) and is not available outside of Node.js at the moment. You can still take snapshots will need to use custom code to compare them.
