### ISSUE TITLE
[Bug]:  The video page does not match the set size when taking a full-screen screenshot.

### ISSUE THREAD

**Issue by limshuang** [microsoft/playwright-java#530]
### Playwright version

1.12.0

### What happened? / Describe the bug

![image](https://user-images.githubusercontent.com/24468368/127253587-69afb29a-78b0-4a8e-b770-8d2696ba1b5e.png)

The video page does not match the set size when taking a full-screen screenshot.  

### Code snippet to reproduce your bug

```shell
private static final int SCREEN_WIDTH_SIZE = 1440;
private static final int SCREEN_HEIGHT_SIZE = 900;

 this.browserContext = this.browser
                .newContext(new Browser.NewContextOptions()
                        .setRecordVideoDir(Paths.get(RECORD_VIDEO_DIR))
                        .setScreenSize(SCREEN_WIDTH_SIZE, SCREEN_HEIGHT_SIZE)
                        .setRecordVideoSize(SCREEN_WIDTH_SIZE, SCREEN_HEIGHT_SIZE)
                        .setViewportSize(SCREEN_WIDTH_SIZE, SCREEN_HEIGHT_SIZE)
                        .setAcceptDownloads(true));
```

**Comment by yury-s** [comment]
This is a known limitation of Chromium implementation (webkit and firefox do not suffer from this): when full page screenshot is being captured the viewport is first changed to fit entire page, then the screenshot is taken and at the end the original viewport is restored back. This is what you see on the video. There are no plans on fixing this so I'm closing this issue.
