### ISSUE TITLE
[Bug]: StorageState not working on headless mode

### ISSUE THREAD

**Issue by brobles82** [microsoft/playwright-java#536]
### Playwright version

1.13.0

### Operating system

Windows, Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

setStorageState is working perfect without headless, but looks like is not working on headless mode activated.

### Code snippet to reproduce your bug

```shell
browser.newContext(new Browser.NewContextOptions().setStorageStatePath(Paths.get(mypath)).setAcceptDownloads(true)
						);
```

**Comment by yury-s** [comment]
Can you share more details about you scenario and what exactly is not working?

**Comment by brobles82** [comment]
Ok looks like I found the problem, the app was working weirdly, and sometimes navigating to the login page with the storage session was working and other times the app was logging out the user.

I tested on other web apps and is working so I found that is not really a playwright bug.

thx
