### ISSUE TITLE
[Bug]: net::ERR_ABORTED when navigating to a page that only initiates a download

### ISSUE THREAD

**Issue by kgoderis** [microsoft/playwright-java#541]
### Playwright version

1.13.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium, Firefox, WebKit

### What happened? / Describe the bug

[see the code snippet]
When navigating a Page to an URL that only returns a JSON file, then at the end of the Request/Response net::ERR_ABORTED is logged. I can not further pinpoint the problem, e.g. is this due to the website concerned (It's Twitter's API endpoint), or is it due to Playwright not handling well such a case

In any case, the onDownload is handled, and a json.json file can be saved to a temp file location

[In the code below, the baseQuery variable corresponds to the twitter URL in the logs]

### Code snippet to reproduce your bug

```shell
Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
			BrowserContext context = browser.newContext(new NewContextOptions().setJavaScriptEnabled(true).setAcceptDownloads(true).setUserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15"));
			com.microsoft.playwright.Page page = context.newPage();

			page.navigate("https://twitter.com/explore");
			page.onConsoleMessage(msg -> System.out.println(msg.text()));

			List<Cookie> cookies = page.context().cookies();
			String xGuestToken = "";
			try {
				xGuestToken = cookies.stream().filter(cookie -> cookie.name.equals("gt")).findFirst().get().value;
			} catch (NoSuchElementException e) {
				logger.error("No guest token present");
			}

			String cursorQuery = baseQquery;

			if (cursor != "") {
				cursorQuery = cursorQuery.concat(String.format("&cursor=%s", cursor));
			}
			
			page.onRequestFinished(request -> parseResponse(page,request));
			page.setExtraHTTPHeaders(Map.of("authorization",
					"Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA",
					"x-guest-token", xGuestToken));
			page.onRequestFailed(request -> logger.info("Failed: <<" + request.url() + " " + request.failure()));
			page.onDownload(download -> parseDownload(download));

			try {
				page.navigate(cursorQuery);
			} catch (Exception e) {
				logger.error("Error scrape " +e.getMessage());
			}
```

### Relevant log output

```shell
Error scrape Error {
  message='net::ERR_ABORTED at https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&query_source=typed_query&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel&count=100&tweet_search_mode=live&q=Apple%20OR%20s2%20OR%20s3%20since:1628314455%20until:1628318055
=========================== logs ===========================
navigating to "https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&query_source=typed_query&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel&count=100&tweet_search_mode=live&q=Apple%20OR%20s2%20OR%20s3%20since:1628314455%20until:1628318055", waiting until "load"
============================================================
  name='Error
  stack='Error: net::ERR_ABORTED at https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&query_source=typed_query&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel&count=100&tweet_search_mode=live&q=Apple%20OR%20s2%20OR%20s3%20since:1628314455%20until:1628318055
=========================== logs ===========================
navigating to "https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&query_source=typed_query&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel&count=100&tweet_search_mode=live&q=Apple%20OR%20s2%20OR%20s3%20since:1628314455%20until:1628318055", waiting until "load"
============================================================
    at FrameSession._navigate (/private/var/folders/s0/ss2_6jns6k9dyqy2_lj0ls380000gn/T/playwright-java-16157182761386662423/package/lib/server/chromium/crPage.js:599:35)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:434:9)
    at async /private/var/folders/s0/ss2_6jns6k9dyqy2_lj0ls380000gn/T/playwright-java-16157182761386662423/package/lib/server/frames.js:624:30
    at async ProgressController.run (/private/var/folders/s0/ss2_6jns6k9dyqy2_lj0ls380000gn/T/playwright-java-16157182761386662423/package/lib/server/progress.js:89:22)
    at async FrameDispatcher.goto (/private/var/folders/s0/ss2_6jns6k9dyqy2_lj0ls380000gn/T/playwright-java-16157182761386662423/package/lib/dispatchers/frameDispatcher.js:79:59)
    at async DispatcherConnection.dispatch (/private/var/folders/s0/ss2_6jns6k9dyqy2_lj0ls380000gn/T/playwright-java-16157182761386662423/package/lib/dispatchers/dispatcher.js:330:22)
```

**Comment by yury-s** [comment]
I believe this is the case when navigation is converted into a download. Normally if such navigation is triggered by a click on a link the new page will be closed immediately after it's opened and the browser realizes that it's a download. Perhaps throwing in this case is valid since the navigation doesn't actually happen. WDYT?

**Comment by yury-s** [comment]
It sounds very similar to the scenario from https://github.com/microsoft/playwright/issues/5962 except that the url is passed to page.navigate() right away.

**Comment by kgoderis** [comment]
@yury-s Indeed, it is a page that is converted into a download, but it is not after clicking on a link. Throwing might be valid, but what is then the right approach to retrieve the content of the page without having the error thrown? Should there then be a Download.download() method or alike ? or Page.download() ?


I noticed another akward side-effect of this issue : if one retries a page.navigate() to another URL after the above error is thrown, it returns the data from the previous call to .navigate() in onDownload(). It is as if a buffer somewhere is not emptied after the page closes, and that buffer is read out again. The solution for this behaviour is to explicitly
do a context.newPage() before attempting another URL

**Comment by yury-s** [comment]
> Throwing might be valid, but what is then the right approach to retrieve the content of the page without having the error thrown? Should there then be a Download.download() method or alike ? or Page.download() ?
> 

You mentioned that the download event is fired and the content could be retrieved, the exception thrown is unfortunate but the scenario is also somewhat exotic. You could restructure the code like this:

```java
Download download = page.waitForDownload(() -> {
  try {
    page.navigate("<url>");
  } catch (PlaywrightException e) {
  }
});
```

> I noticed another akward side-effect of this issue : if one retries a page.navigate() to another URL after the above error is thrown, it returns the data from the previous call to .navigate() in onDownload(). It is as if a buffer somewhere is not emptied after the page closes, and that buffer is read out again. The solution for this behaviour is to explicitly
> do a context.newPage() before attempting another URL

Do you have a repro for this? I would be nice if you could shared the server response (headers) that triggers such behavior so that we could covert it in a unit test.

**Comment by kgoderis** [comment]
I changed code per your suggestion, but it continues to throw the same error. Here are the headers for such a response:

Response Headers for https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&query_source=typed_query&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel&count=100&tweet_search_mode=live&q=Apple+since%3A1628663907+until%3A1628663967&cursor=scroll%3AthGAVUV0VFVBaCwKiBvKfsxycWgMComaKu7McnEnEV3IV6FYCJehgEVVNFUjUBFQAVAAA%3D : 

{date=Wed, 11 Aug 2021 06:39:37 GMT, server=tsa_o, content-length=16480, expires=Tue, 31 Mar 1981 05:00:00 GMT, x-frame-options=SAMEORIGIN, content-encoding=br, x-transaction=b18824322adfa84e, pragma=no-cache, strict-transport-security=max-age=631138519, last-modified=Wed, 11 Aug 2021 06:39:37 GMT, x-xss-protection=0, content-disposition=attachment; filename=json.json, x-content-type-options=nosniff, x-access-level=read, x-connection-hash=60d10cc71874c35e3f687dd695e5f13b09dee383511cd4444411520948dd6690, x-twitter-response-tags=BouncerCompliant, content-type=application/json;charset=utf-8, cache-control=no-cache, no-store, must-revalidate, pre-check=0, post-check=0, x-client-event-enabled=true, status=200 OK}

**Comment by yury-s** [comment]
Thanks, I've added a test upstream that reflects difference in the behavior across browsers. How can I extend it to see the bug you mentioned above: "it returns the data from the previous call to .navigate() in onDownload()" ?

> I changed code per your suggestion, but it continues to throw the same error. Here are the headers for such a response:

page.navigate is expected to throw as the navigation is aborted and the page stays at the old url (in Chromium and WebKit) or are you saying that page.waitForDownload throws too?

**Comment by kgoderis** [comment]
> page.navigate is expected to throw as the navigation is aborted and the page stays at the old url (in Chromium and WebKit) or are you saying that page.waitForDownload throws too?

Yes indeed , page.waitForDownload is also throwing

**Comment by yury-s** [comment]
> Yes indeed , page.waitForDownload is also throwing

Hmm, this is odd, we need a repro as the test added [in this PR](https://github.com/microsoft/playwright-java/pull/558/files) doesn't throw and just returns a Download as expected.

**Comment by mxschmitt** [comment]
Closing since it seems stale, please create a new issue with a repro.
