### ISSUE TITLE
[Question]: master-SNAPSHOT inclusion via JitPack not working ?

### ISSUE THREAD

**Issue by kgoderis** [microsoft/playwright-java#542]
### Your question

Since I need the latest SNAPSHOT for my project, I tried to use JitPack to have this automagically inserted, but it somehow fails to work properly. [I noticed that the playwright jars are downloaded by others based on the counter they show, so somehow this is working for others]

I have added the following to pom.xml [formatting screwed up]

```
	   	<dependency>
	    	<groupId>com.github.microsoft.playwright-java</groupId>
	    	<artifactId>playwright</artifactId>
	    	<version>master-SNAPSHOT</version>
		</dependency>
		<dependency>
	    	<groupId>com.github.microsoft.playwright-java</groupId>
	    	<artifactId>driver</artifactId>
	    	<version>master-SNAPSHOT</version>
		</dependency>
		<dependency>
	    	<groupId>com.github.microsoft.playwright-java</groupId>
	    	<artifactId>driver-bundle</artifactId>
	    	<version>master-SNAPSHOT</version>
		</dependency>
```

and

```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

but when building and running the project, I do get a _Caused by: java.lang.RuntimeException: Failed to create driver_

```
Caused by: java.lang.NullPointerException: null
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:69) ~[driver-bundle-master-fcac298050-1.jar:na]
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:37) ~[driver-bundle-master-fcac298050-1.jar:na]
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52) ~[driver-master-fcac298050-1.jar:na]
	... 40 common frames omitted
```

So, what is the best way to include a working SNAPSHOT build then ?

**Comment by yury-s** [comment]
I'm not sure about JitPack but in Maven central we publish snapshot versions of the following form: 1.14.0-SNAPSHOT. Have a look at the example [pom.xml](https://github.com/microsoft/playwright-java/blob/master/examples/pom.xml), in particular snapshot repository [config](https://github.com/microsoft/playwright-java/blob/master/examples/pom.xml#L34-L41). Hope that works for you.

**Comment by kgoderis** [comment]
@yury-s That is obviously what I tried before, and the import does not resolve as I was not aware of the fact that the artefact was available on sonatype. Maybe something to include in README.md ?
