### ISSUE TITLE
[Question] can set referer

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#544]
### Your question

Hello,
mcPage.navigate("url",new com.microsoft.playwright.Page.NavigateOptions().setReferer("https://www.google.com/"));[Question]: 
 When I set the referer through the api, It doesn't work.

**Comment by yury-s** [comment]
Can you share a code snippet where it doesn't work?

**Comment by xiaowenhuman** [comment]
Any site, for example, liulinging.com 15sky.com .  The first html page can't get the Referer .  Other css request can get the Referer.
first page no referer:
![image](https://user-images.githubusercontent.com/1261933/129016016-39f5c121-c27e-4b18-9b99-2de88488c0f7.png)

css request has the referer 
![image](https://user-images.githubusercontent.com/1261933/129016143-4163ca37-f331-4ae3-8ee1-5675367ca318.png)

**Comment by xiaowenhuman** [comment]
I have solved it.
