### ISSUE TITLE
[Bug]: Browsers not getting installed in Linux Alpine Image

### ISSUE THREAD

**Issue by aarushiag** [microsoft/playwright-java#546]
### Playwright version

1.13.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Java version - Open JDK 11
Linux Distribution - Alpine image (Linux 67e56ec3db81 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 Linux)

### What happened? / Describe the bug

We have been following the script - `https://github.com/microsoft/playwright-java/blob/master/Dockerfile.focal ` to install playwright in a Linux Alpine Image.  It was noticed that the Java Process Builder (https://github.com/microsoft/playwright-java/blob/master/driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java#L47) is unable to find the node executable present inside the temp directory while installing the browsers. 

On some debugging, we found that the executable was indeed present at that location and the it works fine if we copy the executable and run the same command through bash terminal. 

Strangely the above error persists even if we run `export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1` which should ideally print `Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set`

### Code snippet to reproduce your bug

```shell
mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps" -f playwright/pom.xml --no-transfer-progress
```

### Relevant log output

```shell
/tmp/playwright-java-10445247894034150309/playwright.sh: line 3: /tmp/playwright-java-10445247894034150309/node: not found
[WARNING] 
java.lang.RuntimeException: Failed to create driver
    at com.microsoft.playwright.impl.Driver.ensureDriverInstalled (Driver.java:54)
    at com.microsoft.playwright.CLI.main (CLI.java:32)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: 127
    at com.microsoft.playwright.impl.DriverJar.installBrowsers (DriverJar.java:58)
    at com.microsoft.playwright.impl.DriverJar.initialize (DriverJar.java:38)
    at com.microsoft.playwright.impl.Driver.ensureDriverInstalled (Driver.java:52)
    at com.microsoft.playwright.CLI.main (CLI.java:32)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:834)
```

**Comment by yury-s** [comment]
> We have been following the script - `https://github.com/microsoft/playwright-java/blob/master/Dockerfile.focal ` to install playwright in a Linux Alpine Image. It was noticed that the Java Process Builder (https://github.com/microsoft/playwright-java/blob/master/driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java#L47) is unable to find the node executable present inside the temp directory while installing the browsers.

You probably saw [the note](https://playwright.dev/java/docs/docker/#alpine) about Alpine not being officially supported by Playwright. With that said you might be able to make it work with existing Chromium build on Alpine by setting [custom executable path](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch) and `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1`.

> Strangely the above error persists even if we run `export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1` which should ideally print `Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set`

There was a regression of `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` behavior in 1.13 which is fixed by #551 and should make it into the next 1.14 release which will be published in the next few days.

Also note that `install-deps` only works on Ubuntu distros and will fail for Alpine.

**Comment by aarushiag** [comment]
Thanks a lot !! Just a follow up question - 

> Also note that `install-deps` only works on Ubuntu distros and will fail for Alpine.

What exactly do these `exec.args="install-deps"` and  the `exec.args="install-deps"` steps (present in the dockerfile) do ? Will it be sufficient if we are able to download all the drivers and do a mvn install [till - (https://github.com/microsoft/playwright-java/blob/master/Dockerfile.focal#L27)] in the Alpine image for a successful playwright installation ?

Note this is while skipping the browser download and adding a custom path as suggested by you.

**Comment by yury-s** [comment]
> > Also note that `install-deps` only works on Ubuntu distros and will fail for Alpine.
> 
> What exactly do these `exec.args="install-deps"` and the `exec.args="install-deps"` steps (present in the dockerfile) do ?

They install third party libraries that the browsers depend on: https://github.com/microsoft/playwright/blob/master/src/nativeDeps.ts

> Will it be sufficient if we are able to download all the drivers and do a mvn install [till - (https://github.com/microsoft/playwright-java/blob/master/Dockerfile.focal#L27)] in the Alpine image for a successful playwright installation ?
>

If you have working Chromium browser on Alpine AND you replace the Node binary that we bundle with another one that runs on Alpine it might work.
