### ISSUE TITLE
[Question]: Is chromium build supported on Linux Alpine image ? 

### ISSUE THREAD

**Issue by aarushiag** [microsoft/playwright-java#547]
As per the documentation - https://playwright.dev/java/docs/next/docker/#:~:text=Browser%20builds%20for%20Firefox%20and%20WebKit%20are%20built%20for%20the%20glibc%20library.%20Alpine%20Linux%20and%20other%20distributions%20that%20are%20based%20on%20the%20musl%20standard%20library%20are%20not%20supported , it says that Firefox and WebKit builds are unsupported in Alpine base images. Does this mean that Chromium build will be supported ?

**Comment by yury-s** [comment]
Chromium binary bundled with Playwright is built against libc while Alpine works with musl so this binary will not work. But if there is Chromium build available in Alpine you should be able to run Playwright with it by specifying custom executable path like this:
```java
Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
  .setExecutablePath(Paths.get("<path to chrome>")));
```
