### ISSUE TITLE
[Question]: TestPlaywrightCreate is failing

### ISSUE THREAD

**Issue by aarushiag** [microsoft/playwright-java#548]
Hi , I want to skip browser download while calling Playwright. However even if I set the value of environment variable PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 , the initialisation of  `Playwright playwright = Playwright.create(options)` downloads the browser builds. It was validated when I ran the above test case and it failed. Are there some predefined steps to run the above test case? I am just running the above Test after downloading the drivers and successfully running ` mvn install -D skipTests`

The error while running the above test is `org.opentest4j.AssertionFailedError: Did not throw`
Is this an expected behaviour ??

**Comment by yury-s** [comment]
Looks like it was broken by https://github.com/microsoft/playwright/pull/7433

**Comment by yury-s** [comment]
Fixed in #551
