### ISSUE TITLE
get a clear browser [Feature]: 

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#555]
### Feature request

Hello, 

I request a feature about google persistent extensions (https://github.com/microsoft/playwright-java/issues/549),  you tell me need persistent context .  But  need a clear browser  where I request a link everytime , I don't want to be detected by the site . 
And  I don't want to delete user_data dir , it's i/o operation too much. Can you tell I should do ? 

Thanks

**Comment by yury-s** [comment]
It is Chromium's limitation that you can only load extensions in the persistent context and fixing that is too much work (also note that stealth mode is not a priority for test automation scenarios that Playwright focuses on.). You could probably precreate user_data_dir and then start every time with a copy of ti to ensure there are no traces from previous navigations.
