### ISSUE TITLE
[Bug]: Playwright test cases failing in Linux Alpine

### ISSUE THREAD

**Issue by aarushiag** [microsoft/playwright-java#556]
### Playwright version

master commit 

### Operating system

Linux

### Other information

Java -> openjdk11
OS -> Linux Alpine

### What happened? / Describe the bug

No test case is running inside Linux Alpine Image. The error is thrown while creating Playwright object (`Playwright playwright = Playwright.create(options)`) . It looks like the Java process (https://github.com/microsoft/playwright-java/blob/master/playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java#L40) is unable to find the node executable in Linux environment.

On further checking it was found that the UNIX executable was indeed present at the location. Is Java playwright incompatible with Alpine image?? [We have also disabled browser installation through playwright]

### Code snippet to reproduce your bug

```shell
apk add maven
apk add openjdk11
apk add curl
pk add unzip
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
mkdir /tmp/pw-java
Copy code base to /tmp/pw-java
cd /tmp/pw-java
./scripts/download_driver_for_all_platforms.sh
mvn install
```

### Relevant log output

```shell
[ERROR] /tmp/playwright-java-17845343579725696111/playwright.sh: line 3: /tmp/playwright-java-17845343579725696111/node: not found
```

**Comment by yury-s** [comment]
I don't think node.js binary that we ship will work on Alpine (because of the same musl library), you'll need to replace it with a compatible one.

**Comment by aarushiag** [comment]
Thanks, we tried with our version of node and it is working. However we had just replaced the shipped node with ours. Can we get an option in playwright so that we can pass our executable path ? Just like we can pass the browser executable path..

**Comment by yury-s** [comment]
There is undocumented ["playwright.cli.dir"](https://github.com/microsoft/playwright-java/blob/ebf9b09c3447cf2f07c2fb68df550ce70b31a605/driver/src/main/java/com/microsoft/playwright/impl/Driver.java#L69-L72) that you could use to provide the path to preinstalled driver, you can set that property when launching playwright something like:

```sh
mvn test -D playwright.cli.dir="<your unpacked driver dir>"
```

This is non standard property and we may remove/change it in the future. Please file a feature request if you want us to expose a public mechanism for specifying custom driver path (we may end up doing it differently, e.g. via an environment variable or something else).

**Comment by aarushiag** [comment]
Can anyone state whether the above resolution makes sense ? Can we get an option for providing custom node.js path?

**Comment by yury-s** [comment]
> Can anyone state whether the above resolution makes sense ? Can we get an option for providing custom node.js path?

Did you try `playwright.cli.dir` that I mentioned above? It should give you what you want. Instead of having the driver extracted into a temp dir line `/tmp/playwright-java-17487154887695204898` you'd extract/copy it manually into a directory, replace node.js with a binary that works on Alpine and leave js files intact.

**Comment by aarushiag** [comment]
Thanks a lot! This worked :)
