### ISSUE TITLE
change browser "platform" [Question]: 

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#569]
### Your question

Hello,
Could you tell how to change browser "platform"? I don't mean to change UA ，changes "platform" windows to linux.
Thanks

**Comment by mxschmitt** [comment]
Seems like a duplicate of https://github.com/microsoft/playwright/issues/8216 to me. Currently its not yet possible.

**Comment by pavelfeldman** [comment]
What is your use case?

**Comment by xiaowenhuman** [comment]
I just want to crawl some data, some of my other businesses also use it.

**Comment by yury-s** [comment]
Closing in favor of the upstream issue as it'd have to be implemented upstream first. Please upvote [that issue](https://github.com/microsoft/playwright/issues/8216) if you need the feature.
