### ISSUE TITLE
[Bug]: Javadoc for com.microsoft.playwright.Page#navigate(java.lang.String) references page.goto

### ISSUE THREAD

**Issue by jhyot** [microsoft/playwright-java#576]
### Playwright version

1.14.0

### What happened? / Describe the bug

The Javadoc for `com.microsoft.playwright.Page#navigate(java.lang.String)` references a method `page.goto` and `Frame.goto` which doesn't exist. This is maybe a leftover from when `navigate` was still called `goto`?

**Comment by yury-s** [comment]
Should be fixed in the next release with the two PRs above.
