### ISSUE TITLE
hot to get a abs link address?[Question]: 

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#581]
### Your question

Hello,
I want to know how to get to get a long link address ?  For example , there are some short address "a.html" "b.html", I want to get link address(host + address). 

`                List<ElementHandle> elementHandles = page.querySelectorAll("a[href*=\"html\"]");
                String href = elementHandles.get(0).getAttribute("href");`

**Comment by yury-s** [comment]
See base URL parameter in [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) constructor. Evaluating something like `new URL(href, location.href).toString()` in the page context will resolve the href value relative to the page address and give you the long address.

**Comment by xiaowenhuman** [comment]
Thank you very much.
