### ISSUE TITLE
[Question]: Is it Possible to automate an Electron App? 

### ISSUE THREAD

**Issue by alexanderkaiser** [microsoft/playwright-java#584]
### Your question

Hi there, I'm trying to test a simple Electron App. 
So far I came up with the idea to start my Electron App manually and try to connect to the App via `connectOverCDP`.

In simple words my current approach with playwright-java is like

```java
var appUrl = "ws://127.0.0.1:5858/aa8e5c45-2209-487c-b11f-bda4a04e34cb"; // which I receive on startup of the app
var browser = Playwright.create().chromium().connectOverCDP(appUrl);
```

The call to `connectOverCDP(appUrl)` leads to a `com.microsoft.playwright.PlaywrightException` with `Error {
  message='Protocol error (Browser.getVersion): 'Browser.getVersion' wasn't found`.

I've already figured out that the error(message) somehow originates from the Electron App itself, as I observed the following communication:

```
+-------------+                                                                         +-----+
| Playwright  |                                                                         | App |
+-------------+                                                                         +-----+
       |                                                                                   |
       | {"id":1,"method":"Browser.getVersion"}                                            |
       |---------------------------------------------------------------------------------->|
       |                                                                                   |
       |    {"error":{"code":-32601,"message":"'Browser.getVersion' wasn't found"},"id":1} |
       |<----------------------------------------------------------------------------------|
       |                                                                                   |
```

This observation leads me to believe that whole idea should work and I'm just missing some vital points here.

I'm using Playwright `1.14.0` from Maven and electron `^13.2.2` from npm

Thank you, I appreciate any hints 🙂

**Comment by PutziSan** [comment]
Hi, is that still the current status? Is an Electron integration planned in the near future?

**Comment by yury-s** [comment]
No immediate plans for adding Electron support in java.
