### ISSUE TITLE
[Questions]: Playwright version and Chromium versions

### ISSUE THREAD

**Issue by sivadatla** [microsoft/playwright-java#585]
### Your question

Though we see a particular version of `playwright-java` is certified with a particular version of Chromium, 
we observed that Playwright Chromium is upgrading to latest version automatically sometimes, without changing `playwright-java` version! 
* Could you explain when this happens?
* In future if we just upgrade Chromium manually and have `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1` in the env, can we expect it to work?
* Can we expect Playwright to work if we download latest Chromium (not playwright chromium) and place in the appropriate location with `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1` in the env, without changing playwright-java version?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still encounter issues.
