### ISSUE TITLE
[Feature]: Playwright as a replacement for java-cef

### ISSUE THREAD

**Issue by stefan-reich** [microsoft/playwright-java#587]
### Feature request

I basically want to display some simple browser controls, load the page using Playwright and then use the screenshot function repeatedly to display the site contents. Thus simulating a (very crude) browser in a Java program.

Because JCEF sadly does [this](https://botcompany.de/images/1103010) in a VNC session (website contents all gray).

Has anyone tried this before? Thanks

**Comment by yury-s** [comment]
You can forward all input events to the browser and display its screenshots in your java app. This functionality is out of scope of core playwright so we are not planning any work in that direction as part of the library.

**Comment by stefan-reich** [comment]
Sure... I was just inquiring whether this has been done. Thanks
