### ISSUE TITLE
[Question] how to disallow accessing the local file 

### ISSUE THREAD

**Issue by tushitaaggarwal** [microsoft/playwright-java#588]
Hi, 
We are able to see the contents of local files when accessing them through a sample html file in headless mode of playwright for chrome browser on windows. Is there any switch or a flag that can block the same? 
Here is the index.html file:

```
<!DOCTYPE html>
<html>
<body>
	<p>win.ini</p>
	<iframe src="file:///c:/windows/win.ini" width="400" height="400">
	
</body>
</html>
```

Result with playwright(headless execution of chrome):
<img width="1027" alt="Screen Shot 2021-08-31 at 2 43 16 PM" src="https://user-images.githubusercontent.com/29115040/131476176-af1cee18-656d-4a85-a077-f87bac0416a8.png">

**Comment by tushitaaggarwal** [comment]
In further investigation, we tried to access a local file through localhost where, in case of playwright's headless flag false for chrome we were not able to see its contents while in case of headless flag true for chrome, we were able to see the contents. Could you tell us the reason why this might be happening?

Here is the screenshot for that case -

### Playwright with Headless flag true for chrome browser 
<img width="1024" alt="Screen Shot 2021-08-31 at 2 47 43 PM" src="https://user-images.githubusercontent.com/29115040/131476815-1074d3cc-5a17-473d-99e2-a8d4df386763.png">

### Playwright with Headless flag false for chrome browser 
<img width="1023" alt="Screen Shot 2021-08-31 at 2 51 27 PM" src="https://user-images.githubusercontent.com/29115040/131477365-ea418dfe-9e13-441e-9f9c-d972aae2957b.png">

**Comment by yury-s** [comment]
Do you run with MS Edge, what command do you use? It maybe that you have some enterprise policy in place that causes that behavior. Try running with bundled chromium it should be able to load local files in both headed and headless modes.

**Comment by tushitaaggarwal** [comment]
Hi Yury,

We are running with Google Chrome,  and we want to restrict the access of local file ie., we don't want our browser to be able to load the file's contents in the iframe.
This is more important to us and we wanted to know how we can achieve that



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by yury-s** [comment]
By default Chromium doesn't allow load file url into iframe and you should see the following error in the console 'Not allowed to load local resource: file:///....'  That's what's happening when I try to load the page you posted above from `http://localhost:8907/a.html`, is not happening for you? If so could you run with `DEBUG=pw:browser` and post the output here? Whether file urls are allowed from pages loaded from file:// urls is controlled by [--allow-file-access-from-files](https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/content_switches.cc;drc=7751a0f4078bd84e0e9b4c9b045d2cc55d2292ed;l=15) flag in Chrome.

**Comment by yury-s** [comment]
Closing per the comment above.
