### ISSUE TITLE
[Bug]: Not able to upload file using onFileChooser

### ISSUE THREAD

**Issue by ssachdevatwist** [microsoft/playwright-java#591]
### Playwright version

1.12.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I have a situation where I need to upload a file. I can do that either via drag and drop and by clicking on the upload area.

<img width="1431" alt="Screenshot 2021-09-03 at 6 10 49 PM" src="https://user-images.githubusercontent.com/87409477/132007182-a8e950ac-0df6-4a0e-8016-888d0b9734d3.png">

I tried onFileChooser() method for uploading file. I see there was no error but I do not see file was uploaded.

### Code snippet to reproduce your bug

```shell
public class PLaywrightTest {
    private Browser browser;

    @Test
    public void upload(){
        browser = Playwright
                .create()
                .chromium()
                .launch(new BrowserType.LaunchOptions().setHeadless(false));
        Page page = browser.newPage();

        page.navigate("APP URL");
        
        String path = "/Users/sunny.sachdeva/Downloads/pPPRq0824B367866H6.txt";


        page.onFileChooser(fileChooser -> {
            fileChooser.setFiles(Paths.get(path));
        });

        page.click("div.twst-drag-n-drop-upload-msg-and-thumb");       

    }
```

**Comment by yury-s** [comment]
The page uses custom file upload logic, it doesn't create choose file dialog apparently. There must be some hidden `<input type='file'` element somewhere in the page that handles actual upload, once you know how to select that element you can call [`page.setInputFiles()`](https://playwright.dev/java/docs/api/class-page/#page-set-input-files) to set files directly to the input element.
