### ISSUE TITLE
[Question]: emoji colorless in the generated PDF, Windows OS

### ISSUE THREAD

**Issue by ViswanathEmani** [microsoft/playwright-java#592]
### Your question

We are using playwright 1.14.0 version in house for development purpose. We are observing following emojis are rendered color less in the generated PDF on Windows OS (Both Desktop and Server platforms) i.e. Windows 10 and Windows Server 2016 Standard. However the same works when run on Linux and Mac

😶, 🐶

Is there anything specific we need to consider for Windows platforms?

**Comment by yury-s** [comment]
Maybe a bug in Chromium pdf generator, you can report it at https://bugs.chromium.org/. Can you reproduce it without playwright?

**Comment by ViswanathEmani** [comment]
I believe yes, copied the same image in word document and I see the image comes out black and white, you see the difference of the image copied in word document and sticky notes

**Comment by ViswanathEmani** [comment]
![ImageColorless_Windows_OS](https://user-images.githubusercontent.com/11157877/132185061-4f1a29ca-cfba-4b6c-a4fe-a075792b8eee.jpg)

**Comment by yury-s** [comment]
Ok, then it should be reported to Chromium devs.
