### ISSUE TITLE
[Question]: Not sure how to wait properly after Page.click

### ISSUE THREAD

**Issue by stefan-reich** [microsoft/playwright-java#595]
So I'm clicking a button on a page (using Chromium):

`  page.click("[type=submit]:has-text(\"Log in\")");`

And then I scan the follow-up page for a text:

`  assert(page.querySelector("text=abcd") != null);`

However, the second line fails every time with "Execution context was destroyed, most likely because of a navigation."

I tried to insert various waiting commands between the two lines, like this:

`      page.waitForLoadState(); `

Or wrap the first line in waitForNavigation:

```
      page.waitForNavigation(() -> {
        page.click("[type=submit]:has-text(\"Log in\")");
      });
```
   
But none of that makes a difference. The only solution I found is to simply sleep for 3 seconds inbetween the two lines.

There has to be a better way to wait for the navigation to complete?

Thanks in advance.

**Comment by yury-s** [comment]
This issue sounds very similar to #590, see [this comment](https://github.com/microsoft/playwright-java/issues/590#issuecomment-910421279) in particular. `page.click()` will auto-wait for the first navigation triggered by the click to finish. It looks like the page continues to navigate _several times_ to other locations after you click on the 'Log in' button. Can you wait for the page to finish navigating to the page with the final url that contains the element with selector? something along these lines:

```java
page.click("[type=submit]:has-text(\"Log in\")");
page.waitForURL("<expected final URL of the page>");
assert(page.querySelector("text=abcd") != null);
```

**Comment by stefan-reich** [comment]
Ooooh... you are right. 99% sure there is an additional redirect I didn't account for. That absolutely makes sense. Thanks
