### ISSUE TITLE
[Question]: Playwright throwing error INVALID PRINT SETTINGS ERROR for large values of pageheight or pagewidth in pdf options. Is there any limit?

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#603]
### Your question

Hi,

I tried generating pdf with values pageHeight=8.5, pageWidth=1234567890 and also with pageHeight=1234567890, pageWidth=11 . 
In both the scenarios playwright threw excpetion INVALID PRINT SETTINGS ERROR (_Protocol error (Page.printToPDF): Show invalid printer settings error_) . 

I wanted to know what is the limit of page height and page width that are permitted?

Also, is there a way to generate a pdf with default pdf height and width in case such large values are sent?

I have seen such implementation in other implementations like CEF (chromium embedded framework) .

**Comment by yury-s** [comment]
What are you trying to achieve by setting such page sizes?

> Also, is there a way to generate a pdf with default pdf height and width in case such large values are sent?

No, you should compute desired page size when calling `Page.pdf()` at which point you could pick whatever default works for you.

**Comment by abhinav-kipper** [comment]
> What are you trying to achieve by setting such page sizes?
This is just a negative case scenario, in case the client enters such huge value.

> No, you should compute desired page size when calling Page.pdf() at which point you could pick whatever default works for you.

Okay. Do we have any limits for page height and width ?  Can you suggest what are the max values of page height and width that we should provide to playwright

**Comment by yury-s** [comment]
> Do we have any limits for page height and width ? Can you suggest what are the max values of page height and width that we should provide to playwright

I don't see explicit limits in the Chromium base (well, the number has to fit into double). Also running with the numbers you provided does produce a pdf for me, can you share you code snippet?

```java
    Path path = Paths.get("/tmp/out.pdf");
    page.pdf(new Page.PdfOptions().setPath(path).setWidth("1234567890").setHeight("1234567890"));
    long size = Files.size(path);
    System.out.println(size);
```
Here is the generated document info:
![image](https://user-images.githubusercontent.com/9798949/133842119-67b993ee-80ba-4342-a8d4-60ba31782a61.png)

**Comment by abhinav-kipper** [comment]
Hi Yury,

I missed to point out earlier, but I am passing the values of pageheight and pagewidth with "inches" format i.e. 1234567890 inches not 1234567890 pixels.

I think in your case by default it is creating pdf with 1234567890 pixels.

  page.pdf(new Page.PdfOptions().setPath(path).setWidth("1234567890in").setHeight("1234567890in"));

**Comment by yury-s** [comment]
The following snippet fails at 2^25 and passes at 2^24 so you can probably use "16777216in" as an upper limit, also bear in mind that there may be limitations imposed by [the viewer](https://www.cadzation.com/help/pdfpagesize.htm).
```js
  for (let i = 20; i < 30; i++) {
    const size = 1 << i;
    console.log(`trying size: 2^${i} = ${size}`);
    const outputFile = '/tmp/output.pdf';
    await page.pdf({path: outputFile, height: size + 'in', width: size + 'in'});
  }
```
For more precise estimate of the max limit you'll need to look into Chromium codebase or maybe ask this question in crbug.com
