### ISSUE TITLE
how to open flash [Question]: 

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#606]
### Your question

Hello , 
I can open flash used webdriver .
I want to know how to open flash ?

**Comment by yury-s** [comment]
Flash is no longer supported by Chrome, see e.g. [this answer](https://support.google.com/chrome/a/answer/10706877?hl=en).

**Comment by xiaowenhuman** [comment]
I  can use chromedriver playing flash with the same Chrome. So I want to know how to play the flash used playwright?

**Comment by yury-s** [comment]
There is no special support for flash in Playwright but you may be able to dispatch input event e.g. via [Mouse.click](https://playwright.dev/java/docs/api/class-mouse#mouse-click). Please provide more details about what you are trying to do and what is not working if you need further help.
