### ISSUE TITLE
[Question]: Is there a workaround to the restriction for route.resume(options.setUrl()) where in, it does not allow the new Url to have a different protocol than the original one? 

### ISSUE THREAD

**Issue by tushitaaggarwal** [microsoft/playwright-java#607]
### Your question

I am trying to replace a url of an intercepted request say https://localhost/index.html to file://C://somepath/index.html. How can I achieve this in playwright java? I tried using route.resume and set url there but it has the above mentioned restriction. Let me know if there is any way to replace the original url with a new one starting with a different protocol.

I have tried intercepting the request and return the file contents of the file path equivalent of the url as response but in case of a url of type  - C:/Users/file_location/workspace.html?param_one=https%3A%2F%2xyz.com%2F&param_two=xyz, I am not sure what would happen. Could you please help me with that and let me know the pitfalls for this approach. 

Here is the code snippet of what I tried :
``` 
URL url = new URL(route.request().url());
String localhostURL = "https://localhost:9000";
URL routeURL = new URL(html2PDFRequest.getFilePath() + url.toString().substring(localhostURL.length()));
String fileContents = new String(Files.readAllBytes(Paths.get(routeURL.getPath())));
route.fulfill(new Route.FulfillOptions().setBody(fileContents).setContentType(Files.probeContentType(Paths.get(routeURL.getPath()))));
```

We can share the use case in separately in a private thread, since this approach does not work with our use case and I was interested in knowing what must we be doing wrong.

**Comment by mxschmitt** [comment]
Linking https://github.com/microsoft/playwright/issues/8831. I would recommend to proceed there instead of opening a new issue.

**Comment by mxschmitt** [comment]
Closing please continue the discussion in the upstream issue.
