### ISSUE TITLE
[Question]: A strange page loading behaviour in NetBeans ?

### ISSUE THREAD

**Issue by georgeICC** [microsoft/playwright-java#608]
### A strange page loading behaviour in NetBeans ?

Hi, there

I am new to playwright and had a go with following code in NetBeans 12.3:

        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.firefox().launch(new BrowserType.LaunchOptions().setHeadless(true));
            BrowserContext context = browser.newContext();
            Page page = context.newPage();
            String url = "https://www.morningstar.co.uk/uk/funds/snapshot/snapshot.aspx?id=F00000PBF5&tab=3";
            page.navigate(url);
            page.click("#onetrust-accept-btn-handler");
            page.click("#btn_individual");
            String selector = ".snapshotTitleBox > h1:nth-child(1)";
            ElementHandle eh = page.querySelector(selector);
            System.out.println(eh.textContent());
            page.screenshot(new Page.ScreenshotOptions().setPath(Paths.get("screenshot.png")).setFullPage(true));
            browser.close();
        }

It failed to get 'eh' and the screenshot.png is blank. However, if I run it step-by-step in NetBeans' debug mode (with breakpoint set at eh=... line), it works and the screenshot.png is correct. I suspect it is related to page-loading and I have tried various waitFor* method on page/navigation levels, and also disabled timeouts. None of them works. I don't understand why and don't know what I should try next. Could anyone give me a tip, please?

Thanks in advance,

George

**Comment by yury-s** [comment]
> It failed to get 'eh' and the screenshot.png is blank. However, if I run it step-by-step in NetBeans' debug mode (with breakpoint set at eh=... line), it works and the screenshot.png is correct.

Looks like a timing issue: when you run it step-by-step in NetBeans it has enough time to load and render the element while under playwright you query it too soon and it's not there yet. Note that `querySelector` will not wait for an element if it's not there. [`Page.waitForSelector`](https://playwright.dev/java/docs/api/class-page#page-wait-for-selector) will for the element to appear, use that instead. See also [this page](https://playwright.dev/java/docs/actionability) for more information about auto-waiting in Playwright.

**Comment by georgeICC** [comment]
Thank you, Yury, for the tip.
I have replaced the eh=... line with following line and it works.
            ElementHandle eh = page.waitForSelector(selector,new Page.WaitForSelectorOptions().setTimeout(0));
