### ISSUE TITLE
[BUG] Playwright Exception: Failed to read message from driver, pipe closed

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#618]
**Context:**
- Playwright Version: 1.12.1
- Operating System: Windows
- Browser: Chromium
- Extra: Headless mode

**Describe the bug**

In our springboot application, We are using page.pdf() after navigating to a html page to print. 

The code works fine initially i.e. all requests to convert html to pdf are sent to playwright and are successful. 

But after a few days, for all the requests it starts throwing - 
 **Playwright Exception thrown : Failed to read message from driver, pipe closed**

And if we restart the application , the issue gets resolved. 

What can be the reason for this ?

**Comment by yury-s** [comment]
Looks like the driver (node) process dies for some reason. Is there anything interesting in stderr? You can try running with DEBUG=pw:browser to collect some more logs from the browser launcher.

**Comment by abhinav-kipper** [comment]
For every request I am creating new playwright , browser, browser context and page objects. 
```
         Playwright playwright = Playwright.create();

         BrowserType chromium = playwright.chromium();

         Browser browser = chromium.launch(new BrowserType.LaunchOptions()
                .setProxy(proxy).setChromiumSandbox(true));

         BrowserContext browserContext = browser.newContext();

        Page page = browserContext.newPage();
```
After it gets completed (navigates and prints) I close all the 4 objects like this - 
```  
        page.close();
        browserContext.close();
        browser.close();
        playwright.close();

```

I was not having debug flag while the issue arose, so I could not see anything in stderr and simple restarting application resolved the issue for now. 
However , This issue may arise after a while again.

Is there anything you suggest that we can do to prevent it or to better diagnose issue?

**Comment by yury-s** [comment]
> Is there anything you suggest that we can do to prevent it or to better diagnose issue?

Look for debug output, the logs should give a clue. Since it happens after a few days it might be that the temp folder where we extract the driver is changed by another app/deleted. Do I get it right that the playwright app is running for a few days without restart?

> For every request I am creating new playwright , browser, browser context and page objects.

Just curious, is there a reason you recreate playwright and browser rather than just context?

**Comment by abhinav-kipper** [comment]
> Look for debug output, the logs should give a clue. Since it happens after a few days it might be that the temp folder where we extract the driver is changed by another app/deleted. Do I get it right that the playwright app is running for a few days without restart?
Yes right. The app is running without restart.

> Just curious, is there a reason you recreate playwright and browser rather than just context?
Yes. This is because playwright is not thread-safe. 
Initially I was using the same approach to create new browser context for every request and other objects only once but in case of concurrent requests coming on the app, I was getting Playwright Exceptions something like  "Object doesn't exist" .

**Comment by abhinav-kipper** [comment]
@yury-s  Can you tell if there is a way to monitor when the playwright should be restarted ?

**Comment by yury-s** [comment]
> Can you please tell if there is a way to monitor when the playwright should be restarted ?

You should not need to restart it, there is either a bug or the driver is running out of memory like I mentioned above.

> Yes. This is because playwright is not thread-safe.

Interesting, so now you have the app create/close many playwright instances on parallel threads and eventually the driver starts throwing the error, is that correct?

**Comment by abhinav-kipper** [comment]
> Interesting, so now you have the app create/close many playwright instances on parallel threads and eventually the driver starts throwing the error, is that correct?

@yury-s When I create all playwright instances (playwright, browser, browser context, page) seperately on each thread , I do not get this exception. But if I create only browser context seperately for each new thread ( not rest of the playwright instances) ,  I get this exception.

**Comment by yury-s** [comment]
> @yury-s When I create all playwright instances (playwright, browser, browser context, page) seperately on each thread , I do not get this exception. But if I create only browser context seperately for each new thread ( not rest of the playwright instances) , I get this exception.

Well, as our [documentation](https://playwright.dev/java/docs/multithreading)  says it is unsafe to do this, and you are expected to get exceptions like "Object doesn't exist".
