### ISSUE TITLE
[BUG] page.pdf generating blank pdf for domain www.adobe.com

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#622]
**Context:**
- Playwright Version: 1.12.1
- Operating System: Windows
- Browser: Chromium

**Describe the bug**

I am converting adobe.com html to pdf using playwright. In headless mode, empty blank pdf is getting generated while in headed mode / chrome browser the contents are visible.

Code is simply to navigate and print - 
page.navigate("https://www.adobe.com");
page.pdf();

Can you help identify why behaviour is different for www.adobe.com URL for headless mode?

**Comment by yury-s** [comment]
> I am converting adobe.com html to pdf using playwright. In headless mode, empty blank pdf is getting generated while in headed mode / chrome browser the contents are visible.
...
> Can you help identify why behaviour is different for [www.adobe.com](http://www.adobe.com) URL for headless mode?

Looks like some bot protection kicks in on the adobe.com site and it serves different page when you access it from a headless browser (or more generically browser controlled by automation I believe). I get this page in headless:

![image](https://user-images.githubusercontent.com/9798949/134211146-6f035c21-ed75-41ae-8521-4f2dd952e025.png)

**Comment by abhinav-kipper** [comment]
@yury-s is there any special difference in a browser controlled by automation, that a site can identify and block?
Any special properties that are added to browser?

**Comment by yury-s** [comment]
Yes, there are many subtle differences, to start with user-agent header is different, 'navigator.webdriver' property may be true etc. Support for a 'stealth' mode where the server cannot tell if the browser is controlled by automation is not a goal for Playwright at the moment as we assume that in the test environment you can always tweak the server to serve right content.
