### ISSUE TITLE
[Question] how do I wait for dialog box?

### ISSUE THREAD

**Issue by PhilipStubbs** [microsoft/playwright-java#623]
Hi,
I'm needing to wait for a dialog box to appear before continuing.

Whats the best way to wait for dialog box to appear?
I see in the js version we could do `page.waitForEvent('dialog')`. What is the equivalent in Java?

Thanks!

**Comment by PhilipStubbs** [comment]
I actually ended up changing my code to not need a dialog box, but am still interested in the above.

**Comment by yury-s** [comment]
There is [`Page.onDialog`](https://playwright.dev/java/docs/api/class-page#page-event-dialog) that you can use to handle dialogs. Something like this:
```java
boolean[] didShowDialog = {false};
page.onDialog(dialog -> didShowDialog[0] = true);
page.evaluate("setTimeout(() => alert('hello'), 0);");
while (!didShowDialog[0]) {
  page.waitForTimeout(100);
}
```
Unlike other events we didn't add `page.waitForDialog` as the dialog has to be either accepted or dismissed before the page execution can continue and if we returned a dialog object from `waitForDialog` the client could get to the next step in their script before doing anything with the dialog which would lead to a deadlock.
