### ISSUE TITLE
[BUG] Object doesn't exist exception thrown by Playwright

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#624]
**Context:**
- Playwright Version: 1.12.1
- Operating System: Windows
- Browser: Chromium
- Extra: Springboot App ; headless mode; Concurrent requests sent to (Springboot app) playwright code

**Sample Code Snippet 1 [Non-Working] [Only new Browsercontext and new page created for new request]**

```  
 Class printToPDF {
       Playwright playwright;
       BrowserType chromium;
       Browser browser;

      public void execute() {
            if (Objects.nonNull(playwright)) playwright = Playwright.create();
            if (Objects.nonNull(chromium)) chromium = playwright.chromium(); 
            if (Objects.nonNull(browser)) browser = chromium.launch(new BrowserType.LaunchOptions().setProxy(proxy).setChromiumSandbox(true));

      BrowserContext browserContext = browser.newContext();
         Page page = browserContext.newPage();
         .
         .
         .
        page.close();
        browserContext.close();
 
}
}
```

**Sample Code Snippet 2 [Working] [All objects created for new request]**

```  
         Playwright playwright = Playwright.create();
         BrowserType chromium = playwright.chromium();
         Browser browser = chromium.launch(new BrowserType.LaunchOptions().setProxy(proxy).setChromiumSandbox(true));
         BrowserContext browserContext = browser.newContext();
         Page page = browserContext.newPage();
         .
         .
         .
        page.close();
        browserContext.close();
        browser.close();
        playwright.close();
```

**Description**

On running the Code Snippet 1 in multithreaded environment, we are getting _Object doesn't exist_ exception - 

Screenshot of sending concurrent requests (7 threads) with code snippet 1.

<img width="1609" alt="Screenshot 2021-09-23 at 4 54 44 PM" src="https://user-images.githubusercontent.com/22498015/134498820-37e407c7-59fc-493c-b54b-d415e3441279.png">

However, by creating all objects (playwright, browser, browsercontext etc) for every request [Code Snippet 2], this exception does not occur.

Is there a way to fix this problem ? Opening only the browser context for every request can really improve the performance of our system.

**Comment by yury-s** [comment]
Playwright is not thread-safe, see [this document](https://playwright.dev/java/docs/multithreading). It is unsafe to reuse the same Browser instance for creating BrowserContext on parallel threads.
