### ISSUE TITLE
[Question] Java Handle New Page

### ISSUE THREAD

**Issue by ArmanYeghiazaryan** [microsoft/playwright-java#627]
Hello,

The website I would like to handle forces interaction with a new tab, which opens after clicking a button. It looks like this: (See attached screenshot) 
![image](https://user-images.githubusercontent.com/82316190/134671398-8b881c6f-32ea-4bec-9366-7d41fe7b6d37.png)

Main aim is to wait for the popup, print the source code and click on "Go" afterwards. 

Could you be so kind and attach the Java code snippet for this please? I already had a look at Java docs, but could not integrate it. 

Thank you very much.

**Comment by yury-s** [comment]
See [this guide](https://playwright.dev/java/docs/multi-pages#handling-popups).  You need to wrap the click into [`Page.waitForPopup`](https://playwright.dev/java/docs/api/class-page#page-wait-for-popup), something along these lines:

```java
Page popup = page.waitForPopup(() -> {
  page.click("<your button selector>");
});
```

**Comment by ArmanYeghiazaryan** [comment]
So I am using this snippet: 

```
Page popup = page.waitForPopup(() -> {
				page.click("//*[@id=\"__next\"]/div[1]/main/div/div/div/div[1]/div[2]/button");
			});

			System.out.println("Content: " + popup.content());
```

However I am getting a timeout exception, as I cannot find the popup / print the content. Any idea?

**Comment by yury-s** [comment]
Does the popup show up?

**Comment by ArmanYeghiazaryan** [comment]
Yes it does. Maybe it's more likely a tab? As you can see at the screenshot above.

**Comment by yury-s** [comment]
> Yes it does. Maybe it's more likely a tab? As you can see at the screenshot above.

If it's a window opened by the page as a result of the click it must be intercepted. If it's not there it means that it was either opened before the call or it is not opened by the page (Could it be that you have an extension that opens the child window?). You can also listen for all pages created in the context via [`contenxt.onPage`](https://playwright.dev/java/docs/api/class-browsercontext/#browser-context-event-page) to see if it's created as a normal page. Which browser is this?

**Comment by ArmanYeghiazaryan** [comment]
Yes, you are right. It is an extension, which opens the windows after clicking a button. I am using Firefox. What would be the best solution in my case?

**Comment by yury-s** [comment]
We don't support extensions in Firefox yet, you can +1 [this bug](https://github.com/microsoft/playwright/issues/7297) if you are interested in it.

**Comment by ArmanYeghiazaryan** [comment]
Thank you. How can I use playwright with extensions - will chromium work? If yes, can you show me the corresponding doc page?

**Comment by yury-s** [comment]
https://playwright.dev/docs/chrome-extensions

**Comment by ArmanYeghiazaryan** [comment]
Is there also a description in Java? If not, could you please be so kind and send me a code snippet, which would solve my issue? 

Really appreciated. Also, thanks for the fast answers.

**Comment by yury-s** [comment]
Sorry, I forgot to mention that the background pages API is not exposed in Java, there is a [feature request](https://github.com/microsoft/playwright-java/issues/504) for that, so far we've been resisting it as it is a not a standard web api.
