### ISSUE TITLE
[Question] How to insert code in monaco editor using Playwright?

### ISSUE THREAD

**Issue by ibrocodes7** [microsoft/playwright-java#631]
I am trying to test a feature containing monaco editor, and couldn't find anything related in Playwright docs and forums.

This is my test:

```
async ({ page }) => {
    const testPage= new TestPage(page);

    await testPage.navigateTo();
    //dosomething
    await page.waitForSelector(#monaco-editor-selector);
    //Paste a script in monaco editor
}()
```

Please help!

![Screenshot (20)](https://user-images.githubusercontent.com/65076139/135285350-42fcf3c3-68b1-4d3e-9b01-38e61771c162.png)

**Comment by yury-s** [comment]
You can use [`keyboard.type()`](https://playwright.dev/docs/api/class-keyboard#keyboard-type) to type the code into the editor. Would that work?
