### ISSUE TITLE
[Question] How to quickly find out if an element exists in a page or not?

### ISSUE THREAD

**Issue by georgeICC** [microsoft/playwright-java#636]
Hi,

This seems a simple question, but it troubles me for quite a while. So far, the method I found in the doc is 'waitForSelector', which will be timed out (30s by default) if the element does NOT exist. I wonder if there is a quicker method in this case. 
Any tips are appreciated. Thanks.

George

**Comment by yury-s** [comment]
What you need is [`Page.querySelector`](https://playwright.dev/java/docs/api/class-page#page-query-selector), it return immediately without waiting for the element.

**Comment by georgeICC** [comment]
I have tried Page.querySelector method. The problem is that it always return null if the page can not be loaded immediately.

**Comment by georgeICC** [comment]
Below is my testing code, which returns eh correctly. If I add a typo in the selector string, it ends with a timeout after 30s and nothing is returned. In this case, it's hard to tell if it is a timeout or because the element doesn't exist.

However, if I replace 'waitForSelector'  with 'querySelector', the returned eh is always null, no matter what selector string is. 

        try (Playwright pw = Playwright.create(new Playwright.CreateOptions().setEnv(env))) {
            Browser b = pw.chromium().launch(new BrowserType.LaunchOptions().setHeadless(true));
            BrowserContext c = b.newContext();
            Page p = c.newPage();
            String url = "https://www.morningstar.co.uk/Common/funds/snapshot/PortfolioSAL.aspx?Site=uk&FC=F0GBR04SA0&IT=FO&LANG=en-GB";
            p.navigate(url);
            String selector = ".sal-holdings__leftTable > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1)";
            ElementHandle eh = p.waitForSelector(selector);
            System.out.println(eh);
            b.close();
        }

**Comment by georgeICC** [comment]
I found the reason now. The default state 'LOAD' for Page.navigate method is not enough for querySelector call. It has to be NETWORKIDLE in this case.

**Comment by yury-s** [comment]
Networkidle can be flaky as it relies on what requests the pages sends over the network and when. I'd recommend you use another condition to check if the page load is complete (like wait for a certain element to show up in the page or maybe there is some internal js state that you could poll).

**Comment by georgeICC** [comment]
Waiting for another element to show up would not solve the issue because we face the same issue if it does not show up. We simply do know if it doesn't exist or have to wait until timeout. To make use js code in java version of playwright is not a beautiful solution either. If I am a js developer, I probably go for the js version of playwright straight away. 
Actually, if NETWORKIDLE is not ideal and LOAD is not sufficient to tell the end of loading elements before querySelector is called, why not add another state inbetween?

**Comment by yury-s** [comment]
> To make use js code in java version of playwright is not a beautiful solution either. If I am a js developer, I probably go for the js version of playwright straight away.

Yeah, makes sense.

> Actually, if NETWORKIDLE is not ideal and LOAD is not sufficient to tell the end of loading elements before querySelector is called, why not add another state inbetween?

There is no well defined intermediate state and that's unlikely what you need. If the element is resolved after NETWORKIDLE event and it is the same page where LOAD event fired then waitForSelector should just work, I'm curious why it times out for you. Can you share a minimal repro where it doesn't work?

**Comment by georgeICC** [comment]
Please see https://github.com/georgeICC/PlayWrightTester

**Comment by yury-s** [comment]
I changed querySelector to waitForSelector and it works just fine:

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2021-10-05T19:23:35.962Z pw:api navigating to "https://www.morningstar.co.uk/Common/funds/snapshot/PortfolioSAL.aspx?Site=uk&FC=F0GBR04SA0&IT=FO&LANG=en-GB", waiting until "load"
2021-10-05T19:23:36.225Z pw:api   navigated to "https://www.morningstar.co.uk/Common/funds/snapshot/PortfolioSAL.aspx?Site=uk&FC=F0GBR04SA0&IT=FO&LANG=en-GB"
2021-10-05T19:23:36.976Z pw:api   "domcontentloaded" event fired
2021-10-05T19:23:36.982Z pw:api   "load" event fired
2021-10-05T19:23:37.003Z pw:api waiting for selector ".sal-holdings__leftTable > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1)" to be visible
2021-10-05T19:23:37.877Z pw:api   selector resolved to visible <td>L&G US Index R Inc</td>
JSHandle@node
```

**Comment by georgeICC** [comment]
That's exactly what I said at the beginning of this issue thread. To check whether an element exist or not, we can't use waitForSelector because it will time out if the element does not exist and we can't tell it from a genuine timeout due to other reasons such as networking issue. We can't use querySelector (with waiting for LOAD state) either because it always return null even if the element does exist.

I don't think the server serves different pages. I guess the page served by the server is generated dynamically, i.e. by JS. Does the LOAD state means only end of loading 'static' elements excluding dynamically generated elements by js scripts ?
