### ISSUE TITLE
[Question] How do I view the trace using Playwright for Java?

### ISSUE THREAD

**Issue by Leesaaaa** [microsoft/playwright-java#655]
Hi! I just started using Playwright for Java a couple days ago because I could not get Cypress to work with Azure SSO.  I am happy to say Playwright worked easily! Thanks for that! Now on to the question at hand, I am trying to view the trace.   I've read through the documentation here (https://playwright.dev/java/docs/trace-viewer) .  I tried mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="show-trace trace.zip" where trace.zip is the path to my trace file.  I've tried this from inside Intellij's Execute Maven Goal command line dialog. 
![image](https://user-images.githubusercontent.com/89655531/138313602-10c31c8b-23ad-48e0-92ca-245ec58b4dd8.png)
This yields:
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java (default-cli) on project testProject-auto-test: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java are missing or invalid
Any guidance on this error is greatly appreciated.
/////
I wonder if this error is occurring because I am using spring boot as the parent.

**Comment by LongLiveY96** [comment]
> @Leesaaaa而不是在命令行中运行显示跟踪，您可以将浏览器指向https://trace.playwright.dev/然后将跟踪文件拖到该页面查看它。该页面基本上是相同的观看者，但服务器在互联网上。



> @Leesaaaa而不是在命令行中运行显示跟踪，您可以将浏览器指向https://trace.playwright.dev/然后将跟踪文件拖到该页面查看它。该页面基本上是相同的观看者，但服务器在互联网上。

Is the online trace browsing project open-source? Due to security issues, it is inconvenient to upload trace files.

**Comment by LongLiveY96** [comment]
> @Leesaaaa instead of running show-trace in command line you can point your browser to https://trace.playwright.dev/ and then drag your trace file to that page to see it. That page is basically the same viewer but server over the internet.

Is the online trace browsing project open-source? Due to security issues, it is inconvenient to upload trace files.

**Comment by yury-s** [comment]
> > @Leesaaaa instead of running show-trace in command line you can point your browser to https://trace.playwright.dev/ and then drag your trace file to that page to see it. That page is basically the same viewer but server over the internet.
> 
> Is the online trace browsing project open-source? Due to security issues, it is inconvenient to upload trace files.

Yes, it is open sourced (here is [the source code](https://github.com/microsoft/playwright/tree/master/packages/playwright-core/src/web/traceViewer) and here are [the deployed files](https://github.com/microsoft/playwright.dev/tree/master/trace)) and the trace file actually doesn't get uploaded anywhere (you can check that using network panel in devtools). The web site is used to distribute the trace viewer web-app code so that one wouldn't have to launch local server for that.  We'll have to clarify all of this in the docs by the next release, but you can already give it a try.

**Comment by chaganiu** [comment]
@yury-s will we get instructions on how to self-host the trace viewer?

**Comment by yury-s** [comment]
> @yury-s will we get instructions on how to self-host the trace viewer?

There are no plans for that. What's the advantage of self-hosted trace viewer over show-trace [cli command](https://playwright.dev/java/docs/trace-viewer/#viewing-the-trace) ?

**Comment by uchagani** [comment]
security policy. Although nothing gets uploaded to microsoft they would want this hosted on our servers.

**Comment by chaganiu** [comment]
@yury-s security policy. Although nothing gets uploaded to microsoft they would want this hosted on our servers.

**Comment by yury-s** [comment]
In that case we recommend launching trace viewer from command line:

```sh
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="show-trace trace.zip"
```
At this point there are no plans on supporting self-hosted viewer. I'm closing this issue as the original question was addressed, feel free to open a new feature request regarding self-hosted trace viewer.
