### ISSUE TITLE
[Question] How to run playwright java with xvfb virtual display

### ISSUE THREAD

**Issue by insticore** [microsoft/playwright-java#661]
I want to run headful browser in a docker container. So i use xvfb as a virtual display.

I try to run a java playwright app as `xvfb-run --auto-servernum --server-num=0 java <...>`
But **Chrome.launch** JS method called from java constantly fails with timeout if headless set to false.
It looks like JS playwright doesn't know about xvfb because **java** is called with xvfb-run but not NodeJS.

Please help, is there any way to run the java playwright with xfvb?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
