### ISSUE TITLE
[Question]How to improve performance,    Thousands of pages need to be opened and retrieved every 5 minutes

### ISSUE THREAD

**Issue by ylhang** [microsoft/playwright-java#682]
I have a list of about 90 pages, and each page in the list has about a hundred subpages.

If I use playwpage to fetch pages in a single thread, it is impossible to complete all the data that needs to be fetched in a 5-minute cycle

Is there any good solution?  
Help me take a look

**Comment by yury-s** [comment]
You can do something similar to what is described in https://github.com/microsoft/playwright-java/issues/678. Basically set [default navigation timeout](https://playwright.dev/java/docs/api/class-browsercontext/#browser-context-set-default-navigation-timeout) to a very short value and not wait for the page navigation to finish before creating a new page. You'll need to catch timeout exception for that. We are adding a new option to the page.navigate in [this PR](https://github.com/microsoft/playwright/pull/9892) which will make it less hacky and will avoid the timeout exception.
