### ISSUE TITLE
[Question] common interface for Page/Frame methods

### ISSUE THREAD

**Issue by beegotsy** [microsoft/playwright-java#691]
Hello, sorry to bother you.
I am building an interpreter that take as input a JSON list of command (that changes each request) and convert that to Playwright methods. For example, I have a "navigate" command that execute the method "navigate" on a new Playwright page.

I implemented the "change-frame" command, that allow me to select a frame inside my page, and that works fine.
Now, I have the problem that all of Page methods (and signatures) have a different class than all of Frame methods (and signatures), even if a lot of them share the same options.
In other languages (for example Python or JavaScript/Typescript) this would not be a problem, and I know how to overcome this "restriction"; but since I am forced to develop this interpreter in Java, which I am not that confident with, I don't know how to do that.

For example, if I want to call the method click this is a "first approach" that I would use:
```java
public void click_command(BrowserContext ctx, Page page, Frame frame, String selector, double timeout) {        
    if (frame != null) {
        // if I received a frame, I want to execute the click method on the frame
        com.microsoft.playwright.Frame.ClickOptions options = new com.microsoft.playwright.Frame.ClickOptions();
        options.setTimeout(timeout);
        frame.click(selector, options);
    } else {
        // frame was null, so I will execute the click method on the page
        com.microsoft.playwright.Page.ClickOptions options = new com.microsoft.playwright.Page.ClickOptions();
        options.setTimeout(timeout);
        page.click(selector, options);
    }
}
```

I thought different approaches, like creating a Map<String, Object> for the options parameter and then converting it to a specific class with the ObjectMapper, but I don't think that's a clean way to solve my problem.

What would be your suggestions?
I know that's not a Playwright specific question, but since other may find the answer to this question useful I am posting this here

Thank you all for your  patience

**Comment by yury-s** [comment]
Most of the Page methods just delegate to the same method on the main Frame object, so if you already have logic that keeps track of the 'current' frame you can always use just Frame methods as that what Playwright would do internally.

As for the different signtaures/types of arguments - as you correctly noted most of them are structurally equal, we rely on that in our implementation and convert from page argument to frame arguments using Gson. See [Page.click](https://github.com/microsoft/playwright-java/blob/master/playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java#L625-L628) for example, the options are transformed this way: Page.ClickOptions -> json tree -> Frame.ClickOptions. Hope this helps.
