### ISSUE TITLE
[BUG]: Non English Characters are printed as ????? 

### ISSUE THREAD

**Issue by dushyantjoshi23** [microsoft/playwright-java#692]
I tried to read few non english characters from www.google.co.in. After fetching those characters from UI and print them on console , the out put got printed as ?????
- Playwright Version: 1.14.1
- Operating System: Windows
- Browser:All

Code Snippet:
 page.navigate("https://google.co.in");
 List<ElementHandle> elements=	page.locator("xpath=//*[@id=\"SIvCob\"]//a").elementHandles();
 for(int i=0;i<elements.size();i++) {
	  
	 System.out.println(elements.get(i).textContent());
  }

The output gets printed as ???? . Could you please provide insights on how to read unicode characers with playwright.
Add any other details about the problem here.

**Comment by yury-s** [comment]
When I go to that site everything is in English. Can you provide a different URL that has a static page that doesn't depend on where you access it from?

> The output gets printed as ???? .

It's most likely a problem with the fonts in the terminal where you print the text. You can save the text content to a file and open it in an editor that is known to show text in your locale to see that textContent() actually returns correct data..

**Comment by dushyantjoshi23** [comment]
Thank you for quick response. Rightly pointed that issue was with Terminal where text was printed. The problem got resolved after switching the Eclipse IDE encoding to UTF 8 from Run Configurations.
![image](https://user-images.githubusercontent.com/16277973/140604909-4cf6e786-b3a4-4faf-8220-4488e48f2ea7.png)
