### ISSUE TITLE
[BUG] Browser does not start when using selenium grid

### ISSUE THREAD

**Issue by Mikhailnt87** [microsoft/playwright-java#693]
**Context:**
- Playwright Version: 1.16.1
- Operating System: docker ubuntu
- Browser: Chrome

**dockerfile**
FROM mcr.microsoft.com/playwright/java:v1.16.1-focal

WORKDIR /Project/WebPlaywright

COPY . .

RUN cd /Project/WebPlaywright

CMD SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub mvn -pl WebPlaywright clean test

**docker-compose.yml**
version: "2.1"
services:
  chrome:
    image: selenium/standalone-chrome:4.0.0-20211102
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
  selenium-hub:
    image: selenium/hub:4.0.0-20211102
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  
  test_runner:
    build:
      context: C:\Project
      dockerfile: C:\Project\WebPlaywright\Dockerfile
    image: tests_playwright
    container_name: tests_run_playwright
    network_mode: "host"

**Logs:**
docker logs b6d805b9f0e4
2021-11-03 22:11:24,688 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2021-11-03 22:11:24,692 INFO supervisord started with pid 9
2021-11-03 22:11:25,695 INFO spawned: 'selenium-grid-hub' with pid 11
2021-11-03 22:11:26,703 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
22:11:30.913 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
22:11:31.057 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
22:11:32.406 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.19.0.6:4442], XSUB binding to [binding to tcp://*:444
3, advertising as tcp://172.19.0.6:4443]
22:11:33.397 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.19.0.6:4442 and tcp://172.19.0.6:4443
22:11:33.780 INFO [UnboundZmqEventBus.<init>] - Sockets created
22:11:34.795 INFO [UnboundZmqEventBus.<init>] - Event bus ready
22:11:41.709 INFO [Hub.execute] - Started Selenium Hub 4.0.0 (revision 3a21814679): http://172.19.0.6:4444

docker logs ad25940909ae
2021-11-03 23:26:40,254 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2021-11-03 23:26:40,258 INFO supervisord started with pid 7
2021-11-03 23:26:41,261 INFO spawned: 'selenium-grid-hub' with pid 9
2021-11-03 23:26:42,281 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
23:26:44.957 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
23:26:45.013 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
23:26:46.712 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.19.0.6:4442], XSUB binding to [binding to tcp://*:444
3, advertising as tcp://172.19.0.6:4443]
23:26:47.561 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.19.0.6:4442 and tcp://172.19.0.6:4443
23:26:47.970 INFO [UnboundZmqEventBus.<init>] - Sockets created
23:26:49.064 INFO [UnboundZmqEventBus.<init>] - Event bus ready
23:26:57.372 INFO [Hub.execute] - Started Selenium Hub 4.0.0 (revision 3a21814679): http://172.19.0.6:4444
23:35:21.906 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "1443934211edecb0333689d66a610c57","eventTime": 1635982521904778900,"eventName": "HTTP reques
t execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "2264","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession"}}

23:35:21.935 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "7e42bde1d8f1383e885d7859bf8e4ae4","eventTime": 1635982521934164400,"eventName": "HTTP reques
t execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "2264","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession"}}

**Code Snippet**
@BeforeAll
    void launchBrowser() {
        playwright = Playwright.create();
        browserIncognitoModeHeadless = playwright.chromium().launch(new BrowserType.LaunchOptions().setChannel("chrome").setTimeout(160000).setHeadless(true).setArgs(Arrays.asList("--disable-dev-shm-usage")).setArgs(Arrays.asList("--whitelisted-ips")));
        browserIncognitoModeHeadfull = playwright.chromium().launch(new BrowserType.LaunchOptions().setChannel("chrome").setHeadless(false).setArgs(Arrays.asList("--start-maximized")));
    }

**Describe the bug**
When starting tests and launching browser with selenium grid i get error:
Caused by: com.microsoft.playwright.TimeoutError:
tests_run_playwright | Error {
tests_run_playwright |   message='Timeout 160000ms exceeded.
tests_run_playwright | =========================== logs ===========================
tests_run_playwright | <connecting to selenium> http://localhost:4444/wd/hub/

**Comment by dgozman** [comment]
Version 1.18 includes fixes for Selenium 3 and 4. See [here](https://playwright.dev/java/docs/selenium-grid) for documentation and please file new bug reports if you still encounter bugs.
