### ISSUE TITLE
[Question]Is there a feature that allows me to pause and continue tracing

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#696]
Our services involve account login and switch user. For security reasons, we expect to pause tracing(like page.pause()) during login  and then continue tracing.Now, only the start and stop APIs are available.

**Comment by yury-s** [comment]
You can use [`startChunk/stopChunk`](https://playwright.dev/java/docs/api/class-tracing#tracing-start-chunk) methods which are available since v1.16 and pause the tracing whenever you like.
