### ISSUE TITLE
[BUG] Inspector on java does not show source code

### ISSUE THREAD

**Issue by mikomatic** [microsoft/playwright-java#697]
**Context:**
- Playwright Version: 1.16.1
- Operating System: [Windows]
- Browser: Chrome

**Code Snippet**

Generated via "codegen" tool

```java
public class ExampleBug {
    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setHeadless(false));
            BrowserContext context = browser.newContext();

            // Open new page
            Page page = context.newPage();

            // added pause to inspect
            page.pause();

            // Go to https://www.google.com/
            page.navigate("https://www.google.com/");

            // Click [aria-label="Rech."]
            page.click("[aria-label=\"Rech.\"]");

            // Fill [aria-label="Rech."]
            page.fill("[aria-label=\"Rech.\"]", "chocolate");

            // Click text=Chocolat
            page.waitForNavigation(() -> {
                page.click("text=Chocolat");
            });
        }
    }
}
```

**Describe the bug**

When adding a `page.pause` to open playwright inspector, the source code script is not available (as apparent in documentation or demos online)

The inspector is still functional, i can step though the playwright script and see the action in the lower part. But the java script is not visible. See attachment screenshot.

![PLAYWRIGHT_issue](https://user-images.githubusercontent.com/2025943/141471950-deb09889-de86-4230-a156-33ca5f55dc7a.JPG)

Maybe this is normal behaviour but documentation points otherwise.

PS. Loving this framework, keep up the good work!

**Comment by yury-s** [comment]
You need to set [PLAYWRIGHT_JAVA_SRC](https://playwright.dev/java/docs/inspector/#open-playwright-inspector) to the root directory of your source code, otherwise Playwright doesn't know where to search for sources and show only events with blank source page.

**Comment by mikomatic** [comment]
You are right, i missed that on the docs - thanks for the quick response
