### ISSUE TITLE
[Question] is there a way to refresh the iframe content

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#698]
I still encounter iframe with empty content and name

On browser, I can see iframe element HTML  (as the matter of fact, I am able to to find Iframe Element and return correct iframe name),  When I use the iframe ElementHandler to switch to the frame (as code below), the body is empty and get error time out.

```
// NOTE I have element wrapper class
Frame nestedFrame = ((ElementHandle)element.getNativeToolElement()).contentFrame();
nestedFrame.waitForLoadState();
nestedFrame.waitForSelector("body");

```

```
com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "body" to be visible
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "body" to be visible
============================================================
    at ProgressController.run (C:\Users\xxxxx\AppData\Local\Temp\playwright-java-4302232322808460987\package\lib\server\progress.js:84:26)
    at Frame.waitForSelector (C:\Users\xxxxx\AppData\Local\Temp\playwright-java-4302232322808460987\package\lib\server\frames.js:750:23)
    at FrameDispatcher.waitForSelector (C:\Users\xxxxx\AppData\Local\Temp\playwright-java-4302232322808460987\package\lib\dispatchers\frameDispatcher.js:103:110)
    at DispatcherConnection.dispatch (C:\Users\xxxxx\AppData\Local\Temp\playwright-java-4302232322808460987\package\lib\dispatchers\dispatcher.js:349:46)
}
```

![image](https://user-images.githubusercontent.com/6579909/141502809-f5221d38-076e-4172-a76c-7b4642dd8f41.png)

**Comment by yury-s** [comment]
The iframe does something in its onload handler which looks like it navigates to elsewhere (`goToPage()`) this could invalidate the element handle. We discourage use of ElementHandles and recommend Locators instead so that they don't get invalidated if the page navigates/refreshes etc. Can you provide a repro so that we can debug it locally? Otherwise it's hard to make meaningful suggestions.

**Comment by ephung01** [comment]
> The iframe does something in its onload handler which looks like it navigates to elsewhere (`goToPage()`) this could invalidate the element handle. We discourage use of ElementHandles and recommend Locators instead so that they don't get invalidated if the page navigates/refreshes etc. Can you provide a repro so that we can debug it locally? Otherwise it's hard to make meaningful suggestions.

Sorry for slow response.    Have production release.  I will come back on in two days.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
