### ISSUE TITLE
[BUG] Memory Leak in BrowserContextImpl/Connection - Request and ResponseImpl in .objects HashMap never removed

### ISSUE THREAD

**Issue by lambdaupb** [microsoft/playwright-java#717]
**Context:**
- Playwright Version: 1.16.1
- Operating System: Mac
- Browser: Firefox
- Extra: Long Running BrowserContext

```java



   try (Playwright playwright = Playwright.create()) {
    try (Browser browser = playwright.firefox().launch(new BrowserType.LaunchOptions().setHeadless(false))) {
        try(BrowserContext context = browser.newContext()) {

            // Page instances live a lot shorter lifespan than BrowserContext
            try (Page page = context.newPage()) {
                page.route(Pattern.compile("example\\.com"), Route::abort);
                // a few more routes
                page.onRequestFinished(req -> {
                    LOG.info("RESPONSE {} ({}) {} with {}", req.response().statusText(), req.response().status(), req.response().url(), req.response().allHeaders());
                    // and some more
                    doStuff(req.body());
                });



                // something like
                Response response;
                while(true) {
                    response = page.navigate(...);
                }
            }
        }
    }
}
 
```

**Describe the bug**

The BrowserContextImpl.objects and Connection.objects HashMaps contains every Request and ResponseImpl ever made and it does not seem to be cleared.

The JVM heap grows continually (~3GiB used heap after a few thousand navigations), the node process also grows to ~2GiB resident.

I assume the Request/ResponseImpl instances are coupled to mirrors in the node playwright runtime.

This makes continuous monitoring annoying since one has to destroy and re-create the BrowserContext regularly to avoid crashing.

<img width="785" alt="heap_jvm_playwright_objects_map" src="https://user-images.githubusercontent.com/1890613/142692882-e1874f8b-aa03-4fde-aa42-845276aaff7a.png">
<img width="1259" alt="heap_jvm_playwright_counts" src="https://user-images.githubusercontent.com/1890613/142692873-fb6edde0-b35a-4722-aa71-640ed97b8458.png">

<img width="1123" alt="heap_jvm_playwright" src="https://user-images.githubusercontent.com/1890613/142692885-d3e6ebc1-bc86-4000-8344-09eb663fa255.png">

**Comment by yury-s** [comment]
This is by design, each test is expected to create a new context for isolation purposes so the resources associated with the context are only disposed when the context closes and is GC'ed. In your example you can create a new context instead of creating new page every time in the same context.

Please thumb up this upstream issue if you are interested in changing this behavior: https://github.com/microsoft/playwright/issues/6319
