### ISSUE TITLE
[Question] How to show source in Trace Viewer 1.17.0 ?

### ISSUE THREAD

**Issue by mikomatic** [microsoft/playwright-java#719]
Hello to the Team!

This release notes for 1.17.0 indicate that the "Playwright Test traces now include sources by default".
After updating my projet to 1.17.0, the trace viewer does not show sources tab (when uploading my trace to  https://trace.playwright.dev).

I tried setting env variable PLAYWRIGHT_JAVA_SRC=<project.baseDir>\src\test\java (which I usually do to set source to debug in playwright inspector)

is there something i am missing?

**Comment by yury-s** [comment]
> Hello to the Team!
> 
> This release notes for 1.17.0 indicate that the "Playwright Test traces now include sources by default". After updating my projet to 1.17.0, the trace viewer does not show sources tab (when uploading my trace to https://trace.playwright.dev).
> 
This line was by mistake copied from the release notes for Node.js Playwright, it has to do with [Playwright Test Runner](https://playwright.dev/docs/test-runners#playwright-test) which is only available in Node.js. I removed this line from the Java release notes, sorry for the confusion.

> I tried setting env variable PLAYWRIGHT_JAVA_SRC=<project.baseDir>\src\test\java (which I usually do to set source to debug in playwright inspector)
> 
> is there something i am missing?

Unfortunately, there is no easy way to provide access to the local sources from `trace.playwright.dev`, if you need to see sources it's easier to use command line API to launch the trace viewer.
