### ISSUE TITLE
[BUG] xpath syntax error

### ISSUE THREAD

**Issue by limshuang** [microsoft/playwright-java#720]
![image](https://user-images.githubusercontent.com/24468368/143171244-da647641-3b6a-4424-a6ed-cb2a1e8f9a4e.png)

            <dependency>
                <groupId>com.microsoft.playwright</groupId>
                <artifactId>playwright</artifactId>
                <version>1.17.0</version>
            </dependency>

**Comment by ephung01** [comment]
Base on Playwright [selector document](https://playwright.dev/docs/selectors/#xpath-selectors).   
`Selector starting with // or .. is assumed to be an xpath selector. For example, Playwright converts '//html/body' to 'xpath=//html/body'.`

**Comment by yury-s** [comment]
As suggested above use 
```java
page.querySelector("xpath=/html");
```
to make it explicit that it is an xpath selector rather than css.
