### ISSUE TITLE
[Feature]  It's nice to have recursive querySelector (querySelectorAll)

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#726]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?
can we have recursive querySelector with fluent interface for java
**example:**
`page.querySelector("div[name='parentCssSelector']").querySelector("div[name='childCssSelector']").querySelector("button[name='grandChildCssSelector']").click();`

as for CSS we can only do with element (tag):  "div > div > button" (not sure it can done with css selector attribute)

**Comment by ephung01** [comment]
sorry my bad. it already exists

**Comment by yury-s** [comment]
For the record, we recommend using Locators wherever possible instead of handles, so the recommended way to perform the click is:

```java
page.locator("div[name='parentCssSelector']").locator("div[name='childCssSelector']").locator("button[name='grandChildCssSelector']").click();
```
