### ISSUE TITLE
[Feature] Is there a way to get actual frame Frame/FrameImpl object from FrameLocator? How to get childFrames from FrameLocator

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#730]
Is there a way to get child frames from FrameLocator?
Is there a way to get actual FrameImpl object from FrameLocator?   (asFrame()?)

ex (suggested syntax):
```
page.frameLocator("[name='myFrameName']).asFrame().waitForLoadState(LoadState.DOMCONTENTLOADED)
page.frameLocator("[name='myFrameName']).first().asFrame().waitForLoadState(LoadState.DOMCONTENTLOADED); // make sure get first one if multiple
```

```
page.frameLocator("[name='myFrameName']).childFrames()
// can be done like this?:  page.frameLocator("[name='myFrameName']).locator("iframe,frame") 
```

**Comment by yury-s** [comment]
> Is there a way to get child frames from FrameLocator?

Something like this will give you locator for a child frame:
```java
page.frameLocator("[name='myFrameName']").frameLocaltor(".childFrame")
```

> Is there a way to get actual FrameImpl object from FrameLocator? (asFrame()?)
>

No, the idea is that you should not need one and stick with locators. The Locator already provides methods for performing actions in the page, but looks like you need `waitForLoadState`.

**Comment by yury-s** [comment]
See also relevant discussion in the upstream repo: https://github.com/microsoft/playwright/issues/10191. Can you tell us a bit more about your use case? Perhaps it can be addressed without waitForLoadState similar to the example in the bug.

**Comment by ephung01** [comment]
I need to do more tests to see if other event dispatch from the frame after it's been opened.   I just want to make sure if the frame is completed rendering, because, visually, even when I see a popup screen (just div contain iframe inside), it still take a few seconds to complete.  Depend on the application state, if application just start up, it will take longer time to render (due to backend slow response - class loader).

**Comment by ephung01** [comment]
**FrameLocator** interface does not expose functions that Frame has (such as **_url, title, textContent, evaluate, screenshot, and waitForLoadState_**)

**Comment by yury-s** [comment]
> I need to do more tests to see if other event dispatch from the frame after it's been opened. I just want to make sure if the frame is completed rendering, because, visually, even when I see a popup screen (just div contain iframe inside), it still take a few seconds to complete. Depend on the application state, if application just start up, it will take longer time to render (due to backend slow response - class loader).

Do you expect a particular element to be loaded in the iframe (in that case you should be able to use [`locator.waitFor`](https://playwright.dev/java/docs/api/class-locator/#locator-wait-for) or perform a user action using element locator which will auto-wait) or you want to wait for the frame to load for some other reason?

**Comment by ephung01** [comment]
> Do you expect a particular element to be loaded in the iframe (in that case you should be able to use locator.waitFor or perform a user action using element locator which will auto-wait) or you want to wait for the frame to load for some other reason?

I think it would work if I can use locator waitFor.

If I use **_Locator_** to locate an iframe(or frame) would it be any different from using **_FrameLocator_** to locate the iframe(frame)?
internally, Does Playwright have any distinction?  Base on the code look like FrameLocator and Locator just patch CSS Selector to the object.    What if there are multiple levels iframe and middle one is refresh for some reason (could be timer), would that affect?

ex:
```
FrameLocator parentFame = page.frameLocator("[name='parentFrame']")
FrameLocator childFrame = parentFrame.frameLocator("[name='childFrame']");  // can combine above line into one, but I want to show the different
childFrame.locator("input[name='login']").fill("abc");
childFrame.locator("input[name='password']").fill("def");
.... parent frame has been refresh for some reason....
childFrame.locator("button[name='submit']").click();   // <-- would this get affect by parent frame refresh?
```

**Comment by yury-s** [comment]
> If I use **_Locator_** to locate an iframe(or frame) would it be any different from using **_FrameLocator_** to locate the iframe(frame)?

Yes, Locator will resolve to an IFRAME element whereas you want to dive into the content of the iframe which is what FrameLocator is for.

> internally, Does Playwright have any distinction?

Yes, they are handled differently in the driver.

> Base on the code look like FrameLocator and Locator just patch CSS Selector to the object.

Correct, but the devil is in the details, look for 'control=enter-frame' in the frame locator implementation.

> What if there are multiple levels iframe and middle one is refresh for some reason (could be timer), would that affect?
> 

That's OK, the entire selector is reevaluated every time you perform an action and if the previous frame was refreshed/removed it will resolve to the new one. This is one of the key advantages over the element handles and one of the main reasons we recommend locators over handles.

**Comment by ephung01** [comment]
Hello @yury-s,
       Is there a way to convert **_Locator_** to **_FrameLocator_**?   I want to build something generic in my framework which I can find an element by Locator and detect if it is a frame/iframe then I would like to convert it into FrameLocator.   Is it possible?   Since CSS Selector cannot select self (ex:  myLocator.frameLocator(":self")), I cannot convert it this way.    Can we do **_asFrameLocator()_** in LocatorImpl (new Locator method) and just create mew instance of FrameLocatorImpl - with the same frame and css selector object).

```
public FrameLocatorImpl asFrameLocator() {
    return new FrameLocatorImpl(this.frame, this.selector);
}
```

**Comment by yury-s** [comment]
Use [":scope"](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope) CSS selector, it will work:

```java
myLocator.frameLocator(":scope")
```
