### ISSUE TITLE
Playwrite - SelectOption could not find an element

### ISSUE THREAD

**Issue by ermi1968** [microsoft/playwright-java#731]
I am trying to select an element from a dropdown list. The list has at the moment only one member. 

My java code looks like this.

![Capture](https://user-images.githubusercontent.com/74992923/144510267-5a0fa585-093f-4962-abe9-9a3ef56f89aa.PNG)

....
 page.navigate(url +"/shopingList");
        page.selectOption("id=FooterBtn", "Apple");
        Assertions.assertTrue(page.isVisible("Apple"));

...
 and when i run my test it faild with the error 

com.microsoft.playwright.PlaywrightException: Error {
  message='Error: Element is not a <select> element

waiting for selector "id=FooterBtn"
  selector resolved to visible <dl-dropdown-menu _nghost-igc-c5="" id="FooterBtn">…</dl-dropdown-menu>
  selecting specified option(s)
  Element is not a <select> element
  name='Error
  stack='Error: Error: Element is not a <select> element

Br.

**Comment by ephung01** [comment]
Look like the web application is using javascript framework/library to generate dropdown list instead of using html dropdown list tag (select tag).   This case you have to build a custom script function to handle all dropdown

**Comment by yury-s** [comment]
`selectOption` only works with [HTML Select element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) while your page has some custom implementation of the dropdown list. As mentioned above, you'll need custom code that would select an item in it.
