### ISSUE TITLE
[Question] The Java version is running too slowly

### ISSUE THREAD

**Issue by wasd345** [microsoft/playwright-java#732]
The Java version runs too slowly. How to solve it? It takes about 10 seconds from Startup to operation

**Comment by yury-s** [comment]
First time you launch Playwright it it will [download browsers ](https://playwright.dev/java/docs/browsers/#installing-browsers)for your platform. You can do it manually via [command line](https://playwright.dev/java/docs/cli/#install-browsers). After that on each run it will unpack the driver into a temp directory and launch it from there, this process is usually very fast.
