### ISSUE TITLE
Can playwright Java not be used offline？

### ISSUE THREAD

**Issue by wasd345** [microsoft/playwright-java#733]
Do binary drivers have to be downloaded online every time? Can't you put it locally? For example, my application is deployed on CentOS, and CentOS cannot be connected to the network. How can I solve this problem

**Comment by yury-s** [comment]
The driver is just a maven package and needs to be downloaded just once. You are probably talking about browsers, they also need to be downloaded just once, you can do it ahead of time [using cli](https://playwright.dev/java/docs/cli/#install-browsers), see [this page](https://playwright.dev/java/docs/browsers) for more details on browser management.
