### ISSUE TITLE
[Question] What does the Linux browser look like and how to download it in advance through cli?

### ISSUE THREAD

**Issue by wasd345** [microsoft/playwright-java#735]
What does the Linux browser look like and how to download it in advance through cli?

**Comment by wasd345** [comment]
![image](https://user-images.githubusercontent.com/5779660/144986476-d283402a-4295-4844-a9d7-e39dd8462ad7.png)
![image](https://user-images.githubusercontent.com/5779660/144986686-60904617-c441-4766-8ad6-325129611f43.png)

**Comment by wasd345** [comment]
![image](https://user-images.githubusercontent.com/5779660/144988635-8782c86c-68e7-44f1-88bb-2c39949f40a9.png)

**Comment by yury-s** [comment]
Just run the CLI on the linux machine where you want to run the Playwright. It only downloads browsers for the current platform. E.g. if you run linux in docker, you can donwload them when building the image. Why would you need linux binaries on windows?

**Comment by wasd345** [comment]
Because my Linux server can't access the Internet, I want to download it first and then upload it (can I do this? I can run the code on a Linux system that can connect to the Internet, download the browser, and then find a way to get the downloaded browser to Linux that can't connect to the Internet)

**Comment by yury-s** [comment]
See [this page](https://playwright.dev/java/docs/browsers#managing-browser-binaries) for the ways how to configure alternative browser locations etc. You can run playwright locally on a connected linux machine to make it download browsers to `PLAYWRIGHT_BROWSERS_PATH` and then copy that directory to the other machine, just make sure to point `PLAYWRIGHT_BROWSERS_PATH` to the location where you copied the browsers to.
