### ISSUE TITLE
[REGRESSION]: 

### ISSUE THREAD

**Issue by akashshrimali** [microsoft/playwright-java#739]
Context:

GOOD Playwright Version: [what Playwright version worked nicely?] 1.13.0
BAD Playwright Version: [what Playwright version doesn't work any more?] 1.13.0 and 1.17.0
Operating System: [e.g. Windows, Linux or Mac] Linux
Extra: [any specific details about your environment]
Code Snippet

```java
	try (Playwright playwright = Playwright.create()) {
	}
```
Giving error :
```
com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:202)
at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:115)
at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:82)
at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:183)
at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:45)
at com.microsoft.playwright.Playwright.create(Playwright.java:92)
at com.microsoft.playwright.Playwright.create(Playwright.java:96)
```
Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      // ...
    }
  }
}
```
Describe the bug
com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.

Add any other details about the problem here.

**Comment by yury-s** [comment]
Do you run the example via Maven or you use a different deployment method? Try running with `DEBUG=pw:browser,pw:channel` and see what's in the logs.

**Comment by akashshrimali** [comment]
Currently i am running this with docker container. 

Linux distribution is Ubuntu 20.04.2 LTS (GNU/Linux 5.11.0-1022-aws aarch64)

**Comment by yury-s** [comment]
Can you share a full repro or at least your Dockerfile and the commands you use to run the test?

**Comment by akashshrimali** [comment]
yes it an AWS image, i am using following commands to build : 
to run the image: docker run --network="host" -p 5004:5004 tenant-service-local  
image name is : tenant-service-local 
to build the image : sudo docker build -t tenant-service-local:01 . 
[Dockerfile.txt](https://github.com/microsoft/playwright-java/files/7690781/Dockerfile.txt)

ps : i have attached docker file in .txt due to file type not support issue in github

**Comment by yury-s** [comment]
Try with our official **java** image(you are using nodejs one): [mcr.microsoft.com/playwright/java:focal](https://hub.docker.com/_/microsoft-playwright-java). Also you are launching just a jar file (not via a maven), the problem is likely in how you build that and how the driver packaged is deployed but it's hard to tell more without seeing the source. Could you create a minimal repro (including pom files and build instructions) where it doesn't work?

**Comment by akashshrimali** [comment]
I have tried this it's not working  either with 

mcr.microsoft.com/playwright/java:focal

**Comment by akashshrimali** [comment]
It works in my local on spring boot server but it's not working on docker on my local. Seems to be an issue with docker where some properties is required.

**Comment by yury-s** [comment]
The issue might be related to https://github.com/microsoft/playwright-java/issues/346 but symptoms are different.

It likely has something to do with the spring boot loader (it loads resources differently than when running with Maven). We'll need a repro that we can run locally to act on this report (should be doable with docker). Please file a new one and link to this issue when you have a repro.
