### ISSUE TITLE
My Linux server can't access the Internet. How can I download the browser in advance?

### ISSUE THREAD

**Issue by wasd345** [microsoft/playwright-java#741]
Because my Linux server can't access the Internet, I want to download it first and then upload it (can I do this? I can run the code on a Linux system that can connect to the Internet, download the browser, and then find a way to get the downloaded browser to Linux that can't connect to the Internet)

**Comment by yury-s** [comment]
See [this page](https://playwright.dev/java/docs/browsers#managing-browser-binaries) for the ways how to configure alternative browser locations etc. You can run playwright locally on a connected linux machine to make it download browsers to `PLAYWRIGHT_BROWSERS_PATH` and then copy that directory to the other machine, just make sure to point `PLAYWRIGHT_BROWSERS_PATH` to the location where you copied the browsers to.

**Comment by wasd345** [comment]
OK, I see. Thank you very much
