### ISSUE TITLE
[Question] Can we generate accessible/tagged PDF using  playwright?

### ISSUE THREAD

**Issue by abhinav-kipper** [microsoft/playwright-java#745]
Hi,

Chrome has functionality to generate accessible PDFs when printing a webpage Ref - https://blog.chromium.org/2020/07/using-chrome-to-generate-more.html .

Do we have this capability with playwright as well? i.e. Can page.pdf() option of playwright generate tagged pdf?

**Comment by yury-s** [comment]
From the blog post above: "This feature also works with Chrome Headless when you use both the --print-to-pdf and --export-tagged-pdf flags.", so something like this should enable tags:

```java
browserType.launch(new BrowserType.LaunchOptions().setArgs(asList("--export-tagged-pdf")));
```

**Comment by abhinav-kipper** [comment]
Thanks @yury-s .

> Do you think it's worth enabling by default or more slim pdfs would be preferred?
I would say tagged pdfs (as they are more accessible and rich). In fact, chrome browser also by default prints tagged PDFs (in headed mode)
