### ISSUE TITLE
[Question]  How to set Chrome/Chromium/Edge driver "Experimental Options" and "Log Preference Option"

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#746]
How to set Chrome/Chromium/Edge driver "Experimental" and "Log Preference" Options
example: 
- same-site-by-default-cookies=true
- enableNetwork=true
- profile.content_settings.exceptions.clipboard.*.setting=1
- shared-clipboard-ui@1
- file-handling-api@1
... etc....

**Comment by yury-s** [comment]
You can pass command line arguments for some of the features. [This list](https://github.com/microsoft/playwright/blob/921aa02ce4d5e6deb73d913265683598671709f6/packages/playwright-core/src/server/chromium/chromium.ts#L295-L323) contains flags that Playwright passes to Chromium by default, it can be extended via [setArgs](https://playwright.dev/java/docs/next/api/class-browsertype#browser-type-launch-option-args), there is also [setIgnoreDefaultArgs](https://playwright.dev/java/docs/next/api/class-browsertype#browser-type-launch-option-ignore-default-args) to drop some of the arguments if needed.

**Comment by ephung01** [comment]
Hello @yury-s ,
     Circle back to issue [close browser hang (issue# 347)](https://github.com/microsoft/playwright-java/issues/347).   I found out the caused is **_browser.close()_** cannot closed because there is background browser open (daemon) when playwright launch browser.   You've implemented the message timeout 30 seconds to kill the hang process.   This hidden browser is set by the **Default Option** "--no-startup-windows".   If I do setIgnoreDefaultArgs to ignore "--no-startup-windows" , then I see (visually) an additional browser (chrome) popup with default home page, but this help the **_browser.close()_** terminate smoothly.   Do you know why?

Error look like this:  look like it tried to connect to outside (probably looking for update) and got block by the firewall

`2021-12-16T22:44:19.194Z pw:browser [pid=31232][err] [31232:33768:1216/174419.194:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -100`

**Comment by yury-s** [comment]
Please file a separate bug for this problem as it has little to do with the original question about options.

> I found out the caused of **_browser.close()_** cannot closed, it's because there is background browser open (daemon) when playwright launch browser.

Sounds like this is the browser that playwright launches. Normally we launch Chromium with --no-startup-window argument to keep the process alive until first page is created via Playwright API. Without the flag the browser process would exit immediately. Or you say that there is second browser process which you didn't launch?

> You've implemented the message timeout 30 seconds to kill the hang process. This hidden browser is set by the **Default Option** "--no-startup-windows". If I do setIgnoreDefaultArgs to ignore "--no-startup-windows" , then I see (visually) an additional browser (chrome) popup with default home page, but this help the **_browser.close()_** terminate smoothly. Do you know why?

Do I understand correctly that you run in headful mode and when "--no-startup-windows" is removed `browser.close()` works as expected but when the flag is present `browser.close()` will hang? or what is the behavior, at this point I've lost track of what your scenario is?
