### ISSUE TITLE
[Question] Related to Api interception and html reporting

### ISSUE THREAD

**Issue by royanindya-code** [microsoft/playwright-java#751]
Do we have any timeline to include html reporting and api interception in playwright-java like we have for node.js ? Would like to know if we have already because I could not find in the documentation.

**Comment by yury-s** [comment]
Assuming you meant API testing, those are coming in the next release and are already available in the snapshot versions, see [APIRequest](https://playwright.dev/java/docs/next/api/class-apirequest). We'll add a guide for it to java too.

As for html report, there are no current plans to bring it to other languages. It is a part of Playwright Test runner which is available only in nodejs version.

**Comment by royanindya-code** [comment]
Hi @yury-s ,

Thanks for your comment. I have seen demo video for the latest playwright release in node.js and html report looks very promising to me since the stack trace is available for failed tests. It would be great if we could have in java too. And I believe api interception will be available in the future release.

**Comment by yury-s** [comment]
> Thanks for your comment. I have seen demo video for the latest playwright release in node.js and html report looks very promising to me since the stack trace is available for failed tests.

We're going to include stack traces with sources into tracing, this should help with debugging. But html report itself is not being ported to the other languages at the moment.
