### ISSUE TITLE
[Question] how to install ffmpeg in playwright java

### ISSUE THREAD

**Issue by chaowenGUO** [microsoft/playwright-java#753]
From https://github.com/microsoft/playwright-java/issues/571: 

I try gradle.build:
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.microsoft.playwright:playwright:latest.release'
}

task copyDependencies(type: Copy) {
    from configurations.default into 'copyDependencies'
}

task playwright(type: JavaExec) {
    mainClass = 'com.microsoft.playwright.CLI'
    classpath sourceSets.main.runtimeClasspath
    args 'install'
}

it works and show
> Task :copyDependencies
The default configuration has been deprecated for resolution. This will fail with an error in Gradle 8.0. Please resolve the compileClasspath or runtimeClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

BUILD SUCCESSFUL in 13s
1 actionable task: 1 executed
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :playwright
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
Playwright build of chromium v939194 downloaded to /home/runner/.cache/ms-playwright/chromium-939194
Playwright build of ffmpeg v1006 downloaded to /home/runner/.cache/ms-playwright/ffmpeg-1006
Playwright build of firefox v1304 downloaded to /home/runner/.cache/ms-playwright/firefox-1304
Playwright build of webkit v1578 downloaded to /home/runner/.cache/ms-playwright/webkit-1578

But I just want Playwright build of ffmpeg v1006 downloaded to /home/runner/.cache/ms-playwright/ffmpeg-1006, I do not need others
So, I try gradle.build
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.microsoft.playwright:playwright:latest.release'
}

task copyDependencies(type: Copy) {
    from configurations.default into 'copyDependencies'
}

task playwright(type: JavaExec) {
    mainClass = 'com.microsoft.playwright.CLI'
    classpath sourceSets.main.runtimeClasspath
    args 'install ffmpeg'
}
Not work and show
> Task :copyDependencies
The default configuration has been deprecated for resolution. This will fail with an error in Gradle 8.0. Please resolve the compileClasspath or runtimeClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

BUILD SUCCESSFUL in 12s
1 actionable task: 1 executed
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

error: unknown command 'install ffmpeg'
> Task :playwright FAILED
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set

1 actionable task: 1 executed
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':playwright'.
> Process 'command '/opt/hostedtoolcache/Java_Zulu_jdk/17.0.1-12/x64/bin/java'' finished with non-zero exit value 1

Also I try install-deps chromium but still not work show
error: unknown command 'install-deps chromium'

Please help

**Comment by yury-s** [comment]
To do it with maven create `pom.xml` with the following content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>examples</artifactId>
  <version>1.18.0-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
      <version>1.17.0</version>
    </dependency>
  </dependencies>
</project>
```

Then run `mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install ffmpeg"` in the same directory.

You need to ask someone familiar with gradle how to express this in gradle. We currently don't have official support for it.

**Comment by chaowenGUO** [comment]
Thank you, I am not an expert on gradle or maven, I just want a quick fix so I can continue my java project.
