### ISSUE TITLE
[Feature] playwright java should impletement CDPSession

### ISSUE THREAD

**Issue by chaowenGUO** [microsoft/playwright-java#756]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

playwright nodejs and playwright python support browserContext.newCDPSession(page) and browser_context.new_cdp_session(page), but I can not find the corresponding stuff in playwright java. So playwright java should impletement CDPSession.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
