### ISSUE TITLE
[BUG] Why does the page scroll back and forth when the element is clicked?

### ISSUE THREAD

**Issue by limshuang** [microsoft/playwright-java#757]

**Comment by limshuang** [comment]
Actually the elements can be found.




LOG:

etrying click action, attempt #41
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (509,629.67)
  <input aria-label="全all" type="checkbox" aria-checked="fa…/> from <div aria-hidden="true" class="next-table next-table-…>…</div> subtree intercepts pointer events
retrying click action, attempt #42
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (509,442.67)
  <input aria-label="all" type="checkbox" aria-checked="fa…/> from <div aria-hidden="true" class="next-table next-table-…>…</div> subtree intercepts pointer events
retrying click action, attempt #43
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling

**Comment by yury-s** [comment]
Is the issue that the element cannot be clicked? Please provide a repro (playwright code and the page where it fails), otherwise we can only guess what's going on.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
