### ISSUE TITLE
[Question]Does the playwright support multi-thread operations?

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#758]
I want to use the Java thread pool to operate multiple page objects in a browser instance enabled through PlayWright to perform different operations. Can PlayWright support this function?

**Comment by yury-s** [comment]
No, playwright API is not thread-safe, see [this doc](https://playwright.dev/java/docs/multithreading). You'll basically need to ensure that each playwright instance is accessed from a signle thread at any given time.
