### ISSUE TITLE
[Question] `window.playwright` object without `page.pause()` call

### ISSUE THREAD

**Issue by beegotsy** [microsoft/playwright-java#761]
Hello, sorry to bother you again,

I was trying to use the injected playwright object (I think it's called [ConsoleAPI](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/supplements/injected/consoleApi.ts)) in a [frame.evaluate(...)](https://playwright.dev/java/docs/api/class-frame#frame-evaluate) call, but it works only if I first call the [page.pause() method](https://playwright.dev/docs/api/class-page#page-pause), which opens the inspector.

For example, with this minimal code:
```java
// code is an input string and there are reason to bypass the Java API and fetch elements with the playwright.$ selector in an evaluate call
String code = "playwright.$(`:text('Example')`"; // minimal example to reproduce the issue
frame.evaluate(code); // com.microsoft.playwright.impl.DriverException: Error { message='Evaluation failed: ReferenceError: playwright is not defined at ... }

String code = "playwright.$(`:text('Example')`";
frame.page().pause(); // opens the inspector and inject the window.playwright object
frame.evaluate(code); // it works
```

Is there a way to use the injected playwright object without a pause AND in headless mode?
I couldn't find where the Java code inject the playwright object in the window when calling the [page.pause() method](https://playwright.dev/docs/api/class-page#page-pause).

Thank you all for your patience and your amazing work for this library

**Comment by beegotsy** [comment]
A solution is to _save as file_ the compiled source code of `injectedScript` and `ConsoleAPI` and then importing them with the [browserContext.addInitScript](https://playwright.dev/docs/api/class-browsercontext#browser-context-add-init-script).

To find the compiled source code of those object you can use the Chrome inspector to see what is the `[[FunctionLocation]]` of `playwright.$`; then place a breakpoint on the function to see where is the `[[FunctionLocation]]` of a function of `this._injectedScript.`; then save both the opened file and you have your compiled source code.

I don't know if in the future there will be an easier way to include those scripts, but this is a doable workaround.

Happy Holidays (if any)

**Comment by yury-s** [comment]
`playwright` object is only injected in [debug mode](https://playwright.dev/java/docs/debug#run-in-debug-mode). If you need to make a call from the page script back to playwright code, you can inject your own functions in the page context via [exposeBinding](https://playwright.dev/java/docs/api/class-page#page-expose-binding) or [exposeFunction](https://playwright.dev/java/docs/api/class-page#page-expose-function) which will trigger java callback when the function is called in the page. I'd discourage you from copying the internal scripts and injecting them manually into the page as their behavior may change any time.
