### ISSUE TITLE
[BUG] No resource with given identifier when calling response.body()  in onResponse

### ISSUE THREAD

**Issue by robertvanloenhout** [microsoft/playwright-java#762]
I'm trying to save all the requests and responses when navigating to a page. I navigate by doing:

```java
var browserContext = Playwright.create().chromium().launch().newContext();
var page = browserContext.newPage();
page.onResponse(this::handleResponse);
page.navigate(url);
```

When the handleResponse method accesses the body, I sometimes get the following error:

```
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Protocol error (Network.getResponseBody): No resource with given identifier found
  name='Error
  stack='Error: Protocol error (Network.getResponseBody): No resource with given identifier found
```

So this happens when I call response.body(), even when response.ok() returns true. The resource can be accessed fine when I enter the url of that response in my browser.
The url's of responses that throw that exception seems rather random.

**Context:**
- Playwright Version: 1.17.2
- Operating System: Windows
- Browser: Chromium

**Comment by yury-s** [comment]
Network resource data including response body is [clean up](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/inspector_network_agent.cc;drc=73a504d9c4206b06598fc62da68407a4a6b703b4;l=2103) in Chromium upon navigation. I.e. once the page [committed](https://playwright.dev/java/docs/navigations#navigation-lifecycle) navigation to a new URL all network data from the previous navigation is deleted from the browser and won't be accessible to the client. If you need to access the response body you should do it before next navigation in the page, one way to achieve that is to [intercept](https://playwright.dev/java/docs/api/class-route) the navigation request and ensure that all body data is read before the request is [resumed](https://playwright.dev/java/docs/api/class-route#route-continue).
