### ISSUE TITLE
[Question] APIRequestContext mentioned in docs for 1.17.2 but actually page().request() or context().request() is absent.

### ISSUE THREAD

**Issue by DanteGrek** [microsoft/playwright-java#765]
https://playwright.dev/java/docs/api/class-apirequestcontex
<img width="1636" alt="Screenshot 2022-01-07 at 21 49 50" src="https://user-images.githubusercontent.com/13424683/148599256-8f763e05-9314-4d1e-99e7-493e035a7d85.png">
<img width="727" alt="Screenshot 2022-01-07 at 21 50 40" src="https://user-images.githubusercontent.com/13424683/148599273-769a444c-ac61-4cdf-9b32-37137b9fcb58.png">
t

**Comment by yury-s** [comment]
I don't see it at that url:

![image](https://user-images.githubusercontent.com/9798949/148603063-6e22d869-b914-4fa6-8858-e4c18a42a257.png)

Only at https://playwright.dev/docs/next/api/class-apirequestcontext which is `next` version where it is being added.

**Comment by yury-s** [comment]
> I don't see it at that url:

I can actually navigate to it from Page.request docs.

It was indeed by mistake included in java documentation as well as nodejs docs for 1.17. The API is coming to java in 1.18 which is slated to be released soon (next few weeks), so I'm closing this bug.
