### ISSUE TITLE
[BUG] Strict mode does not work for focus.

### ISSUE THREAD

**Issue by DanteGrek** [microsoft/playwright-java#775]
**Context:**
- Playwright Version: 1.17.2
- Operating System: [Mac]
- Browser: [Chromium, Firefox, WebKit]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
public static void main(String[] args) {
        Browser browser = Playwright.create().chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
        BrowserContext context = browser.newContext();
        Page page = context.newPage();
        page.navigate("https://dantegrek.github.io/testautomation-playground/forms.html");
        page.focus("input", new Page.FocusOptions().setStrict(true));
    }
```

**Describe the bug**

Due to this doc page: https://playwright.dev/java/docs/api/class-page#page-focus. Last row suppose to throw exception. But code in main put focus on first element instead.

**Comment by yury-s** [comment]
It is already fixed in `1.18.0-SNAPSHOT` and will make it to `1.18` release which is slated for the next week or so.
