### ISSUE TITLE
[BUG] Issue when lunch firefox in github actions.

### ISSUE THREAD

**Issue by DanteGrek** [microsoft/playwright-java#776]
**Context:**
- Playwright Version: [17.2]
- Operating System: [Mac, Windows]
- Browser: [Firefox]

**Code Snippet**

[Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```
com.microsoft.playwright.TimeoutError: 
Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /Users/runner/Library/Caches/ms-playwright/firefox-1304/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -headless -profile /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/playwright_firefoxdev_profile-Qyckeo -juggler-pipe -silent
<launched> pid=1638
[pid=1638][err] *** You are running in headless mode.
[pid=1638][out] 
[pid=1638][out] Juggler listening to the pipe
```
links on to failed build.
https://github.com/DanteGrek/jPlay/runs/4846684698?check_suite_focus=true
https://github.com/DanteGrek/jPlay/pull/16/checks?check_run_id=4852916495

**Comment by yury-s** [comment]
> https://github.com/DanteGrek/jPlay/pull/16/checks?check_run_id=4852916495

Looks like there is not enough RAM on the machine to run firefox and it is just OOMing (`Hit MOZ_CRASH([unhandlable oom] Failed to allocate slots while tenuring.) at D:/firefox/js/src/vm/JSContext.cpp:1240`)

**Comment by yury-s** [comment]
Closing as there is not much we can do about it on our end.

**Comment by DanteGrek** [comment]
SOLVED!

added reuseForks false to maven-surefire-plugin

```
<plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M5</version>
                    <configuration>
                        <forkCount>1</forkCount>
                        <reuseForks>false</reuseForks>
                    </configuration>
                </plugin>
```
