### ISSUE TITLE
[BUG] Empty file written as result of `download.saveAs(...)`

### ISSUE THREAD

**Issue by jartysiewicz** [microsoft/playwright-java#789]
**Context:**
- Playwright Version: 1.17.2
- Operating System: Linux
- Browser: Chromium
- Extra:

**Code Snippet**

```java
import java.nio.file.Paths;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.Playwright;

public class ExampleReproducible {
    public static void main(String[] args) {
        try (var playwright = Playwright.create();
             var browser = playwright.chromium().connectOverCDP("ws://127.0.0.1:3333/devtools/browser/5cca67e4-1efd-4c81-a1ab-7116812db37f");
             var context = browser.newContext(new Browser.NewContextOptions().setAcceptDownloads(true));
             var page = context.newPage()) {

            page.navigate("https://search.maven.org/artifact/org.clojure/clojure/1.11.0-alpha4/jar");
            page.waitForSelector("text=Downloads").click();
            var jar = page.waitForSelector("text=jar");

            var downloads = page.waitForDownload(() -> {
                jar.click();
            });

            var p = Paths.get(downloads.suggestedFilename());
            downloads.saveAs(p);
        }  }
}

```

Download looks like successful but **saved file is 0 size**. The file name (`downloads.suggestedFilename()`) is correct.
When I try to get `InputStream` and read it effect is quite similar, I receive 0 bytes.

The reason I need it to work thought `connectOverCDP` it that I want to use this with `browserless/chrome` container  and didn't find the way to connect it via `connect`.

thanks in advance!

Jan

**Comment by yury-s** [comment]
I cannot reproduce it locally. What Chromium version are you connecting to?

**Comment by jartysiewicz** [comment]
@yury-s 

```
$ chromium --version
Chromium 97.0.4692.99 snap
```

The same efect is when I try to use it with `browserless/chrome`. 
```
docker run -e "DEFAULT_HEADLESS=false" -p 3000:3000  --restart always  --name browserless browserless/chrome
```

and then use `ws://localhost:3000` to connect

**Comment by yury-s** [comment]
> The reason I need it to work thought connectOverCDP it that I want to use this with browserless/chrome container and didn't find the way to connect it via connect.

Does it reproduce without connect?

> 97.0.4692.99

v1.17.2 comes with `Chromium 98.0.4695.0`, can you try it with the browser that comes with Playwright please? If it reproduces, could you run it with `DEBUG=pw:protocol` and shared the log?

> The same efect is when I try to use it with `browserless/chrome`.

Is it reproducible with local chromium that comes with playwright 1.17.2 (`~/.cache/ms-playwright/chromium-939194/chrome-linux/chrome --user-data-dir=/tmp/pw-test --remote-debugging-port=8192 --headless`) ?

**Comment by jartysiewicz** [comment]
@yury-s 

It **doesn't** reproduce (in other words: downloads is successful) with:
1. system Chromium (Chromium 97.0.4692.99 snap) and **no** connectOverCDP
2. Chromium bundled with Playwright

[Here is a log](https://github.com/microsoft/playwright-java/files/7958233/pw.log) from reproducing a bug with system chrominum

**Comment by yury-s** [comment]
> [Here is a log](https://github.com/microsoft/playwright-java/files/7958233/pw.log) from reproducing a bug with system chrominum

The log looks normal. There is 
```
 2022-01-28T11:22:09.049Z pw:protocol ◀ RECV {"method":"Browser.downloadProgress","params":{"guid":"a3efb45f-a815-4aae-aaac-5043747e8488","totalBytes":4101886,"receivedBytes":4101886,"state":"completed"}}
```
which means the file was completely downloaded. Can you please run the failing test with `DEBUG=pw:channel`?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
