### ISSUE TITLE
[Question] Timeout issues with Playwright

### ISSUE THREAD

**Issue by aarushiag** [microsoft/playwright-java#792]
Hi, we have been using Playwright library (version 1.12.1) for performing HTML to PDF conversions. We have a multithreaded environment (threads = 2), however we use create different objects (BrowserContext, Browser, Page) for each thread as suggested here - https://playwright.dev/java/docs/multithreading. Since few days we have started seeing following timeouts exceptions during launch of chromium browser (randomly on some URLs) - 

`"Playwright Exception thrown : Error {\n  message='Timeout 30000ms exceeded.\n=========================== logs ===========================\n<launching> z:\\sharedcloud\\html2pdfservice\\pw-browsers\\chromium-888113\\chrome-win\\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading,GlobalMediaControls --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=C:\\Windows\\TEMP\\playwright_chromiumdev_profile-KXpEBH --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --proxy-server=http://sc-prod-ue1-perm-trident.adobesc.com:8080 --proxy-bypass-list=<-loopback>;localhost --disable-web-security --no-startup-window\n<launched> pid=164\n============================================================\nNote: use DEBUG=pw:api environment variable to capture Playwright logs.\n  name='TimeoutError\n  stack='TimeoutError: Timeout 30000ms exceeded.\n=========================== logs ===========================\n<launching> z:\\sharedcloud\\html2pdfservice\\pw-browsers\\chromium-888113\\chrome-win\\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading,GlobalMediaControls --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=C:\\Windows\\TEMP\\playwright_chromiumdev_profile-KXpEBH --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --proxy-server=http://sc-prod-ue1-perm-trident.adobesc.com:8080 --proxy-bypass-list=<-loopback>;localhost --disable-web-security --no-startup-window\n<launched> pid=164\n============================================================\nNote: use DEBUG=pw:api environment variable to capture Playwright logs.\n    at ProgressController.run (C:\\Windows\\Temp\\playwright-java-7995547068693129745\\package\\lib\\server\\progress.js:72:30)\n    at Chromium.launch (C:\\Windows\\Temp\\playwright-java-7995547068693129745\\package\\lib\\server\\browserType.js:75:42)\n    at BrowserTypeDispatcher.launch (C:\\Windows\\Temp\\playwright-java-7995547068693129745\\package\\lib\\dispatchers\\browserTypeDispatcher.js:30:44)\n    at DispatcherConnection.dispatch (C:\\Windows\\Temp\\playwright-java-7995547068693129745\\package\\lib\\dispatchers\\dispatcher.js:232:46)\n}"`

**Another type of error that can be seen** - 

`"Playwright Exception thrown : Error {\n  message='Timeout 30000ms exceeded.\n  name='TimeoutError\n  stack='TimeoutError: Timeout 30000ms exceeded.\n    at ProgressController.run (C:\\Windows\\Temp\\playwright-java-6077831003667194595\\package\\lib\\server\\progress.js:72:30)\n    at Chromium.launch (C:\\Windows\\Temp\\playwright-java-6077831003667194595\\package\\lib\\server\\browserType.js:75:42)\n    at BrowserTypeDispatcher.launch (C:\\Windows\\Temp\\playwright-java-6077831003667194595\\package\\lib\\dispatchers\\browserTypeDispatcher.js:30:44)\n    at DispatcherConnection.dispatch (C:\\Windows\\Temp\\playwright-java-6077831003667194595\\package\\lib\\dispatchers\\dispatcher.js:232:46)\n}"`

**NOTE:- These errors are not particular to any URL / HTML**

_Could you suggest what can be the possible cause for these timeouts ?_

**Comment by yury-s** [comment]
Try running with `DEBUG=pw:browser` environment variable to see if the is a browser crash or some other error printed out to the console. It's hard to tell why it would suddenly stop launching, most likely something has changed in your environment.

1.12.1 is very old, can you check if the problem is reproducible with the latest playwright (1.18.0) ?

**Comment by aarushiag** [comment]
Thanks a lot @yury-s  for your suggestions. We'll try updating the playwright version. Between, could you suggest as to how we can save the logs on console after setting` DEBUG=pw:browser` in a file ? 

We want to access the logs on the server and the console logs aren't visible on the server.

**Comment by yury-s** [comment]
> BTW, could you suggest as to **how we can save the logs on console after setting` DEBUG=pw:browser` in a file **

If you run your tests with maven something like [redirectTestOutputToFile](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#redirectTestOutputToFile) can help.



> Also should the variable value be **`DEBUG=pw:browser` or ` DEBUG=pw:api`** since we didn't get any logs with `DEBUG=pw:browser` ?

You can set both (`DEBUG=pw:browser,pw:api`), but I'm particularly interested in pw:browser because if will capture potential crash logs  of the browser.

**Comment by yury-s** [comment]
@aarushiag what windows version are you on?

**Comment by aarushiag** [comment]
@yury-s we are on Windows Server 2016. Also, we updated the playwright to the latest version and still seeing the issues.
