### ISSUE TITLE
[Question] Configure Playwright CLI to download from artifactory

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright-java#793]
Hi all,

first want to say that Playwright is something really great, thank you for that.

My issues comes from the process of downloading all those browsers. 
A lot of people like me are working from a company that has firewalls and other stuff that can block the downloading of those browsers.

Currenttly I have a maven project and I am trying to run version 1.18.0

When executing the the following command:
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

I get error message: 

[Info] --- exec-maven-plugin:3.0.0:java (default cli)
java.lang.RuntimeException: Failed to create driver 
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: -1073741511
at com.microsoft.playwright.impl.Driver.ensureDriverInstalled (Driver.java:54)

I pretty sure that this is because it is not able to download the browsers due to firewall. 

In the company we have artifactory repository and I saw that there is a env variable PLAYWRIGHT_DOWNLOAD_HOST that I can use to tell playwright to download from there. But the problem is that I cannot just write the IP address of this artifactory repository. In order to access it I have to configure a whole bunch of stuff (auth key, email, password, proxy, etc).

I found a way to intall the browser via the npm by running the command: 
npm i -D playwright 

But before that I had to configure a .npmrc file (to authenticate myself) and tell the npm to download the browsers from the company artifactory.

The problems is that maven and java are not seeing the browsers that I installed with the help of the npm, so I am not able to run my tests. 

Do you know a way how I can configure the java playwright cli to download the browsers via the company artifactory by creating a config file with all my authentications (similar to a .npmrc file) ?

PS: ---------------------------------------
If I run the java command on version 1.17.0 it gives me the following error: 
Failed to install browsers
Error: Failed to download chrome vXXXX, cause by
Error: connect ETIMEDOUT 13.107.213.45:443
 at TCPConnectWrap.afterConnect [as oncomlete] (net.js:1148:16
 
 
At least it is saying which version of the browser is trying to download, on 1.18.0 I even dont get this info.

**Comment by yury-s** [comment]
> I get error message:
> 
> [Info] --- exec-maven-plugin:3.0.0:java (default cli) java.lang.RuntimeException: Failed to create driver Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: -1073741511 at com.microsoft.playwright.impl.Driver.ensureDriverInstalled (Driver.java:54)
> 
> I pretty sure that this is because it is not able to download the browsers due to firewall.
>

Try running with `DEBUG=pw:install` to see more info about what's being installed and where.
 
> In the company we have artifactory repository and I saw that there is a env variable PLAYWRIGHT_DOWNLOAD_HOST that I can use to tell playwright to download from there. But the problem is that I cannot just write the IP address of this artifactory repository. In order to access it I have to configure a whole bunch of stuff (auth key, email, password, proxy, etc).
> 
Perhaps you can connect via proxy, see the possible options on this page: https://playwright.dev/java/docs/browsers#install-behind-a-firewall-or-a-proxy We don't support custom authentication with PLAYWRIGHT_DOWNLOAD_HOST.

> I found a way to intall the browser via the npm by running the command: npm i -D playwright
> 
> But before that I had to configure a .npmrc file (to authenticate myself) and tell the npm to download the browsers from the company artifactory.
> 
> The problems is that maven and java are not seeing the browsers that I installed with the help of the npm, so I am not able to run my tests.

That's likely because you use different version of playwright in java and node. Try running it with `DEBUG=pw:install` and compare downloaded browser versions with java. The location should be the same if playwright versions match.

> 
> Do you know a way how I can configure the java playwright cli to download the browsers via the company artifactory by creating a config file with all my authentications (similar to a .npmrc file) ?
> 

There is no special configuration for that except for what's described at https://playwright.dev/java/docs/browsers.

> PS: --------------------------------------- If I run the java command on version 1.17.0 it gives me the following error: Failed to install browsers Error: Failed to download chrome vXXXX, cause by Error: connect ETIMEDOUT 13.107.213.45:443 at TCPConnectWrap.afterConnect [as oncomlete] (net.js:1148:16
> 
> At least it is saying which version of the browser is trying to download, on 1.18.0 I even dont get this info.

We might have changed the output a bit, sounds like we should bring the version back.

**Comment by NikkTod** [comment]
Hi @yury-s ,

I tried running the command with DEBUG=pw:install set, but unfortunatelly there was no additional information on the error. 

Would you be able to tell me which browser versions does playwright in java searches in version 1.18.0 ? 
Is there any link with this kind of information?

For version version 1.17.0 , the playwright in java is searching for those browsers:
chromium-939194
ffmpeg-1006
firefox-1304
webkit-1578

My idea is to install the browsers through node js and change the version numbers to the ones that java wants, that is why I need this information for 1.18.0

It will be very helpful if you bring back the output, which says the browser version that it searches, or at least to provide a some link with this information.

Thank you for your help!

**Comment by yury-s** [comment]
> I tried running the command with DEBUG=pw:install set, but unfortunatelly there was no additional information on the error.

Perhaps something is broken before the download, you should see output like this:

![image](https://user-images.githubusercontent.com/9798949/151402961-d7fb892c-efa3-4c6e-aaf5-cde66cedfc38.png)

Can you share full log including the command and exception with the call stack ?

> Would you be able to tell me which browser versions does playwright in java searches in version 1.18.0 ?
> Is there any link with this kind of information?

https://github.com/microsoft/playwright/blob/release-1.18/packages/playwright-core/browsers.json (note 1.18 branch) contains all browser versions used in 1.18.* by both java and nodejs versions.

> My idea is to install the browsers through node js and change the version numbers to the ones that java wants,

This will make further debugging much harder. The browsers change from one version to another and oftentimes playwright relies on the features that are only available in newer versions, I'd discourage you from renaming the directories. You can specify [`executablePath`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch-option-executable-path) pointing to a custom browser location if you want to.

**Comment by NikkTod** [comment]
Hi @yury-s ,

seems that something is broken even before download.

As the company has very strict rules I am not able to copy and share the logs as text, but I was able to made a few screenshots.

Steps on version 1.18.0:
1. set DEBUG=pw:install
2. mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

![1](https://user-images.githubusercontent.com/94455079/151415113-db0d7800-8741-4abb-99c2-b450f5225ba2.png)
![2](https://user-images.githubusercontent.com/94455079/151415148-db44efc2-1341-4654-8f40-212075acfc52.png)

Steps on version 1.17.0 (here all is good and I dont have this exception)
![3](https://user-images.githubusercontent.com/94455079/151415312-525af930-b61c-496b-98b4-e6604078e9df.png)

**Comment by yury-s** [comment]
Thanks for sharing the screenshots, not much new info unfortunately :( Some debugging thoughts: -1073741511 is 0xC0000139 which is according to [this page](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55): `{Entry Point Not Found} The procedure entry point %hs could not be located in the dynamic link library %hs.` Which apparently indicates that node.js process (which runs playwright driver) cannot fails to load a dll. What Windows version are you on?

**Comment by NikkTod** [comment]
Hi @yury-s ,

I was afraid you would ask this :) Unfortunatelly our VMs are with Windows 7 and I have installed NodeJs version 12.16.1

There is also a warning for missing libraries: api-ms-win-core-winrt-error-l1-1-0.dll , but I am able to run tests under v1.17.0.

But It seems that for version 1.18.0 I am out of luck.

**Comment by yury-s** [comment]
> I was afraid you would ask this :) Unfortunatelly our VMs are with Windows 7 and I have installed NodeJs version 12.16.1

Yeah, we don't support Windows 7. I believe you are lucky that it worked before. I was going to suggest download https://nodejs.org/dist/v16.13.0/node-v16.13.0-win-x64.zip which is the node version we bundle in 1.18 and try to run it on your machine but even if it fails there is not much we can do.

 > There is also a warning for missing libraries: api-ms-win-core-winrt-error-l1-1-0.dll , but I am able to run tests under v1.17.0.
>
> It seems that for version 1.18.0 I am out of luck.
Yeah, looks like 1.17 is your best bet on win 7. Missing dll may bite you at some point but it may be you just don't use features that require those dll's.

I'm closing this bug as Win 7 is end-of-lifed and playwright doesn't officially support it.
