### ISSUE TITLE
[Feature] Allow multiple directories to be set for PLAYWRIGHT_JAVA_SRC

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright-java#800]
We separate our code between `src/main/java ` and `src/test/java ` and would like to be able to see the source of both areas. 

Perhaps a semicolon separated list of directories could be parsed from the `PLAYWRIGHT_JAVA_SRC` environment variable?

**Comment by uchagani** [comment]
@yury-s any idea when this will be released?

**Comment by yury-s** [comment]
It's already available in 1.19
