### ISSUE TITLE
[Question] How can I get the Page object from a FrameLocator or Locator?

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright-java#801]
we have a lot of iFrames in our code and i would like to be able to pass around FrameLocators and get the Frame/Page object from that.

Prior to using locators or frame locators, I used to pass around Frame objects and was able to do `frame.page` to get to the page from the frame.

**Comment by yury-s** [comment]
[`Locator.page()`](https://playwright.dev/java/docs/next/api/class-locator#locator-page) is available in the current snapshot version and will be released in 1.19. To get Page from `FrameLocator` you can convert `FrameLocator` to locator like this:
```java

Locator locator = frameLocator.locator(":scope");
Page = locator.page();
```

**Comment by uchagani** [comment]
@yury-s what if a locator belongs to a frame?  For example, `Locator loc = page.frameLocator("#foo").locator(".blah")`.  Will there be a corresponding `locator.frame()` too?

**Comment by yury-s** [comment]
No, there is no `frame` getter, only page. Do you have a use case for `Locator.frame()` ?
