### ISSUE TITLE
[Feature]Allow PlaywrightAssertions to work with Response object

### ISSUE THREAD

**Issue by chaganiu** [microsoft/playwright-java#815]
PlaywrightAssertions works with APIResponse object but I'd like to also be able to use it with the [Response](https://playwright.dev/java/docs/api/class-response) object.  The use-case is being able to ensure certain requests that are made as part of page events are successful.  Based on the result of those requests certain UI elements are enabled or disabled.

**Comment by chaganiu** [comment]
@yury-s your example is exactly what i'm doing today.  I was just hoping to use a more readable assertion but the if/else works just fine.  This is part of a smoke test to validate that a grid gets loaded with data if there is data in the response.  

basically my test looks like this:

```java
  @Test
  public void somePageTest(Page page) {
      var response = page.waitForResponse(SomePage.onLoadEndpoint, () -> dashboardPage.someStuff.click());
      var somePage = PageFactory.create(SomePage.class, page);

      // when this fails the error message would be "expected true got false" and i was hoping for consistent error messages.
      assertThat(response.ok()).isTrue();
     
      if(response.length > 0) {
          assertThat(somePage.someGrid).isVisible();        
      }
      
      assertThat(somePage.someGridRows).isVisible();

    }
```

**Comment by yury-s** [comment]
Related upstream issue: https://github.com/microsoft/playwright/issues/12171

**Comment by mxschmitt** [comment]
Folding into the upstream issue, since this is not Java specific.
