### ISSUE TITLE
[BUG] Dead link in Javadoc

### ISSUE THREAD

**Issue by jhyot** [microsoft/playwright-java#817]
**Context:**
- Playwright Version: 1.19.0

**Describe the bug**

The javadoc for `Page#waitForSelector` https://www.javadoc.io/static/com.microsoft.playwright/playwright/1.19.0/com/microsoft/playwright/Page.html#waitForSelector-java.lang.String-

has a dead link on the text "working with selectors" (link points to: https://playwright.dev/java/docs/selectors/)

**Comment by yury-s** [comment]
The link doesn't work because of the trailing slash. We should fix this in our docusaurus docs upstream. As a workaround you can manually delete the trailing slash (https://playwright.dev/java/docs/selectors will work).

**Comment by mxschmitt** [comment]
Seems fixed, closing by that!

**Comment by mxschmitt** [comment]
I was able to verify that `working with selector` link is now working.
