### ISSUE TITLE
[Question] how to resolve java spring boot app throws "Failed to create driver" 

### ISSUE THREAD

**Issue by tony-playwright** [microsoft/playwright-java#820]
Hi there,

I am using playwright java implementation. I understand this is class loader issue. the driver.jar and driver-bundle.jar  dependencies are in maven pom.xml and I can see they are in the generated /lib dir of the war file.  If I deploy to standard tomcat server, I "Failed to create driver" error. I have to explicitly add these 2 jars in the system class path even they are in the lib dir of the war. the issue looks like they are unable to create playwright-java-3892430927773655149/playwright.sh and related node package on temp folder. It looks to me class loader found the jars other wise I should get unable to find driver error.
My question is how to make that playwright working on spring boot with embedded tomcat?

Another question is from the code
private static Driver createDriver() throws Exception {
    String pathFromProperty = System.getProperty("playwright.cli.dir");
    if (pathFromProperty != null) {
      return new PreinstalledDriver(Paths.get(pathFromProperty));
    }

    Class<?> jarDriver = Class.forName("com.microsoft.playwright.impl.DriverJar");
    return (Driver) jarDriver.getDeclaredConstructor().newInstance();
  }

How to define "playwright.cli.dir"? From the doc, it is node application and there is no separate cli installation.

Thanks

**Comment by tony-playwright** [comment]
Hi Yury,

I created a sprint boot repo for you to review. It exposed as Restful API call. the spring boot loader you mentioned is standalone application and I have no issue to run it as standalone. I am guessing on J2ee server, playwright has issue to fork process to run the node js package because of web class loader.
 
here is repo that you can reproduce. please refer to readme file with my 3 test cases. I even tested on wildfly 11 without luck.

https://github.com/tony-playwright/spring-boot-playwright-pdf

to your question "Does the app have proper access to a temp dir?". yes. I am running on my local mac machine.

Thanks
Tony

**Comment by mxschmitt** [comment]
Closing this issue as part of our triage process - looks like this issue felt under our radar, sorry! 

If you still encounter issues, please re-file in this repository.

**Comment by yuanyal** [comment]
Hi @tony-playwright were you able to resolve the issue?
