### ISSUE TITLE
[Question] Can we change network preferences in playwright java to simulate slow network

### ISSUE THREAD

**Issue by kabhinav26** [microsoft/playwright-java#821]
I want to check application performance in different network conditions,  found below code snippet for playwright regarding changing network conditions (supported by puppeteer). 

<img width="485" alt="image" src="https://user-images.githubusercontent.com/32130277/154847024-a306f684-d6a5-4a32-9b9b-542777f4a098.png">

Can we do anything similar in playwright java?

**Comment by mxschmitt** [comment]
This is not possible yet, because Playwright for Java does not have the CDP support yet. I changed this to a feature request.
