### ISSUE TITLE
[Feature] Implement CDPSession

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-java#823]
Make it possible to issue CDP commands like in Playwright for Node.js

**Comment by FROD-Neotys** [comment]
This feature would be much appreciated !

**Comment by alaczyz** [comment]
Hi,
I would love to have this feature too. Do you have any timeline on implementing it?

**Comment by manoj-raghavendran** [comment]
This feature would be really helpful for my work. Has there been any indication from the Devs that this is something they're looking to implement? Especially since Playwright for JavaScript already has this feature.
