### ISSUE TITLE
[Question] Can playwright java connect to Aerokube Moon cloud deployment?

### ISSUE THREAD

**Issue by kabhinav26** [microsoft/playwright-java#826]
I tried running the test cases on Selenium grid 4 and it worked fine with specifying the SELENIUM_REMOTE_URL, however using the local  minikube moon deployment i am getting below error

Running with --> PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 SELENIUM_REMOTE_URL=http://127.0.0.1:4444/wd/hub mvn test

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/32130277/155461019-2873e4bf-419e-4098-b2e6-8ce5185259c6.png">

is it due moon using selenium 3 which is not supported by playwright?

Also can you let me know what is the suggested approach to run playwright java test cases on cloud ?

**Comment by chaganiu** [comment]
Moon has support for playwright but it looks like you're not connecting to it correctly: https://aerokube.com/moon/latest/#_using_playwright

**Comment by yury-s** [comment]
Please follow the instructions from the comment above. If it still doesn't work feel free to file a new issue with a repro.
