### ISSUE TITLE
Playwright for Java 1.19 throws Exception when trying to open new Page

### ISSUE THREAD

**Issue by cortizcuellar** [microsoft/playwright-java#828]
Playwright 1.18 works but 1.19 dont.

![image](https://user-images.githubusercontent.com/85301269/155709665-1a521992-1e0b-4301-8e1d-8c8ea0daddad.png)
![image](https://user-images.githubusercontent.com/85301269/155709748-e0857d50-69da-4dd0-be49-8c976ee94ad5.png)

The problem is in **browser.newPage()**

Im using **java.runtime.version=1.8.0_181-b13** 

Thanks :) and keep rocking

**Comment by yury-s** [comment]
Looks like you are connecting to remote playwright which is older than 1.19. Note that both client and server have to have same versions to work correctly. If that's not the case please share a repro.

**Comment by cortizcuellar** [comment]
Yep it throws when i use **.connect** method with a external provider using launch not problem is thrown. I think this will close the issue. 
![image](https://user-images.githubusercontent.com/85301269/156421197-192237bd-7ff4-4ef5-ae67-870d1b76787b.png)
