### ISSUE TITLE
[BUG] Dockerfile does not set correct permissions for browser path

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright-java#834]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.18+ but could be all i think
- Operating System: [e.g. Windows, Linux or Mac] docker
- Browser: [e.g. All, Chromium, Firefox, WebKit] all
- Extra: [any specific details about your environment]

**Describe the bug**

When the Dockerfile [sets 777 permissions ](https://github.com/microsoft/playwright-java/blob/main/utils/docker/Dockerfile.focal#L26) for the browser path it doesn't actually work or it doesn't carry over once browsers are populated in there.  This is what the `/ms-playwright` directory looks like after the image is built:

```
root@87a85857f426:/# ls -lah /ms-playwright/
total 28K
drwxrwxrwx 1 root root 4.0K Mar  4 23:47 .
drwxr-xr-x 1 root root 4.0K Mar  5 00:39 ..
drwxr-xr-x 2 root root 4.0K Mar  4 23:47 .links
drwxr-xr-x 3 root root 4.0K Mar  4 23:46 chromium-956323
drwxr-xr-x 2 root root 4.0K Mar  4 23:46 ffmpeg-1007
drwxr-xr-x 3 root root 4.0K Mar  4 23:46 firefox-1313
drwxr-xr-x 4 root root 4.0K Mar  4 23:47 webkit-1596
```

If my assumption is correct the `chmod` command should be moved [after here](https://github.com/microsoft/playwright-java/blob/main/utils/docker/Dockerfile.focal#L38) and then it works and the directory then looks like this:

```
root@87a85857f426:/# ls -lah /ms-playwright/
total 52K
drwxrwxrwx 1 root root 4.0K Mar  4 23:47 .
drwxr-xr-x 1 root root 4.0K Mar  5 00:39 ..
drwxrwxrwx 1 root root 4.0K Mar  4 23:47 .links
drwxrwxrwx 1 root root 4.0K Mar  4 23:46 chromium-956323
drwxrwxrwx 1 root root 4.0K Mar  4 23:46 ffmpeg-1007
drwxrwxrwx 1 root root 4.0K Mar  4 23:46 firefox-1313
drwxrwxrwx 1 root root 4.0K Mar  4 23:47 webkit-1596
```

**Comment by mxschmitt** [comment]
What is an actual use-case which is broken as of today? Using pwuser is not working for you?

**Comment by mxschmitt** [comment]
What is an actual use-case which is broken as of today? Using pwuser is not working for you?

**Comment by uchagani** [comment]
I was trying to use the instructions in this Dockerfile to add to another image that has a jenkins user.  These instructions won't work because i'll get a permission denied.  but after moving the chmod command it works correctly.
