### ISSUE TITLE
[Question]  User agent not setting when running test with aerokube/moon

### ISSUE THREAD

**Issue by kabhinav26** [microsoft/playwright-java#841]
I am using playwright java with "moon" on GCP and connecting it as below

"wss://endpoint/playwright/chromium/playwright-1.19.0?headless=false&enableVideo=false&arg=--start-maximized"

and setting the the User-agent in browser context as below

Browser.NewContextOptions n =
    new Browser.NewContextOptions()
        .setUserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0")
        .setViewportSize(null);    
      context = browser.newContext(n);  
    Page page = context.newPage();

But still while running the user agent in getting set as "headless chrome" and due to which it is getting captured as bot/automation traffic.  How to solve this issue?

<img width="653" alt="image" src="https://user-images.githubusercontent.com/32130277/157821944-d1d4d413-ab2c-4247-8262-9d8d274a7396.png">

**Comment by yury-s** [comment]
Can you reproduce it locally (by start a browser with --remote-debugging-port= and connecting to it)? Please share a repro.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
