### ISSUE TITLE
Location of browser binaries

### ISSUE THREAD

**Issue by Leesaaaa** [microsoft/playwright-java#854]
Hello.  What is the URL for the location where the default Playwright downloads (binaries) browsers are stored on Microsoft CDN? I will also need the url for the Google CDN.  Thanks. [Question]

**Comment by yury-s** [comment]
You can reconstruct the URLs by looking at [this file](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/registry.ts). Note that this is an implementation details and may change any time. We don't use Google CDN.

Do you mind sharing why you need the URLs?

**Comment by Leesaaaa** [comment]
We need to have them in our internal Artifactory which we will pull from during CI/CD execution.

**Comment by yury-s** [comment]
Not sure if you've seen this page already but it may be useful for the task and you won't need to depend on the exact CDN urls: https://playwright.dev/docs/browsers#managing-browser-binaries
