### ISSUE TITLE
[BUG] java.nio.file.FileSystemNotFoundException: Provider "vfs" not installed

### ISSUE THREAD

**Issue by htr3n** [microsoft/playwright-java#856]
**Context:**
- Playwright Version: 1.19.0
- Operating System: Linux
- Browser: N/A
- Extra: Playwright JARs are bundled inside a WAR and deployed into WildFly/JBoss application server v11.0.0.Final

**Code Snippet**

```java
import com.microsoft.playwright.Browser;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.options.Margin;
import com.microsoft.playwright.options.Media;

try (Playwright playwright = Playwright.create();
    Browser browser = playwright.chromium().launch()) {
  final String tmpFile = "/tmp/file-" + Instant.now().getEpochSecond() + ".html";
  Files.write(Paths.get(tmpFile), html.getBytes());
  try (final Page page = browser.newPage()) {
    page.navigate("file://" + tmpFile);
    final Page.PdfOptions pdfOptions = configurePageOptions(header, footer);
    rendered = page.pdf(pdfOptions);
  }
}
```

**Describe the bug**

Playwright returns an exception `Caused by: java.lang.RuntimeException: Failed to create driver` which is caused by `java.nio.file.FileSystemNotFoundException: Provider "vfs" not installed` as following (redacted due to verbosity).

It happens at the line `try (Playwright playwright = Playwright.create();`.

```
io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_152]
Caused by: java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54) [driver-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40) [playwright-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.Playwright.create(Playwright.java:96) [playwright-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.Playwright.create(Playwright.java:100) [playwright-1.19.0.jar:1.19.0]
	at au.com.infomedix.pdfkit.PlaywrightHtmlToPdf.render(PlaywrightHtmlToPdf.java:31) [:]

...

	... 228 more
Caused by: java.nio.file.FileSystemNotFoundException: Provider "vfs" not installed
	at java.nio.file.Paths.get(Paths.java:147) [rt.jar:1.8.0_152]
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:90) [driver-bundle-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:44) [driver-bundle-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52) [driver-1.19.0.jar:1.19.0]
	... 257 more

ERROR [default task-14] WFLYEJB0034: EJB Invocation failed on component PdfRenderService for method public byte[] au.com.infomedix.pdfkit.service.PdfRenderService.render(au.com.infomedix.pdfkit.dto.HtmlToPdfRequest) throws java.io.IOException: javax.ejb.EJBTransactionRolledbackException: Failed to create driver

...

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_152]
Caused by: java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54) [driver-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40) [playwright-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.Playwright.create(Playwright.java:96) [playwright-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.Playwright.create(Playwright.java:100) [playwright-1.19.0.jar:1.19.0]
	at au.com.infomedix.pdfkit.PlaywrightHtmlToPdf.render(PlaywrightHtmlToPdf.java:31) [:]

...
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_152]
Caused by: java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54) [driver-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40) [playwright-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.Playwright.create(Playwright.java:96) [playwright-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.Playwright.create(Playwright.java:100) [playwright-1.19.0.jar:1.19.0]
	at au.com.infomedix.pdfkit.PlaywrightHtmlToPdf.render(PlaywrightHtmlToPdf.java:31) [:]

...
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:255) [wildfly-ejb3-11.0.0.Final.jar:11.0.0.Final]
	... 228 more
Caused by: java.nio.file.FileSystemNotFoundException: Provider "vfs" not installed
	at java.nio.file.Paths.get(Paths.java:147) [rt.jar:1.8.0_152]
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:90) [driver-bundle-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:44) [driver-bundle-1.19.0.jar:1.19.0]
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52) [driver-1.19.0.jar:1.19.0]
	... 257 more
```

I set a breakpoint and noticed that the exception is thrown from Java 1.8 `java.nio.Path.get()` method

```java
    public static Path get(URI uri) {
        String scheme =  uri.getScheme();
        if (scheme == null)
            throw new IllegalArgumentException("Missing scheme");

        // check for default provider to avoid loading of installed providers
        if (scheme.equalsIgnoreCase("file"))
            return FileSystems.getDefault().provider().getPath(uri);

        // try to find provider
        for (FileSystemProvider provider: FileSystemProvider.installedProviders()) {
            if (provider.getScheme().equalsIgnoreCase(scheme)) {
                return provider.getPath(uri);
            }
        }

        throw new FileSystemNotFoundException("Provider \"" + scheme + "\" not installed");
    }
```

The problematic `scheme` is  `vfs:/content/pdf-rest-server.war/WEB-INF/lib/driver-bundle-1.19.0.jar/driver/linux/`

The same code above ran successfully as a standalone Java application (i.e. not deployed inside an application server such as WildFly/JBoss).

**Comment by htr3n** [comment]
Digging into this issue, I've realised that, when the JAR dependencies of playwright such as `com.microsoft.playwright:driver` and `com.microsoft.playwright:driver-bundle` are bundled as a JAR inside a WAR, the aforementioned error happens.

When I use the `maven-dependency-plugin` to unpack these two JARs `driver` and `driver-bundle` into the WAR, Playwright works properly.

**Comment by yury-s** [comment]
There are many ways to repackage the playwright classes and some of them may well break existing logic of extracting the driver from jar. Officially we only support running via  Maven and from the prebuilt maven modules that we publish. This is the setup that we test on our CI/CD. With that said if there is something in particular in the current implementation that we can change to make it work in your setup we can try that (you are also welcome to send a PR). We had a similar [problem](https://github.com/microsoft/playwright-java/issues/306) with spring bootloader before and managed to [make that work.](https://github.com/microsoft/playwright-java/pull/342).

Given that there is a workaround that you described above I'm closing this issue, feel free to open a new one if you have a concrete proposal on how we can change the code to make it work for your deployment.

**Comment by htr3n** [comment]
@yury-s Thanks for your feedbacks. I'm aware of the Maven CLI to install deps and tools. There are many other cases, for instance, deploying on production or test servers that don't have Maven or the POM to run Maven.

**Comment by htr3n** [comment]
@yury-s Today I delved into this issue and noticed that, it's not due to the repackaging. I looked into the linked tickets and noticed they are actually not the same issue. I would ask you to reopen this ticket until there is a proper fix. 

Regardless of the repackaging method (e.g. the one I mentioned above), I got the same error when deploying into a real Java EE application server such as WildFly/JBoss. Before, I run it from my IDE that does not really deploy the WAR but links the compiled resources to WildFly, hence the false negative result.

The root cause is actually in `com.microsoft.playwright.impl.DriverJar` where `Classloader#getResource()` is used to retrieve the URI. 

```java
  private void extractDriverToTempDir() throws URISyntaxException, IOException {
    ClassLoader classloader = Thread.currentThread().getContextClassLoader();
    URI originalUri = classloader.getResource("driver/" + platformDir()).toURI();
```

Unfortunately, the outcome of `getResource()` is not quite reliable and portable and subject to the underlying runtime. For instance, in a standalone JAR, it would be something like `jar://`  or `file://` but in case of WildFly/JBoss application servers, it's `vfs://` and the corresponding logic below does not handle that case and hence, always fail regardless of repacking methods.

```java
  private void extractDriverToTempDir() throws URISyntaxException, IOException {
    ClassLoader classloader = Thread.currentThread().getContextClassLoader();
    URI originalUri = classloader.getResource("driver/" + platformDir()).toURI();
    URI uri = maybeExtractNestedJar(originalUri);

    // Create zip filesystem if loading from jar.
    try (FileSystem fileSystem = "jar".equals(uri.getScheme()) ? FileSystems.newFileSystem(uri, Collections.emptyMap()) : null) {
```

An example of the URI returned by WildFly/JBoss on a Linux host is `vfs:/content/pdf-server.war/WEB-INF/classes/driver/linux/`.

There are some SO topics like [this](https://stackoverflow.com/questions/57679687/class-getresource-within-java-ee-wildfly) and [another one](https://stackoverflow.com/questions/27001497/jboss-wildfly-8-x-provider-vfs-not-installed-when-using-java-nio-paths) give some insights about `ClassLoader#getResource()` behaviour on Java EE application servers.

**Comment by htr3n** [comment]
@yury-s After looking into Playwright source code on loading drivers, I was able to load the drivers with JBoss/WildFly. Unfortunately, that workaround would need a depenpency to [`org.jboss:jboss-vfs`](https://search.maven.org/artifact/org.jboss/jboss-vfs) to handle the `vfs:/` schema in the resource URI returned from `ClassLoader#getResource(...)`. I don't think we want to bind Playwright to a Java EE implementation like that.

My proposal would be changing `Driver.jar` where an implementation of `Driver` is loaded so that, a custom implementation of `Driver` can be loaded instead. That is,

instead of

```java
  private static Driver createDriver() throws Exception {
    String pathFromProperty = System.getProperty("playwright.cli.dir");
    if (pathFromProperty != null) {
      return new PreinstalledDriver(Paths.get(pathFromProperty));
    }

    Class<?> jarDriver = Class.forName("com.microsoft.playwright.impl.DriverJar");
    return (Driver) jarDriver.getDeclaredConstructor().newInstance();
  }
```
we change to

```java
  private static Driver createDriver() throws Exception {
    String pathFromProperty = System.getProperty("playwright.cli.dir");
    if (pathFromProperty != null) {
      return new PreinstalledDriver(Paths.get(pathFromProperty));
    }

    String driverImpl = System.getenv("PLAYWRIGHT_DRIVER_IMPL");

    if (driverImpl != null) {
      driverImpl = System.getProperty("playwright.driver.impl");
    }

    if (driverImpl != null) {
      driverImpl = "com.microsoft.playwright.impl.DriverJar";
    }

    Class<?> jarDriver = Class.forName(driverImpl);
    return (Driver) jarDriver.getDeclaredConstructor().newInstance();
  }
```

* If the env `PLAYWRIGHT_DRIVER_IMPL` is set, then used it to load the subclass of `Driver`
* Else, if the property `playwright.driver.impl` is set, then used it to load the subclass of `Driver`
* Else (default/fallback):  used the default `com.microsoft.playwright.impl.DriverJar`

What do you think?

**Comment by htr3n** [comment]
@yury-s Happy to create a PR, but a test? Are there any ways to assert the correct loading of the `Driver` subclass?

**Comment by htr3n** [comment]
> We can do what you suggest. Would system property suffice or you need env variable as well?

I think the system property would suffice.

**Comment by htr3n** [comment]
@yury-s I've submitted a PR.

**Comment by renanzera** [comment]
Hi, here is the same error reported.
How exactly do you use AlternativeDriver class tuning?

**Comment by d-i-l-a** [comment]
I got it working with Wildfly by tweeking the DriverJar. 


`public class CustomDriverJar extends Driver {
    private static final String PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD";
    private static final String SELENIUM_REMOTE_URL = "SELENIUM_REMOTE_URL";
    private final Path driverTempDir;
    private Path preinstalledNodePath;

    public CustomDriverJar() throws IOException {
        String alternativeTmpdir = System.getProperty("playwright.driver.tmpdir");
        String prefix = "playwright-java-";
        this.driverTempDir = alternativeTmpdir == null ? Files.createTempDirectory(prefix) : Files.createTempDirectory(Paths.get(alternativeTmpdir), prefix);
        this.driverTempDir.toFile().deleteOnExit();
        String nodePath = System.getProperty("playwright.nodejs.path");
        if (nodePath != null) {
            this.preinstalledNodePath = Paths.get(nodePath);
            if (!Files.exists(this.preinstalledNodePath, new LinkOption[0])) {
                throw new RuntimeException("Invalid Node.js path specified: " + nodePath);
            }
        }

        logMessage("created DriverJar: " + this.driverTempDir);
    }

    protected void initialize(Boolean installBrowsers) throws Exception {
        if (this.preinstalledNodePath == null && this.env.containsKey("PLAYWRIGHT_NODEJS_PATH")) {
            this.preinstalledNodePath = Paths.get((String)this.env.get("PLAYWRIGHT_NODEJS_PATH"));
            if (!Files.exists(this.preinstalledNodePath, new LinkOption[0])) {
                throw new RuntimeException("Invalid Node.js path specified: " + this.preinstalledNodePath);
            }
        } else if (this.preinstalledNodePath != null) {
            this.env.put("PLAYWRIGHT_NODEJS_PATH", this.preinstalledNodePath.toString());
        }

        this.extractDriverToTempDir();
        logMessage("extracted driver from jar to " + this.driverDir());
        if (installBrowsers) {
            this.installBrowsers(this.env);
        }

    }

    private void installBrowsers(Map<String, String> env) throws IOException, InterruptedException {
        String skip = (String)env.get(PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD);
        if (skip == null) {
            skip = System.getenv(PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD);
        }

        if (skip != null && !"0".equals(skip) && !"false".equals(skip)) {
            logMessage("Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set");
        } else if (env.get(SELENIUM_REMOTE_URL) == null && System.getenv(SELENIUM_REMOTE_URL) == null) {
            Path driver = this.driverDir();
            if (!Files.exists(driver, new LinkOption[0])) {
                throw new RuntimeException("Failed to find driver: " + driver);
            } else {
                ProcessBuilder pb = this.createProcessBuilder();
                pb.command().add("install");
                pb.redirectError(Redirect.INHERIT);
                pb.redirectOutput(Redirect.INHERIT);
                Process p = pb.start();
                boolean result = p.waitFor(10L, TimeUnit.MINUTES);
                if (!result) {
                    p.destroy();
                    throw new RuntimeException("Timed out waiting for browsers to install");
                } else if (p.exitValue() != 0) {
                    throw new RuntimeException("Failed to install browsers, exit code: " + p.exitValue());
                }
            }
        } else {
            logMessage("Skipping browsers download because `SELENIUM_REMOTE_URL` env variable is set");
        }
    }

    private static boolean isExecutable(Path filePath) {
        String name = filePath.getFileName().toString();
        return name.endsWith(".sh") || name.endsWith(".exe") || !name.contains(".");
    }

    private FileSystem initFileSystem(URI uri) throws IOException {
        try {
            return FileSystems.newFileSystem(uri, Collections.emptyMap());
        } catch (FileSystemAlreadyExistsException var3) {
            return null;
        }
    }

    void extractDriverToTempDir() throws URISyntaxException, IOException {
        URI originalUri = getDriverResourceURI();
        URI uri = this.maybeExtractNestedJar(originalUri);
        FileSystem fileSystem = "jar".equals(uri.getScheme()) ? this.initFileSystem(uri) : null;

        try {
            Path srcRoot = Paths.get(uri);
            Path srcRootDefaultFs = Paths.get(srcRoot.toString());
            Files.walk(srcRoot).forEach((fromPath) -> {
                if (this.preinstalledNodePath != null) {
                    String fileName = fromPath.getFileName().toString();
                    if ("node.exe".equals(fileName) || "node".equals(fileName)) {
                        return;
                    }
                }

                Path relative = srcRootDefaultFs.relativize(Paths.get(fromPath.toString()));
                Path toPath = this.driverTempDir.resolve(relative.toString());

                try {
                    if (Files.isDirectory(fromPath, new LinkOption[0])) {
                        Files.createDirectories(toPath);
                    } else {
                        Files.copy(fromPath, toPath);
                        if (isExecutable(toPath)) {
                            toPath.toFile().setExecutable(true, false);
                        }
                    }

                    toPath.toFile().deleteOnExit();
                } catch (IOException e) {
                    throw new RuntimeException("Failed to extract driver from " + uri + ", full uri: " + originalUri, e);
                }
            });
        } catch (Throwable var7) {
            if (fileSystem != null) {
                try {
                    fileSystem.close();
                } catch (Throwable var6) {
                    var7.addSuppressed(var6);
                }
            }

            throw var7;
        }

        if (fileSystem != null) {
            fileSystem.close();
        }
    }

    public URI getDriverResourceURI() {
        File tempDir = new File(System.getProperty("playwright.driver.dir") + "/" + platformDir());
        return tempDir.toURI();
    }

    private URI maybeExtractNestedJar(final URI uri) throws URISyntaxException {
        if (!"jar".equals(uri.getScheme())) {
            return uri;
        } else {
            String JAR_URL_SEPARATOR = "!/";
            String[] parts = uri.toString().split("!/");
            if (parts.length != 3) {
                return uri;
            } else {
                String innerJar = String.join("!/", parts[0], parts[1]);
                URI jarUri = new URI(innerJar);

                try {
                    FileSystem fs = FileSystems.newFileSystem(jarUri, Collections.emptyMap());

                    URI var9;
                    try {
                        Path fromPath = Paths.get(jarUri);
                        Path toPath = this.driverTempDir.resolve(fromPath.getFileName().toString());
                        Files.copy(fromPath, toPath);
                        toPath.toFile().deleteOnExit();
                        var9 = new URI("jar:" + toPath.toUri() + "!/" + parts[2]);
                    } catch (Throwable var11) {
                        if (fs != null) {
                            try {
                                fs.close();
                            } catch (Throwable var10) {
                                var11.addSuppressed(var10);
                            }
                        }

                        throw var11;
                    }

                    if (fs != null) {
                        fs.close();
                    }

                    return var9;
                } catch (IOException e) {
                    throw new RuntimeException("Failed to extract driver's nested .jar from " + jarUri + "; full uri: " + uri, e);
                }
            }
        }
    }

    private static String platformDir() {
        String name = System.getProperty("os.name").toLowerCase();
        String arch = System.getProperty("os.arch").toLowerCase();
        if (name.contains("windows")) {
            return "win32_x64";
        } else if (name.contains("linux")) {
            return arch.equals("aarch64") ? "linux-arm64" : "linux";
        } else if (name.contains("mac os x")) {
            return arch.equals("aarch64") ? "mac-arm64" : "mac";
        } else {
            throw new RuntimeException("Unexpected os.name value: " + name);
        }
    }

    public Path driverDir() {
        return this.driverTempDir;
    }
}
`
