### ISSUE TITLE
[BUG] : Playwright inspector doesn't open/ unclickable

### ISSUE THREAD

**Issue by bunty709** [microsoft/playwright-java#857]
- Playwright Version: <version>1.18.0</version>
- Operating System: [ Windows]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: While running .java class I have added environment variable PWDEBUG=1, which opens up playwright inspector but somehow it's unclickable and unable to perform any action on it. Even with page.pause() also it's the same issue. 

For example:
https://user-images.githubusercontent.com/101847324/158919712-600b565b-5d5a-4713-be7e-0b2ea056d8f2.mp4

**Comment by yury-s** [comment]
We need more details, what is the OS version. Does it reproduce with  `channel: chrome` only or with bundled browser as well? What is the chrome version you run with?

**Comment by bunty709** [comment]
Hi Yury,  Chrome Version  is 99.0.4844.74 (Official Build) (64-bit). Issue is same with the chromium bundle which gets installed on C:\Users\****\AppData\Local\ms-playwright. Does the size of laptop effect anyway , mine is 14 inch

**Comment by yury-s** [comment]
> Does the size of laptop effect anyway , mine is 14 inch.

Looks the same as https://github.com/microsoft/playwright/issues/5696 the inspector might be open just outside of the screen area. What is your screen resolution?

**Comment by bunty709** [comment]
My screen resolution is 1920*1080. I used this as alternative mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen --viewport-size=800,600 --color-scheme=dark eaapp.somee.com/" but the issue persists. What is the recommended resolution? How to fix this permanently irrespective of any resolution?

**Comment by yury-s** [comment]
> What is the recommended resolution?

There were some issues on smaller screens like <1280 width but it doesn't seem the case for you and it's likely a different issue.

**Comment by mxschmitt** [comment]
This should be fixed in version 1.22. Please try updating and file a new issue if you still encounter issues.
