### ISSUE TITLE
[BUG] File uploading being very slow, sometimes not doing anything after long wait.

### ISSUE THREAD

**Issue by Randall-Coding** [microsoft/playwright-java#859]
**Context:**
- Playwright Version: 1.19.0
- Operating System: Linux
- Browser: Firefox (having trouble using Chromium at all so just using Firefox)
- Extra: Pepperoni

**Code Snippet**

Here is the code I use where this is occurring.

```java
    ElementHandle video_input = page.querySelector("xpath=//input[@name='videoInput']");
    video_input.setInputFiles(FileSystems.getDefault().getPath("../test_data/test3.mp4"));
    Thread.sleep(1200000);
```

**Describe the bug**
I have no issue uploading smile files of 1 or 2mb using my playwright-java, but for anything of appreciable size (30mb and above) I notice that the upload time is being significantly increased in total (it appears to be at least 3x more time).  Let me explain further. First there is a very long pause where nothing appears to be happening in the browser after which time the actual normal file transfer begins that I would expect when uploading manually.  That initial pause takes up the most time, and I don't notice any problems once normal upload begins on the screen (once the websites progress bar starts showing 1%, 2%, etc, then it's like normal).  

When I tried a 300mb file, it took so long in that initial pause, that my sleep timer of 20 minutes timed out and the application closed before the normal upload ever started.  However during this time I saw no errors in the java or javascript consoles.  It should also be noted, uploading a 300mb file manually (as a human) only takes about 5 minutes.

I'm coming here because you are more familiar with the inner workings of this program, so perhaps you can help me understand and potentially fix this issue.

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/3768 Currently large file upload fails but we are working on a fix that should address this issue too. Please upvote the upstream one.

**Comment by Randall-Coding** [comment]
> Folding this into [microsoft/playwright#3768](https://github.com/microsoft/playwright/issues/3768) Currently large file upload fails but we are working on a fix that should address this issue too. Please upvote the upstream one.

Thanks for the info, much appreciated.
