### ISSUE TITLE
[Question] Text content of parent element ignoring child elements

### ISSUE THREAD

**Issue by easyrepro** [microsoft/playwright-java#861]
How to get text for current parent element only and ignore text from all of its child elements. In below example I would like to extract "ABCD" only. Tried with `page.locator("h1").innerText()` `page.locator("h1").textContent()` and both returning "ABCD XYZ"

Example html:
`<h1> ABCD <span>XYZ</span></h1>`

**Comment by yury-s** [comment]
Something like `page.locator("h1 :first-child").innerText()` or `page.locator("h1 :first-child").textContent()` should work (see [:first-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child) docs for more details).
