### ISSUE TITLE
[Question] ERR_ABORTED while trying to download a file inside TeamCity CI machine within Chrome

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright-java#863]
Hi all,

Our application has the functionality to export a certain type of report (pdf, csv, etc) 

Playwright version 1.20.1

**I have the following code:**

page.locator(exportButton).click();
Download download = page.waitForDownload(() -> { page.locator(exportPDF).click(); });

**As settings I have set the following:**

launchOptions.headless = true;
launchOptions.channel = "chrome";
launchOptions.setDownloadsPath(Path.get(System.getProperty("user.dir")
contextOptions.acceptsDownloads = true;

-------------------------------------------------------------------------------------------------------------------------
I do not download browsers, I am using chrome that is already installed in the machine.
All these code lines above are working fine when I execute them locally. File gets downloded and checks are passing.

The problem comes when I try to run the test via TeamCity.The following error occure:

StackTrace:
com.microsoft.playwright.TimeoutError: Timeout 30000 ms exceeded
.....

I have a trace file in which I can see on the last step in the Network tab -> 
>> 200 GET 
>> net::ERR_ABORTED GET .....

What I can see is that the button that initiate the download has been pressed and the file is actually downloaded.
I have it within the build artifacts, so I am sure that it was downloaded.

Do you know what could cause this ERR_ABORTED, maybe I need to set some additional arguments upon browser launch.

The machine is running on Linux and it has preinstalled Chrome browser

**Comment by NikkTod** [comment]
Hi @yury-s ,

sorry about the screenshots, it just that the company has very strict policy about sharing. 

Here is the full stack:
![image](https://user-images.githubusercontent.com/94455079/160012197-80a627eb-830e-4a91-af3b-cca9c8618c5e.png)

Here are also 3 screenshots from the traces, sorry for hind some data and that I am not able to provide it:
![image](https://user-images.githubusercontent.com/94455079/160012962-7db3ec5d-1955-409b-90e3-ca08e2663f5e.png)

![image](https://user-images.githubusercontent.com/94455079/160013463-d086abbb-0252-4a6b-859f-3c16a73f76a5.png)

![image](https://user-images.githubusercontent.com/94455079/160013775-dd6548e3-1ec6-4a8d-bd81-62031dd10694.png)

Chrome version is the same as local. I will now try to run it with DEBUG=pw:protocol

Just as info I found one other issue https://github.com/microsoft/playwright/issues/5509  that has similar behaivior. 

I can also see that the file is actually downloded, but also got this net::ERR_ABORTED.

**Comment by yury-s** [comment]
Is it a navigation that becomes a download? If that's the case it is the same issue as https://github.com/microsoft/playwright-java/issues/541 and this is just how Chromium behaves in that case. It's unclear though why the behavior would be different on the TeamCity machines compared to the local one.

**Comment by NikkTod** [comment]
I think it is not navigation. 

After clicking on the PDF link a GET request is send.

![image](https://user-images.githubusercontent.com/94455079/160030310-b1f8de5e-388c-4c35-9f18-a954b9436901.png)

From previous post within the pw:api logs we can see that page.waitForDownload is started and it returns 200 code (that can be seen from the traces screenshot), but after that timesout.

**Comment by NikkTod** [comment]
Hi @yury-s,

hope you had a nice weekend. 

I have one more question, is there a way to somehow to avoid using the download class.

I mean I can just click on the button and the file will be downloaded, the problem is that the file name is some generated number.

So I am not able to validate if the file has the .pdf extention for example. 

Is there a way to set up downloads to be always saved with the suggestedFilename ? This way even if I am not able to use the download class I would be able to verify if a file has been downloaded in the folder location and check its name.

**Comment by yury-s** [comment]
> I mean I can just click on the button and the file will be downloaded, the problem is that the file name is some generated number.

You can call  [download.suggestedFilename()](https://playwright.dev/docs/api/class-download#download-suggested-filename).

> Is there a way to set up downloads to be always saved with the suggestedFilename ? 

No, there is no way to do that. To save the file with a custom name you can call [saveAs](https://playwright.dev/docs/api/class-download#download-save-as).


> The pw:protocol did not work out, so I tried pw:api

What do you mean by 'did not work out', no output? Looking at 'pw:api' trace there are at least 2 successful `waitForDownload` calls but maybe the second one is dispatched on a different page. Can you share a reproduction scenario?

**Comment by NikkTod** [comment]
Hi @yury-s ,

it seems that you were right that the navigation becomes a download. I have also checked the issue that you send me, but there seems to be no solution.

I was able to debug and below you can find my findings:

On local machine (Windows, Chorome, Headful) the following code is throwing:

![image](https://user-images.githubusercontent.com/94455079/160667579-286265ec-8186-4c74-8dcf-bc91b6aef432.png)

Stacktrace is:
![image](https://user-images.githubusercontent.com/94455079/160668434-e5977636-d43e-42be-b8ae-41d3c4a2d9af.png)

Nevertheless the file is downloaded, but test failes because of the error. Do you have an idea how I can fix this?

**Comment by NikkTod** [comment]
Hi @yury-s,

seems that I have mislead you.

On my local machine the chrome browser is version 99 and the download is not throwing.

On the Teamcity machine the browser version is 88.

I found the following issue https://github.com/microsoft/playwright/issues/3726#issuecomment-767254216

Could this be the problem, that the download is not working on browsers that are old more than 6 months ?

**Comment by yury-s** [comment]
Yeah, it may well be the case. 88 is too old there have been some changes to the download implementation since then which could fix the issue. I'd suggest you update chrome on the Teamcity machine to current stable version and try with that.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
