### ISSUE TITLE
When I create multiple playwright instances in multiple threads, the server overflows after running for a period of time. What is the reason?[BUG]

### ISSUE THREAD

**Issue by wasd345** [microsoft/playwright-java#867]
1： For example, after I created 13 playwright instances in 13 threads, the memory will rise bit by bit as the service runs, eventually leading to memory overflow。

2： Another question is, how can I run playwright Java on the non networked winserver 2008 operating system? You need to install offline JDK and node JS? Do you still need to copy the secondary browser file?

**Comment by yury-s** [comment]
> 1： For example, after I created 13 playwright instances in 13 threads, the memory will rise bit by bit as the service runs, eventually leading to memory overflow。
> 
Playwright will hold some resources until corresponding BrowserContext is closed, make sure you properly close contexts after using them. If you think there is a memory leak please provide a reproduction scenario.


> 2： Another question is, how can I run playwright Java on the non networked winserver 2008 operating system? You need to install offline JDK and node JS? Do you still need to copy the secondary browser file?

Normally playwright downloads browser on the first launch. See [this documentation](https://playwright.dev/java/docs/browsers#managing-browser-binaries) for more details on custom handling of the browser installation. In your case you can probably download the borwsers locally to a directory and then copy it over to the target machine and set the path to the folder via `PLAYWRIGHT_BROWSERS_PATH`. Winserver 2008  is end of lifed though, so playwright will most likely fail there.

**Comment by wasd345** [comment]
> > 1： For example, after I created 13 playwright instances in 13 threads, the memory will rise bit by bit as the service runs, eventually leading to memory overflow。
> 
> Playwright will hold some resources until corresponding BrowserContext is closed, make sure you properly close contexts after using them. If you think there is a memory leak please provide a reproduction scenario.
> 
> > 2： Another question is, how can I run playwright Java on the non networked winserver 2008 operating system? You need to install offline JDK and node JS? Do you still need to copy the secondary browser file?
> 
> Normally playwright downloads browser on the first launch. See [this documentation](https://playwright.dev/java/docs/browsers#managing-browser-binaries) for more details on custom handling of the browser installation. In your case you can probably download the borwsers locally to a directory and then copy it over to the target machine and set the path to the folder via `PLAYWRIGHT_BROWSERS_PATH`. Winserver 2008 is end of lifed though, so playwright will most likely fail there.

Hello, why don't you see closing page and context in the demo given in the source code
![image](https://user-images.githubusercontent.com/5779660/160221174-f633b816-5ddc-4a18-9ca6-920d954c9db2.png)

**Comment by wasd345** [comment]
package com.artisan.spider.task;


import com.artisan.spider.consts.Consts;
import com.artisan.spider.domain.SpError;
import com.artisan.spider.domain.SpLawChl;
import com.artisan.spider.service.ScheduledTaskJob;
import com.artisan.spider.service.impl.SpErrorServiceImpl;
import com.artisan.spider.service.impl.SpLawChlServiceImpl;
import com.artisan.spider.util.DateUtil;
import com.artisan.spider.util.SpiderUtil;
import com.artisan.spider.util.SpringContextUtil;
import com.microsoft.playwright.*;
import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;
import java.util.List;

/**
 * 中央法规--行政法规 栏目抓取
 */
@Slf4j
public class ZyfgXzfgTask implements ScheduledTaskJob{

    @Override
    public void run() {
        log.info("中央法规--行政法规,当前线程名称 {} ", Thread.currentThread().getName());
        try {
            collectionInfo();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void collectionInfo(){
        try (Playwright playwright = Playwright.create()) {
            String pageUrl = Consts.zyxzfg;
            Browser browser = playwright.chromium().launch();
            BrowserContext context = browser.newContext();
            Page page = context.newPage();
            page.navigate(String.format(pageUrl, 1));
            // 获取页数
            int pageNum = Integer.valueOf(page.querySelector(".page").innerText().split("/")[1].replace("页", "").trim());
            for (int i = 1; i <= pageNum; i++) {
                List<SpLawChl> list=new ArrayList();
                SpiderUtil.pageChuli("zyfg",context,page, pageUrl, i, pageNum,list);
                try {
                    SpringContextUtil.getBean(SpLawChlServiceImpl.class).saveBatch(list);
                }catch (Exception e){
                    List<SpError> errorList=new ArrayList();
                    for (SpLawChl spLawLar:list){
                        SpError spError=new SpError();
                        spError.setPageUrl(spLawLar.getPageUrl());
                        spError.setCreateTime(DateUtil.getCurrentTime());
                        errorList.add(spError);
                    }
                    SpringContextUtil.getBean(SpErrorServiceImpl.class).saveBatch(errorList);
                    continue;
                }
            }
            page.close();
            context.close();
            browser.close();
        }
    }
}
 Locator rows = page.locator("td a");
        int count = rows.count();
        log.info("每页的大小--》{},当前页数{}", count,currentNum);
        for (int k = 0; k < count; k++) {

            // 判断是不是曾经抓取过
            QueryWrapper<SpLawChl> queryWrapper=new QueryWrapper();
            queryWrapper.eq("page_url",rows.nth(k).getAttribute("href"));
            int lawNumber=SpringContextUtil.getBean(ISpLawChlService.class).count(queryWrapper);
            if(lawNumber==0){
                Page detail = null;
                try{
                    detail= browserContext.newPage();
                    String herf= Consts.rootUrl+"/"+rows.nth(k).getAttribute("href");
                    detail.navigate(herf);

                    log.info("第{}页-第{}篇文章的标题----->{},url为{},", currentNum, k + 1, rows.nth(k).textContent(),herf);

                    String title=detail.locator(".qw-bt").textContent();


                    // 发布部门也可能存在多个
                    Locator fbbmLocator = detail.locator("td:right-of(:text(\"发布部门\"))");
                    String fbbm = "";
                    String fbbmCode = "";
                    if (fbbmLocator.count() != 0) {
                        Locator lb=fbbmLocator.nth(0).locator("a");
                        if (lb.count() != 0) {
                            if (lb.count() > 1) {
                                for (int i = 0; i < lb.count(); i++) {
                                    Locator locator=lb.nth(i);
                                    fbbmCode += getType(locator,"fdep_id","&menuname");
                                    fbbm +=locator.textContent();
                                    if(i!= lb.count()-1){
                                        fbbmCode+=",";
                                        fbbm+=",";
                                    }
                                }
                            } else {
                                Locator locator=lb.nth(0);
                                fbbm = locator.textContent();
                                fbbmCode=getType(locator,"fdep_id","&menuname");
                            }
                        }
                    }

                    String fwzh = "";
                    Locator fbzhLocator = detail.locator("td:right-of(:text(\"发文字号\"))");
                    if (fbzhLocator.count() != 0) {
                        fwzh = fbzhLocator.nth(0).textContent();
                    }

                    String fbrq = "";
                    Locator fbrqLocator = detail.locator("td:right-of(:text(\"发布日期\"))");
                    if (fbrqLocator.count() != 0) {
                        fbrq = fbrqLocator.nth(0).textContent();
                    }

                    String ssrq = "";
                    Locator ssrqLocator = detail.locator("td:right-of(:text(\"实施日期\"))");
                    if (ssrqLocator.count() != 0) {
                        ssrq = ssrqLocator.nth(0).textContent();
                    }


                    String ppbm = "";
                    String ppbmCode = "";
                    Locator ppbmLocator = detail.locator("td:right-of(:text(\"批准部门\"))");
                    if (ppbmLocator.count() != 0) {
                        Locator lb=ppbmLocator.nth(0).locator("a");
                        if (lb.count() != 0) {
                            if (lb.count() > 1) {
                                for (int i = 0; i < lb.count(); i++) {
                                    Locator locator=lb.nth(i);
                                    ppbmCode += getType(locator,"pdep_id","&menuname");
                                    ppbm +=locator.textContent();
                                    if(i!= lb.count()-1){
                                        ppbmCode+=",";
                                        ppbm+=",";
                                    }
                                }
                            } else {
                                Locator locator=lb.nth(0);
                                ppbm = locator.textContent();
                                ppbmCode=getType(locator,"pdep_id","&menuname");
                            }
                        }
                    }



                    String sxx = "";
                    String sxxCode="";
                    Locator sxxLocator = detail.locator("td:right-of(:text(\"时效性\"))");
                    if (sxxLocator.count() != 0) {
                        Locator locator=sxxLocator.nth(0).locator("a");
                        sxx = locator.textContent();
                        sxxCode=getType(locator,"shixiao_id","&menuname");
                    }

                    String xljb = "";
                    String xljbCode="";
                    Locator xljbLocator = detail.locator("td:right-of(:text(\"效力级别\"))");
                    if (xljbLocator.count() != 0) {
                        Locator locator=xljbLocator.nth(0).locator("a");
                        xljb = locator.textContent();
                        xljbCode=SpiderUtil.getType(locator,"xiaoli_id","&menuname");
                    }


                    // 法规类别有可能是多个
                    String fglb = "";
                    String fglbCode="";
                    Locator fglbLocator = detail.locator("td:right-of(:text(\"法规类别\"))");
                    if (fglbLocator.count() != 0) {
                        // 如果法规类别有多个
                        Locator lb = fglbLocator.nth(0).locator("a");
                        if (lb.count() != 0) {
                            if (lb.count() > 0) {
                                for (int i = 0; i < lb.count(); i++) {
                                    Locator locator=lb.nth(i);
                                    fglb += locator.textContent();
                                    fglbCode += getType(locator,"sort_id","&menuname");
                                    if(i!= lb.count()-1){
                                        fglb+=",";
                                        fglbCode+=",";
                                    }
                                }
                            } else {
                                Locator locator=lb.nth(0);
                                fglb = locator.textContent();
                                fglbCode=getType(locator,"sort_id","&menuname");
                            }
                        }
                    }
                    String content = detail.locator("#div_content").innerHTML();

                    log.info("发布部门名称,编码--》{},{}", fbbm,fbbmCode);
                    log.info("发文字号--》{}", fwzh);
                    log.info("发布日期--》{}", fbrq);
                    log.info("实施日期--》{}", ssrq);
                    log.info("时效性名称,编码--》{},{}", sxx,sxxCode);
                    log.info("效力级别名称,编码--》{},{}", xljb,xljbCode);
                    log.info("法规类别名称,编码--》{}", fglb,fglbCode);
                    log.info("全文--》{}", content);
                    log.info("*******************************第{}页-第{}篇文章处理完成", currentNum, k + 1);

                    SpLawChl SpLawChl=new SpLawChl();
                    SpLawChl.setId(UuidUtils.getUUid());
                    SpLawChl.setFbDeptName(fbbm);
                    SpLawChl.setFbDeptCode(fbbmCode);
                    SpLawChl.setPzDeptName(ppbm);
                    SpLawChl.setPzDeptCode(ppbmCode);
                    SpLawChl.setLssuedNumber(fwzh);
                    SpLawChl.setReleaseDate(fbrq);
                    SpLawChl.setTimeName(sxx);
                    SpLawChl.setTimeCode(sxxCode);
                    SpLawChl.setXiaoliName(xljb);
                    SpLawChl.setXiaoliCode(xljbCode);
                    SpLawChl.setFaguiName(fglb);
                    SpLawChl.setFaguiCode(fglbCode);
                    SpLawChl.setImplDate(ssrq);
                    SpLawChl.setTitle(title);
                    SpLawChl.setFullText(content);
                    SpLawChl.setStatus("1");
                    SpLawChl.setCreateTime(DateUtil.getCurrentTime());
                    SpLawChl.setPageUrl(rows.nth(k).getAttribute("href"));
                    SpLawChl.setFgfl(mark);
                    list.add(SpLawChl);
                    detail.close();
                }catch (Exception e){
                    e.printStackTrace();
                    detail.close();
                    log.info("*******************************第{}页-第{}篇文章处理失败", currentNum, k + 1);
                    log.info("错误链接："+Consts.rootUrl+"/"+rows.nth(k).getAttribute("href"));
                    SpError spError=new SpError();
                    spError.setCreateTime(DateUtil.getCurrentTime());
                    spError.setPageUrl(rows.nth(k).getAttribute("href"));
                    SpringContextUtil.getBean(ISpErrorService.class).save(spError);
                    continue;
                }
            }else{
                continue;
            }
        }
        // 跳转列表页
        if (pageNum != currentNum) {
            page.navigate(String.format(pageUrl, currentNum + 1));
        }
    }

**Comment by wasd345** [comment]
> PLAYWRIGHT_BROWSERS_PATH

How to set up, how to execute this command on a new winserver2012 operating system that can't be connected to the Internet, do you need to install Maven?I have now copied the browser binaries from other machines
