### ISSUE TITLE
try (Playwright playwright = Playwright.create()) { ...       What is this syntax? Playwright can be called multiple times in multiple threads Create()?[Question]

### ISSUE THREAD

**Issue by wasd345** [microsoft/playwright-java#869]
try (Playwright playwright = Playwright.create()) { ...     

  What is this syntax? Playwright can be called multiple times in multiple threads Create()?

**Comment by yury-s** [comment]
You can have one playwright instance per thread without complicated synchronization, see https://playwright.dev/java/docs/multithreading
