### ISSUE TITLE
Because the for loop collects multiple articles, the URL of some articles cannot be opened, which will trigger an error exception of 30 seconds, and this piece does not recycle memory. If there are more and more wrong articles, will it lead to memory overflow?

### ISSUE THREAD

**Issue by wasd345** [microsoft/playwright-java#871]
For example, I collected 40 articles in the for loop. If an article could not be opened due to a URL error, the playwright reported an error, but I didn't stop running, so that your JS process didn't terminate. Instead, I caught an exception and continued to parse the next article. Is it a memory overflow caused by this? Is there a command for JS to send to terminate the process in the captured exception?

**Comment by yury-s** [comment]
You can close the context by calling [`BrowserContext.close()`](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-close), it will free-up all resources associated with the pages from the context but the browser process will keep running. You can close running browser by calling [Browser.close](https://playwright.dev/java/docs/api/class-browser#browser-close)
