### ISSUE TITLE
How can I use a firefox profile with playwright-java? [Question]

### ISSUE THREAD

**Issue by vivekrao1985** [microsoft/playwright-java#872]
Hello,

I'm trying to create a Firexfox profile that's setup with some defaults (eg - enable camera and mic use by default) and use it with playwright. Here's my code -
```
try (Playwright playwright = Playwright.create()) {
    BrowserType browserType = playwright.firefox();
    BrowserType.LaunchPersistentContextOptions options = new BrowserType.LaunchPersistentContextOptions();
    options.setHeadless(false);
    options.setArgs(Arrays.asList("--profile-directory=default"));
    BrowserContext browser = browserType.launchPersistentContext(Paths.get("/path/before/default"), options);
}
```
As per the [documentation](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch-persistent-context) I need to provide the parent directory of the directory that has my firefox profile, which I have done and indicated above. However, when I run the above I get this error -
```
message='Pass userDataDir parameter to `browserType.launchPersistentContext(userDataDir, ...)` instead of specifying --profile argument
```
Does playwright support running custom profiles? From the documentation I infer this setting can only be used to create the profile the browser runs with, but you can't use it to point to an existing profile?

Playwright version - 1.17.0

**Comment by yury-s** [comment]
> As per the [documentation](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch-persistent-context) I need to provide the parent directory of the directory that has my firefox profile,

It is parent directory only for chromium, for firefox it's just the profile directory.

> which I have done and indicated above. However, when I run the above I get this error -

Remove ` options.setArgs(Arrays.asList("--profile-directory=default"));` from the snippet and it should work, you already pass the profile dir to launchPersistentContext.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by vivekrao1985** [comment]
@yury-s sorry for the late comment, but I have the same issue as this [ticket](https://github.com/microsoft/playwright/issues/12632). Removing session files works for now. Thank you!
