### ISSUE TITLE
The binary file of $Wren \ server 2012 can't be copied to the corresponding directory of $Wren \ server \ administrator_ BROWSERS_ PATH="$env:USERPROFILE\AppData\Local\ms-playwright"  , but I still can't open the browser after running the program

### ISSUE THREAD

**Issue by wasd345** [microsoft/playwright-java#880]
What is the reason

![image](https://user-images.githubusercontent.com/5779660/161187326-07d0f759-a829-4edb-97bb-6db8998c08c1.png)

**Comment by yury-s** [comment]
It's hard to tell from the description what's the goal and what the problem is.
