### ISSUE TITLE
[Question] Does setSources(true) works with Cucumber tests ?

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright-java#885]
Hello,

I have a project with cucumber tests (features, steps and actions files) and I am trying to get the Sources tab within the traces file. 

To which location should the environment variable PLAYWRIGHT_JAVA_SRC points to ? 
How to set up multiple locations, could you give me an example ?

**Comment by yury-s** [comment]
> I have a project with cucumber tests (features, steps and actions files) and I am trying to get the Sources tab within the traces file.

I don't know how exactly cucumber works but I'd expect it to first translate Cucumber scripts to .java files which are compiled and run on a jvm. In that case you should be able to add the directory with the generated .java files to PLAYWRIGHT_JAVA_SRC and they will appear in the stack traces and sources tab. This will not give you original cucumber sources though only the generated java sources.

> To which location should the environment variable PLAYWRIGHT_JAVA_SRC points to ?

It should point to the parent directory of the root package, see e.g. this test on our CI:

https://github.com/microsoft/playwright-java/blob/447578c5824688e5209dadbb233867ed0b20385c/.github/workflows/test.yml#L37-L41

> How to set up multiple locations, could you give me an example ?

The value is a list of directories separated by `File.pathSeparator`, so e.g. on Linux:

```
PLAYWRIGHT_JAVA_SRC=/home/me/foo/java/src:/home/me/bar/java/src
```

**Comment by NikkTod** [comment]
Thank you very very much @yury-s 

I was able to add the sources tab to the traces, _working directory/src/test/java_ did the trick.

For adding multiple paths in windows we can use ; => linux is with :

**Comment by yury-s** [comment]
Let me also update the docs to mention this.
