### ISSUE TITLE
when playwright docker image is used , Iam getting file not found error.

### ISSUE THREAD

**Issue by bharathi-divya** [microsoft/playwright-java#902]
Iam using the playwright java docker file from https://gist.github.com/uchagani/af1c2fcc9f66c1dcb21650a3b914473e.
When I download the project and try to build and run it, I get the below error.

![image](https://user-images.githubusercontent.com/103580190/163185154-65a93f2b-9f63-4e6d-ba2f-28cffbab5c9c.png)

The same error is thrown when run in local WSL or when run in azure pipeline.
I need support to build docker image to run playwright Java test scripts. 
Can someone help on why this file not found error is thrown for download_driver_for_all_platforms.sh file though the file is available in scripts folder.

**Comment by yury-s** [comment]
Normally we recommend you use our published [docker images](https://playwright.dev/java/docs/docker). If you want to build it from source you need to checkout this repository and run build the docker from its root, we build from https://github.com/microsoft/playwright-java/blob/main/utils/docker/Dockerfile.focal (look at our CD https://github.com/microsoft/playwright-java/blob/main/.github/workflows/publish_canary_docker.yml)

**Comment by bharathi-divya** [comment]
Yes Iam using the same repo which you have pointed and trying to build it. But I get "file not found error". 
![image](https://user-images.githubusercontent.com/103580190/163558768-938ba84a-f4be-4976-9acd-e6f9646f6c55.png)
I didnt make any change in repo just downloaded it and ran it in WSL.
May I know like why Iam getting file not found though .sh file is available in scripts folder. Kindly help.

**Comment by yury-s** [comment]
You are probably running from a wrong directory.

**Comment by bharathi-divya** [comment]
OKay. Iam trying to build it from playwright-java main directory now using ubuntu WSL.  Iam running WSL as a root user and below is the error I get.
![image](https://user-images.githubusercontent.com/103580190/163781642-3a84344f-bbf6-41d2-9d5d-804f9f5b3aa4.png)
What I tried it just downloaded the repo (https://github.com/microsoft/playwright-java/) and navigated to playwright-java folder using cd command in my WSL and tried to build the image using the below command.
![image](https://user-images.githubusercontent.com/103580190/163782093-ed812966-68b8-4853-a972-04edeadd2f91.png)
but the build fails.

**Comment by bharathi-divya** [comment]
Hi Yury-s,

I fixed my file permission issues and now Iam able to build docker file. When I try run a jar file using CMD java -jar mytest.jar, I get configuration failures while running.
The error printed in console is 
/tmp/playwright-java-11395942908041039402/playwright.sh: 3: /tmp/playwright-java-11395942908041039402/node: Permission denied
/tmp/playwright-java-11395942908041039402/playwright.sh: 3: /tmp/playwright-java-11395942908041039402/node: Permission denied

When I run the same jar in my local system system(using CMD without docker), I could see a playwright-java folder getting created in temp folder . Jar is running fine in local.
![image](https://user-images.githubusercontent.com/103580190/164439828-d641f130-b4bd-4585-a4b4-bc012e794b35.png)
But for same jar file when run in docker, I get permission denied for node.exe in temp folder. Can you suggest how I can fix this error as this temp folder is created uniquely for every time we run the Jar file.

**Comment by yury-s** [comment]
Check permissions of /tmp probably its content doesn't get executable bit, the code that extracts the driver is [here](https://github.com/microsoft/playwright-java/blob/59e7c0cc946c4c32861cd81aa405f709987d4f74/driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java#L85) you can try pausing there and check the permissions.

**Comment by bharathi-divya** [comment]
Thanks Yury.
I checked for the code and there we have lines to set executable . But still when I run the example test case using docker file, I get the below error.Tried many ways to resolve but nothing helped.
![image](https://user-images.githubusercontent.com/103580190/166678880-bbb40278-e5a7-4786-a0fa-bca75cacb4ee.png)
