### ISSUE TITLE
[BUG] --disable-web-security not working with Chromium

### ISSUE THREAD

**Issue by aarushiag** [microsoft/playwright-java#907]
**Context:**
- Playwright Version: **1.21.0**
- Operating System: **Windows**
- Browser: **Chromium**

**Code Snippet**

```
Browser browser = chromium.launch(new BrowserType.LaunchOptions().setArgs(Arrays.asList("--disable-web-security")).setProxy(proxy).setChromiumSandbox(true).setHeadless(false)); 
```

**Describe the bug**
The Chrome does not launch in disabled web security mode. Is there some other parameter that we would need to set for disabling web security ? 
I am able to manually run the Chromium in disabled web security mode using the following command - 
 
```chrome.exe --user-data-dir="C://Chrome dev session" --disable-web-security```

However, passing the parameter `--user-data-dir` as an argument along with `--disable-web-security` above command does not seem to work either.

**Comment by yury-s** [comment]
It might conflict with some other flags that we pass by default, you can run with `DEBUG=pw:browser` environment variable to see how the browser is launched. The command line flags can be adjusted with `setArgs` and [`setIgnoreAllDefaultArgs`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch-option-ignore-all-default-args) and [`setIgnoreDefaultArgs`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch-option-ignore-default-args).

**Comment by aarushiag** [comment]
After using `setIgnoreAllDefaultArgs` , I was able to open the browser in disabled web security mode. My command is as follows - 

`Browser browser = chromium.launch(new BrowserType.LaunchOptions().setIgnoreAllDefaultArgs(true).setArgs(Arrays.asList(new String[]{"--disable-web-security", "--user-data-dir=C:\\Users\\Administrator\\AppData\\Local\\Temp\\Chromium_Dev", "--allow-file-access-from-files"})).setProxy(proxy).setChromiumSandbox(true).setHeadless(false)); 
`
However, the browser process terminates with the following logs - 

`2022-04-21T21:13:37.084Z pw:browser [pid=10764][err] [10764:6372:0421/211337.081:ERROR:device_event_log_impl.cc(214)] [21:13:37.081] Bluetooth: bluetooth_adapter_winrt.cc:1075 Getting Default Adapter failed.`

Could you suggest what flags could be conflicting in this case ?

**Comment by aarushiag** [comment]
Hi @yury-s , could you help us with the above query ?

**Comment by mxschmitt** [comment]
This is not a Playwright for Java bug, I'd recommend filing one upstream. Also setting custom args or modifying the default ones might break Playwright like in your case.

Setting a custom user-data-dir is not supported for launch(), we have launchPersistentContext() for that.

**Comment by kherath4139** [comment]
Still reproducing this issue , any fix?
