### ISSUE TITLE
[BUG]: Websocket connection to Moon not closing on calling context.close() and browser.close()

### ISSUE THREAD

**Issue by kabhinav26** [microsoft/playwright-java#912]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Linux
- Browser: Chromium
- Extra: Connecting to browser instance on Moon deployed on GCP using websocket

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
     BrowserType.ConnectOptions connectOptions = new BrowserType.ConnectOptions().setTimeout(0)
        .setHeaders(Collections.singletonMap("User-Agent", USER_AGENT_FULL));
      Browser browser = Playwright.create().chromium().connect("ws://<HOST>/playwright/chromium/playwright-1.21.1?headless=false&enableVideo=false&arg=--start-maximized&arg=--user-agent="+USER_AGENT", connectOptions);
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      // ...
    System.out.println("Start Date:" + startDate);
    System.out.println("End Date:" + endDate);
    System.out.println("Test Duration:" + (endDate -startDate));
    context.close();
    browser.close();
    }
  }
}
```

**Bug Description:**
As shown in above snippet i am connecting to moon hosted over gcp using websocket. 
After the sout stmt's calling context.close() and browser.close() to end session, but process gets hung and waits for 5min and then ends.

**Sample run**:
Start Date:1651146064343
End Date:1651146081913
Test Duration:17570

[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 530.51 s - in TestSuite

Here test ran in 17 sec but process hung for 5min and then exited

Moon Logs:

2022/04/28 11:41:02 moon-b45d69fcc-qhmc9: moon: chromium-playwright-1-21-1-7855a004-c692-4f0e-bd45-68d014b37575: session created: 5.093s
2022/04/28 11:47:58 moon-b45d69fcc-qhmc9: moon: chromium-playwright-1-21-1-7855a004-c692-4f0e-bd45-68d014b37575: deleting session
2022/04/28 11:47:58 moon-b45d69fcc-qhmc9: moon: chromium-playwright-1-21-1-7855a004-c692-4f0e-bd45-68d014b37575: deleting pod

Browser Pod logs:
2022/04/28 11:41:00 listening on :4444
2022/04/28 11:41:01 starting browser server with parameters: {"headless":false,"args":["--start-maximized","--user-agent=Mozilla/5.0"]}
2022/04/28 11:41:02 forwarding requests to: http://127.0.0.1:43669/2e1ce293a74d46324061b2a54952b6a7
2022/04/28 11:47:58 graceful shutdown in 5m0s
2022/04/28 11:47:58 exited

**Comment by yury-s** [comment]
Can you run it with `DEBUG=pw:browser,pw:protocol` and show the logs? Is it reproducible without Moon if you run Chromium with `--remote-debugging-port=9222` and connect to it?

**Comment by kabhinav26** [comment]
@yury-s : I tried running test cases as DEBUG=pw:browser,pw:protocol mvn clean test

**This is the only additional log i saw as start time** 

2022-04-30T06:20:38.877Z pw:browser <ws connecting> ws://<HOST>/playwright/chromium/playwright-1.21.1?headless=false&enableVideo=false&arg=--start-maximized&arg=--user-agent=Mozilla/5.0
2022-04-30T06:21:43.193Z pw:browser <ws connected> ws://<HOST>/playwright/chromium/playwright-1.21.1?headless=false&enableVideo=false&arg=--start-maximized&arg=--user-agent=Mozilla/5.0

**and then again got stuck after on step context.close()

I tried again with commenting context close step and then it ran without any issues**

2022-04-30T07:09:10.076Z pw:browser <ws connecting> ws://moon-np.infra-sg.cld/playwright/chromium/playwright-1.21.1?headless=false&enableVideo=false&arg=--start-maximized&arg=--user-agent=Mozilla/5.0
2022-04-30T07:09:17.794Z pw:browser <ws connected> ws://moon-np.infra-sg.cld/playwright/chromium/playwright-1.21.1?headless=false&enableVideo=false&arg=--start-maximized&arg=--user-agent=Mozilla/5.0
.......
.......
2022-04-30T07:10:49.178Z pw:browser <ws disconnecting> ws://<HOST>/playwright/chromium/playwright-1.21.1?headless=false&enableVideo=false&arg=--start-maximized&arg=--user-agent=Mozilla/5.0
Start Date:1651302572872
End Date:1651302607662
Test Duration:34790
2022-04-30T07:10:49.440Z pw:browser <ws disconnected> ws://<HOST>/playwright/chromium/playwright-1.21.1?headless=false&enableVideo=false&arg=--start-maximized&arg=--user-agent=Mozilla/5.0 code=1005 reason=


**I need context.close() as i am putting n/w calls to HAR file, and without calling context.close(), data is not written to file**

**Comment by yury-s** [comment]
> I need context.close() as i am putting n/w calls to HAR file, and without calling context.close(), data is not written to file

Can you share actual snippet that hangs (including har options etc)? Try running with `DEBUG=pw:channel` to collect some more logs, it seems that context.close() hangs while writing har data to the local file in your case. Do both ends (moon and local) use same playwright versions?

**Comment by kabhinav26** [comment]
Snippet while initialisation is as below:

`
    context = browser.newContext(new Browser.NewContextOptions()
        .setRecordHarPath("/tmp/h1.har")
        .setUserAgent(MW_USER_AGENT)
        .setViewportSize(300, 700)
        .setDeviceScaleFactor(3)
        .setIsMobile(true)
        .setHasTouch(true)
        .setPermissions(Collections.singletonList("geolocation"))
        .setGeolocation(-6.175110, 106.865039)
        .setColorScheme(ColorScheme.DARK)
        .setLocale("in-ID"));`

Closing 

`System.out.println("Start Date:" + Common.startDate);
    System.out.println("End Date:" + Common.endDate);
    System.out.println("Test Duration:" + (Common.endDate - Common.startDate));
    System.out.println("MW Time before context.close()"+new Date());
    context.close();
    System.out.println("MW Time after context.close()"+new Date());
    browser.close();
    File f = new File("/tmp/h1.har");
    boolean harFileExist = f.exists();
    System.out.println("Is file written:"+harFileExist);
    if(harFileExist){
      System.out.println("HAR File is deleted successfully"+f.delete());
    }`

This is the result of debug logs i have put:

`Start Date:1651674859874
End Date:1651674875098
Test Duration:15224
MW Time before context.close() Wed May 04 14:34:36 UTC 2022
MW Time after context.close() Wed May 04 14:41:07 UTC 2022
Is file written:true
HAR File is deleted successfully:true`

So file is written but takes 5 min? Is it due to mw emulation?

**Comment by kabhinav26** [comment]
File size for desktop run is 24 kilobytes and mobile web run is 27 kilobytes. So not much diff in size

**Comment by yury-s** [comment]
> So file is written but takes 5 min?

Seems so.

> Is it due to mw emulation?

Can you tell us what you mean by mw emulation?

> With normal desktop mode it works without any issue

So it clearly has to do with the moon browser.

> Try running with `DEBUG=pw:channel` to collect some more logs, it seems that context.close() hangs while writing har data to the local file in your case. Do both ends (moon and local) use same playwright versions?

Can you answer to these questions? We need more information to understand what's going on.

**Comment by kabhinav26** [comment]
- Both moon and local are using same playwright version 1.21.0
- mw emulation : using chrome in mobile web mode

`    Browser.NewContextOptions contextOptions =
        new Browser.NewContextOptions()
            .setUserAgent(MW_USER_AGENT)
            .setViewportSize(300, 700)
            .setDeviceScaleFactor(3)
            .setIsMobile(true)
            .setHasTouch(true)
            .setPermissions(Collections.singletonList("geolocation"))
            .setGeolocation(-6.175110, 106.865039)
            .setColorScheme(ColorScheme.DARK)
            .setLocale("in-ID");`

Using  DEBUG=pw:channel writes lot of logs anything you need specifically?

**Comment by yury-s** [comment]
> Using DEBUG=pw:channel writes lot of logs anything you need specifically?

I'd like to look at the full log to see if there is anything unusual.

**Comment by yury-s** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
