### ISSUE TITLE
How to achieve IP binding through playwright?

### ISSUE THREAD

**Issue by SilenceCarrot** [microsoft/playwright-java#917]
Ask a question: When visiting a site through a domain name, I need to specify a bound IP.
How to achieve IP binding through playwright?
It's like configuring a DNS configuration in the hosts file.

**Comment by yury-s** [comment]
This is not currently possible. There are no current plans to support this as this is not normally needed in testing scenarios, so I'm closing this issue.

**Comment by SilenceCarrot** [comment]
Thanks for your answer.
I have a different opinion: I think this is a pretty common use case.
For example, within an enterprise, there are scenarios where multiple testers test the same service (same domain name) at the same time. In order to avoid mutual influence, everyone has a dedicated test site (the same test branch, deployed on different machines).

Since it is a non-production environment, the domain name service is not configured for the service of the test environment.

At this point, I have a machine with playwright-based services deployed, and different testers need to dynamically specify DNS when running the use case in order to be able to access their own machine.

At present, the goal can be achieved by modifying the /etc/hosts file of the executing machine, but this is a manual process, and I cannot dynamically modify the hosts file through java code, because the application is started with non-root privileges.
So I hope that playwright can dynamically maintain a set of DNS configurations like JVM DNS Cache, so that different testers can use the services provided by different machines when opening the same domain name.

This kind of scenario is very common here, if there is a plan to support it, it would be very grateful.

Or, do you have any good solutions for this scenario?
Looking forward to your reply.

**Comment by yury-s** [comment]
> So I hope that playwright can dynamically maintain a set of DNS configurations like JVM DNS Cache

I don't think this is sufficient as it will not affect browsers that actually send the requests. How do you currently solve for the browsers? Do you somehow circumvent /etc/hosts config for them?

**Comment by SilenceCarrot** [comment]
thank you for your reply.

> I don't think this is sufficient as it will not affect browsers that actually send the requests. How do you currently solve for the browsers? Do you somehow circumvent /etc/hosts config for them?

Sadly, I don't currently have a solution to the dynamic binding DNS configuration, and am still trying to see if seninum has a strategy for this.

> In this case each machine will have its unique address and each tester can point their tests to the machine of their choice (basically pass dns name or ip address of the machine as a parameter to the test suite), why does it not work?

Although the services that different users want to access have different IPs, the IP bound in the hosts file is the IP of the machine that provides the nginx service, not the IP of the machine that provides the business service.
Due to security policy, we cannot directly access the IP that provides business services.
Replacing host with the IP of the nginx server will also not work, because nginx will not know which service site you want to access. Therefore, only the DNS configuration can be provided for correct access, for example:
nginxIP : hostA

The following figure is a network model we use (I will not elaborate on the specific reasons for this design).
![image](https://user-images.githubusercontent.com/15966265/169449681-13d36a7e-1c47-4826-9fb2-77dff56a7d4a.png)

**Comment by yury-s** [comment]
From what you describe it sounds like IP1 and IP2 machines can be set as a proxy and redirect hostA  requests to appropriate destinations. You can configure browsers via  [proxy](https://playwright.dev/java/docs/next/network#http-proxy) parameter. Would that work for you?

**Comment by SilenceCarrot** [comment]
I'll check the proxy's documentation and try it out.
thank you for your reply.

**Comment by hanzhihong9** [comment]
Maybe you can try 'X-Forwarded-For'  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
```
   await page.route('**/*', route => {
      const headers = route.request().headers();
      headers['X-Forwarded-For'] = '77.77.77.77';
      route.continue({ headers });
    });
```

**Comment by gyunaev** [comment]
> This is not currently possible. There are no current plans to support this as this is not normally needed in testing scenarios, so I'm closing this issue.

A typical test scenario for this is to test a website in unstable network conditions. This is normally done on Linux by creating multiple virtual interfaces and using `tc` to add delays or packet drops, i.e. https://stackoverflow.com/questions/614795/simulate-delayed-and-dropped-packets-on-linux

Binding playwright to an interface allows:

- not screwing up your main network interface;
- run tests in parallel in different network condition (i.e. a) low speed, b) high latency, c) high packet loss d) combination of b+c etc).

There are ways to achieve it without playwright support, i.e. via network namespaces or https://github.com/JsBergbau/BindToInterface - but having a built-in support would allow enclosing this information into the test configuration, simplifying usage.
