### ISSUE TITLE
[Question] Maximize browser to screen

### ISSUE THREAD

**Issue by AlexBravo95** [microsoft/playwright-java#923]
Dear I am reading the documentation but I can not find a command to maximize the window to the size of the screen.

Is there a command?

I am using a java-maven project

Thanks for your job.

**Comment by yury-s** [comment]
This not currently supported, there is an open feature request for it upstream: https://github.com/microsoft/playwright/issues/4046 you can 👍 to help us prioritize it.

**Comment by AlexBravo95** [comment]
Ready thanks. I really like your library.
