### ISSUE TITLE
How to wait in playwright until we get specific API and http method Response in UI 

### ISSUE THREAD

**Issue by raiajithkumarr** [microsoft/playwright-java#932]
Hi Team,
As a E2E test, we are deleting entry and verifying whether that record is present or not 
while performing it. It is deleting record and immediately I am searching record whether it is delete or not.

In this gap I want verify Api response 

Example API in backend call : v1/user/{**guid**}  >> here I don't have guid I want to check url contain v1/user and Method : DELETE  if it is 200 response then proceed with searching record.

How to achieve this can you suggest me.

**Comment by yury-s** [comment]
I assume that the delete request is sent by the page in response to a user action. You can listen to outgoing requests and [wait](https://playwright.dev/java/docs/next/api/class-page#page-wait-for-request) for the one you expect before proceeding to the next step:

```java

Request deleteRequest = page.waitForRequest(request -> request.url().contains("v1/user/") && "DELETE".equals(request.method()), () -> {
    // Triggers the request
    page.click("button.that.deletes.user");
});

```
Will this work for you?
