### ISSUE TITLE
[BUG] Initial requests through Proxy missing Proxy-Authorization header

### ISSUE THREAD

**Issue by mitch-mcginnis** [microsoft/playwright-java#933]
**Context:**
- Playwright Version: Confirmed on 1.14.0 & 1.21.0
- Operating System: Mac
- Browser: Firefox, suspected with all browsers 

**Code Snippet**
```kotlin
import com.microsoft.playwright.BrowserType
import com.microsoft.playwright.Playwright
import com.microsoft.playwright.options.Proxy

data class MyProxy(val host: String, val port: Int, val username: String, val password: String)

fun main() {
    val proxy = MyProxy("proxy", 1234, "admin", "password")
    Playwright.create().use { playwright ->
        playwright.firefox().launch(BrowserType.LaunchOptions().apply {
            setHeadless(true)
            setProxy(
                    Proxy("${proxy.host}:${proxy.port}").also {
                        it.username = proxy.username
                        it.password = proxy.password
                    }
            )
        }).use { browser ->
            browser.newContext().use { context ->
                context.newPage().use {
                    it.navigate("https://www.walmart.com/")
                }
            }
        }
    }
}
```

**Describe the bug**

When using a proxy that requires a username and password the initial requests don't include the Proxy-Authorization header. Using wireshark to track requests, the first two requests don't include Proxy-Authorization header resulting in 407s.

- Failed request without Proxy-Authorization to ocsp.digicert.com - ![Screen Shot 2022-05-17 at 12 23 58 PM](https://user-images.githubusercontent.com/100439417/168897603-ada2f4d4-cb92-42f5-ae21-46a6c601a2c6.png)
- Failed connect without Proxy-Authorization - ![Screen Shot 2022-05-17 at 12 24 33 PM](https://user-images.githubusercontent.com/100439417/168897608-4be5ea73-207a-4a9a-87fe-9ec45aedbda6.png)
- Successful connect with Proxy-Authorization - ![Screen Shot 2022-05-17 at 12 24 52 PM](https://user-images.githubusercontent.com/100439417/168897609-19046843-a698-42e6-9db7-7017a97443f4.png)

**Workaround**
1. To remove the first call to ocsp.digicert.com switch proxy to "per-context"
2. Force include the auth header

```kotlin
import com.microsoft.playwright.Browser
import com.microsoft.playwright.BrowserType
import com.microsoft.playwright.Playwright
import com.microsoft.playwright.options.Proxy
import java.util.Base64

data class MyProxy(val host: String, val port: Int, val username: String, val password: String) {
    fun headers(): Map<String, String> {
        val encoded = Base64.getEncoder().encodeToString("${this.username}:${this.password}".toByteArray())
        return mapOf("Proxy-Authorization" to "Basic $encoded")
    }
}

fun main() {
    val proxy = MyProxy("proxy", 1234, "admin", "password")
    Playwright.create().use { playwright ->
        playwright.firefox().launch(BrowserType.LaunchOptions().apply {
            setHeadless(true)
            setProxy("per-context")
        }).use { browser ->
            browser.newContext(Browser.NewContextOptions().apply {
                setProxy(
                    Proxy("${proxy.host}:${proxy.port}").also {
                        it.username = proxy.username
                        it.password = proxy.password
                    }
                )
                setExtraHTTPHeaders(proxy.headers())
            }).use { context ->
                context.newPage().use {
                    it.navigate("https://www.walmart.com/")
                }
            }
        }
    }
}
```

**Comment by yury-s** [comment]
Can you try and see if it works in other browsers?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
