### ISSUE TITLE
Long image screenshot is incomplete, please help me!

### ISSUE THREAD

**Issue by bestRunner** [microsoft/playwright-java#934]
The following is the playwright version and code sample：

com.microsoft.playwright
playwright
1.17.0
public static void main(String[] args) throws Exception {
try (Playwright playwright = Playwright.create()) {
Browser browser = playwright.chromium().launch();
Page page = browser.newPage();
page.addInitScript(Paths.get("./scroll.js"));
Page.NavigateOptions navigateOptions = new Page.NavigateOptions();
navigateOptions.setWaitUntil(WaitUntilState.NETWORKIDLE);
page.navigate("https://www.meipian.cn/3eh6t1fr", navigateOptions);
while (true) {
page.keyboard().down("PageDown");
TimeUnit.MILLISECONDS.sleep(500);
Boolean isBottom = (Boolean) page.evaluate("isBottom()");
if (isBottom) {
TimeUnit.MILLISECONDS.sleep(500);
break;
}
}
page.evaluate("scrollTop()");

        TimeUnit.MILLISECONDS.sleep(1000);
        Page.ScreenshotOptions screenshotOptions = new Page.ScreenshotOptions();
        screenshotOptions.setFullPage(true);
        byte[] screenshot = page.screenshot(screenshotOptions);
        byte2image(screenshot, "./tmp.jpg");
        System.out.println("over!");
        browser.close();
    }
}

**Comment by mxschmitt** [comment]
It's not clear for us what you are trying to achieve and what the issue is. Keep in mind that we discourage from using time.sleep see here: https://playwright.dev/java/docs/next/multithreading#pagewaitfortimeout-vs-threadsleep

**Comment by yury-s** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
