### ISSUE TITLE
How can I add Allure or any other HTML report using Playwright Java?

### ISSUE THREAD

**Issue by Mosorathia** [microsoft/playwright-java#946]
I am using Playwright with Java and TestNG and I want to generate HTML report.. Can you share how can I implement that?

**Comment by Mosorathia** [comment]
Solved - Done using Extent Report

**Comment by kishorejawalkar** [comment]
@Mosorathia Even i am looking to implement the same, can you please share your implementation. Thanks

**Comment by Mosorathia** [comment]
> @Mosorathia Even i am looking to implement the same, can you please share your implementation. Thanks

@kishorejawalkar You can check this out.. Here the example is of selenium but it works in similar way for Playwright and TestNG  [](https://www.seleniumeasy.com/selenium-tutorials/extent-reports-using-testng-listeners)
