### ISSUE TITLE
[Question] Playwright Java Page Object Model with Automatic Authentication Framework example

### ISSUE THREAD

**Issue by kishorejawalkar** [microsoft/playwright-java#953]
I am trying to setup new framework using Playwright Java Page Object Model with Automatic Authentication Framework. Also i am planning to use Spring as much as possible. 

I can't find any example anywhere, so if anyone knows of any example repos or websites, please let me know. 

Any info is highly appreciated !

Cheers

**Comment by yury-s** [comment]
There is [a doc](https://playwright.dev/java/docs/next/pom) explaining how POMs can be implemented based on Playwright. We don't provide framework-specific guides, is there anything specific that doesn't work for you?

**Comment by kishorejawalkar** [comment]
Thanks for your response @yury-s I am looking to implement Automatic Authentication in my framework.

The steps performed are:
1. Playwright, Browser, BrowserContext and Page are instantiated using Spring Beans and the url is loaded
2. @BeforeAll method performs the sign in, stores the login state in a json file, signs out from the application, closes the page and browserContext.
3. @BeforeEach method loads the logins state, however i can see 2 browsers launched 1 from @Bean and other from login state using the storageState. So i have to check which page is active and close the other so the browser also closes and continue with test.
4. So i am looking for a solution to launch the page from @Bean when the @Test methods are executed.

Following is my code:

`@Bean(destroyMethod="", name="browser")
    @DependsOn("playwright")
    public Browser browser() {
        BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions()
                .setChannel(browserName)
                .setHeadless(shouldRunHeadless)
                .setSlowMo(100);

        Playwright playwright = playwright();
        BrowserType browserType;
        switch (browserName) {
            case "chrome":
            case "msedge":
                browserType = playwright.chromium();
                break;
            case "firefox":
                browserType = playwright.firefox();
                break;
            case "safari":
                browserType = playwright.webkit();
                break;
            default:
                throw new IllegalArgumentException("Incorrect browser name.");
        }
        return browserType.launch(launchOptions);
    }

    @Bean(destroyMethod="")
    @DependsOn({"browser", "desktopContext", "newPage"})
    public Page page() {
        Page page;
        if (screenType.equals(DESKTOP)) {
            page = newPage(newDesktopBrowserContext(browser()));
            navigate(Map.of(), page);
        } else {
            page = newPage(newMobileBrowserContext(browser()));
            navigate(Map.of("mobile", "true"), page);
        }
        return page;
    }
`

`@BeforeAll
    private void signIn() {
        signInPage.UserName.setText(username);
        signInPage.Password.setText(password);
        signInPage.SignIn.click();
        automaticAuthentication.setLoginState();
        assertThat(landingPage.signOut.isVisible(), is(true));
        signOut();
        closePage();
        closeBrowserContext();
    }`

`@BeforeEach
    private void setLogin() {
        newPage = automaticAuthentication.automaticLogin();
    }`

`public Page automaticLogin() {
        if (!page.isClosed()) {
            page.close();
        }
        newPage = getLoginState().newPage();
        newPage.navigate(baseUrl);
        return newPage;
    }`

**Comment by yury-s** [comment]
Does `automaticAuthentication` launch its own browser? You should be able to pass the same browser/context/page to `automaticAuthentication.automaticLogin(); `. It's not quite clear from the code snippet that you shared what the relationship between automaticAuthentication and the browser/page created in the @Bean. Can you share all pieces including test that creates 2 pages instead of 1 and all the methods that create pages, perform auth?

> 3\. @beforeeach method loads the logins state, however i can see 2 browsers launched 1 from @bean and other from login state using the storageState. So i have to check which page is active and close the other so the browser also closes and continue with test.

Perhaps you can change ` public Page page() {` behavior to return signed in page (not sure if it meets your requirements). In any case the problem is very specific to how you structure the code using the beans.

**Comment by kishorejawalkar** [comment]
@yury-s Please find attached my code.

[Playwright Java Spring Boot Code](https://drive.google.com/drive/folders/156VGYLESKJfttcS3auXT7r0BS9K-hRqd?usp=sharing)

**Comment by chaganiu** [comment]
@kishorejawalkar if you're using JUnit 5 take a look at [junit-playwright](https://github.com/uchagani/junit-playwright) which will give you Playwright objects you can inject into your tests.  With this you can then implement auto login process pretty easily.

**Comment by yury-s** [comment]
I looked at the project you shared but it's hard to tell what's going on, can you reduce it to a minimal scenario which doesn't work?

**Comment by kishorejawalkar** [comment]
@yury-s When i run my tests 2 browsers are launching this is due to @Bean 

```
@Component
public class AutomaticAuthentication extends BasePage {

    private static final String FILE_NAME = "./src/test/java/com/testing/ui/authenticationstate/LoginState.json";

    @Autowired
    private BrowserContext context;

    @Autowired
    private Browser browser;

    @Autowired
    private Page page;

    @Value("${ds.baseUrl}")
    private String baseUrl;

    @Value("${ds.enable.trace.viewer}")
    private boolean enableTraceViewer;

    public void setLoginState() {
        context.storageState(new BrowserContext.StorageStateOptions().setPath(Paths.get(FILE_NAME)));
    }

    public Page automaticLogin() {
        if (!page.isClosed()) {
            page.close();
        }
        newPage = getLoginState().newPage();
        newPage.navigate(baseUrl);
        return newPage;
    }

    private BrowserContext getLoginState() {
        return browser.newContext(new Browser.NewContextOptions().setStorageStatePath(Paths.get(FILE_NAME)));
    }
}
```
```
@Bean(destroyMethod="", name="browser")
    @DependsOn("playwright")
    public Browser browser() {
        BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions()
                .setChannel(browserName)
                .setHeadless(shouldRunHeadless)
                .setSlowMo(100);

        Playwright playwright = playwright();
        BrowserType browserType;
        switch (browserName) {
            case "chrome":
            case "msedge":
                browserType = playwright.chromium();
                break;
            case "firefox":
                browserType = playwright.firefox();
                break;
            case "safari":
                browserType = playwright.webkit();
                break;
            default:
                throw new IllegalArgumentException("Incorrect browser name.");
        }
        return browserType.launch(launchOptions);
    }
```
```
@Bean(name="desktopContext")
    @DependsOn("browser")
    public BrowserContext newDesktopBrowserContext(Browser browser) {
        return browser.newContext(new Browser.NewContextOptions().setViewportSize(1400, 900));
    }
```

```
@Bean(destroyMethod="")
    @DependsOn({"browser", "desktopContext", "newPage"})
    public Page page() {
        Page page;
        if (screenType.equals(DESKTOP)) {
            page = newPage(newDesktopBrowserContext(browser()));
            navigate(Map.of(), page);
        } else {
            page = newPage(newMobileBrowserContext(browser()));
            navigate(Map.of("mobile", "true"), page);
        }
        return page;
    }
```

```
@Bean(name="newPage")
    public Page newPage(BrowserContext browserContext) {
        return browserContext.newPage();
    }
```

```
private void navigate(Map<String, String> queryParams, Page page) {
        if (queryParams.isEmpty()) {
            page.navigate(baseUrl, new Page.NavigateOptions().setWaitUntil(WaitUntilState.NETWORKIDLE));
        } else {
            final String queryParamsAsString = queryParams.entrySet().stream().
                    map(entry -> "&" + entry.getKey() + "=" + entry.getValue())
                    .collect(joining("&"));
            page.navigate(baseUrl + "?" + queryParamsAsString, new Page.NavigateOptions().setWaitUntil(WaitUntilState.NETWORKIDLE));
        }
    }
```


```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@TestPropertySource({"classpath:testing-ui-${test.environment:dev}.properties"})
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public abstract class BaseTest {

    private static final String FILE_PATH = "./src/test/resources/";

    @Autowired
    @RegisterExtension
    private TestHandler testHandler;

    @Autowired
    private SignInPage signInPage;

    @Autowired
    private LandingPage landingPage;

    @Autowired
    private Page page;

    @Autowired
    private Browser browser;

    @Autowired
    private BrowserContext browserContext;

    @Autowired
    private Playwright playwright;

    @Autowired
    private BaseClient baseClient;

    @Autowired
    private AutomaticAuthentication automaticAuthentication;

    @Value("${ds.credentials.username}")
    private String username;

    @Value("${ds.credentials.password}")
    private String password;

    @Value("${ds.enable.trace.viewer}")
    private boolean enableTraceViewer;

    @BeforeAll
    private void signIn() {
        signInPage.ID.setText(username);
        signInPage.password.setText(password);
        signInPage.signIn.click();
        automaticAuthentication.setLoginState();
        assertThat(landingPage.signOut.isVisible(), is(true));
        signOut();
        closePage();
    }

    @BeforeEach
    private void setLogin() {
        if (enableTraceViewer) {
            browserContext.tracing().start(new Tracing.StartOptions().setScreenshots(true).setSnapshots(true).setSources(true));
        }
        newPage = automaticAuthentication.automaticLogin();
    }

    @AfterEach
    private void close(TestInfo testInfo) {
        disposeAPIRequestContext();
        signOut();
        closePage();
        if (enableTraceViewer) {
            browserContext.tracing().stop(new Tracing.StopOptions()
                    .setPath(Paths.get(FILE_PATH + "traces/" + testInfo.getDisplayName().replaceAll("\\(|\\)", "_") +
                            LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd_MM_yyyy_hh_mm_ss")) + ".zip")));
        }
        closeBrowserContext();
        closeBrowser();
    }

    @AfterAll
    private void tearDown() {
        closePlaywright();
    }

    void signOut() {
        if (landingPage.signOut.isVisible()) {
            landingPage.signOut.click();
        }
    }

    void disposeAPIRequestContext() {
        disposeApsAPIRequestContext();
        disposeDasAPIRequestContext();
    }

    void disposeDasAPIRequestContext() {
        APIRequestContext dasApiRequestContext = baseClient.getDasApiRequestContext();
        if (dasApiRequestContext != null) {
            dasApiRequestContext.dispose();
        }
    }

    void disposeApsAPIRequestContext() {
        APIRequestContext apsApiRequestContext = baseClient.getApsApiRequestContext();
        if (apsApiRequestContext != null) {
            apsApiRequestContext.dispose();
        }
    }

    void closePage() {
        if (page != null) {
            page.close();
            page = null;
        } else if (!newPage.isClosed()) {
            newPage.close();
            newPage = null;
        }
    }

    void closeBrowserContext() {
        if (browserContext != null) {
            browserContext.close();
            browserContext = null;
        }
    }

    void closeBrowser() {
        if (browser != null) {
            browser.close();
            browser = null;
        }
    }

    void closePlaywright() {
        if (playwright != null) {
            playwright.close();
            playwright = null;
        }
    }
}
```

**Comment by yury-s** [comment]
It does look like there is a real bug here, but it is very hard to understand what's going on. We often spend days on these kinds of bugs that involve digging into large codebases. Feel free to open a new issue with a smaller repro script.

**Comment by sdseenu** [comment]
Hi, I am new to Playwright. Please can any one help me?
I have created 3 pages and 3 tests when I ran the third could not auto-login. Even if the page is open the validated state ie the test run is looking at the initial page one, not a recently opened page.

I am used Jave POM with StorageStateOptions..
