### ISSUE TITLE
[BUG] When listening for requests, the body of the POST method gets null.

### ISSUE THREAD

**Issue by SilenceCarrot** [microsoft/playwright-java#957]
Hi, I have a problem:
When listening for requests, the body of the POST method gets null.

![image](https://user-images.githubusercontent.com/15966265/175245477-22d6671f-cbca-4732-8e75-763df747e3cd.png)
![image](https://user-images.githubusercontent.com/15966265/175245580-7324d5da-9232-4889-89b8-a586bb638d53.png)

The business problem I have now is: the server returns me a 403 error when I post a request. In the body of this post method, I will bring the authentication information.
Now I want to see if the body parameter of the post request is correct when executing playwrightScript again.

Looking forward to your advice again, thank you very much.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by SilenceCarrot** [comment]
Thanks for your reply, I try to provide the scene to you.
