### ISSUE TITLE
[Question] PLAYWRIGHT_JAVA_SRC as Property vs Environment variable

### ISSUE THREAD

**Issue by easyrepro** [microsoft/playwright-java#965]
Setting PLAYWRIGHT_JAVA_SRC as Environment variable only succeeds for `setSources(true)` while tracing. 
Setting using `System.setProperty(PLAYWRIGHT_JAVA_SRC,"")` is failing with error
`com.microsoft.playwright.PlaywrightException: Source root directory must be specified via PLAYWRIGHT_JAVA_SRC environment variable when source collection is enabled`

Why can't playwright honor `System.setProperty(PLAYWRIGHT_JAVA_SRC,"")`

**Comment by yury-s** [comment]
These are two different mechanisms, the variable can only be set as environment variable and System.setProperty doesn't affect those. Is there a reason why environment variable doesn't work for you?

**Comment by yury-s** [comment]
I see, I'm going to add support for it in [Playwright.create](https://playwright.dev/java/docs/api/class-playwright#playwright-create-option-env) so that you could specify the environment variable also when creating a playwright instance.
