### ISSUE TITLE
[Feature] Set declarative image tag with java

### ISSUE THREAD

**Issue by ShaharM7** [microsoft/playwright-java#989]
Hi,
When I used  "mcr.microsoft.com/playwright/java:v1.23.1-focal" I can't know which java I use it.
To solve it I inspected the to the container or I saw the dockerfile, but it very difficult to handle docker images tags' like that.
 I will like to declarative the java version with the playwright version in the image tag.
For example: "mcr.microsoft.com/playwright/java:v1.23.1-focal-java11".
It will very helpful to handle the ci cd in the automation pipeline.
Thank you🙏

**Comment by yury-s** [comment]
So far all our images have been using Open JDK 11, so I it probably won't make much sense to include the version into the tag name. We could add it to the description of the docker image somewhere but on the other hand it may accidentally get outdated and the ultimate source of truth is the [Dockerfile](https://github.com/microsoft/playwright-java/blob/e372513fa4ee280727cfdd625c19d1768a1736ea/utils/docker/Dockerfile.focal#L9) where you can see which jdk is used. Does that work for you or you still have a use case where it'd be desirable to include the java version into the tag name?

**Comment by ShaharM7** [comment]
First of all, thank you for your answer.
Second, my concern is what will happen if my project is updated with a new java version, of course in my company we decide to update the java version, but we want at some point to update it. We started an automation project and we decided to use java 11 then we see that the image used java 11 but it is a very accidental state and I don't know about other projects.
Also, java is compatible with its other versions but I have to say, I don't trust that because it is java lol.
Regarding tags name, you can do it as you did in the [playwright/chromium](https://hub.docker.com/r/playwright/chromium/tags). I understand that all your images use Open JDK 11, but at some point, you will update the java version or maybe not.
So my offer maybe is when you will update the playwright version, you will start giving the: playwright version and then the java version. and if anybody wants only the playwright version it will be o.k, because you will release an image with only the new playwright version and the same java version, or you will not change the java version at all?

**Comment by yury-s** [comment]
We discussed this in a meeting today and decided to start with adding the SDK version to the description of the image. The safest way to pin the java version is to have an image based off the playwright one that adds a java sdk on top of it.

Btw, the playwright/chromium repo you refer to is not an official one, in the official repository we don't have any version tags other than playwright versions.

**Comment by ShaharM7** [comment]
That is a amazing idea. To give a base sdk of playwright, and build on top of that. 
I think that will be a very nice, I think we can close the issue🙏 
Thank you very much
