### ISSUE TITLE
[Question] Is possible to make a multiple tabs app with different classes?

### ISSUE THREAD

**Issue by NICOGTZL** [microsoft/playwright-java#990]
Closed, was a problem with my java installation

**Comment by yury-s** [comment]
I'm not sure I understand what is blocking you. Each Page instance in Playwright will work as a separate tab in the browser. You can pick and choose whether you create the pages in the same context or in different contexts and whether those contexts belong to the same browser or different ones.

> In this way I've been searching around the internet, I know how to create different tabs and everything, but I'm still having troubles to find a way to unify different classes in playwright, since I don't find the way to import different classes to others.

Can you elaborate on what you mean by "unify different classes" ?

**Comment by NICOGTZL** [comment]
Hello Yury, 

I would like to create everything in one context, so all context I have now will be replaced for different browser tabs, in this way I've tried to create different classes to keep my code clean so I can find everything easily.

I'm trying to automatize a store, instead of having everything in one class, I'd like to order it in different classes: ttps://i.imgur.com/vC5Qbgt.png but when I'm trying to call methods from other classes I don't find the way, I'm not sure if this is a problem with playwright or with my Java installation, since it's seems that I doesn't recognize other classes when I'm calling the methods.

Thanks for helping!
