### ISSUE TITLE
Get request status code is returning 403 instead of 200

### ISSUE THREAD

**Issue by vasu31dev** [microsoft/playwright-java#991]
**Context:**

Playwright Version: 1.23.0
Operating System: Mac OS 12.4
Browser: Chrome 103.0.5060.114

**Code Snippet**
```
import com.microsoft.playwright.APIRequest;
import com.microsoft.playwright.APIRequestContext;
import com.microsoft.playwright.Playwright;

import java.util.HashMap;
import java.util.Map;


public class TestResponse {

  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      final String URL = "https://support.metronetbusiness.com/hc/en-us";
      Map<String,String> headers = new HashMap<>();
      headers.put("User-Agent", "PostmanRuntime/7.29.0");
      APIRequestContext apiRequestContext = playwright.request().newContext(new APIRequest.NewContextOptions().setExtraHTTPHeaders(headers));
      var response = apiRequestContext.get(URL);
      System.out.println("status code-"+response.status());
    }
  }
}
```
In Postman I am able to get the response status as 200 but in Playwright I am getting the status code as 403
<img width="1146" alt="PostMan" src="https://user-images.githubusercontent.com/32603657/178318077-67372370-7194-4ae3-8598-bbcdbed1b4bb.png">

Not sure If the User-Agent header as "PostmanRuntime/7.29.0" is working or if there is any other issue in Playwright?
Note: With the Restassued jar file I was able to get the status code as 200 by setting the header with "User-Agent" as "PostmanRuntime/7.29.0"

**Comment by yury-s** [comment]
Looks like you don't pass the cookie or some other required token (in postman you have `Cookie` and `Postman-Token but I don't see them in your snippet). 

You can  either use [tracing](https://playwright.dev/java/docs/api/class-tracing) to see what headers playwright sends to the server or run it with `DEBUG=pw:api`. That should give you an idea what headers are missing. If that doesn't help feel free to open a new issue and reference this one.
