### ISSUE TITLE
[Question] Is possible to open in the same browser context page a new tab?

### ISSUE THREAD

**Issue by NICOGTZL** [microsoft/playwright-java#992]
Hello!

I am currently making a program to automate a store, the problem is that every time I open a page with a context I have to log in again. I would like to know, if there is any way that I could open a new tab and be able to use that tab to do processes like checking information and such, I know that once I open a new tab, the browser saves the cookies and therefore I am inside the session, that's why I would like to do it like this. But of course, if there is an easier way to do what I need, please tell me.

I have tried:
`Page Checker = page1.waitForPopup(() -> {`

For clarification:
- How can I open several tabs in the same browser to run processes there?

Thanks!

**Comment by yury-s** [comment]
You can create a new page in the same context via [`context.newPage()`](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-new-page). All pages in the same context will share cookies, local storage state etc. The new page behaves like a new tab in a regular browser.
