### ISSUE TITLE
[Feature] Tracing at Browser level 

### ISSUE THREAD

**Issue by easyrepro** [microsoft/playwright-java#993]
We have multi app workflow 

 - Launch Browser
   - Start new context(a) with App 1, do some activity
   - Start another context(b) with App 2, do some activity
   - Do some activity in App 1 with context(a)

Tracing at context level creates different traces but a combined trace level at browser level gives overall picture. i.e., Tracing at Browser level will show combined activity from both context a and context b.

As we have below implementation in Java, combining context traces may be possible. 
> Playwright Java is not thread safe, i.e. all its methods as well as methods on all objects created by it (such as [BrowserContext](https://playwright.dev/java/docs/api/class-browsercontext), [Browser](https://playwright.dev/java/docs/api/class-browser), [Page](https://playwright.dev/java/docs/api/class-page) etc.) are expected to be called on the same thread

Leveraging video recording option doesn't provide metadata given by tracing.

**Comment by yury-s** [comment]
You can drag and drop multiple trace files into the same [trace viewer](https://playwright.dev/java/docs/trace-viewer) window.
