### ISSUE TITLE
[Feature] Expose baseUrl in BrowserContext

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [microsoft/playwright-java#994]
Using the Page Object Model (https://playwright.dev/java/docs/pom) I find myself in situations where I need the `baseUrl` but can't access it.
For example when using [waitForResponse](https://playwright.dev/java/docs/api/class-page#page-wait-for-response).
The offical example uses a hard-coded string:
```java
// Waits for the next response with the specified url
Response response = page.waitForResponse("https://example.com/resource", () -> {
  // Triggers the response
  page.click("button.triggers-response");
});
```

But since the `page` contains the `browserContext`which itself contains the `baseUrl` this could be avoided by adding a getter for the `baseUrl` to the `browserContext`.

I'm aware that if I could match the response URL using a path that is than matched against the `baseUrl`. But since I need to add further checks against the request body I need to use the predicate.

Is there a reason why the `baseUrl` isn't made available from the page?

**Comment by yury-s** [comment]
You can always pass `baseURL` to the response handler/predicate using a variable external to playwright, moreover each matching response will have `response.url()` which includes the base URL, so exposing it on BrowserContext wouldn't add much value. Can you tell us more about your scenario and why such approaches don't work?

**Comment by ChristianHuff-DEV** [comment]
The approach of passing the `baseUrl` as a variable to where I need it would work. But I was hoping to avoid that.

Using the example from the docs I want to write the following code:
```java
Response response = page.waitForResponse(response -> baseUrl + "/path/to/resource".equals(response.url()) && response.status() == 200, () -> {
  // Triggers the response
  page.click("button.triggers-response");
});
```

Using the example above I want to do use the `baseUrl` as the variable part of the URL I'm waiting for the response from. Since different environments (dev/staging/prod) have different baseURLs I can't hard code it. I need something to compare the `response.url()` with.
Having to pass the `baseUrl` through all the methods seems unnecessary if the `baseUrl` is already present in the `BrowserContext` and could be use to compare it.

**Comment by yury-s** [comment]
Can you rewrite it like this?

```java
Response response = page.waitForResponse(response -> response.url().endsWith("/path/to/resource") && response.status() == 200, () -> {
  // Triggers the response
  page.click("button.triggers-response");
});
```

**Comment by ChristianHuff-DEV** [comment]
> Can you rewrite it like this?
> 
> ```java
> Response response = page.waitForResponse(response -> response.url().endsWith("/path/to/resource") && response.status() == 200, () -> {
>   // Triggers the response
>   page.click("button.triggers-response");
> });
> ```

I can! Thank you for tip!
