### ISSUE TITLE
[QUESTION] Allow browser to connect on HTTP website

### ISSUE THREAD

**Issue by Sanady** [microsoft/playwright-java#995]
Hello,
Currently, I am testing an application that has a sign-in form and after successful authorization, sign-in should redirect the user to a custom URL that contains a code, for now, that URL is localhost. After redirect on GUI less, I see that redirect link on chromium, and second, after redirect, I get this kind of error:
`chrome-error://chromewebdata/`
Basically, it says that chrome could not connect to that specific URL. is there an option to allow Playwright to connect on redirected localhost URL? Without any proxy or some kind of other things that are being used. So far I haven't found any helpful information about this topic when the user gets redirected to an HTTP page instead of HTTPS. 

I hope that there is an solution for my issue,
Best regards,
Sanady

**Comment by yury-s** [comment]
> I get this kind of error:
chrome-error://chromewebdata/
Basically, it says that chrome could not connect to that specific URL.

What does the error say? It seems that requested URL is not reachable. Can you try loading that url directly and check if you get the same error?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by Sanady** [comment]
Hello yury-s, the issue was that the firm sign-in page contains a redirect URL within the sign-in URL. When the user inserts the correct credentials, he gets redirected to the HTTP URL within the sign-in URL. But Playwright somehow cannot connect on the redirected unsafe URL, but I don't even need to connect only what I wanted is to redirect the URL with the code, even though that is impossible due to the error that Playwright show. Is it possible to connect on an unsafe URL with all the browsers? 

I saw a solution with the `connectOverCDP`  method, but even that method hasn't helped me. Is there any other solution?
