### ISSUE TITLE
[Question] Is playwright compatible with javafx?

### ISSUE THREAD

**Issue by NICOGTZL** [microsoft/playwright-java#996]
Hello,

I'm using: OpenJDK 18.0.1
Dependencies: https://imgur.com/a/KA7r3cC

Currently I'm making a panel to administrate my playwright code, and this error occurs:

`See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
1 actionable task: 1 executed
error: the unnamed module reads package com.microsoft.playwright.impl from both playwright and driver
error: the unnamed module reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module javafx.graphicsEmpty reads package com.microsoft.playwright.impl from both playwright and driver
error: module javafx.graphicsEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module javafx.baseEmpty reads package com.microsoft.playwright.impl from both playwright and driver
error: module javafx.baseEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module driver.bundle reads package com.microsoft.playwright.impl from both playwright and driver
error: module driver.bundle reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module driver reads package com.microsoft.playwright.impl from both playwright and driver
error: module driver reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module javafx.controlsEmpty reads package com.microsoft.playwright.impl from both playwright and driver
error: module javafx.controlsEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module playwright reads package com.microsoft.playwright.impl from both driver and driver.bundle
error: module playwright reads package com.microsoft.playwright.impl from both driver and playwright
C:\Users\nicol\IdeaProjects\WarehouseBot\src\main\java\module-info.java:1: error: module WarehouseBot.main reads package com.microsoft.playwright.impl from both playwright and driver
module WarehouseBot.main {
^
15 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
19:45:46: Execution finished ':Main.main()'.
`

15 errors:
`> Task :compileJava FAILED
error: the unnamed module reads package com.microsoft.playwright.impl from both playwright and driver
error: the unnamed module reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module javafx.graphicsEmpty reads package com.microsoft.playwright.impl from both playwright and driver
error: module javafx.graphicsEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module javafx.baseEmpty reads package com.microsoft.playwright.impl from both playwright and driver
error: module javafx.baseEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module driver.bundle reads package com.microsoft.playwright.impl from both playwright and driver
error: module driver.bundle reads package com.microsoft.playwright.impl from both playwright and driver.bundle
the unnamed module reads package com.microsoft.playwright.impl from both playwright and driver

error: module driver reads package com.microsoft.playwright.impl from both playwright and driver
error: module driver reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module javafx.controlsEmpty reads package com.microsoft.playwright.impl from both playwright and driver
error: module javafx.controlsEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle
error: module playwright reads package com.microsoft.playwright.impl from both driver and driver.bundle
error: module playwright reads package com.microsoft.playwright.impl from both driver and playwright
the unnamed module reads package com.microsoft.playwright.impl from both playwright and driver.bundle

C:\Users\nicol\IdeaProjects\WarehouseBot\src\main\java\module-info.java:1: error: module WarehouseBot.main reads package com.microsoft.playwright.impl from both playwright and driver
module javafx.graphicsEmpty reads package com.microsoft.playwright.impl from both playwright and driver

module WarehouseBot.main {
module javafx.graphicsEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle

^
module javafx.baseEmpty reads package com.microsoft.playwright.impl from both playwright and driver

15 errors

module javafx.baseEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle

module driver.bundle reads package com.microsoft.playwright.impl from both playwright and driver

module driver.bundle reads package com.microsoft.playwright.impl from both playwright and driver.bundle

module driver reads package com.microsoft.playwright.impl from both playwright and driver

module driver reads package com.microsoft.playwright.impl from both playwright and driver.bundle

module javafx.controlsEmpty reads package com.microsoft.playwright.impl from both playwright and driver

module javafx.controlsEmpty reads package com.microsoft.playwright.impl from both playwright and driver.bundle

module playwright reads package com.microsoft.playwright.impl from both driver and driver.bundle

module playwright reads package com.microsoft.playwright.impl from both driver and playwright
`

Module error:
`C:\Users\nicol\IdeaProjects\WarehouseBot\src\main\java\module-info.java:1: error: module WarehouseBot.main reads package com.microsoft.playwright.impl from both playwright and driver
module WarehouseBot.main {
^`

**Comment by NICOGTZL** [comment]
It's seems I'm not the only one with this error: 

https://stackoverflow.com/questions/72753702/using-playwright-in-a-modular-java-application

**Comment by yury-s** [comment]
This was reported before: https://github.com/microsoft/playwright-java/issues/683. I believe we can fix it by changing the module structure a bit. Can you share a minimal repro where this happens?

**Comment by NICOGTZL** [comment]
Hello Yury,

Thanks for replying. I have created a repository with a minimal repro: https://github.com/NICOGTZL/BugReportRepro

Let me know whether I can help you furthermore.

**Comment by yury-s** [comment]
> Thanks for replying. I have created a repository with a minimal repro: https://github.com/NICOGTZL/BugReportRepro
> 
> Let me know whether I can help you furthermore.

Thanks for sharing! What steps should I run to reproduce the error?

**Comment by NICOGTZL** [comment]
No worries! I don't quite know what you mean, the error occurs when the Main class runs. 

The main class should open a javafx interface and have a button, which when clicked would start playwright and it should navigate to the microsoft web page. 

Let me know if this is not what you meant :)

**Comment by yury-s** [comment]
Nevermind, I wanted to run the project from command line but ended up doing it from IDE. I can reproduce it.

**Comment by NICOGTZL** [comment]
> Nevermind, I wanted to run the project from command line but ended up doing it from IDE. I can reproduce it.

Alright! So is it solved already? I tried to run the repro I sent you but it seems that doesn't work yet.

**Comment by yury-s** [comment]
The changes will be published in the next release - v1.25.0, you can try it already by switching to 1.25.0-SNAPSHOT version. You'll need to configure separate maven repository in Gradle for the snapshots similar to [this](https://github.com/microsoft/playwright-java/blob/560575a9b5a19e397fab08e190ea390c9f293207/examples/pom.xml#L35-L40).

**Comment by NICOGTZL** [comment]
Sorry if I am annoying, I have not managed to do it, it seems that when I put the pom.xml you attached and put the version, my ide does not recognize that version and tells me it does not exist. I don't know if I'm doing something wrong, maybe I should wait until version 1.25.0 finally comes out when do you think it will be published? Thanks!

**Comment by yury-s** [comment]
> I have not managed to do it, it seems that when I put the pom.xml you attached and put the version, my ide does not recognize that version and tells me it does not exist.

I'm not a Gradle expert but I guess you need to covert that part of pom.xml into something like [this](https://docs.gradle.org/current/userguide/declaring_repositories.html#maven_repository_filtering). A normal way to configure snapshot repositories should work.
